CREATE TABLE 'arcade_minigame_talk' ('id' INTEGER NOT NULL, 'talk_type' INTEGER NOT NULL, 'text_index' INTEGER NOT NULL, 'name' TEXT NOT NULL, 'content' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/1, /*talk_type*/1, /*text_index*/1, /*name*/"名前", /*content*/"まだまだお仕事は始まったばかり。¥n適度に休憩を挟んで、優雅に参りましょうね。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/2, /*talk_type*/1, /*text_index*/2, /*name*/"名前", /*content*/"そうですわね。¥nゆっくりお紅茶でもいただいて、英気を養ったら……¥nもうひと頑張り、いたしましょう♪");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/3, /*talk_type*/1, /*text_index*/3, /*name*/"名前", /*content*/"盛り上がりが足りないわね !¥nアタシたちで、一発お見舞いしてやるわよ !");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/4, /*talk_type*/2, /*text_index*/1, /*name*/"名前", /*content*/"おっけー !¥nみんなの長所を活かして、連携技でいこう !");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/5, /*talk_type*/2, /*text_index*/2, /*name*/"名前", /*content*/"仲間の力を合わせれば、なんだってできるさ !");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/6, /*talk_type*/2, /*text_index*/3, /*name*/"名前", /*content*/"おっけー !¥nみんなの長所を活かして、連携技でいこう !");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/7, /*talk_type*/3, /*text_index*/1, /*name*/"名前", /*content*/"仲間の力を合わせれば、なんだってできるさ !");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/8, /*talk_type*/4, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃぴにゃ、ぴにゃにゃ ! \n※一曲目を発表します。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/9, /*talk_type*/5, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴにゃにゃ ! \n ※次の楽曲はこちらです。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/10, /*talk_type*/6, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はキュートアイドルが有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/11, /*talk_type*/7, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はクールアイドルが有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/12, /*talk_type*/8, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はパッションアイドルが有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/13, /*talk_type*/9, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はキュートアイドルが有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/14, /*talk_type*/10, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はクールアイドルが有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/15, /*talk_type*/11, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はパッションアイドルが有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/16, /*talk_type*/12, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はキュートアイドルが少しだけ有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/17, /*talk_type*/13, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はクールアイドルが少しだけ有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/18, /*talk_type*/14, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴーにゃぴにゃ、ぴにゃにゃ ! \n ※今回はパッションアイドルが少しだけ有利です。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/19, /*talk_type*/15, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴにゃ、ぴにゃ ! \n ※今回はキュートアイドルのみ特技が発動します。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/20, /*talk_type*/16, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴにゃ、ぴにゃ ! \n ※今回はクールアイドルのみ特技が発動します。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/21, /*talk_type*/17, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴにゃ、ぴにゃ ! \n ※今回はパッションアイドルのみ特技が発動します。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/22, /*talk_type*/18, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃ ! \n ※全アイドルが自由にアピールできます。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/23, /*talk_type*/19, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴにゃ、ぴにゃにゃ ! \n ※今回はキュートとクールアイドルのみ特技が発動します。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/24, /*talk_type*/20, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴにゃ、ぴにゃにゃ ! \n ※今回はクールとパッションアイドルのみ特技が発動します。");
INSERT INTO `arcade_minigame_talk` VALUES (/*id*/25, /*talk_type*/21, /*text_index*/1, /*name*/"DJぴにゃ", /*content*/"ぴにゃにゃ、ぴにゃ、ぴにゃにゃ ! \n ※今回はキュートとパッションアイドルのみ特技が発動します。");
CREATE INDEX 'arcade_minigame_talk_0_talk_type' on 'arcade_minigame_talk'('talk_type');
CREATE INDEX 'arcade_minigame_talk_0_text_index' on 'arcade_minigame_talk'('text_index');
