CREATE TABLE 'arcade_talk_text' ('id' INTEGER NOT NULL, 'talk_type' INTEGER NOT NULL, 'card_id' INTEGER NOT NULL, 'word_num' INTEGER NOT NULL, 'word_text' TEXT NOT NULL, 'icon' INTEGER NOT NULL, 'position' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `arcade_talk_text` VALUES (/*id*/1, /*talk_type*/10, /*card_id*/300157, /*word_num*/1, /*word_text*/"さぁ、プロデューサーさん !¥nみんなを取り返すために、ゲームゲーム !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/2, /*talk_type*/10, /*card_id*/300157, /*word_num*/2, /*word_text*/"もし負けちゃっても、諦めないで !¥n何度だってリトライすればいいからね !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/3, /*talk_type*/10, /*card_id*/300157, /*word_num*/3, /*word_text*/"力を合わせて、ゲームクリアを目指そう !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/4, /*talk_type*/20, /*card_id*/300157, /*word_num*/1, /*word_text*/"よーし、順調順調 !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/5, /*talk_type*/20, /*card_id*/300291, /*word_num*/2, /*word_text*/"超☆脱出 !¥nありがとうございます、紗南ちゃん、プロデューサー !", /*icon*/300291, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/6, /*talk_type*/20, /*card_id*/300291, /*word_num*/3, /*word_text*/"しかぁし !¥nゲームのやりすぎはいけません !¥n今日はいったん休憩をして目を休め……。", /*icon*/300291, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/7, /*talk_type*/20, /*card_id*/300157, /*word_num*/4, /*word_text*/"あーあーあーあー !¥n委員長、今日は見逃してよ !¥nみんなを助けなきゃいけないんだって !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/8, /*talk_type*/20, /*card_id*/300291, /*word_num*/5, /*word_text*/"む……。", /*icon*/300291, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/9, /*talk_type*/20, /*card_id*/300157, /*word_num*/6, /*word_text*/"風紀の役目は、みんなを守ることでしょ？¥nだから、今日はゲームプレイが風紀 !¥n超☆風紀委員なら、わかってくれるでしょ？", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/10, /*talk_type*/20, /*card_id*/300291, /*word_num*/7, /*word_text*/"むぅ……。たしかに。¥n超☆風紀委員には、柔軟な判断も必要ですからね……。¥nいいでしょう。今日だけですよ !", /*icon*/300291, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/11, /*talk_type*/20, /*card_id*/300157, /*word_num*/8, /*word_text*/"ちょろい……。¥nよーし、この調子でいくよ !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/12, /*talk_type*/30, /*card_id*/300157, /*word_num*/1, /*word_text*/"よし ! あきらちゃんの影、撃破 !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/13, /*talk_type*/30, /*card_id*/200671, /*word_num*/2, /*word_text*/"ん……よかった。出てこれた。¥nありがとうございます。", /*icon*/200671, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/14, /*talk_type*/30, /*card_id*/200671, /*word_num*/3, /*word_text*/"さすがデスね、ゲーマーアイドル。", /*icon*/200671, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/15, /*talk_type*/30, /*card_id*/300157, /*word_num*/4, /*word_text*/"あきらちゃん、影とはいえ手強かったよ……。", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/16, /*talk_type*/30, /*card_id*/200671, /*word_num*/5, /*word_text*/"みんな助けられたら、改めて対戦しましょう。", /*icon*/200671, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/17, /*talk_type*/30, /*card_id*/300157, /*word_num*/6, /*word_text*/"うんっ ! もちろん !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/18, /*talk_type*/30, /*card_id*/300157, /*word_num*/7, /*word_text*/"よーし、あと少し !¥n頑張ろうね、プロデューサーさん !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/19, /*talk_type*/40, /*card_id*/300157, /*word_num*/1, /*word_text*/"か、勝った…… !¥n杏さんの影を倒したよ !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/20, /*talk_type*/40, /*card_id*/100027, /*word_num*/2, /*word_text*/"ふぃ～。¥n紗南、プロデューサー、ありがと。¥nおかげで杏たちもどうにか脱出できたよ～。", /*icon*/100027, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/21, /*talk_type*/40, /*card_id*/100027, /*word_num*/3, /*word_text*/"いやぁ……いくら働きたくないとはいえ、¥nゲームの中に捕まってるのはごめんだよね～。", /*icon*/100027, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/22, /*talk_type*/40, /*card_id*/300157, /*word_num*/4, /*word_text*/"杏さんは、どんなときでも変わらないなぁ……。", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/23, /*talk_type*/40, /*card_id*/300157, /*word_num*/5, /*word_text*/"さてと……。¥nこれで、アイドルのみんなは全員助け出せたけど……。", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/24, /*talk_type*/40, /*card_id*/300157, /*word_num*/6, /*word_text*/"…… ! まだ何か挑んでくる !¥nこれは……まさかっ !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/25, /*talk_type*/40, /*card_id*/100027, /*word_num*/7, /*word_text*/"なるほどね。¥nここまでの戦いで、分析済みってわけか……。", /*icon*/100027, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/26, /*talk_type*/40, /*card_id*/100027, /*word_num*/8, /*word_text*/"これまでの相手とは、わけが違う。¥n気を付けてね、紗南、プロデューサー !", /*icon*/100027, /*position*/1);
INSERT INTO `arcade_talk_text` VALUES (/*id*/27, /*talk_type*/40, /*card_id*/300157, /*word_num*/9, /*word_text*/"さぁ、いくよっ !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/28, /*talk_type*/11, /*card_id*/300157, /*word_num*/1, /*word_text*/"プロデューサーさん !¥nあたしたちと、ゲームで対戦しようよ !", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/29, /*talk_type*/11, /*card_id*/300157, /*word_num*/2, /*word_text*/"お仕事で忙しいのはわかるけど……¥nみんなも、プロデューサーさんと対戦したがってるし !¥nね、いいでしょ？", /*icon*/300157, /*position*/0);
INSERT INTO `arcade_talk_text` VALUES (/*id*/30, /*talk_type*/11, /*card_id*/300157, /*word_num*/3, /*word_text*/"まだまだ、楽しいゲームタイムは終わらないよっ !", /*icon*/300157, /*position*/0);
CREATE INDEX 'arcade_talk_text_0_talk_type' on 'arcade_talk_text'('talk_type');
