CREATE TABLE 'brand_data' ('id' INTEGER NOT NULL, 'brand_name' TEXT NOT NULL, 'brand_text' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `brand_data` VALUES (/*id*/1, /*brand_name*/"Stella Closet", /*brand_text*/"Stella Closet");
INSERT INTO `brand_data` VALUES (/*id*/2, /*brand_name*/"etc. Style", /*brand_text*/"etc. Style");
INSERT INTO `brand_data` VALUES (/*id*/3, /*brand_name*/"HAVE FUN", /*brand_text*/"HAVE FUN");
INSERT INTO `brand_data` VALUES (/*id*/4, /*brand_name*/"pastel dream", /*brand_text*/"pastel dream");
INSERT INTO `brand_data` VALUES (/*id*/5, /*brand_name*/"rafinest", /*brand_text*/"rafinest");
INSERT INTO `brand_data` VALUES (/*id*/6, /*brand_name*/"Dear Eliza", /*brand_text*/"Dear Eliza");
INSERT INTO `brand_data` VALUES (/*id*/7, /*brand_name*/"Ewig Maiden", /*brand_text*/"Ewig Maiden");
INSERT INTO `brand_data` VALUES (/*id*/8, /*brand_name*/"Mimi", /*brand_text*/"Mimi");
INSERT INTO `brand_data` VALUES (/*id*/9, /*brand_name*/"GENES", /*brand_text*/"GENES");
INSERT INTO `brand_data` VALUES (/*id*/10, /*brand_name*/"Abbie&Libby", /*brand_text*/"Abbie&Libby");
INSERT INTO `brand_data` VALUES (/*id*/11, /*brand_name*/"Nostalgia", /*brand_text*/"Nostalgia");
INSERT INTO `brand_data` VALUES (/*id*/12, /*brand_name*/"KTS", /*brand_text*/"KTS");
INSERT INTO `brand_data` VALUES (/*id*/13, /*brand_name*/"Kasa Blanca", /*brand_text*/"Kasa Blanca");
INSERT INTO `brand_data` VALUES (/*id*/14, /*brand_name*/"浅井洋品店", /*brand_text*/"浅井洋品店");
INSERT INTO `brand_data` VALUES (/*id*/15, /*brand_name*/"晴れ晴゛れ", /*brand_text*/"晴れ晴゛れ");
INSERT INTO `brand_data` VALUES (/*id*/16, /*brand_name*/"Freely", /*brand_text*/"Freely");
INSERT INTO `brand_data` VALUES (/*id*/17, /*brand_name*/"765ショップ", /*brand_text*/"765ショップ");
INSERT INTO `brand_data` VALUES (/*id*/18, /*brand_name*/"Re:Lucks", /*brand_text*/"Re:Lucks");
INSERT INTO `brand_data` VALUES (/*id*/19, /*brand_name*/"Daily Happiness", /*brand_text*/"Daily Happiness");
INSERT INTO `brand_data` VALUES (/*id*/20, /*brand_name*/"COSTUME LAB", /*brand_text*/"COSTUME LAB");
INSERT INTO `brand_data` VALUES (/*id*/21, /*brand_name*/"Ailes", /*brand_text*/"Ailes");
INSERT INTO `brand_data` VALUES (/*id*/22, /*brand_name*/"Classic Victoria", /*brand_text*/"Classic Victoria");
INSERT INTO `brand_data` VALUES (/*id*/23, /*brand_name*/"マンガート ビームス", /*brand_text*/"マンガート ビームス");
INSERT INTO `brand_data` VALUES (/*id*/24, /*brand_name*/"BISOU", /*brand_text*/"BISOU");
