CREATE TABLE 'bremer_card_comment' ('id' INTEGER NOT NULL, 'comment_id' INTEGER NOT NULL, 'use_type' INTEGER NOT NULL, 'index' INTEGER NOT NULL, 'voice_flag' INTEGER NOT NULL, 'description' TEXT NOT NULL, 'insert_word_type' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `bremer_card_comment` VALUES (/*id*/1, /*comment_id*/101, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"はい、卯月ですっ♪笑顔でいきましょう !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/2, /*comment_id*/102, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"武の神髄をお見せしましょう !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/3, /*comment_id*/103, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"フルートの音色で、癒しを…Zzｚ…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/4, /*comment_id*/104, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"プロデューサーのお手伝い、頑張りますっ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/5, /*comment_id*/105, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"お待たせドーナツ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/6, /*comment_id*/106, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"えっと、えっと…め、メモは任せてくださいっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/7, /*comment_id*/107, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"はーい♪先生とウサコちゃんがお助けしますね♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/8, /*comment_id*/108, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"お菓子持ってきたよ ! みんなで食べよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/9, /*comment_id*/109, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"森の歩き方は、わだすに任せてください !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/10, /*comment_id*/110, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"もしかしてぇ、マル秘スポット見つけちゃった感じぃ？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/11, /*comment_id*/111, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"進むの、き、緊張しますけど…いきましょうっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/12, /*comment_id*/112, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"クローバーさん、私たちを守ってください…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/13, /*comment_id*/113, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"お弁当にレジャーシートに、準備はばっちりです♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/14, /*comment_id*/114, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"みゆき、知らない場所でも頑張れるよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/15, /*comment_id*/115, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"お供いたしますわ。優雅に参りましょう♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/16, /*comment_id*/116, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"チャンスは逃しませんよ♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/17, /*comment_id*/117, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"いつだって前向き ! それがアイドルですよね♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/18, /*comment_id*/118, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"魔法少女ラブリーチカにお任せっ ! ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/19, /*comment_id*/119, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"一歩ずつ一歩ずつ、しっかり進んでいこうね", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/20, /*comment_id*/120, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"アッキーってば優秀だもん ! ここでも大活躍 !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/21, /*comment_id*/121, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"お山を探しに、たとえ火の中森の中 !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/22, /*comment_id*/122, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ズガガガガーっていっちゃうぽよーっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/23, /*comment_id*/123, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"フゴゴっ ! ？フゴ ! フゴーっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/24, /*comment_id*/124, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ふわぁー…こずえも……がんばるー…？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/25, /*comment_id*/125, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ま、待ってぇ、置いてかないでぇ～っ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/26, /*comment_id*/126, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"くんくん、なんだか面白そうな香り～♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/27, /*comment_id*/127, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ねこチャンパワー、全開にゃーっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/28, /*comment_id*/128, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"瑛梨華ちんが\nO・TA・SU・KE♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/29, /*comment_id*/129, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ブログタイトルは…早耶の不思議な冒険♪とかぁ？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/30, /*comment_id*/130, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"お紅茶でも飲んで…落ち着いて参りましょう？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/31, /*comment_id*/131, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"フレちゃんの直感力に任せたまえっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/32, /*comment_id*/132, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"しゃなりしゃなり、参りまひょ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/33, /*comment_id*/133, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"私、とってもワクワクしてしまって !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/34, /*comment_id*/134, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"杏の出番？勘弁してよぉ～", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/35, /*comment_id*/135, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ふぇいふぇいダヨー ! 一緒に進もうネ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/36, /*comment_id*/136, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"絵本を冒険大作戦 ! スタート♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/37, /*comment_id*/137, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"わたくしにできることで、サポートいたしますわ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/38, /*comment_id*/138, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"素敵な絵本、小さいころにママが読んでくれたのぉ♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/39, /*comment_id*/139, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"勝利を引き寄せてあげる !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/40, /*comment_id*/140, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"任せて ! 合戦なら詳しいから !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/41, /*comment_id*/141, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ど、ドジには気を付けましゅっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/42, /*comment_id*/145, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"手当ては私に任せてくださいね", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/43, /*comment_id*/147, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"メイクして勇気をつけて、進もうねぇ♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/44, /*comment_id*/148, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"頼れるお姉さんの出番ですよね !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/45, /*comment_id*/149, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"はわぁ…ついていけばいいんですかぁ？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/46, /*comment_id*/150, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ボクを呼びましたか？しょうがないですねぇ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/47, /*comment_id*/151, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"これは…名探偵の出番っ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/48, /*comment_id*/152, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"物語の中…少しだけ、心が躍ります", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/49, /*comment_id*/153, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"異世界×元の世界…いや、逆に…？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/50, /*comment_id*/154, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"メルヘンチェーンジ ! ナナ、いっきまーす !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/51, /*comment_id*/155, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"地道に進んでいけば、たどり着ける !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/52, /*comment_id*/156, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"あんまり無茶をしちゃダメですよっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/53, /*comment_id*/157, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ヒョウくん、プロデューサーさん、頼りにしてますから～", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/54, /*comment_id*/158, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"どうか私たちを、正しくお導きください…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/55, /*comment_id*/159, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"まゆ、探すのは得意なんです♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/56, /*comment_id*/160, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"迷ったときはぁ…どーんと進む !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/57, /*comment_id*/161, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"どんな不幸にも、負けませんから…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/58, /*comment_id*/162, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"へへ、ウチの出番だなッ ! さぁ、ついてこいッ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/59, /*comment_id*/163, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"どんな場所でだって、歌ってみせるよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/60, /*comment_id*/164, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"走るのは得意ですからっ ! ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/61, /*comment_id*/165, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"整備はバッチリだよっ♪アクセル全開 !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/62, /*comment_id*/166, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"さぁ、我が発明をお披露目といこう !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/63, /*comment_id*/167, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"立ち止まらないよ。どこまでだって !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/64, /*comment_id*/168, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"頼られたのなら、応えなきゃいけないわね", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/65, /*comment_id*/169, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"アタシのボディで悩殺してア・ゲ・ル♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/66, /*comment_id*/170, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"タフネスとガッツ ! アタシ流のファイトでいくよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/67, /*comment_id*/171, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"オトナなりのやり方、みせてアゲル♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/68, /*comment_id*/172, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"知恵を貸すわ。さぁ、落ち着いていきましょう", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/69, /*comment_id*/173, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ふふ、わかるわ。私の助けが必要なのね !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/70, /*comment_id*/174, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"なんだよ水臭いな…一緒にいくよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/71, /*comment_id*/175, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"私の眼鏡にかかれば、ぜんぶお見通しです !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/72, /*comment_id*/176, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"おお…これが異世界転生…違うっスか？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/73, /*comment_id*/177, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"よし…君の手腕を見せてくれ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/74, /*comment_id*/178, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"私のロックは止められないぜっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/75, /*comment_id*/179, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"身のこなしには自信アリ ! 頼ってくれていいよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/76, /*comment_id*/180, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"千枝にもできること、ありますか？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/77, /*comment_id*/181, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"私を必要としてくださるのなら…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/78, /*comment_id*/182, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"貴方のためなら。やれるところまで、やってみるわ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/79, /*comment_id*/183, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"まったく…君といると飽きないな", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/80, /*comment_id*/184, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"私の手が、何かを為すお手伝いができるのなら", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/81, /*comment_id*/185, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"美波、全力でサポートしますね !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/82, /*comment_id*/186, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"いざという時は、私の弓で…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/83, /*comment_id*/187, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"これは心象でしょうか…興味深いですね", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/84, /*comment_id*/188, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"任せてください。ロジカルに行きましょう", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/85, /*comment_id*/189, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"物語を読み解くのであれば…お力添えいたします", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/86, /*comment_id*/190, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"情報収集と思考…それが一番の武器よ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/87, /*comment_id*/191, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ライラさんも、お助けしますですー", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/88, /*comment_id*/192, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"釣りみたいに、焦らず、根気よくいくのれす～", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/89, /*comment_id*/193, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"これは…異世界レベル ! !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/90, /*comment_id*/194, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"よし、歌でも歌おうか。勇気が出るヤツをさ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/91, /*comment_id*/195, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"頭を使って、トライ＆エラーで進みましょ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/92, /*comment_id*/196, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"探求…この場所もまた、興味深いわね", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/93, /*comment_id*/197, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"絵本の世界だなんて…え、ほんと？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/94, /*comment_id*/198, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"堕天使の炎、その目に焼き付けるがいい !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/95, /*comment_id*/199, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"この景色は、私に何を教えてくれるのかしら", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/96, /*comment_id*/200, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"この世界…ワインはあるのかしら", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/97, /*comment_id*/201, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"絵本かー。昔は好きだったなー", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/98, /*comment_id*/202, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ムカシムカシ、あるところに…チガウ？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/99, /*comment_id*/203, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"深い森の中というのも、海に似て、いいものですね", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/100, /*comment_id*/204, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ぴにゃこら太…どこかにいませんか？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/101, /*comment_id*/205, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"…冒険、いく。\nちょっと……どきどき……", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/102, /*comment_id*/210, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"隠されていて、アブナくて、探したくなるもの…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/103, /*comment_id*/211, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"みんなの手助けなら任せて。得意なの", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/104, /*comment_id*/212, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"こーいうときは、直感で進むっすよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/105, /*comment_id*/213, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"この場所は、不思議な音がしますね", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/106, /*comment_id*/214, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"みんな一緒に、いこう、ね…えへへ♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/107, /*comment_id*/215, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"困ったときはぁ、あやかのおねだりでなんとかするねぇ♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/108, /*comment_id*/216, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"冒険の予感 ! もう待ちきれませんっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/109, /*comment_id*/217, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"幻想的で…まるで、オペラの舞台のような場所…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/110, /*comment_id*/218, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"わぁ…♪ちょっとだけ、スケッチさせてください", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/111, /*comment_id*/219, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"占いの結果に従えば、余裕よ余裕 !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/112, /*comment_id*/220, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"流浪人シューコちゃんも、妙なとこに来たもんだー", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/113, /*comment_id*/221, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"プロデューサー殿の剣となりましょう ! いざっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/114, /*comment_id*/222, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ま、まずは落ち着いて…はい、いきましょう", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/115, /*comment_id*/223, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ご褒美は、キスでいいわよ♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/116, /*comment_id*/224, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"友だちのためのロジック…全力でいくね !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/117, /*comment_id*/225, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"いきます…選んでくれて嬉しいな…はっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/118, /*comment_id*/226, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"自分の夢を一緒に散策するなんて、ひどいはずかしめなんですけど…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/119, /*comment_id*/227, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"おとぎ話の中…冒険、しますか？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/120, /*comment_id*/228, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"地雷除去ならお任せあれ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/121, /*comment_id*/229, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"へっへー、ゴールに届けるのならオレに任せろ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/122, /*comment_id*/230, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"なんともナンセンスな世界だが、楽しませてもらおう", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/123, /*comment_id*/231, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"仕方ねぇ、手伝ってやるよ。お前の頼みだからな", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/124, /*comment_id*/232, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"歌うぐらいしかできませんけど、少しでも力になれば…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/125, /*comment_id*/233, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"みなさんに、幸運がありますよう♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/126, /*comment_id*/234, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"切り込み隊長は未央ちゃんにお任せあれっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/127, /*comment_id*/235, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"今日のお散歩は、少し変わった場所ですね♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/128, /*comment_id*/236, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"せっかくだし、ちょっと寄り道もしてみない？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/129, /*comment_id*/237, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"かおる、せんせぇと一緒に探検しまーっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/130, /*comment_id*/238, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"音楽は共通言語さ。さぁ、かき鳴らそうかっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/131, /*comment_id*/239, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"私の出番？ふふ、きちんと見ててね !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/132, /*comment_id*/240, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"今日のランニングコースは、なかなかハード !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/133, /*comment_id*/241, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"流れを読むのは得意よ ! サーファーの勘ってやつ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/134, /*comment_id*/242, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"わたしの爆笑ギャグで、道を切り開きますっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/135, /*comment_id*/243, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"なになに、みんなで大冒険？みりあもやる～っ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/136, /*comment_id*/244, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"バスケで鍛えたフットワーク、見せてあげるッ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/137, /*comment_id*/245, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"とりあえず、このへん走ってみよっか !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/138, /*comment_id*/246, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ゆいとプロデューサーちゃんなら無敵っしょ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/139, /*comment_id*/247, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"4番、姫川…狙うは満塁ホームラン !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/140, /*comment_id*/249, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"なになに？柚チャンも混ぜろーっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/141, /*comment_id*/250, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"この着ぐるみなら、防御も万全たい !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/142, /*comment_id*/251, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"あまーいものがほしくなったら、言ってくださいねぇ♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/143, /*comment_id*/253, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"みんなをもーっと元気にしちゃいますよー !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/144, /*comment_id*/254, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"レイナサマを罠にかけようなんて、100年早いわ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/145, /*comment_id*/255, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"こういうときはぁ、みんなで協力 ! だよねぇ☆", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/146, /*comment_id*/256, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"と、トモダチのためなら…いっくぜぇぇぇぇエエ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/147, /*comment_id*/257, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"悪いやつの相手ならまっかせなさい !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/148, /*comment_id*/258, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ユッコのサイキック、ご覧あれっ ! !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/149, /*comment_id*/259, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"かき分けて進むのは得意 ! なんてねっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/150, /*comment_id*/260, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"しょーがないわねぇ、手伝ってあげるわよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/151, /*comment_id*/261, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"いいわ、支配者が誰か、教えてあげる…", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/152, /*comment_id*/262, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"そなたの探し物を、お手伝いいたしましょー", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/153, /*comment_id*/263, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"知らないお花ばっかり…ホントに絵本の中なんだ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/154, /*comment_id*/264, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"はっぴーお届け、そらちんでりばりー、れっつごー☆", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/155, /*comment_id*/265, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"さぁ、ワタシと一緒に駆けぬけましょ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/156, /*comment_id*/266, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"フレーフレー、み・ん・な !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/157, /*comment_id*/267, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"オッケー★頼りにしてて !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/158, /*comment_id*/268, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"やっほー☆楽しんでこー !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/159, /*comment_id*/269, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"よっしゃ ! いくか ! 大きな声で探そうぜ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/160, /*comment_id*/270, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"トラーイっ ! 私はもう止められませんよっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/161, /*comment_id*/271, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"にょっわー☆きらりん大活躍 ! 頑張るにぃ☆", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/162, /*comment_id*/272, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"頼りにしてますね、プロデューサーさん♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/163, /*comment_id*/273, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"一緒なら安心だナ ! とりあえず、踊るカ？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/164, /*comment_id*/274, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"根性には自信があるの ! さ、いきましょ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/165, /*comment_id*/275, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"特製パフェひとつ、お待たせいたしましたー !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/166, /*comment_id*/280, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"鬼の特攻隊長、向井拓海…いくぜオラァッ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/167, /*comment_id*/283, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"絵本の中でごぜーますか ! ？すげーっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/168, /*comment_id*/284, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"むふふ、むふ…あら？ついに、妄想の中に…？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/169, /*comment_id*/285, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ほっとけないからね ! ウチもいくよっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/170, /*comment_id*/286, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"へっへー、パーッと走り抜けちゃお !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/171, /*comment_id*/287, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ダーリンのお願いだもの ! お手伝いしてあげるワ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/172, /*comment_id*/288, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"軽いステップで、どんどん進むよ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/173, /*comment_id*/289, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"Here comes\nMIYOSHI\nSANA ! ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/174, /*comment_id*/290, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"義を見てせざるはなんとやら ! 力を貸すよっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/175, /*comment_id*/291, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"無敵のハリセンの威力、見せたるで !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/176, /*comment_id*/292, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ニンッ ! 主命に従い、サポートいたしますっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/177, /*comment_id*/293, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"おう、うちにどーんと任せとけや !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/178, /*comment_id*/294, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"宝石とか見つけたら、持って帰ってもええ？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/179, /*comment_id*/295, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"旅のおともなら、あたしに決まり !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/180, /*comment_id*/296, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ななな、なんですかこの場所は !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/181, /*comment_id*/297, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"んもー☆はぁとがいないと、ダメなんだから♪", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/182, /*comment_id*/298, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"アタシが来たから、もう心配ないっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/183, /*comment_id*/300, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"ブリッツェーン、いきますよーっ !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/184, /*comment_id*/304, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"りんごパワー、見せちゃうんご !", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/185, /*comment_id*/305, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"了解デス。…まぁ、任せてよ", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/186, /*comment_id*/306, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"どーも、歩く本能寺、りあむちゃんでーす", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/187, /*comment_id*/307, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"あはっ♪いいよ、上手に使ってみせて？", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/188, /*comment_id*/308, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"お前の従者になった覚えはありませんが", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/189, /*comment_id*/309, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"凪を使いこなせるか、お手並み拝見", /*insert_word_type*/0);
INSERT INTO `bremer_card_comment` VALUES (/*id*/190, /*comment_id*/310, /*use_type*/1, /*index*/1, /*voice_flag*/0, /*description*/"はーのこと、頼りにしてね !", /*insert_word_type*/0);
CREATE INDEX 'bremer_card_comment_0_comment_id' on 'bremer_card_comment'('comment_id');
