CREATE TABLE 'campaign_description' ('id' INTEGER NOT NULL, 'title' TEXT NOT NULL, 'description' TEXT NOT NULL, 'page_index' INTEGER NOT NULL, 'panel_icon_id' INTEGER NOT NULL, 'panel_frame_id' INTEGER NOT NULL, 'disp_order' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `campaign_description` VALUES (/*id*/1, /*title*/"レッスン", /*description*/"レッスン大成功率{0}倍 !", /*page_index*/504, /*panel_icon_id*/2, /*panel_frame_id*/0, /*disp_order*/111);
INSERT INTO `campaign_description` VALUES (/*id*/14, /*title*/"LIVE", /*description*/"LIVEでの獲得マニー数{0}倍 ! ", /*page_index*/100, /*panel_icon_id*/4, /*panel_frame_id*/0, /*disp_order*/106);
INSERT INTO `campaign_description` VALUES (/*id*/24, /*title*/"LIVE", /*description*/"LIVEでの獲得経験値{0}倍 ! ", /*page_index*/100, /*panel_icon_id*/4, /*panel_frame_id*/0, /*disp_order*/109);
INSERT INTO `campaign_description` VALUES (/*id*/34, /*title*/"LIVE", /*description*/"LIVEでの獲得親愛度{0}倍 ! ", /*page_index*/100, /*panel_icon_id*/4, /*panel_frame_id*/0, /*disp_order*/107);
INSERT INTO `campaign_description` VALUES (/*id*/44, /*title*/"LIVE", /*description*/"LIVEでの獲得ファン数{0}倍 ! ", /*page_index*/100, /*panel_icon_id*/4, /*panel_frame_id*/0, /*disp_order*/108);
INSERT INTO `campaign_description` VALUES (/*id*/71, /*title*/"LIVE", /*description*/"LIVEで特別な報酬が出現 !", /*page_index*/100, /*panel_icon_id*/4, /*panel_frame_id*/0, /*disp_order*/110);
INSERT INTO `campaign_description` VALUES (/*id*/81, /*title*/"ガシャ", /*description*/"シンデレラフェス ブラン開催中 ! ", /*page_index*/400, /*panel_icon_id*/7, /*panel_frame_id*/155, /*disp_order*/3);
INSERT INTO `campaign_description` VALUES (/*id*/84, /*title*/"ガシャ", /*description*/"プラチナオーディションガシャ1日1回無料 !", /*page_index*/400, /*panel_icon_id*/7, /*panel_frame_id*/155, /*disp_order*/2);
INSERT INTO `campaign_description` VALUES (/*id*/85, /*title*/"ガシャ", /*description*/"プラチナオーディションガシャ1日1回10連無料 !", /*page_index*/400, /*panel_icon_id*/7, /*panel_frame_id*/155, /*disp_order*/1);
INSERT INTO `campaign_description` VALUES (/*id*/86, /*title*/"ガシャ", /*description*/"シンデレラフェス ノワール開催中 ! ", /*page_index*/400, /*panel_icon_id*/7, /*panel_frame_id*/155, /*disp_order*/4);
INSERT INTO `campaign_description` VALUES (/*id*/87, /*title*/"ガシャ", /*description*/"プラチナガシャ1日1回無料 !", /*page_index*/400, /*panel_icon_id*/7, /*panel_frame_id*/155, /*disp_order*/0);
INSERT INTO `campaign_description` VALUES (/*id*/88, /*title*/"ガシャ", /*description*/"プラチナガシャ開催期間ごとに\n初回10連無料 !", /*page_index*/400, /*panel_icon_id*/7, /*panel_frame_id*/155, /*disp_order*/0);
INSERT INTO `campaign_description` VALUES (/*id*/89, /*title*/"ガシャ", /*description*/"ログインボーナスで\nプラチナガシャ1日1回無料 !", /*page_index*/400, /*panel_icon_id*/7, /*panel_frame_id*/155, /*disp_order*/0);
INSERT INTO `campaign_description` VALUES (/*id*/92, /*title*/"営業", /*description*/"営業での獲得経験値{0}倍 ! ", /*page_index*/3300, /*panel_icon_id*/6, /*panel_frame_id*/0, /*disp_order*/0);
INSERT INTO `campaign_description` VALUES (/*id*/93, /*title*/"営業", /*description*/"営業での獲得ファン数{0}倍 ! ", /*page_index*/3300, /*panel_icon_id*/6, /*panel_frame_id*/0, /*disp_order*/0);
INSERT INTO `campaign_description` VALUES (/*id*/111, /*title*/"LIVE", /*description*/"ドリームユニットキャンペーン実施中 !", /*page_index*/100, /*panel_icon_id*/4, /*panel_frame_id*/0, /*disp_order*/101);
INSERT INTO `campaign_description` VALUES (/*id*/112, /*title*/"アイドル編成", /*description*/"ルームのお気に入り編成で未所持SSレア・Sレア衣装が着用可能 !", /*page_index*/503, /*panel_icon_id*/2, /*panel_frame_id*/0, /*disp_order*/102);
INSERT INTO `campaign_description` VALUES (/*id*/113, /*title*/"プロデュースノート", /*description*/"フォトスタジオで未所持SSレアの衣装が着用可能 !", /*page_index*/907, /*panel_icon_id*/8, /*panel_frame_id*/0, /*disp_order*/103);
INSERT INTO `campaign_description` VALUES (/*id*/114, /*title*/"デレスポ", /*description*/"フォトスタジオ、VRLIVEでドリームユニットキャンペーン中 !", /*page_index*/14, /*panel_icon_id*/11, /*panel_frame_id*/0, /*disp_order*/104);
INSERT INTO `campaign_description` VALUES (/*id*/115, /*title*/"キャンペーン", /*description*/"SSレアアイドル勧誘チャレンジ開催中 !", /*page_index*/4000, /*panel_icon_id*/2, /*panel_frame_id*/0, /*disp_order*/105);
INSERT INTO `campaign_description` VALUES (/*id*/201, /*title*/"オートLIVEチケット", /*description*/"ログインボーナスでオートLIVE\nチケットを追加獲得 ! ", /*page_index*/100, /*panel_icon_id*/4, /*panel_frame_id*/0, /*disp_order*/0);
INSERT INTO `campaign_description` VALUES (/*id*/202, /*title*/"LIVE PARTY!!", /*description*/"LIVE PARTY!!の獲得スター\nエンブレムが2倍 !", /*page_index*/2900, /*panel_icon_id*/13, /*panel_frame_id*/0, /*disp_order*/0);
INSERT INTO `campaign_description` VALUES (/*id*/205, /*title*/"LIVE", /*description*/"LIVEでスターエンブレムを\n確率で獲得 !", /*page_index*/100, /*panel_icon_id*/4, /*panel_frame_id*/0, /*disp_order*/0);
INSERT INTO `campaign_description` VALUES (/*id*/206, /*title*/"当日限定スタミナドリンク", /*description*/"ログインボーナスで当日限定\nスタミナドリンク50を獲得 !", /*page_index*/703, /*panel_icon_id*/17, /*panel_frame_id*/0, /*disp_order*/0);
