CREATE TABLE 'card_subtype' ('card_data_id' INTEGER NOT NULL, 'sub_attribute' INTEGER NOT NULL, PRIMARY KEY('card_data_id'));
INSERT INTO `card_subtype` VALUES (/*card_data_id*/101295, /*sub_attribute*/3);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/101296, /*sub_attribute*/3);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/101317, /*sub_attribute*/2);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/101318, /*sub_attribute*/2);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/201323, /*sub_attribute*/1);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/201324, /*sub_attribute*/1);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/201355, /*sub_attribute*/3);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/201356, /*sub_attribute*/3);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/201377, /*sub_attribute*/1);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/201378, /*sub_attribute*/1);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/301267, /*sub_attribute*/2);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/301268, /*sub_attribute*/2);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/301295, /*sub_attribute*/1);
INSERT INTO `card_subtype` VALUES (/*card_data_id*/301296, /*sub_attribute*/1);
