CREATE TABLE 'carnival_rankuptext' ('event_id' INTEGER NOT NULL, 'rank' INTEGER NOT NULL, 'word_num' INTEGER NOT NULL, 'word_text' TEXT NOT NULL, 'icon' INTEGER NOT NULL, 'position' INTEGER NOT NULL);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/2, /*word_num*/1, /*word_text*/"楽しいカーニバルのはじまりだにぃ !¥nキラキラのきらりん星を目指して、しゅっぱーつ !", /*icon*/300033, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/2, /*word_num*/2, /*word_text*/"星が奏でるメロディーで、みなさまの旅を彩ります。¥nさぁごゆっくり、お楽しみくださいませ♪", /*icon*/100171, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/2, /*word_num*/3, /*word_text*/"星の向こうには、何がいるかな……。¥n新しいトモダチとか、見つかるかも……フヒヒ。", /*icon*/300069, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/3, /*word_num*/1, /*word_text*/"O・MA・TA・SE☆ 瑛梨華ちんたちの歌とダンスで、¥nみんなをもっと笑顔にするからね☆¥nこの想い、TO・DO・KE☆", /*icon*/100341, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/3, /*word_num*/2, /*word_text*/"みんなのすまいるを、お空の星も楽しみにしてるよ☆¥n夢のぱわーで、宇宙の果てまでれっつ・ごー☆", /*icon*/300023, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/4, /*word_num*/1, /*word_text*/"みんなの応援のおかげで、私たちはもっと頑張れます !¥n空の向こう側まで届くような歌、¥nみんなで歌っていきましょうね♪", /*icon*/100001, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/4, /*word_num*/2, /*word_text*/"うん♪ みやびぃたちなら、きっとできるよねぇ。¥nだってみんなの力を合わせれば、¥nできないことなんてないもん♪", /*icon*/100183, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/4, /*word_num*/3, /*word_text*/"はい……♪¥n暗い夜でも、月明かりが照らしてくれるように……¥nみなさんの心に、寄り添って歌いますから……。", /*icon*/200219, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/7, /*word_num*/1, /*word_text*/"古来から、人は夜空に想いを馳せてきた。¥nそして今、私たちはその先頭に立っている……感慨深いものね。", /*icon*/200303, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/7, /*word_num*/2, /*word_text*/"私たちも、夜空に夢を描きましょう。¥nたくさんの、サズヴィエーズヂイ……星座たちと一緒に、¥n私たちの光を……。", /*icon*/200039, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/9, /*word_num*/1, /*word_text*/"見よ、空に輝く星たちを !¥nそろって光る三ツ星だけじゃないよ。¥nみんなの想いの数だけ、星があるんだっ !", /*icon*/300001, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/9, /*word_num*/2, /*word_text*/"誰もがそれぞれ、誰かにとっての一番星。¥nだったら進むしかないよね、どこまでも自分らしく♪", /*icon*/200085, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/9, /*word_num*/3, /*word_text*/"信じて進めば、そこがうちらの道になる。¥nみんなが描いた星の道を、存分に見せつけるんじゃ !", /*icon*/300129, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/11, /*word_num*/1, /*word_text*/"キラキラわちゃわちゃ、楽しいことがいっぱいの宇宙 !¥nみんなもおいでよ、はーたちと一緒に楽しもー !", /*icon*/200657, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/11, /*word_num*/2, /*word_text*/"今を楽しむ我々の声は、どこまでも響くことでしょう。¥nそう、はるか彼方のアンドロメダまでも…… !", /*icon*/200125, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/11, /*word_num*/3, /*word_text*/"夢や希望を動力源にして、無限の宇宙を飛んでいく。¥nそんなみんなのステージに、幸運を……ってね♪", /*icon*/100087, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/12, /*word_num*/1, /*word_text*/"重力なんか振り切って、私たちは進むんだ !¥n想いの力があれば、どこへだって行けるよ !", /*icon*/200015, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/12, /*word_num*/2, /*word_text*/"空に広がる天の川も、越えてみせます。¥nロマンスは、宇宙よりも広いですから……♪", /*icon*/100089, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/13, /*word_num*/1, /*word_text*/"全宇宙から、みんなの声が……星の力が集まってくる感じ。¥nならこっちも、期待に応えるしかないデスよね。", /*icon*/200671, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7008, /*rank*/13, /*word_num*/2, /*word_text*/"欲しいものは、ちゃんと受け取りました。¥n次は私たちが、みんなを宇宙に……¥nじゃなくて、夢中にさせちゃいます♪", /*icon*/200023, /*position*/1);
CREATE INDEX 'carnival_rankuptext_0_rank_1_word_num' on 'carnival_rankuptext'('rank','word_num');
