CREATE TABLE 'carnival_performer_idol' ('event_id' INTEGER NOT NULL, 'chara_id' INTEGER NOT NULL);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/159);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/304);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/307);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/105);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/106);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/115);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/122);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/126);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/131);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/147);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/178);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/198);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/230);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/167);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/174);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/184);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/188);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/201);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/219);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/235);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/238);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/260);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/261);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/273);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/280);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7014, /*chara_id*/285);
CREATE INDEX 'carnival_performer_idol_0_event_id' on 'carnival_performer_idol'('event_id');
