CREATE TABLE 'carnival_story_detail' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'open_step_id' INTEGER NOT NULL, 'next_detail_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `carnival_story_detail` VALUES (/*id*/4117, /*event_id*/7001, /*type*/1, /*open_step_id*/0, /*next_detail_id*/4118);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4118, /*event_id*/7001, /*type*/0, /*open_step_id*/2, /*next_detail_id*/4119);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4119, /*event_id*/7001, /*type*/0, /*open_step_id*/3, /*next_detail_id*/4120);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4120, /*event_id*/7001, /*type*/0, /*open_step_id*/4, /*next_detail_id*/4121);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4121, /*event_id*/7001, /*type*/0, /*open_step_id*/5, /*next_detail_id*/4122);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4122, /*event_id*/7001, /*type*/0, /*open_step_id*/6, /*next_detail_id*/4123);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4123, /*event_id*/7001, /*type*/2, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4124, /*event_id*/7001, /*type*/0, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4125, /*event_id*/7001, /*type*/0, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4202, /*event_id*/7002, /*type*/1, /*open_step_id*/0, /*next_detail_id*/4203);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4203, /*event_id*/7002, /*type*/0, /*open_step_id*/2, /*next_detail_id*/4204);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4204, /*event_id*/7002, /*type*/0, /*open_step_id*/3, /*next_detail_id*/4205);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4205, /*event_id*/7002, /*type*/0, /*open_step_id*/4, /*next_detail_id*/4206);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4206, /*event_id*/7002, /*type*/0, /*open_step_id*/5, /*next_detail_id*/4207);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4207, /*event_id*/7002, /*type*/0, /*open_step_id*/6, /*next_detail_id*/4215);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4208, /*event_id*/7002, /*type*/3, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4209, /*event_id*/7002, /*type*/3, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4210, /*event_id*/7002, /*type*/3, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4211, /*event_id*/7002, /*type*/3, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4212, /*event_id*/7002, /*type*/3, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4213, /*event_id*/7002, /*type*/3, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4214, /*event_id*/7002, /*type*/3, /*open_step_id*/0, /*next_detail_id*/0);
INSERT INTO `carnival_story_detail` VALUES (/*id*/4215, /*event_id*/7002, /*type*/2, /*open_step_id*/0, /*next_detail_id*/0);
CREATE INDEX 'carnival_story_detail_0_event_id_1_type' on 'carnival_story_detail'('event_id','type');
