CREATE TABLE 'carnival_rank' ('event_id' INTEGER NOT NULL, 'rank' INTEGER NOT NULL, 'rank_bg' INTEGER NOT NULL, 'rank_icon' INTEGER NOT NULL, 'need_point' INTEGER NOT NULL, 'boothnum' INTEGER NOT NULL, 'medal_rate' INTEGER NOT NULL, 'resetflag' INTEGER NOT NULL, 'ranking_entry_flag' INTEGER NOT NULL);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/1, /*rank_bg*/1, /*rank_icon*/15, /*need_point*/2600, /*boothnum*/2, /*medal_rate*/1000, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/2, /*rank_bg*/1, /*rank_icon*/14, /*need_point*/4300, /*boothnum*/3, /*medal_rate*/1000, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/3, /*rank_bg*/1, /*rank_icon*/13, /*need_point*/6100, /*boothnum*/4, /*medal_rate*/1000, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/4, /*rank_bg*/1, /*rank_icon*/12, /*need_point*/9000, /*boothnum*/5, /*medal_rate*/1080, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/5, /*rank_bg*/1, /*rank_icon*/11, /*need_point*/11000, /*boothnum*/5, /*medal_rate*/1080, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/6, /*rank_bg*/1, /*rank_icon*/10, /*need_point*/12000, /*boothnum*/5, /*medal_rate*/1080, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/7, /*rank_bg*/1, /*rank_icon*/9, /*need_point*/22000, /*boothnum*/6, /*medal_rate*/1150, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/8, /*rank_bg*/1, /*rank_icon*/8, /*need_point*/28000, /*boothnum*/6, /*medal_rate*/1150, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/9, /*rank_bg*/1, /*rank_icon*/7, /*need_point*/45000, /*boothnum*/7, /*medal_rate*/1150, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/10, /*rank_bg*/1, /*rank_icon*/6, /*need_point*/50000, /*boothnum*/7, /*medal_rate*/1260, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/11, /*rank_bg*/1, /*rank_icon*/5, /*need_point*/69000, /*boothnum*/8, /*medal_rate*/1260, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/12, /*rank_bg*/1, /*rank_icon*/4, /*need_point*/94000, /*boothnum*/9, /*medal_rate*/1260, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/13, /*rank_bg*/1, /*rank_icon*/3, /*need_point*/125000, /*boothnum*/10, /*medal_rate*/1420, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/14, /*rank_bg*/1, /*rank_icon*/2, /*need_point*/150000, /*boothnum*/10, /*medal_rate*/1580, /*resetflag*/1, /*ranking_entry_flag*/0);
INSERT INTO `carnival_rank` VALUES (/*event_id*/7002, /*rank*/15, /*rank_bg*/1, /*rank_icon*/1, /*need_point*/0, /*boothnum*/10, /*medal_rate*/1800, /*resetflag*/1, /*ranking_entry_flag*/1);
CREATE INDEX 'carnival_rank_0_rank' on 'carnival_rank'('rank');
