CREATE TABLE 'carnival_reward_rank' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'rank' INTEGER NOT NULL, 'reward_type' INTEGER NOT NULL, 'reward_id' INTEGER NOT NULL, 'reward_value' INTEGER NOT NULL, 'add_value_1' INTEGER NOT NULL, 'add_value_2' INTEGER NOT NULL, 'add_value_3' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `carnival_reward_rank` VALUES (/*id*/1, /*event_id*/7004, /*rank*/2, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/10, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/2, /*event_id*/7004, /*rank*/3, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/20, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/3, /*event_id*/7004, /*rank*/4, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/30, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/4, /*event_id*/7004, /*rank*/5, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/30, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/5, /*event_id*/7004, /*rank*/6, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/30, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/6, /*event_id*/7004, /*rank*/7, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/40, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/7, /*event_id*/7004, /*rank*/8, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/50, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/8, /*event_id*/7004, /*rank*/9, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/50, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/9, /*event_id*/7004, /*rank*/10, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/100, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/10, /*event_id*/7004, /*rank*/11, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/100, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/11, /*event_id*/7004, /*rank*/12, /*reward_type*/5, /*reward_id*/64004, /*reward_value*/200, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/12, /*event_id*/7004, /*rank*/13, /*reward_type*/7, /*reward_id*/4031, /*reward_value*/1, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/13, /*event_id*/7004, /*rank*/14, /*reward_type*/7, /*reward_id*/4032, /*reward_value*/1, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
INSERT INTO `carnival_reward_rank` VALUES (/*id*/14, /*event_id*/7004, /*rank*/15, /*reward_type*/7, /*reward_id*/4033, /*reward_value*/1, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0);
CREATE INDEX 'carnival_reward_rank_0_event_id' on 'carnival_reward_rank'('event_id');
