CREATE TABLE 'carnival_performer_idol' ('event_id' INTEGER NOT NULL, 'chara_id' INTEGER NOT NULL);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/119);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/133);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/161);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/229);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/231);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/293);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/309);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/106);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/109);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/117);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/139);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/155);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/164);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/168);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/171);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/174);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/183);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/195);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/205);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/222);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/225);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/310);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/241);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/242);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7011, /*chara_id*/268);
CREATE INDEX 'carnival_performer_idol_0_event_id' on 'carnival_performer_idol'('event_id');
