CREATE TABLE 'carnival_rankuptext' ('event_id' INTEGER NOT NULL, 'rank' INTEGER NOT NULL, 'word_num' INTEGER NOT NULL, 'word_text' TEXT NOT NULL, 'icon' INTEGER NOT NULL, 'position' INTEGER NOT NULL);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/2, /*word_num*/1, /*word_text*/"春といえば……眼鏡と猫ちゃんです !¥n猫ちゃんたち、このうららかな陽気に誘われて、¥nゴキゲンな顔を見せにきてくれるかもしれません♪", /*icon*/200011, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/2, /*word_num*/2, /*word_text*/"それは……絶対可愛いわね。¥nもし出会えたら、私も猫ちゃんに触れて、撫でまわして……¥nは、無理だから、できるだけそばで見守らせてちょうだい。", /*icon*/200207, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/3, /*word_num*/1, /*word_text*/"ん～ ! 最高のカーニバル日和だね♪¥nみんなの笑顔を乗せて、¥nアクセル全開で駆け抜けちゃおう !", /*icon*/100133, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/3, /*word_num*/2, /*word_text*/"あたしたちは止まらない、止められないっ !¥n誰も見たことのない世界まで、¥nみんなを連れていってあげるね !", /*icon*/300017, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/3, /*word_num*/3, /*word_text*/"幸せな景色をたくさん見つけるために、¥n顔を上げていきましょう。¥n進むべき道は、目の前に広がっていますよ♪", /*icon*/200337, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/4, /*word_num*/1, /*word_text*/"わぁ、とっても盛り上がってますねっ♪¥n私もうずうずしてきちゃいました !¥n智絵里ちゃん、思いきってぴょーんと飛び込んじゃいましょう !", /*icon*/300035, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/4, /*word_num*/2, /*word_text*/"ぴょっ、ぴょんぴょん、ぴーょん♪¥nふふっ……元気いっぱいのうさぎさんみたいに、¥n私たちもカーニバルを全力で楽しみます♪", /*icon*/100015, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/7, /*word_num*/1, /*word_text*/"おっしゃあああ ! !¥nみんなの歓声でパワーが漲ってきたぁぁああー ! !¥nアタシら3人も、ガンガン盛り上げていくぞーっ ! !", /*icon*/300081, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/7, /*word_num*/2, /*word_text*/"パワフルな歌とダンスで、みんなを楽しませます♪¥n欲張りなメガ盛りパフェみたいな時間、¥nめいっぱい味わってくださいね♪", /*icon*/300255, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/7, /*word_num*/3, /*word_text*/"疲れだって、私たちが吹き飛ばしちゃいますよ !¥n一緒に笑って、たくさん体を動かして、¥n最高の瞬間を重ねていきましょうっ !", /*icon*/300319, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/9, /*word_num*/1, /*word_text*/"ああ、聞こえてくるわね。騒がしい鳴き声が。¥nまったく……キツい躾けが必要かしら。¥n鞭の味、今すぐ教えてあげてもいいのよ。", /*icon*/300283, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/9, /*word_num*/2, /*word_text*/"じゃじゃ馬を馴らすのは、ワタシも得意よ♪¥nふふっ……しっかり乗りこなして、大自然を駆け抜けるような、¥nとっても刺激的な時間にしていきましょ♪", /*icon*/300025, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/11, /*word_num*/1, /*word_text*/"世界は広いわ。¥nけれど、どんな場所だろうと、ダンスがあれば通じ合える !¥nさあ、ともに踊りましょう。魂が躍動するままに !", /*icon*/220227, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/11, /*word_num*/2, /*word_text*/"世界はラブ＆ピースで繋がっていますからね。¥nみんなで手を取り合って、歌って踊って、¥n幸せを分かち合いたいです♪", /*icon*/100221, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/11, /*word_num*/3, /*word_text*/"新しい世界に飛び込んでみるのって、刺激的よね♪¥n知らなかった自分が、見つかるかもしれないし……¥nさあ、私たちと一緒にフライトしましょう♪", /*icon*/300261, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/12, /*word_num*/1, /*word_text*/"雫しゃんからもらった牛乳飲んで、¥nくるみ、元気もりもりなのぉ !¥nみんなでたくさん楽しんで、たくさん笑おうねぇ♪", /*icon*/100265, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/12, /*word_num*/2, /*word_text*/"あたしもあたしも ! 牛乳飲んで、¥n素晴らしいお山に囲まれて、元気もりもりの山盛り♪¥nああ……どっちからいこうか、迷っちゃうっ !", /*icon*/100159, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/12, /*word_num*/3, /*word_text*/"うふふー、搾りたてのパワーが、¥n私たちの背中を押してくれてますねー。¥nここから、もーっとのびのびと、胸を張っていきますよー♪", /*icon*/300071, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/13, /*word_num*/1, /*word_text*/"わぁ～、すっごく盛り上がってるにゃあ !¥nみんなが心の底から楽しんでる姿を見ると、嬉しくなるね♪¥nみくもめいっぱい、いっくにゃ～っ !", /*icon*/100019, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7013, /*rank*/13, /*word_num*/2, /*word_text*/"みんなにとって、忘れられない¥nハッピーな思い出になりますように……♪¥n最後の最後まで、ナナたちも楽しみつくしましょう !", /*icon*/100037, /*position*/1);
CREATE INDEX 'carnival_rankuptext_0_rank_1_word_num' on 'carnival_rankuptext'('rank','word_num');
