CREATE TABLE 'carnival_rankuptext' ('event_id' INTEGER NOT NULL, 'rank' INTEGER NOT NULL, 'word_num' INTEGER NOT NULL, 'word_text' TEXT NOT NULL, 'icon' INTEGER NOT NULL, 'position' INTEGER NOT NULL);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/2, /*word_num*/1, /*word_text*/"聞こえるのは、旅が始まる音……。¥nこれから先、貴方は苦難の訪れとなる音も、¥n高鳴る鼓動の音も聞くでしょう……。", /*icon*/200872, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/2, /*word_num*/2, /*word_text*/"未知の世界を歩くときは、不安がつきもの。¥nでも、どんな世界にも、ラブとピースは宿りますっ !¥nさぁ、探しに行きましょう♪", /*icon*/101194, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/2, /*word_num*/3, /*word_text*/"私たちからは、せめて……歌を贈らせてください。¥n長い旅の中……あなたがずっと、あなたらしく¥n歩いていくための歌を……。", /*icon*/201358, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/2, /*word_num*/4, /*word_text*/"4人の歌が、過酷な旅の支えとなりますように……。¥n歌は空へ。祈りは心へ。あなたの旅が、¥nどうか幸多きものになりますように……。", /*icon*/100476, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/3, /*word_num*/1, /*word_text*/"フフッ……いい顔をしているね。¥n決して希望を捨てない、そんな想いがあるのだろう。¥n強い想いは、それだけで美しい力になるものだから。", /*icon*/201072, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/3, /*word_num*/2, /*word_text*/"小さき一歩でも、歩みは歩み。私たちは、¥n守られてばかりの世間知らずではいられません。¥nどうぞ、好奇心の赴くままに、前へと !", /*icon*/101074, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/4, /*word_num*/1, /*word_text*/"戦う覚悟はおありのようですわね。¥nわたくしたちにも、もちろんありますわ。¥n一蓮托生のこの想い、音楽でも示します♪", /*icon*/101044, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/4, /*word_num*/2, /*word_text*/"私たちはこの世界に、そして音楽にかけているのよ。¥n青空のような清廉な想いも、情念のような灰色の心も¥n……全ては、歌にのせられるから !", /*icon*/201116, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/7, /*word_num*/1, /*word_text*/"麗人とか貴族とか怪人とか、いろんな人に会えたね !¥nこの先にもたくさんの出会いがあるよ。たとえば、¥n目の前のあたしたちは……そう、ドーナツなんだっ♪", /*icon*/101206, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/7, /*word_num*/2, /*word_text*/"せ、せめてドーナツの妖精にしよう？¥nえっとね、私たちは、頑張ってるあなたを¥nあまーい気持ちにする、お茶会の妖精なんだ。", /*icon*/100370, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/7, /*word_num*/3, /*word_text*/"妖精だから、可愛くて、ちっちゃくて、ふわふわって¥n飛べちゃいますっ。私たちは、なりたい自分になれる¥nこの世界が、大好きなんですよっ !", /*icon*/100574, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/9, /*word_num*/1, /*word_text*/"この世界でどう生きましょうか。射手になることも¥nできれば、美食を究めることもできる。だからこそ……¥n世界の可能性を奪わせてはいけません。絶対に。", /*icon*/200306, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/9, /*word_num*/2, /*word_text*/"翠ちゃんは真面目だなー。でも、みゆきも同じ気持ち。¥n大好きなものにいっぱい囲まれて、素敵な大人に¥nなりたいからっ。翠ちゃんと一緒に !", /*icon*/100738, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/11, /*word_num*/1, /*word_text*/"後半戦、バテてないか……って、心配はいらないな。¥nここまで戦ってきたなら、アンタも立派なファイターだ。¥n想いの一撃、ぶちかませ ! !", /*icon*/201210, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/11, /*word_num*/2, /*word_text*/"たたかいつづけるのは……さだめにあらがい¥nつづけることー……。そっかー……。じゃあ、¥nおにんぎょうのままじゃ……いられないねー……。", /*icon*/100990, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/12, /*word_num*/1, /*word_text*/"ずいぶん遠いところまで来たな。君の軌跡を讃えよう。¥nだが、旅はまだまだ続くぞ？¥n君が進みたいと願う限り、いつまでも、どこまでも !", /*icon*/200604, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/12, /*word_num*/2, /*word_text*/"背中ならいくらでも押すっすよ ! エスコートも、¥nお望みとあらば。だって、いろいろあっても、¥n最後には楽しくなるのが冒険じゃないっすか♪", /*icon*/200764, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/12, /*word_num*/3, /*word_text*/"つまり、まだまだ止まれないってことだ !¥nアタシたちに見せてくれるんだろ？¥nシビれるくらいカッコイイ、夢ってやつを !", /*icon*/300296, /*position*/1);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/13, /*word_num*/1, /*word_text*/"世界がどうなっても、絶望なんてしないっ !¥n言い聞かせてるんじゃないよ。本当のことだもん。¥n輝ける日は、自分を好きになる未来は、絶対に来る !", /*icon*/201416, /*position*/0);
INSERT INTO `carnival_rankuptext` VALUES (/*event_id*/7017, /*rank*/13, /*word_num*/2, /*word_text*/"それまであたしたちは、歌って踊って、戦いつづける。¥nそれが「灰被り」……もっと言えば、アンタと一緒に¥n戦うことを決めた、「シンデレラガールズ」なんだ !", /*icon*/201418, /*position*/1);
CREATE INDEX 'carnival_rankuptext_0_rank_1_word_num' on 'carnival_rankuptext'('rank','word_num');
