CREATE TABLE 'carnival_performer_idol' ('event_id' INTEGER NOT NULL, 'chara_id' INTEGER NOT NULL);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/103);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/113);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/133);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/161);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/235);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/116);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/126);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/135);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/136);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/145);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/148);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/149);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/160);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/175);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/178);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/188);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/219);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/251);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/263);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/275);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/284);
INSERT INTO `carnival_performer_idol` VALUES (/*event_id*/7010, /*chara_id*/292);
CREATE INDEX 'carnival_performer_idol_0_event_id' on 'carnival_performer_idol'('event_id');
