CREATE TABLE 'cookie_swap_story_detail' ('id' INTEGER NOT NULL, 'campaign_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'next_detail_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3128, /*campaign_id*/20001, /*type*/1, /*next_detail_id*/0);
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3129, /*campaign_id*/20001, /*type*/0, /*next_detail_id*/3130);
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3130, /*campaign_id*/20001, /*type*/0, /*next_detail_id*/3131);
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3131, /*campaign_id*/20001, /*type*/0, /*next_detail_id*/3132);
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3132, /*campaign_id*/20001, /*type*/0, /*next_detail_id*/3136);
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3133, /*campaign_id*/20001, /*type*/3, /*next_detail_id*/0);
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3134, /*campaign_id*/20001, /*type*/3, /*next_detail_id*/0);
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3135, /*campaign_id*/20001, /*type*/3, /*next_detail_id*/0);
INSERT INTO `cookie_swap_story_detail` VALUES (/*id*/3136, /*campaign_id*/20001, /*type*/2, /*next_detail_id*/0);
