CREATE TABLE 'cookie_swap_pdata_event' ('id' INTEGER NOT NULL, 'campaign_id' INTEGER NOT NULL, 'sort' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'event_idol_id' TEXT NOT NULL, 'song_name' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/1, /*campaign_id*/20007, /*sort*/1, /*event_id*/3043, /*event_idol_id*/"", /*song_name*/"Majoram Therapie");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/2, /*campaign_id*/20007, /*sort*/2, /*event_id*/2048, /*event_idol_id*/"156,187", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/3, /*campaign_id*/20007, /*sort*/3, /*event_id*/1083, /*event_idol_id*/"", /*song_name*/"チョコ？レモ？どっち？？");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/4, /*campaign_id*/20007, /*sort*/4, /*event_id*/7012, /*event_idol_id*/"", /*song_name*/"Dreamy Anniversary");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/5, /*campaign_id*/20007, /*sort*/5, /*event_id*/6031, /*event_idol_id*/"225,140", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/6, /*campaign_id*/20007, /*sort*/6, /*event_id*/1084, /*event_idol_id*/"", /*song_name*/"ハートボイルドウォーズ");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/7, /*campaign_id*/20007, /*sort*/7, /*event_id*/5033, /*event_idol_id*/"", /*song_name*/"Isosceles");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/8, /*campaign_id*/20007, /*sort*/8, /*event_id*/2049, /*event_idol_id*/"129,169", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/9, /*campaign_id*/20007, /*sort*/9, /*event_id*/8006, /*event_idol_id*/"", /*song_name*/"N.O.R.~革命のための覚書~");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/10, /*campaign_id*/20007, /*sort*/10, /*event_id*/3044, /*event_idol_id*/"", /*song_name*/"Starry Night");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/11, /*campaign_id*/20007, /*sort*/11, /*event_id*/6032, /*event_idol_id*/"151,255", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/12, /*campaign_id*/20007, /*sort*/12, /*event_id*/1085, /*event_idol_id*/"", /*song_name*/"ミライコンパス");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/13, /*campaign_id*/20007, /*sort*/13, /*event_id*/5034, /*event_idol_id*/"", /*song_name*/"さやけき花の生命に");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/14, /*campaign_id*/20007, /*sort*/14, /*event_id*/1086, /*event_idol_id*/"", /*song_name*/"Shine In The Sky☆");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/15, /*campaign_id*/20007, /*sort*/15, /*event_id*/2050, /*event_idol_id*/"172,259", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/16, /*campaign_id*/20007, /*sort*/16, /*event_id*/7013, /*event_idol_id*/"", /*song_name*/"全開 ! ミラクルアドベンチャー !");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/17, /*campaign_id*/20007, /*sort*/17, /*event_id*/1087, /*event_idol_id*/"", /*song_name*/"Nightwear");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/18, /*campaign_id*/20007, /*sort*/18, /*event_id*/2051, /*event_idol_id*/"236,110", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/19, /*campaign_id*/20007, /*sort*/19, /*event_id*/3045, /*event_idol_id*/"", /*song_name*/"なつっこ音頭");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/20, /*campaign_id*/20007, /*sort*/20, /*event_id*/6033, /*event_idol_id*/"179,109", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/21, /*campaign_id*/20007, /*sort*/21, /*event_id*/8007, /*event_idol_id*/"", /*song_name*/"悠久星涼");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/22, /*campaign_id*/20007, /*sort*/22, /*event_id*/5035, /*event_idol_id*/"", /*song_name*/"Next Chapter");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/23, /*campaign_id*/20007, /*sort*/23, /*event_id*/2052, /*event_idol_id*/"186,239", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/24, /*campaign_id*/20007, /*sort*/24, /*event_id*/1088, /*event_idol_id*/"", /*song_name*/"Night Time Wander");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/25, /*campaign_id*/20007, /*sort*/25, /*event_id*/3046, /*event_idol_id*/"", /*song_name*/"さよならアロハ");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/26, /*campaign_id*/20007, /*sort*/26, /*event_id*/6034, /*event_idol_id*/"137,294", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/27, /*campaign_id*/20007, /*sort*/27, /*event_id*/1089, /*event_idol_id*/"", /*song_name*/"ノートの中のテラリウム");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/28, /*campaign_id*/20007, /*sort*/28, /*event_id*/7014, /*event_idol_id*/"", /*song_name*/"無限L∞PだLOVE♡");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/29, /*campaign_id*/20007, /*sort*/29, /*event_id*/2053, /*event_idol_id*/"136,196", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/30, /*campaign_id*/20007, /*sort*/30, /*event_id*/8008, /*event_idol_id*/"", /*song_name*/"Hardcore Toyworld");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/31, /*campaign_id*/20007, /*sort*/31, /*event_id*/5036, /*event_idol_id*/"", /*song_name*/"パジャマジャマ");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/32, /*campaign_id*/20007, /*sort*/32, /*event_id*/6035, /*event_idol_id*/"285,204", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/33, /*campaign_id*/20007, /*sort*/33, /*event_id*/1090, /*event_idol_id*/"", /*song_name*/"HALLOWEEN GAME");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/34, /*campaign_id*/20007, /*sort*/34, /*event_id*/3047, /*event_idol_id*/"", /*song_name*/"D-ark L-ily's Grin");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/35, /*campaign_id*/20007, /*sort*/35, /*event_id*/2054, /*event_idol_id*/"251,160", /*song_name*/"");
INSERT INTO `cookie_swap_pdata_event` VALUES (/*id*/36, /*campaign_id*/20007, /*sort*/36, /*event_id*/1091, /*event_idol_id*/"", /*song_name*/"この恋の解を答えなさい");
CREATE INDEX 'cookie_swap_pdata_event_0_campaign_id' on 'cookie_swap_pdata_event'('campaign_id');
CREATE INDEX 'cookie_swap_pdata_event_0_event_id' on 'cookie_swap_pdata_event'('event_id');
