CREATE TABLE 'cookie_swap_pdata_page_setting' ('id' INTEGER NOT NULL, 'campaign_id' INTEGER NOT NULL, 'page' INTEGER NOT NULL, 'sub_head' INTEGER NOT NULL, 'popup_sort' INTEGER NOT NULL, 'name' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/1, /*campaign_id*/20007, /*page*/1, /*sub_head*/2, /*popup_sort*/1, /*name*/"ログイン日数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/2, /*campaign_id*/20007, /*page*/1, /*sub_head*/2, /*popup_sort*/2, /*name*/"一番ログインしている時間帯");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/3, /*campaign_id*/20007, /*page*/2, /*sub_head*/2, /*popup_sort*/1, /*name*/"LIVEクリア回数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/4, /*campaign_id*/20007, /*page*/2, /*sub_head*/2, /*popup_sort*/2, /*name*/"一番LIVEをした日");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/5, /*campaign_id*/20007, /*page*/2, /*sub_head*/2, /*popup_sort*/3, /*name*/"LIVEクリア回数詳細");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/6, /*campaign_id*/20007, /*page*/3, /*sub_head*/3, /*popup_sort*/1, /*name*/"営業成功回数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/7, /*campaign_id*/20007, /*page*/3, /*sub_head*/3, /*popup_sort*/2, /*name*/"営業時間");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/8, /*campaign_id*/20007, /*page*/3, /*sub_head*/3, /*popup_sort*/3, /*name*/"営業成功回数詳細");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/9, /*campaign_id*/20007, /*page*/4, /*sub_head*/4, /*popup_sort*/1, /*name*/"消費したスタミナ");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/10, /*campaign_id*/20007, /*page*/4, /*sub_head*/5, /*popup_sort*/2, /*name*/"獲得した合計ファン数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/11, /*campaign_id*/20007, /*page*/4, /*sub_head*/5, /*popup_sort*/3, /*name*/"一番ファンを獲得したアイドル");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/12, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/1, /*name*/"合計イベントpt");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/13, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/2, /*name*/"合計アイドルpt");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/14, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/3, /*name*/"イベントptランキング");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/15, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/4, /*name*/"ハイスコアランキング");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/16, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/5, /*name*/"合計観客動員数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/17, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/6, /*name*/"合計獲得メダル枚数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/18, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/7, /*name*/"到達ランク");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/19, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/8, /*name*/"Voltageランキング");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/20, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/9, /*name*/"ルート合計進行");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/21, /*campaign_id*/20007, /*page*/5, /*sub_head*/6, /*popup_sort*/10, /*name*/"アイドル獲得回数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/23, /*campaign_id*/20007, /*page*/6, /*sub_head*/7, /*popup_sort*/1, /*name*/"無償スタージュエル　獲得数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/24, /*campaign_id*/20007, /*page*/6, /*sub_head*/7, /*popup_sort*/2, /*name*/"無償スタージュエル　使用数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/25, /*campaign_id*/20007, /*page*/6, /*sub_head*/8, /*popup_sort*/3, /*name*/"マニー　獲得数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/26, /*campaign_id*/20007, /*page*/6, /*sub_head*/8, /*popup_sort*/4, /*name*/"マニー　消費数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/27, /*campaign_id*/20007, /*page*/1, /*sub_head*/1, /*popup_sort*/1, /*name*/"プロデューサー名");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/28, /*campaign_id*/20008, /*page*/1, /*sub_head*/1, /*popup_sort*/1, /*name*/"プロデューサー名");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/29, /*campaign_id*/20008, /*page*/1, /*sub_head*/2, /*popup_sort*/2, /*name*/"ログイン日数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/30, /*campaign_id*/20008, /*page*/1, /*sub_head*/2, /*popup_sort*/3, /*name*/"一番ログインしている時間帯");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/31, /*campaign_id*/20008, /*page*/2, /*sub_head*/2, /*popup_sort*/1, /*name*/"LIVEクリア回数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/32, /*campaign_id*/20008, /*page*/2, /*sub_head*/2, /*popup_sort*/2, /*name*/"一番LIVEをした日");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/33, /*campaign_id*/20008, /*page*/2, /*sub_head*/2, /*popup_sort*/3, /*name*/"LIVEクリア回数詳細");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/34, /*campaign_id*/20008, /*page*/3, /*sub_head*/3, /*popup_sort*/1, /*name*/"営業成功回数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/35, /*campaign_id*/20008, /*page*/3, /*sub_head*/3, /*popup_sort*/2, /*name*/"営業時間");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/36, /*campaign_id*/20008, /*page*/3, /*sub_head*/3, /*popup_sort*/3, /*name*/"営業成功回数詳細");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/37, /*campaign_id*/20008, /*page*/4, /*sub_head*/4, /*popup_sort*/1, /*name*/"消費したスタミナ");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/38, /*campaign_id*/20008, /*page*/4, /*sub_head*/5, /*popup_sort*/2, /*name*/"獲得した合計ファン数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/39, /*campaign_id*/20008, /*page*/4, /*sub_head*/5, /*popup_sort*/3, /*name*/"一番ファンを獲得したアイドル");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/40, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/1, /*name*/"合計イベントpt");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/41, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/2, /*name*/"合計アイドルpt");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/42, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/3, /*name*/"イベントptランキング");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/43, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/4, /*name*/"ハイスコアランキング");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/44, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/5, /*name*/"合計観客動員数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/45, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/6, /*name*/"合計獲得メダル枚数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/46, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/7, /*name*/"到達ランク");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/47, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/8, /*name*/"Voltageランキング");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/48, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/9, /*name*/"ルート合計進行");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/49, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/10, /*name*/"アイドル獲得回数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/50, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/11, /*name*/"獲得アイドル種数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/51, /*campaign_id*/20008, /*page*/5, /*sub_head*/6, /*popup_sort*/12, /*name*/"絆Lv");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/52, /*campaign_id*/20008, /*page*/6, /*sub_head*/7, /*popup_sort*/1, /*name*/"無償スタージュエル　獲得数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/53, /*campaign_id*/20008, /*page*/6, /*sub_head*/7, /*popup_sort*/2, /*name*/"無償スタージュエル　使用数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/54, /*campaign_id*/20008, /*page*/6, /*sub_head*/8, /*popup_sort*/3, /*name*/"マニー　獲得数");
INSERT INTO `cookie_swap_pdata_page_setting` VALUES (/*id*/55, /*campaign_id*/20008, /*page*/6, /*sub_head*/8, /*popup_sort*/4, /*name*/"マニー　消費数");
CREATE INDEX 'cookie_swap_pdata_page_setting_0_campaign_id' on 'cookie_swap_pdata_page_setting'('campaign_id');
CREATE INDEX 'cookie_swap_pdata_page_setting_0_campaign_id_1_page' on 'cookie_swap_pdata_page_setting'('campaign_id','page');
