CREATE TABLE 'dress_data' ('id' INTEGER NOT NULL, 'name' TEXT NOT NULL, 'description' TEXT NOT NULL, 'open_type' INTEGER NOT NULL, 'dress_type' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `dress_data` VALUES (/*id*/1, /*name*/"スターリースカイ・ブライト", /*description*/"新たなる舞台に立つ、少女達を祝福するドレス。\n星々の光を受けて織られたように輝いている。", /*open_type*/0, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/2, /*name*/"アクロス・ザ・スターズ", /*description*/"扉を開け、城より出でる騎士を模したドレス。\n星辰を渡る旅路は、音楽と笑顔に彩られている。", /*open_type*/0, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/3, /*name*/"パーティータイム・ゴールド", /*description*/"360度、光の海を泳ぐ少女たちのドレス。\nアクティブなパンツスタイルの衣装は\nアガるダンスフロアの主役にふさわしい。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/4, /*name*/"ディープスカイ・ブレイズ", /*description*/"光の舞台に立つ、少女達を力付けるドレス。\n深淵の炎を織られたように輝いている。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/5, /*name*/"ショータイム・イリュージョン", /*description*/"一夜の煌めきを楽しむためのドレス。\n今宵の出来事は、全て幻のイリュージョン。\n想い出だけが、みんなの心に残り続ける。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/6, /*name*/"シンデレラドリーム", /*description*/"アイドルたちの背中を押す、夢の衣装。\nたくさんの思い出と、いつの日にか叶える願いが\n形になった、メモリアルなドレス。", /*open_type*/4, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7, /*name*/"ネクスト・フロンティア", /*description*/"星の輝きを目指す、開拓者の衣装。思い出と経験を武器に、己の足で先へ進む\n少女たちの強い意志が刻み込まれている。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/8, /*name*/"アクロス・ザ・スターズ／コーデ", /*description*/"パーツごとにカラーを変更できる\nドレスコーデ対応衣装になります。", /*open_type*/2, /*dress_type*/2);
INSERT INTO `dress_data` VALUES (/*id*/9, /*name*/"パーティータイム・ゴールド／コーデ", /*description*/"パーツごとにカラーを変更できる\nドレスコーデ対応衣装になります。", /*open_type*/2, /*dress_type*/2);
INSERT INTO `dress_data` VALUES (/*id*/100, /*name*/"SSレア衣装", /*description*/"", /*open_type*/1, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7001000, /*name*/"プレゼントオブスノウ", /*description*/"赤や緑のリボンで包んだ雪のようなドレス。\n星の光が煌めく夜、季節の扉が開いて届いた\n真っ白なプレゼント。そのドレスを翼にして\nファンの元へ駆けだす少女たちは天使のよう。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7002000, /*name*/"フレグランスオブナイト", /*description*/"忘れられない夜を彩るドレス。\n夜のあいだにだけ咲く花たちがある。\n花びらから溢れ出すのは、魅惑の香り。\nその芳しい蜜は人を惑わし、口づけを誘う。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7003000, /*name*/"マーチング☆メロディーズ", /*description*/"マーチングバンド風の可愛らしいドレス。\nリズムが聞こえたら、小さな楽団が大集合。\nカラフルでゆかいな行進が始まるよ !", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7004000, /*name*/"ヴァルキュリア・オース", /*description*/"未来を掴みとるための、戦いのドレス。\n汚れなき純白の制服に身を包み、\n己が意志を高らかに歌う姿は、\n神話に謳われた戦乙女のよう。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7005000, /*name*/"雷舞弩麗守－炎－", /*description*/"己の信じる道を\n真っ直ぐに駆け抜ける者の弩麗守。\n彼女たちの炎のような生き様に、\n見る者の心にもアツい火が灯る。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7006000, /*name*/"スカーレット・ローズ", /*description*/"永遠を夢見て、愛を捧げる乙女のドレス。\n真紅の薔薇には棘があり、危うさ故に美しい。\n一途な想いと運命が編み込まれている。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7007000, /*name*/"マリンガール・カーニバル", /*description*/"太陽が映える、海に舞う者たちのドレス。\n祭りの陽気と爽やかな潮風が、\nアツい夏を盛り上げる。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7008000, /*name*/"スウィート・パティシエール", /*description*/"甘美な夢を見せる少女たちのドレス。\n彼女たちがつくりだす幻想は、\nどんなお菓子よりも甘く優しく、\n見る者の心をとらえて離さない。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7009000, /*name*/"シンセサイズ・ハーモニー", /*description*/"スタイリッシュに魅せる、クールなドレス。\n鮮やかに舞う姿は、電脳世界の歌姫のよう。\n計算されつくしたフォルムから覗く\n生身の感情が、見る者を惹きつける。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7010000, /*name*/"ウィル・フォーエバー", /*description*/"愛を祝福する少女たちのドレス。\n純真な乙女たちの幸福な願いと、\n永遠の誓いが込められている。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7011000, /*name*/"デイバイデイ・プレゼント", /*description*/"積み重ねた日々を讃えるドレス。\n少女たちを祝う贈り物。\n育んできた絆が、彼女たちを輝かせる。", /*open_type*/3, /*dress_type*/0);
