CREATE TABLE 'dress_decal_tab_declare' ('dress_id' INTEGER NOT NULL, 'main_tab2key' TEXT NOT NULL, 'sub_tab2key' TEXT NOT NULL, PRIMARY KEY('dress_id'));
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/8, /*main_tab2key*/"0,1,2,3,4", /*sub_tab2key*/"E,E,E,E,E");
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/9, /*main_tab2key*/"0,1,2,3", /*sub_tab2key*/"E,E,E,E");
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/12, /*main_tab2key*/"0,1,2", /*sub_tab2key*/"E,E,E");
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/17, /*main_tab2key*/"0,1,2,3,4", /*sub_tab2key*/"E,E,E,E,E");
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/26, /*main_tab2key*/"0,1,2,3,4", /*sub_tab2key*/"E,E,E,E,E");
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/28, /*main_tab2key*/"0,1,2,3,4", /*sub_tab2key*/"E,E,E,E,E");
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/29, /*main_tab2key*/"0,1,2,3,4", /*sub_tab2key*/"E,E,E,E,E");
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/41, /*main_tab2key*/"0,1,2,3,4", /*sub_tab2key*/"E,E,E,E,E");
INSERT INTO `dress_decal_tab_declare` VALUES (/*dress_id*/45, /*main_tab2key*/"0,1,2,3,4", /*sub_tab2key*/"E,E,E,E,E");
