CREATE TABLE 'dress_data' ('id' INTEGER NOT NULL, 'name' TEXT NOT NULL, 'description' TEXT NOT NULL, 'open_type' INTEGER NOT NULL, 'dress_type' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `dress_data` VALUES (/*id*/1, /*name*/"スターリースカイ・ブライト", /*description*/"新たなる舞台に立つ、少女達を祝福するドレス。\n星々の光を受けて織られたように輝いている。", /*open_type*/0, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/2, /*name*/"アクロス・ザ・スターズ", /*description*/"扉を開け、城より出でる騎士を模したドレス。\n星辰を渡る旅路は、音楽と笑顔に彩られている。", /*open_type*/0, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/3, /*name*/"パーティータイム・ゴールド", /*description*/"360度、光の海を泳ぐ少女たちのドレス。\nアクティブなパンツスタイルの衣装は\nアガるダンスフロアの主役にふさわしい。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/4, /*name*/"ディープスカイ・ブレイズ", /*description*/"光の舞台に立つ、少女達を力付けるドレス。\n深淵の炎を織られたように輝いている。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/5, /*name*/"ショータイム・イリュージョン", /*description*/"一夜の煌めきを楽しむためのドレス。\n今宵の出来事は、全て幻のイリュージョン。\n想い出だけが、みんなの心に残り続ける。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/6, /*name*/"シンデレラドリーム", /*description*/"アイドルたちの背中を押す、夢の衣装。\nたくさんの思い出と、いつの日にか叶える願いが\n形になった、メモリアルなドレス。", /*open_type*/4, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7, /*name*/"ネクスト・フロンティア", /*description*/"星の輝きを目指す、開拓者の衣装。思い出と経験を武器に、己の足で先へ進む\n少女たちの強い意志が刻み込まれている。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/8, /*name*/"アクロス・ザ・スターズ／コーデ", /*description*/"パーツごとにカラーを変更できる\nドレスコーデ対応衣装になります。", /*open_type*/2, /*dress_type*/2);
INSERT INTO `dress_data` VALUES (/*id*/9, /*name*/"パーティータイム・ゴールド／コーデ", /*description*/"パーツごとにカラーを変更できる\nドレスコーデ対応衣装になります。", /*open_type*/2, /*dress_type*/2);
INSERT INTO `dress_data` VALUES (/*id*/10, /*name*/"レッスンウェア", /*description*/"パーツごとにカラーを変更できる\nドレスコーデ対応衣装になります。", /*open_type*/2, /*dress_type*/4);
INSERT INTO `dress_data` VALUES (/*id*/11, /*name*/"レインボー・カラーズ", /*description*/"すべての個性を彩る、虹のドレス。\nたくさんの願いと想いが繋がって、\nひとりひとりの色を輝かせている。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/12, /*name*/"ショータイム・イリュージョン／コーデ", /*description*/"パーツごとにカラーを変更できる\nドレスコーデ対応衣装になります。", /*open_type*/2, /*dress_type*/2);
INSERT INTO `dress_data` VALUES (/*id*/13, /*name*/"クリスタルナイトパーティ", /*description*/"新たな自分に会いに行くためのドレス｡\n困難に立ち向かう少女達の意志が\n込められている｡", /*open_type*/4, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/15, /*name*/"Go To Paradise", /*description*/"楽園を満喫するためのドレス。\nステージは爽やかな青空と白い雲のように、\nリゾートでの姿は、地上で輝く太陽のよう。\n2つの着回しで、アイドルも遊びも楽しもう。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/16, /*name*/"Go To Paradise/リゾート", /*description*/"楽園を満喫するためのドレス。\nステージは爽やかな青空と白い雲のように、\nリゾートでの姿は、地上で輝く太陽のよう。\n2つの着回しで、アイドルも遊びも楽しもう。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/100, /*name*/"SSレア衣装", /*description*/"", /*open_type*/1, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/201, /*name*/"Sレア衣装", /*description*/"", /*open_type*/0, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/202, /*name*/"レア衣装", /*description*/"", /*open_type*/0, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/203, /*name*/"ノーマル衣装", /*description*/"", /*open_type*/0, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/204, /*name*/"エクストラ衣装", /*description*/"", /*open_type*/0, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7001000, /*name*/"プレゼントオブスノウ", /*description*/"赤や緑のリボンで包んだ雪のようなドレス。\n星の光が煌めく夜、季節の扉が開いて届いた\n真っ白なプレゼント。そのドレスを翼にして\nファンの元へ駆けだす少女たちは天使のよう。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7002000, /*name*/"フレグランスオブナイト", /*description*/"忘れられない夜を彩るドレス。\n夜のあいだにだけ咲く花たちがある。\n花びらから溢れ出すのは、魅惑の香り。\nその芳しい蜜は人を惑わし、口づけを誘う。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7003000, /*name*/"マーチング☆メロディーズ", /*description*/"マーチングバンド風の可愛らしいドレス。\nリズムが聞こえたら、小さな楽団が大集合。\nカラフルでゆかいな行進が始まるよ !", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7004000, /*name*/"ヴァルキュリア・オース", /*description*/"未来を掴みとるための、戦いのドレス。\n汚れなき純白の制服に身を包み、\n己が意志を高らかに歌う姿は、\n神話に謳われた戦乙女のよう。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7005000, /*name*/"雷舞弩麗守－炎－", /*description*/"己の信じる道を\n真っ直ぐに駆け抜ける者の弩麗守。\n彼女たちの炎のような生き様に、\n見る者の心にもアツい火が灯る。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7006000, /*name*/"スカーレット・ローズ", /*description*/"永遠を夢見て、愛を捧げる乙女のドレス。\n真紅の薔薇には棘があり、危うさ故に美しい。\n一途な想いと運命が編み込まれている。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7007000, /*name*/"マリンガール・カーニバル", /*description*/"太陽が映える、海に舞う者たちのドレス。\n祭りの陽気と爽やかな潮風が、\nアツい夏を盛り上げる。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7008000, /*name*/"スウィート・パティシエール", /*description*/"甘美な夢を見せる少女たちのドレス。\n彼女たちがつくりだす幻想は、\nどんなお菓子よりも甘く優しく、\n見る者の心をとらえて離さない。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7009000, /*name*/"シンセサイズ・ハーモニー", /*description*/"スタイリッシュに魅せる、クールなドレス。\n鮮やかに舞う姿は、電脳世界の歌姫のよう。\n計算されつくしたフォルムから覗く\n生身の感情が、見る者を惹きつける。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7010000, /*name*/"ウィル・フォーエバー", /*description*/"愛を祝福する少女たちのドレス。\n純真な乙女たちの幸福な願いと、\n永遠の誓いが込められている。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7011000, /*name*/"デイバイデイ・プレゼント", /*description*/"積み重ねた日々を讃えるドレス。\n少女たちを祝う贈り物。\n育んできた絆が、彼女たちを輝かせる。", /*open_type*/2, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7012000, /*name*/"リトル・カラフル", /*description*/"少女たちの主張が詰まった、ポップな衣装。\nカラフルなライムの中に、\nひとりひとりの色が主張している。", /*open_type*/2, /*dress_type*/1);
INSERT INTO `dress_data` VALUES (/*id*/7013000, /*name*/"お伽衣装・不思議の国のアリス", /*description*/"一日の幻を形にした衣装。\n『不思議の国のアリス』がモチーフ。\n様々な役柄が、少女たちを楽しく彩る。", /*open_type*/3, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7014000, /*name*/"お伽衣装・ヘンゼルとグレーテル", /*description*/"一日の幻を形にした衣装。\n『ヘンゼルとグレーテル』がモチーフ。\n様々な役柄が、少女たちを楽しく彩る。", /*open_type*/3, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7015000, /*name*/"お伽衣装・白雪姫", /*description*/"一日の幻を形にした衣装。\n『白雪姫』がモチーフ。\n様々な役柄が、少女たちを楽しく彩る。", /*open_type*/3, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7016000, /*name*/"お伽衣装・魔法の司書", /*description*/"一日の幻を形にした衣装。\n魔法図書館の司書がモチーフ。\n様々な役柄が、少女たちを楽しく彩る。", /*open_type*/3, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7017000, /*name*/"てるてる珠美To You !", /*description*/"梅雨をテーマにした、珠美の衣装。\n振袖にレインブーツの組み合わせがキュート。\nデザインした者の想いがこもっている。", /*open_type*/3, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7018000, /*name*/"サンライトオブフラワー", /*description*/"太陽を浴びて輝くドレス。\nあたたかな陽光によって織られている。\nこのドレスと共に、少女たちの笑顔も花開く。", /*open_type*/3, /*dress_type*/0);
INSERT INTO `dress_data` VALUES (/*id*/7019000, /*name*/"Cheese ! Cheese !", /*description*/"ねずみをテーマにした、肇の衣装。\n愛らしい髪型と、チーズなフリルがポイント。\nデザインした者の想いがこもっている。", /*open_type*/3, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7020000, /*name*/"宵の花衣", /*description*/"宵の花を彩る衣装。\nいずれ散りゆく運命なれど、\n命を燃やして咲く恋は美しい。\nその艶姿は、見る者の心に永久に残る。", /*open_type*/5, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7021000, /*name*/"春纏う霞衣", /*description*/"桜のように咲き誇る、少女たちの衣装。\n芽吹き、咲き、散ってゆく。\nそれでも桜はまた咲き、皆を惹きつける。\nそしてまた、満開の笑顔が花開く。", /*open_type*/5, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7022000, /*name*/"スクールメイト・ブレザー", /*description*/"少女たちの青春を包む制服ドレス。\nBakuBakuのハートにしっかり封をして、\nステキな恋を届けよう。", /*open_type*/5, /*dress_type*/3);
INSERT INTO `dress_data` VALUES (/*id*/7023000, /*name*/"セーシュン・チアーズ", /*description*/"青春を応援する少女たちの制服ドレス。\n上手くいかない時も、つまづいてしまう時も\nある。それでも、今という時を全力で走ろう。\nその情熱は、輝く明日へと繋がっている。", /*open_type*/5, /*dress_type*/3);
