CREATE TABLE 'gacha_scout_ticket_hub' ('id' INTEGER NOT NULL, 'group_id' INTEGER NOT NULL, 'ticket_id' INTEGER NOT NULL, 'disp_order' INTEGER NOT NULL, 'description' TEXT NOT NULL, 'close_original' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/1, /*group_id*/1, /*ticket_id*/85001, /*disp_order*/1, /*description*/"プライズスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/2, /*group_id*/1, /*ticket_id*/85002, /*disp_order*/2, /*description*/"プライズSレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/3, /*group_id*/1, /*ticket_id*/81900, /*disp_order*/3, /*description*/"10周年スカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/4, /*group_id*/1, /*ticket_id*/81901, /*disp_order*/4, /*description*/"10周年Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/5, /*group_id*/1, /*ticket_id*/83501, /*disp_order*/5, /*description*/"チャレンジスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/6, /*group_id*/1, /*ticket_id*/89001, /*disp_order*/6, /*description*/"10周年記念アニメスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/7, /*group_id*/1, /*ticket_id*/89002, /*disp_order*/7, /*description*/"アニメU149第1巻スカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/8, /*group_id*/1, /*ticket_id*/89003, /*disp_order*/8, /*description*/"アニメU149第2巻スカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/9, /*group_id*/1, /*ticket_id*/89004, /*disp_order*/9, /*description*/"アニメU149第3巻スカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/10, /*group_id*/1, /*ticket_id*/89005, /*disp_order*/10, /*description*/"アニメU149第4巻スカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/11, /*group_id*/1, /*ticket_id*/89006, /*disp_order*/11, /*description*/"「All for YOU!!!」スカウトチケット(Cu)", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/12, /*group_id*/1, /*ticket_id*/89007, /*disp_order*/12, /*description*/"「All for YOU!!!」スカウトチケット(Co)", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/13, /*group_id*/1, /*ticket_id*/89008, /*disp_order*/13, /*description*/"「All for YOU!!!」スカウトチケット(Pa)", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/14, /*group_id*/1, /*ticket_id*/83001, /*disp_order*/14, /*description*/"プラチナスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/15, /*group_id*/1, /*ticket_id*/83002, /*disp_order*/15, /*description*/"スカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/16, /*group_id*/1, /*ticket_id*/82001, /*disp_order*/16, /*description*/"イベント限定アイドルスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/17, /*group_id*/1, /*ticket_id*/86001, /*disp_order*/17, /*description*/"カムバックSレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/18, /*group_id*/1, /*ticket_id*/84001, /*disp_order*/18, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/19, /*group_id*/1, /*ticket_id*/84002, /*disp_order*/19, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/20, /*group_id*/1, /*ticket_id*/84003, /*disp_order*/20, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/21, /*group_id*/1, /*ticket_id*/84004, /*disp_order*/21, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/22, /*group_id*/1, /*ticket_id*/84005, /*disp_order*/22, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/23, /*group_id*/1, /*ticket_id*/84006, /*disp_order*/23, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/24, /*group_id*/1, /*ticket_id*/84007, /*disp_order*/24, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/25, /*group_id*/1, /*ticket_id*/84008, /*disp_order*/25, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/26, /*group_id*/1, /*ticket_id*/84009, /*disp_order*/26, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/27, /*group_id*/1, /*ticket_id*/84010, /*disp_order*/27, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/28, /*group_id*/1, /*ticket_id*/84011, /*disp_order*/28, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/29, /*group_id*/1, /*ticket_id*/84012, /*disp_order*/29, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/30, /*group_id*/1, /*ticket_id*/84013, /*disp_order*/30, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/31, /*group_id*/1, /*ticket_id*/84014, /*disp_order*/31, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/32, /*group_id*/1, /*ticket_id*/84015, /*disp_order*/32, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/33, /*group_id*/1, /*ticket_id*/84016, /*disp_order*/33, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/34, /*group_id*/1, /*ticket_id*/84017, /*disp_order*/34, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/35, /*group_id*/1, /*ticket_id*/84018, /*disp_order*/35, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/36, /*group_id*/1, /*ticket_id*/84019, /*disp_order*/36, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/37, /*group_id*/1, /*ticket_id*/84020, /*disp_order*/37, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/38, /*group_id*/1, /*ticket_id*/84021, /*disp_order*/38, /*description*/"Carnival Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/39, /*group_id*/1, /*ticket_id*/81014, /*disp_order*/39, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/40, /*group_id*/1, /*ticket_id*/87001, /*disp_order*/40, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/41, /*group_id*/1, /*ticket_id*/87002, /*disp_order*/41, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/42, /*group_id*/1, /*ticket_id*/87003, /*disp_order*/42, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/43, /*group_id*/1, /*ticket_id*/87004, /*disp_order*/43, /*description*/"Sレアスカウトチケット", /*close_original*/1);
INSERT INTO `gacha_scout_ticket_hub` VALUES (/*id*/44, /*group_id*/1, /*ticket_id*/87005, /*disp_order*/44, /*description*/"Sレアスカウトチケット", /*close_original*/1);
CREATE INDEX 'gacha_scout_ticket_hub_0_group_id' on 'gacha_scout_ticket_hub'('group_id');
CREATE UNIQUE INDEX 'gacha_scout_ticket_hub_0_ticket_id' on 'gacha_scout_ticket_hub'('ticket_id');
