CREATE TABLE 'gacha_priority' ('id' INTEGER NOT NULL, 'id_type' INTEGER NOT NULL, 'priority' INTEGER NOT NULL, PRIMARY KEY('id','id_type'));
INSERT INTO `gacha_priority` VALUES (/*id*/60430, /*id_type*/1, /*priority*/1100);
INSERT INTO `gacha_priority` VALUES (/*id*/60431, /*id_type*/1, /*priority*/1200);
INSERT INTO `gacha_priority` VALUES (/*id*/31121, /*id_type*/1, /*priority*/1300);
INSERT INTO `gacha_priority` VALUES (/*id*/31122, /*id_type*/1, /*priority*/1400);
INSERT INTO `gacha_priority` VALUES (/*id*/154, /*id_type*/2, /*priority*/3000);
INSERT INTO `gacha_priority` VALUES (/*id*/155, /*id_type*/2, /*priority*/3100);
INSERT INTO `gacha_priority` VALUES (/*id*/156, /*id_type*/2, /*priority*/3200);
INSERT INTO `gacha_priority` VALUES (/*id*/157, /*id_type*/2, /*priority*/3300);
INSERT INTO `gacha_priority` VALUES (/*id*/158, /*id_type*/2, /*priority*/3400);
