CREATE TABLE 'gacha_l_e_list' ('id' INTEGER NOT NULL, 'g_id' INTEGER NOT NULL, 'reward_type' INTEGER NOT NULL, 'reward_id' INTEGER NOT NULL, 'reward_value' INTEGER NOT NULL, 'sub_reward_type_1' INTEGER NOT NULL, 'sub_reward_id_1' INTEGER NOT NULL, 'sub_reward_value_1' INTEGER NOT NULL, 'sub_reward_type_2' INTEGER NOT NULL, 'sub_reward_id_2' INTEGER NOT NULL, 'sub_reward_value_2' INTEGER NOT NULL, 'add_value_1' INTEGER NOT NULL, 'add_value_2' INTEGER NOT NULL, 'add_value_3' INTEGER NOT NULL, PRIMARY KEY('id'))
INSERT INTO `gacha_l_e_list` VALUES (/*id*/1, /*g_id*/1, /*reward_type*/6, /*reward_id*/100255, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/100256, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/2, /*g_id*/1, /*reward_type*/6, /*reward_id*/100297, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/100298, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/3, /*g_id*/1, /*reward_type*/6, /*reward_id*/100343, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/100344, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/4, /*g_id*/1, /*reward_type*/6, /*reward_id*/100395, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/100396, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/5, /*g_id*/1, /*reward_type*/6, /*reward_id*/200253, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/200254, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/6, /*g_id*/1, /*reward_type*/6, /*reward_id*/200293, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/200294, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/7, /*g_id*/1, /*reward_type*/6, /*reward_id*/200345, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/200346, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/8, /*g_id*/1, /*reward_type*/6, /*reward_id*/200377, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/200378, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/9, /*g_id*/1, /*reward_type*/6, /*reward_id*/300235, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/300236, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/10, /*g_id*/1, /*reward_type*/6, /*reward_id*/300279, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/300280, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
INSERT INTO `gacha_l_e_list` VALUES (/*id*/11, /*g_id*/1, /*reward_type*/6, /*reward_id*/300335, /*reward_value*/1, /*sub_reward_type_1*/7, /*sub_reward_id_1*/300336, /*sub_reward_value_1*/1, /*sub_reward_type_2*/0, /*sub_reward_id_2*/0, /*sub_reward_value_2*/0, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/1);
