CREATE TABLE 'gallery_stage_list' ('id' INTEGER NOT NULL, 'disp_order' INTEGER NOT NULL, 'disp_name' TEXT NOT NULL, 'bg_id' INTEGER NOT NULL, 'bg_type' INTEGER NOT NULL, 'left_degree' INTEGER NOT NULL, 'right_degree' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gallery_stage_list` VALUES (/*id*/1, /*disp_order*/1, /*disp_name*/"ステージ シンデレラ", /*bg_id*/4001, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/2, /*disp_order*/2, /*disp_name*/"ステージ キュート", /*bg_id*/1014, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/3, /*disp_order*/3, /*disp_name*/"ステージ クール", /*bg_id*/2012, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/4, /*disp_order*/4, /*disp_name*/"ステージ パッション", /*bg_id*/3012, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/5, /*disp_order*/101, /*disp_name*/"スクリーン キュート", /*bg_id*/1, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/6, /*disp_order*/102, /*disp_name*/"スクリーン クール", /*bg_id*/2, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/7, /*disp_order*/103, /*disp_name*/"スクリーン パッション", /*bg_id*/3, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/11, /*disp_order*/201, /*disp_name*/"ARスタジオ マーカーモード", /*bg_id*/0, /*bg_type*/3, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/12, /*disp_order*/202, /*disp_name*/"ARスタジオ オートモード", /*bg_id*/0, /*bg_type*/4, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/13, /*disp_order*/5, /*disp_name*/"ステージ BEYOND THE STARLIGHT", /*bg_id*/4012, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/14, /*disp_order*/6, /*disp_name*/"ステージ EVERMORE", /*bg_id*/4017, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/15, /*disp_order*/7, /*disp_name*/"ステージ イリュージョニスタ !", /*bg_id*/4031, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/16, /*disp_order*/8, /*disp_name*/"ステージ ガールズ・イン・ザ・フロンティア", /*bg_id*/4044, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/17, /*disp_order*/9, /*disp_name*/"ステージ Tulip", /*bg_id*/4006, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/18, /*disp_order*/10, /*disp_name*/"ステージ 生存本能ヴァルキュリア", /*bg_id*/4008, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/19, /*disp_order*/11, /*disp_name*/"ステージ 純情Midnight伝説", /*bg_id*/4009, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/20, /*disp_order*/12, /*disp_name*/"ステージ Take me☆Take you", /*bg_id*/4030, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/21, /*disp_order*/13, /*disp_name*/"ステージ 明日また会えるよね", /*bg_id*/1004, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/22, /*disp_order*/14, /*disp_name*/"ステージ 咲いてJewel", /*bg_id*/2004, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/23, /*disp_order*/15, /*disp_name*/"ステージ きみにいっぱい☆", /*bg_id*/3004, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/24, /*disp_order*/16, /*disp_name*/"ステージ サマカニ ! !", /*bg_id*/4011, /*bg_type*/1, /*left_degree*/96, /*right_degree*/96);
INSERT INTO `gallery_stage_list` VALUES (/*id*/25, /*disp_order*/17, /*disp_name*/"ステージ ハイファイ☆デイズ", /*bg_id*/4007, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/26, /*disp_order*/18, /*disp_name*/"ステージ Love∞Destiny", /*bg_id*/4010, /*bg_type*/1, /*left_degree*/125, /*right_degree*/125);
INSERT INTO `gallery_stage_list` VALUES (/*id*/27, /*disp_order*/19, /*disp_name*/"ステージ Snow Wings", /*bg_id*/4003, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
INSERT INTO `gallery_stage_list` VALUES (/*id*/28, /*disp_order*/20, /*disp_name*/"ステージ 命燃やして恋せよ乙女", /*bg_id*/4020, /*bg_type*/1, /*left_degree*/360, /*right_degree*/360);
