CREATE TABLE 'gallery_gimmick_data' ('id' INTEGER NOT NULL, 'gimmick_type' INTEGER NOT NULL, 'gimmick_name' TEXT NOT NULL, 'fade_type' INTEGER NOT NULL, 'source_type' INTEGER NOT NULL, 'source_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/1, /*gimmick_type*/1, /*gimmick_name*/4002, /*fade_type*/1, /*source_type*/1, /*source_id*/31);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/2, /*gimmick_type*/1, /*gimmick_name*/"0132_1611", /*fade_type*/1, /*source_type*/1, /*source_id*/36);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/3, /*gimmick_type*/1, /*gimmick_name*/0220, /*fade_type*/1, /*source_type*/1, /*source_id*/36);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/4, /*gimmick_type*/1, /*gimmick_name*/"0220_2322", /*fade_type*/1, /*source_type*/1, /*source_id*/36);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/5, /*gimmick_type*/1, /*gimmick_name*/"0220_2922", /*fade_type*/1, /*source_type*/1, /*source_id*/36);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/6, /*gimmick_type*/1, /*gimmick_name*/"0257_01", /*fade_type*/1, /*source_type*/1, /*source_id*/37);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/7, /*gimmick_type*/1, /*gimmick_name*/4002, /*fade_type*/1, /*source_type*/1, /*source_id*/42);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/8, /*gimmick_type*/1, /*gimmick_name*/"", /*fade_type*/1, /*source_type*/1, /*source_id*/52);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/9, /*gimmick_type*/1, /*gimmick_name*/0293, /*fade_type*/1, /*source_type*/1, /*source_id*/53);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/10, /*gimmick_type*/1, /*gimmick_name*/"0257_3617", /*fade_type*/1, /*source_type*/1, /*source_id*/37);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/11, /*gimmick_type*/1, /*gimmick_name*/0175, /*fade_type*/1, /*source_type*/1, /*source_id*/62);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/12, /*gimmick_type*/1, /*gimmick_name*/"0175_2014", /*fade_type*/1, /*source_type*/1, /*source_id*/62);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/13, /*gimmick_type*/1, /*gimmick_name*/"0175_2314", /*fade_type*/1, /*source_type*/1, /*source_id*/62);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/14, /*gimmick_type*/1, /*gimmick_name*/"0175_2614", /*fade_type*/1, /*source_type*/1, /*source_id*/62);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/15, /*gimmick_type*/1, /*gimmick_name*/"0175_7001175", /*fade_type*/1, /*source_type*/1, /*source_id*/62);
INSERT INTO `gallery_gimmick_data` VALUES (/*id*/16, /*gimmick_type*/1, /*gimmick_name*/"", /*fade_type*/1, /*source_type*/1, /*source_id*/61);
CREATE INDEX 'gallery_gimmick_data_0_source_type_1_source_id' on 'gallery_gimmick_data'('source_type','source_id');
