CREATE TABLE 'gallery_music_list' ('id' INTEGER NOT NULL, 'disp_order' INTEGER NOT NULL, 'live_id' INTEGER NOT NULL, 'motion_id' INTEGER NOT NULL, 'fade_msec' INTEGER NOT NULL, 'cutt_name' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gallery_music_list` VALUES (/*id*/1, /*disp_order*/1, /*live_id*/1, /*motion_id*/1001, /*fade_msec*/1000, /*cutt_name*/"Cutt_Oneshin");
INSERT INTO `gallery_music_list` VALUES (/*id*/2, /*disp_order*/2, /*live_id*/9, /*motion_id*/3001, /*fade_msec*/1000, /*cutt_name*/"Cutt_Sing");
INSERT INTO `gallery_music_list` VALUES (/*id*/3, /*disp_order*/3, /*live_id*/10, /*motion_id*/3002, /*fade_msec*/1000, /*cutt_name*/"Cutt_Never");
INSERT INTO `gallery_music_list` VALUES (/*id*/4, /*disp_order*/4, /*live_id*/11, /*motion_id*/3003, /*fade_msec*/1000, /*cutt_name*/"Cutt_Mituboshi");
INSERT INTO `gallery_music_list` VALUES (/*id*/5, /*disp_order*/12, /*live_id*/12, /*motion_id*/3004, /*fade_msec*/1000, /*cutt_name*/"Cutt_Kazeiro");
INSERT INTO `gallery_music_list` VALUES (/*id*/9, /*disp_order*/11, /*live_id*/17, /*motion_id*/3009, /*fade_msec*/1000, /*cutt_name*/"Cutt_DOKIDOKI");
INSERT INTO `gallery_music_list` VALUES (/*id*/10, /*disp_order*/9, /*live_id*/18, /*motion_id*/3010, /*fade_msec*/1000, /*cutt_name*/"Cutt_ShallWe");
INSERT INTO `gallery_music_list` VALUES (/*id*/11, /*disp_order*/10, /*live_id*/28, /*motion_id*/3014, /*fade_msec*/1000, /*cutt_name*/"Cutt_Twilight");
INSERT INTO `gallery_music_list` VALUES (/*id*/101, /*disp_order*/101, /*live_id*/19, /*motion_id*/5001, /*fade_msec*/1000, /*cutt_name*/"Cutt_Star");
