CREATE TABLE 'gallery_pose_list' ('id' INTEGER NOT NULL, 'disp_order' INTEGER NOT NULL, 'disp_name' TEXT NOT NULL, 'motion_id' INTEGER NOT NULL, 'fade_msec' INTEGER NOT NULL, 'cutt_name' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gallery_pose_list` VALUES (/*id*/1, /*disp_order*/1, /*disp_name*/"じっとしてて !", /*motion_id*/1, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose0001");
INSERT INTO `gallery_pose_list` VALUES (/*id*/101, /*disp_order*/2, /*disp_name*/"手を振って !", /*motion_id*/101, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose0101");
INSERT INTO `gallery_pose_list` VALUES (/*id*/102, /*disp_order*/3, /*disp_name*/"みんなに手を振って !", /*motion_id*/102, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose0102");
INSERT INTO `gallery_pose_list` VALUES (/*id*/103, /*disp_order*/4, /*disp_name*/"おつかれさまです !", /*motion_id*/103, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose0103");
INSERT INTO `gallery_pose_list` VALUES (/*id*/104, /*disp_order*/5, /*disp_name*/"わっ !", /*motion_id*/104, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose0104");
INSERT INTO `gallery_pose_list` VALUES (/*id*/1011, /*disp_order*/101, /*disp_name*/"卯月ちゃんっぽく !", /*motion_id*/1011, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose1011");
INSERT INTO `gallery_pose_list` VALUES (/*id*/1081, /*disp_order*/108, /*disp_name*/"かな子ちゃんっぽく !", /*motion_id*/1081, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose1081");
INSERT INTO `gallery_pose_list` VALUES (/*id*/1341, /*disp_order*/134, /*disp_name*/"杏ちゃんっぽく !", /*motion_id*/1341, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose1341");
INSERT INTO `gallery_pose_list` VALUES (/*id*/1671, /*disp_order*/167, /*disp_name*/"凛ちゃんっぽく !", /*motion_id*/1671, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose1671");
INSERT INTO `gallery_pose_list` VALUES (/*id*/1691, /*disp_order*/169, /*disp_name*/"沙理奈ちゃんっぽく !", /*motion_id*/1691, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose1691");
INSERT INTO `gallery_pose_list` VALUES (/*id*/1781, /*disp_order*/178, /*disp_name*/"李衣菜ちゃんっぽく !", /*motion_id*/1781, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose1781");
INSERT INTO `gallery_pose_list` VALUES (/*id*/2341, /*disp_order*/234, /*disp_name*/"未央ちゃんっぽく !", /*motion_id*/2341, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose2341");
INSERT INTO `gallery_pose_list` VALUES (/*id*/2711, /*disp_order*/271, /*disp_name*/"きらりちゃんっぽく !", /*motion_id*/2711, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose2711");
INSERT INTO `gallery_pose_list` VALUES (/*id*/2731, /*disp_order*/273, /*disp_name*/"ナターリアちゃんっぽく !", /*motion_id*/2731, /*fade_msec*/1000, /*cutt_name*/"Cutt_Pose2731");
