CREATE TABLE 'gallery_stage_condition' ('id' INTEGER NOT NULL, 'source_id' INTEGER NOT NULL, 'condition_type' INTEGER NOT NULL, 'condition_id' INTEGER NOT NULL, 'condition_value' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gallery_stage_condition` VALUES (/*id*/2, /*source_id*/13, /*condition_type*/301, /*condition_id*/13, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/3, /*source_id*/14, /*condition_type*/301, /*condition_id*/14, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/4, /*source_id*/15, /*condition_type*/301, /*condition_id*/15, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/5, /*source_id*/16, /*condition_type*/301, /*condition_id*/16, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/6, /*source_id*/17, /*condition_type*/301, /*condition_id*/17, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/7, /*source_id*/18, /*condition_type*/301, /*condition_id*/18, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/8, /*source_id*/19, /*condition_type*/301, /*condition_id*/19, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/9, /*source_id*/20, /*condition_type*/301, /*condition_id*/20, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/10, /*source_id*/21, /*condition_type*/301, /*condition_id*/21, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/11, /*source_id*/22, /*condition_type*/301, /*condition_id*/22, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/12, /*source_id*/23, /*condition_type*/301, /*condition_id*/23, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/13, /*source_id*/24, /*condition_type*/301, /*condition_id*/24, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/14, /*source_id*/25, /*condition_type*/301, /*condition_id*/25, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/15, /*source_id*/26, /*condition_type*/301, /*condition_id*/26, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/16, /*source_id*/27, /*condition_type*/301, /*condition_id*/27, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/17, /*source_id*/28, /*condition_type*/301, /*condition_id*/28, /*condition_value*/1);
INSERT INTO `gallery_stage_condition` VALUES (/*id*/18, /*source_id*/29, /*condition_type*/301, /*condition_id*/29, /*condition_value*/1);
CREATE INDEX 'gallery_stage_condition_0_source_id' on 'gallery_stage_condition'('source_id');
