CREATE TABLE 'gift_message' ('id' INTEGER NOT NULL, 'discription' TEXT NOT NULL, 'type_1' INTEGER NOT NULL, 'type_2' INTEGER NOT NULL, 'type_3' INTEGER NOT NULL, 'type_4' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `gift_message` VALUES (/*id*/1, /*discription*/"LIVE「{0}(難易度：{1})」クリアで加入したアイドルです。", /*type_1*/1, /*type_2*/2, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2, /*discription*/"LIVE「{0}(難易度：{1})」{2}目標「{3}」達成で加入したアイドルです。", /*type_1*/1, /*type_2*/2, /*type_3*/3, /*type_4*/4);
INSERT INTO `gift_message` VALUES (/*id*/3, /*discription*/"「{0}」{1}日目で獲得した報酬です。", /*type_1*/5, /*type_2*/6, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/4, /*discription*/"プロデューサーランク「{0}」達成で加入したアイドルです。", /*type_1*/7, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/5, /*discription*/"「{0}」で加入したアイドルです。", /*type_1*/8, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/6, /*discription*/"「{0}({1}STEP目)」で加入したアイドルです。", /*type_1*/8, /*type_2*/9, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/7, /*discription*/"エピソードコミュ「{0}」で加入したアイドルです。", /*type_1*/13, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/8, /*discription*/"ストーリーコミュ「{0}『{1}』」で加入したアイドルです。", /*type_1*/11, /*type_2*/13, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9, /*discription*/"メモリアルコミュ「{0}」で加入したアイドルです。", /*type_1*/13, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/10, /*discription*/"1stパネル「{0}」で獲得した報酬です。", /*type_1*/14, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11, /*discription*/"1stパネルクリアで獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/12, /*discription*/"招待成功で加入したアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/13, /*discription*/"招待コードの入力で加入したアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/15, /*discription*/"シリアルコードの入力で加入したアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/16, /*discription*/"PRP{0}達成で加入したアイドルです。", /*type_1*/18, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/17, /*discription*/"LIVE「{0}(難易度：{1})」クリア報酬です。", /*type_1*/1, /*type_2*/2, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/18, /*discription*/"LIVE「{0}(難易度：{1})」{2}目標「{3}」達成報酬です。", /*type_1*/1, /*type_2*/2, /*type_3*/3, /*type_4*/4);
INSERT INTO `gift_message` VALUES (/*id*/19, /*discription*/"「{0}」{1}日目で獲得した報酬です。", /*type_1*/5, /*type_2*/6, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20, /*discription*/"プロデューサーランク「{0}」達成報酬です。", /*type_1*/7, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/21, /*discription*/"「{0}」で獲得した報酬です。", /*type_1*/8, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/22, /*discription*/"「{0}({1}STEP目)」で獲得した報酬です。", /*type_1*/8, /*type_2*/9, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/23, /*discription*/"エピソードコミュ「{0}」で獲得した報酬です。", /*type_1*/13, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/24, /*discription*/"ストーリーコミュ「{0}『{1}』」で獲得した報酬です。", /*type_1*/11, /*type_2*/13, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/25, /*discription*/"メモリアルコミュ「{0}」で獲得した報酬です。", /*type_1*/13, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/26, /*discription*/"パネルミッション{0}周目「{1}」で獲得した報酬です。", /*type_1*/15, /*type_2*/14, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/27, /*discription*/"パネルミッション{0}周目コンプリートで獲得した報酬です。", /*type_1*/15, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/28, /*discription*/"招待成功で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/29, /*discription*/"招待コードの入力で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/30, /*discription*/"シリアルコードの入力で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/31, /*discription*/"PRP{0}達成で獲得した報酬です。", /*type_1*/18, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/34, /*discription*/"2ndパネル「{0}」で獲得した報酬です。", /*type_1*/14, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/35, /*discription*/"2ndパネルクリアで獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/36, /*discription*/"3rdパネル「{0}」で獲得した報酬です。", /*type_1*/14, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/37, /*discription*/"3rdパネルクリアで獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/38, /*discription*/"ルームアイテムで獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/39, /*discription*/"「{0}」でスカウトしたアイドルです。", /*type_1*/29, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/40, /*discription*/"「{0}」で獲得した報酬です。", /*type_1*/29, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/41, /*discription*/"エクストラコミュ「{0}」で加入したアイドルです。", /*type_1*/13, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/42, /*discription*/"エクストラコミュ「{0}」で獲得した報酬です。", /*type_1*/13, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/43, /*discription*/"アイドルからのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/44, /*discription*/"スターシャインでスカウトしたアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/45, /*discription*/"スターシャインで獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/46, /*discription*/"提供期間を過ぎたスターシャインを自動変換したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/47, /*discription*/"スターピース交換で獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/48, /*discription*/"イベント限定アイドルスカウトチケットでスカウトしたアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/49, /*discription*/"ポテンシャル初期化で返還されたアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/50, /*discription*/"プロデューサーランク「SSSアイドルマスター」ランクアップで加入したアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/51, /*discription*/"プロデューサーランク「SSSアイドルマスター」ランクアップ報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/52, /*discription*/"マニーショップで購入したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/53, /*discription*/"鋼鉄公演きらりんロボ外伝　－モロボシティS.O.S ! － で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/54, /*discription*/"自動移籍で獲得したマニーです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/70, /*discription*/"営業「{0}」で加入したアイドルです。", /*type_1*/36, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/71, /*discription*/"営業「{0}」で獲得した報酬です。", /*type_1*/36, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/72, /*discription*/"プラチナメダル交換で獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/73, /*discription*/"営業コミュ「{0}」で加入したアイドルです。", /*type_1*/12, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/74, /*discription*/"営業コミュ「{0}」で獲得した報酬です。", /*type_1*/12, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/75, /*discription*/"{0}で購入したアイテムです。", /*type_1*/37, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/76, /*discription*/"「{0}」で獲得した報酬です。", /*type_1*/38, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/77, /*discription*/"{0}で獲得したアイテムです。", /*type_1*/37, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/78, /*discription*/"「{0}」で加入したアイドルです。", /*type_1*/38, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/79, /*discription*/"ルナシャインでスカウトしたアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/80, /*discription*/"ルナシャインで獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/81, /*discription*/"ゲームセンターのメダル交換所で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/82, /*discription*/"ミニゲーム「{0}(ステージ：{1})」ランク「{2}」達成報酬です。", /*type_1*/39, /*type_2*/40, /*type_3*/41, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/83, /*discription*/"ゲームセンターのメダル交換所でスカウトしたアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/84, /*discription*/"ミニゲーム「{0}(ステージ：{1})」ランク「{2}」で加入したアイドルです。", /*type_1*/39, /*type_2*/40, /*type_3*/41, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/85, /*discription*/"MIYOSHI QUEST ～暴走ゲームと囚われのアイドル～ で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/86, /*discription*/"プライズコイン交換で獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/87, /*discription*/"プレミアムパスの特典で獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/88, /*discription*/"親愛度超過報酬で獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/89, /*discription*/"ミニゲーム「{0}({1})」ランク「{2}」達成報酬です。", /*type_1*/39, /*type_2*/40, /*type_3*/41, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/90, /*discription*/"ミニゲーム「{0}({1})」ランク「{2}」で加入したアイドルです。", /*type_1*/39, /*type_2*/40, /*type_3*/41, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/91, /*discription*/"{0}からのプレゼントです。", /*type_1*/31, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/92, /*discription*/"ホワイトデーキャンペーンで獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/93, /*discription*/"ぴにゃこら太と遊ぼう ! ～アイドルクイズ王決定戦～ で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/94, /*discription*/"ミニゲーム「{0}」ランク「{1}」達成報酬です。", /*type_1*/39, /*type_2*/41, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/95, /*discription*/"ミニゲーム「{0}」ランク「{1}」で加入したアイドルです。", /*type_1*/39, /*type_2*/41, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/96, /*discription*/"アイドルをパシャ♪～Pがカメラを持ったなら～で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/97, /*discription*/"「{0}」のシャインゲージ{1}到達で加入したアイドルです。", /*type_1*/8, /*type_2*/90, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/98, /*discription*/"「{0}」のシャインゲージ{1}到達の報酬です。", /*type_1*/8, /*type_2*/90, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/99, /*discription*/"「{0}」のシャインゲージ{1}到達で加入したアイドルです。", /*type_1*/43, /*type_2*/90, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/100, /*discription*/"「{0}」のシャインゲージ{1}到達の報酬です。", /*type_1*/43, /*type_2*/90, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/101, /*discription*/"ハッピークリスマスキャンペーンで獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/102, /*discription*/"{0}でスカウトしたアイドルです。", /*type_1*/46, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/103, /*discription*/"{0}で獲得した報酬です。", /*type_1*/46, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/104, /*discription*/"提供期間を過ぎた{0}を自動変換したアイテムです。", /*type_1*/46, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/105, /*discription*/"「{0}」で獲得した報酬です。", /*type_1*/47, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/106, /*discription*/"「{0}」で獲得した報酬です。", /*type_1*/48, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/107, /*discription*/"MVメイカーで獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/108, /*discription*/"アイテム所持数が上限に達しているため、プレゼントに送られました。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/109, /*discription*/"「ぴにゃ博士からのミッションキャンペーン」で獲得した報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/111, /*discription*/"ぴにゃこら大脱走 ! ～ゲーミングぴにゃこら太を捕獲せよ～で獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/112, /*discription*/"「{0}」を変換して獲得したアイテムです。", /*type_1*/29, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/113, /*discription*/"ぴにゃこら大脱走 ! アゲイン ～ぴにゃ教授と解き放たれた パン ドラの箱～で獲得したアイテムです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1001, /*discription*/"イベント「{0}」{1}イベントpt達成報酬です。", /*type_1*/19, /*type_2*/20, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1002, /*discription*/"イベント「{0}」ポイントランキング{1}位～{2}位で獲得した報酬です。", /*type_1*/19, /*type_2*/21, /*type_3*/22, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1003, /*discription*/"イベント「{0}」ハイスコアランキング{1}位～{2}位で獲得した報酬です。", /*type_1*/19, /*type_2*/23, /*type_3*/24, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1004, /*discription*/"イベント「{0}」{1}イベントpt達成で加入したアイドルです。", /*type_1*/19, /*type_2*/20, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1005, /*discription*/"イベント「{0}」ポイントランキング{1}位～{2}位で加入したアイドルです。", /*type_1*/19, /*type_2*/21, /*type_3*/22, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1006, /*discription*/"イベント「{0}」ハイスコアランキング{1}位～{2}位で加入したアイドルです。", /*type_1*/19, /*type_2*/23, /*type_3*/24, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1007, /*discription*/"イベント「{0}」参加報酬で獲得した報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1008, /*discription*/"イベント「{0}」参加報酬で加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1009, /*discription*/"イベント「{0}」イベントコミュ「{1}」で獲得した報酬です。", /*type_1*/19, /*type_2*/12, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1010, /*discription*/"イベント「{0}」イベントコミュ「{1}」で加入したアイドルです。", /*type_1*/19, /*type_2*/12, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1011, /*discription*/"イベント「{0}」のLIVEクリアで加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1012, /*discription*/"イベント「{0}」のメダル交換所で獲得した報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1013, /*discription*/"イベント「{0}」のメダル交換所でスカウトしたアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1014, /*discription*/"イベント「{0}」ポイントランキング{1}位で獲得した報酬です。", /*type_1*/19, /*type_2*/30, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1015, /*discription*/"イベント「{0}」の協力報酬で獲得した報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1016, /*discription*/"イベント「{0}」の個人報酬で獲得した報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1017, /*discription*/"イベント「{0}」の協力報酬で加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1018, /*discription*/"イベント「{0}」の個人報酬で加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1019, /*discription*/"イベント「{0}」累計観客動員数{1}人達成で加入したアイドルです。", /*type_1*/19, /*type_2*/20, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1020, /*discription*/"イベント「{0}」累計観客動員数{1}人の達成報酬です。", /*type_1*/19, /*type_2*/20, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1021, /*discription*/"イベント「{0}」公演クリアで加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1022, /*discription*/"イベント「{0}」公演クリア報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1023, /*discription*/"「{0}」のスターエンブレム交換所で獲得した報酬です。", /*type_1*/33, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1024, /*discription*/"「{0}」のスターエンブレム交換所でスカウトしたアイドルです。", /*type_1*/33, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1025, /*discription*/"「{0}」の協力報酬で獲得した報酬です。", /*type_1*/33, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1026, /*discription*/"「{0}」の個人報酬で獲得した報酬です。", /*type_1*/33, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1027, /*discription*/"「{0}」の協力報酬で加入したアイドルです。", /*type_1*/33, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1028, /*discription*/"「{0}」の個人報酬で加入したアイドルです。", /*type_1*/33, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1029, /*discription*/"イベント「{0}」{1}マス到達で加入したアイドルです。", /*type_1*/19, /*type_2*/35, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1030, /*discription*/"イベント「{0}」{1}マスの到達報酬です。", /*type_1*/19, /*type_2*/35, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1031, /*discription*/"イベント「{0}」課題クリアで加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1032, /*discription*/"イベント「{0}」課題クリア報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1033, /*discription*/"イベント「{0}」のLIVEクリア報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1034, /*discription*/"イベント「{0}」のランクアップ報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1035, /*discription*/"イベント「{0}」のVoltagePointランキング{1}位の報酬です。", /*type_1*/19, /*type_2*/30, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1036, /*discription*/"「{0}」の追加報酬で獲得した報酬です。", /*type_1*/33, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1037, /*discription*/"「{0}」の追加報酬で加入したアイドルです。", /*type_1*/33, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1038, /*discription*/"イベント「{0}」VoltagePointランキング1位～2000位で獲得した報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1039, /*discription*/"イベント「{0}」VoltagePointランキング{1}位～{2}位で獲得した報酬です。", /*type_1*/19, /*type_2*/21, /*type_3*/22, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1040, /*discription*/"イベント「{0}」{1}アイドルpt達成報酬です。", /*type_1*/19, /*type_2*/20, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1041, /*discription*/"イベント「{0}」{1}アイドルpt達成で加入したアイドルです。", /*type_1*/19, /*type_2*/20, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1042, /*discription*/"イベント「{0}」フロア課題クリアで加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1043, /*discription*/"イベント「{0}」フロア課題クリア報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1044, /*discription*/"過去の「LIVE Infinity」にて条件を達成したイベント称号です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1045, /*discription*/"イベント「{0}」イベントptランキング{1}位～{2}位で獲得した報酬です。", /*type_1*/19, /*type_2*/21, /*type_3*/22, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1046, /*discription*/"イベント「{0}」イベントptランキング{1}位～{2}位で加入したアイドルです。", /*type_1*/19, /*type_2*/21, /*type_3*/22, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1047, /*discription*/"イベント「{0}」アイドルptランキング{1}位～{2}位で獲得した報酬です。", /*type_1*/19, /*type_2*/21, /*type_3*/22, /*type_4*/2);
INSERT INTO `gift_message` VALUES (/*id*/1048, /*discription*/"イベント「{0}」アイドルptランキング{1}位～{2}位で加入したアイドルです。", /*type_1*/19, /*type_2*/21, /*type_3*/22, /*type_4*/1);
INSERT INTO `gift_message` VALUES (/*id*/1049, /*discription*/"イベント「{0}」アイドルptランキング{1}位で獲得した報酬です。", /*type_1*/19, /*type_2*/30, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1050, /*discription*/"イベント「{0}」絆Lvアップで獲得した報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1051, /*discription*/"イベント「{0}」絆Lvアップで加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1052, /*discription*/"イベント「{0}」お仕事で獲得した報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1053, /*discription*/"イベント「{0}」お仕事で加入したアイドルです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1054, /*discription*/"イベント「{0}」イベントメモリーコンプリート報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1055, /*discription*/"イベント「{0}」ちひろさんからの差し入れです。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/1999, /*discription*/"協力LIVE βテスト {0}イベントpt達成報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2001, /*discription*/"デイリーミッション「{0}」で獲得した報酬です。", /*type_1*/25, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2002, /*discription*/"デイリーミッション「{0}」で加入したアイドルです。", /*type_1*/25, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2003, /*discription*/"ウィークリーミッション「{0}」で獲得した報酬です。", /*type_1*/26, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2004, /*discription*/"ウィークリーミッション「{0}」で加入したアイドルです。", /*type_1*/26, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2005, /*discription*/"ウィークリーミッション「ミニゲーム『{0}』を1回プレイしよう」で獲得した報酬です。", /*type_1*/42, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2011, /*discription*/"ノーマルミッション「{0}」で獲得した報酬です。", /*type_1*/27, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2012, /*discription*/"ノーマルミッション「{0}」で加入したアイドルです。", /*type_1*/27, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2013, /*discription*/"期間限定ミッション「{0}」で獲得した報酬です。", /*type_1*/28, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2014, /*discription*/"期間限定ミッション「{0}」で加入したアイドルです。", /*type_1*/28, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2015, /*discription*/"オールスター カウントダウンLIVEのミッション「{0}」で獲得した報酬です。", /*type_1*/34, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2016, /*discription*/"オールスター カウントダウンLIVEのミッション「{0}」で獲得した報酬です。", /*type_1*/34, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2017, /*discription*/"オールスター カウントダウンLIVEのミッション「{0}」で獲得した報酬です。", /*type_1*/28, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2018, /*discription*/"オールスター カウントダウンLIVEのミッション「{0}」で加入したアイドルです。", /*type_1*/28, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2019, /*discription*/"5周年記念 ! Twitterキャンペーンのプレゼントです。", /*type_1*/34, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2020, /*discription*/"5周年記念 ! Twitterキャンペーンのプレゼントです。", /*type_1*/34, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2021, /*discription*/"「デレステビンGO ! 」のOPEN報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2022, /*discription*/"「デレステビンGO ! 」のビンゴ報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2023, /*discription*/"「デレステビンGO ! 」の{0}マス分のOPEN報酬です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/2024, /*discription*/"「デレステビンGO ! 」の{0}ライン分のビンゴ報酬です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3001, /*discription*/"プレミアムパス特典：イベント「{0}」{1}イベントpt達成報酬です。", /*type_1*/19, /*type_2*/20, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3004, /*discription*/"プレミアムパス特典：イベント「{0}」{1}イベントpt達成で加入したアイドルです。", /*type_1*/19, /*type_2*/20, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3029, /*discription*/"プレミアムパス特典：イベント「{0}」{1}マス到達で加入したアイドルです。", /*type_1*/19, /*type_2*/35, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3030, /*discription*/"プレミアムパス特典：イベント「{0}」{1}マスの到達報酬です。", /*type_1*/19, /*type_2*/35, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3034, /*discription*/"プレミアムパス特典：イベント「{0}」のランクアップ報酬です。", /*type_1*/19, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3035, /*discription*/"「Stage for Cinderella」予選グループAの累計投票数{0}枚到達報酬です。", /*type_1*/44, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3036, /*discription*/"「Stage for Cinderella」予選グループBの累計投票数{0}枚到達報酬です。", /*type_1*/44, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3037, /*discription*/"「Stage for Cinderella」予選グループCの累計投票数{0}枚到達報酬です。", /*type_1*/44, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3038, /*discription*/"「Stage for Cinderella」予選グループDの累計投票数{0}枚到達報酬です。", /*type_1*/44, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3039, /*discription*/"「Stage for Cinderella」本選の累計投票数{0}枚到達報酬です。", /*type_1*/44, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/3999, /*discription*/"「DMM GAMES版連携キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9000, /*discription*/"運営からのお詫びです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9001, /*discription*/"運営からの補てんです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9002, /*discription*/"運営からのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9003, /*discription*/"メンテナンス協力のお礼です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9004, /*discription*/"バージョンアップ協力のお礼です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9005, /*discription*/"アップデート協力のお礼です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/9999, /*discription*/"デバッグツールで入手しました。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/10400, /*discription*/"400万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/10500, /*discription*/"500万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/10600, /*discription*/"600万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/10700, /*discription*/"700万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/10800, /*discription*/"800万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/10900, /*discription*/"900万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11000, /*discription*/"1000万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11100, /*discription*/"1100万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11200, /*discription*/"1200万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11300, /*discription*/"1300万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11400, /*discription*/"1400万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11500, /*discription*/"1500万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11600, /*discription*/"1600万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11700, /*discription*/"1700万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11800, /*discription*/"1800万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/11900, /*discription*/"1900万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/12000, /*discription*/"2000万DL突破記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/12500, /*discription*/"2500万DL突破記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20001, /*discription*/"東京ゲームショウ出展記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20002, /*discription*/"特別キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20003, /*discription*/"ストアランキング1位初獲得記念プレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20004, /*discription*/"「1周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20005, /*discription*/"1周年記念キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20006, /*discription*/"CM連動キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20007, /*discription*/"「新春 ! プラチナ宝くじ」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20008, /*discription*/"「5th Anniversary Party ニコ生SP」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20009, /*discription*/"「Shadowverseコラボキャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20010, /*discription*/"「5thLIVEツアー連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20011, /*discription*/"ガシャのレア度別提供割合変更にともなう運営からのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20012, /*discription*/"「祝2周年 ! プラチナ宝くじ」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20013, /*discription*/"「2周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20014, /*discription*/"「デレステ2周年記念 ! レッツプレゼントキャンペーン」開催記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20015, /*discription*/"「2周年記念ログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20016, /*discription*/"「Twitterフォロワー数500,000人突破キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20017, /*discription*/"「レッツプレゼントキャンペーン」スタージュエル賞のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20018, /*discription*/"「アイドルマスター シンデレラガールズ 6th Anniversary Memorial Party」開催記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20019, /*discription*/"「新春 ! ハッピーニューイヤーログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20020, /*discription*/"「Twitterフォロワー数600,000人突破キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20021, /*discription*/"「新生活応援ログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20022, /*discription*/"「3周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20023, /*discription*/"「Twitterフォロー＆RTキャンペーン」開催記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20024, /*discription*/"「祝3周年 ! プラチナ宝くじ」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20025, /*discription*/"「Twitterフォロー＆RTキャンペーン」スタージュエル賞のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20026, /*discription*/"「6thLIVE連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20027, /*discription*/"「カバー曲リクエスト」協力のお礼です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20028, /*discription*/"「ゆくM@S くるM@S 2018」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20029, /*discription*/"「乃々を探せ ! レベル41 ! ～ののと不思議な絵本～」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20030, /*discription*/"「もっと ! デレステ☆NIGHT」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20031, /*discription*/"「アイドルマスター14周年記念ニコ生～14th Anniversary P@rty!!!!!～」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20032, /*discription*/"「祝4周年 ! プラチナチャンス」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20033, /*discription*/"「4周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20034, /*discription*/"Twitterキャンペーン開催記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20035, /*discription*/"「7thLIVE連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20036, /*discription*/"「バンナムフェス開催記念キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20037, /*discription*/"「ゆくM@S くるM@S 2019」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20038, /*discription*/"「新春 ! プラチナチャンス」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20039, /*discription*/"「新春 ! プラチナチャンス」{0}等A賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20040, /*discription*/"「新春 ! プラチナチャンス」{0}等B賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20041, /*discription*/"「新春 ! プラチナチャンス」{0}等C賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20042, /*discription*/"「新春 ! プラチナチャンス」特別賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20043, /*discription*/"「デレステ5DAYSジュエルフェスティバル」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20044, /*discription*/"「りも～っと ! デレステ☆NIGHT」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20045, /*discription*/"「7thLIVE ナゴヤドーム振り返りも～っとくばん ! !」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20046, /*discription*/"「5周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20047, /*discription*/"「DJ KOO × デレステ コラボキャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20048, /*discription*/"「24magic放送記念キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20049, /*discription*/"24時間生放送「デレステCHALLENGE」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20050, /*discription*/"「祝5周年 ! プラチナチャンス」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20051, /*discription*/"「祝5周年 ! プラチナチャンス」{0}等A賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20052, /*discription*/"「祝5周年 ! プラチナチャンス」{0}等B賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20053, /*discription*/"「祝5周年 ! プラチナチャンス」{0}等C賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20054, /*discription*/"「祝5周年 ! プラチナチャンス」特別賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20055, /*discription*/"「アイドルマスター シンデレラガールズ」9周年を記念したプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20056, /*discription*/"「キッコーマン豆乳コラボ」開催記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20057, /*discription*/"「カムバックSレアスカウトチケット」追加記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20058, /*discription*/"「ゆくM@S くるM@S 2020」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20059, /*discription*/"「新年LIVE連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20060, /*discription*/"デレぽDE川柳の参加報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20061, /*discription*/"デレぽDE川柳の採用報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20062, /*discription*/"「NEXT LIVE発表会」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20063, /*discription*/"「DyDoコラボ」開催記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20064, /*discription*/"「アイドルマスター16周年生配信～16th Anniversary P@rty!!!!!～」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20065, /*discription*/"「6周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20066, /*discription*/"「祝6周年 ! プラチナチャンス」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20067, /*discription*/"「祝6周年 ! プラチナチャンス」{0}等A賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20068, /*discription*/"「祝6周年 ! プラチナチャンス」{0}等B賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20069, /*discription*/"「祝6周年 ! プラチナチャンス」{0}等C賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20070, /*discription*/"「祝6周年 ! プラチナチャンス」特別賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20071, /*discription*/"「いつかこの宇宙の下で キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20072, /*discription*/"「10th ANNIVERSARY LIVE連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20073, /*discription*/"「10周年記念プレゼントキャンペーン Wチャンス 1等」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20074, /*discription*/"「10周年記念プレゼントキャンペーン Wチャンス 2等」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20075, /*discription*/"「10周年記念プレゼントキャンペーン Wチャンス 3等」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20076, /*discription*/"「10周年記念プレゼントキャンペーン 参加賞」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20077, /*discription*/"「ゆくM@S くるM@S 2021」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20078, /*discription*/"「バンナムフェス2nd開催記念キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20079, /*discription*/"「新総選挙 Stage for Cinderella 組分け抽選会」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20080, /*discription*/"「アイドルマスター17周年生配信～17th Anniversary P@rty!!!!!～」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20081, /*discription*/"「祝7周年 ! プラチナチャンス」のミッション達成数{0}で獲得した報酬です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20082, /*discription*/"「7周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20083, /*discription*/"「祝7周年 ! プラチナチャンス」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20084, /*discription*/"「祝7周年 ! プラチナチャンス」{0}等A賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20085, /*discription*/"「祝7周年 ! プラチナチャンス」{0}等B賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20086, /*discription*/"「祝7周年 ! プラチナチャンス」{0}等C賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20087, /*discription*/"「祝7周年 ! プラチナチャンス」特別賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20088, /*discription*/"「LIKE4LIVE #cg_ootd連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20089, /*discription*/"「SSレアアイドル勧誘チャレンジ」の通常報酬（信頼度{0}達成）です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20090, /*discription*/"「SSレアアイドル勧誘チャレンジ」の参加報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20091, /*discription*/"「SSレアアイドル勧誘チャレンジ」の正式加入報酬です。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20092, /*discription*/"「{0}」の参加報酬です。", /*type_1*/45, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20093, /*discription*/"「Twinkle LIVE Constellation Gradation連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20094, /*discription*/"「ゆくM@S くるM@S 2022」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20095, /*discription*/"「新春 ! プラチナチャンス」のミッション達成数{0}で獲得した報酬です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20096, /*discription*/"TVアニメ「U149」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20097, /*discription*/"「熱い想いを届けマス ! みんな元気!!!!!プロジェクト」達成記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20098, /*discription*/"「燿城夜祭 -かがやきよまつり-連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20099, /*discription*/"「アイドルマスター18周年生配信～18th Anniversary Colorful P@rty!!!!!～」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20100, /*discription*/"新機能「あにぷち」追加記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20101, /*discription*/"「8周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20102, /*discription*/"「祝8周年 ! プラチナチャンス」のミッション達成数{0}で獲得した報酬です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20103, /*discription*/"「祝8周年 ! プラチナチャンス」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20104, /*discription*/"「祝8周年 ! プラチナチャンス」{0}等A賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20105, /*discription*/"「祝8周年 ! プラチナチャンス」{0}等B賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20106, /*discription*/"「祝8周年 ! プラチナチャンス」{0}等C賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20107, /*discription*/"「祝8周年 ! プラチナチャンス」特別賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20108, /*discription*/"「Shout out Live!!!連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20109, /*discription*/"新機能「ロケ撮」追加記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20110, /*discription*/"「Next LIVE Invit@tion!」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20111, /*discription*/"「異次元フェス」開催記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20112, /*discription*/"「ゆくM@SくるM@S」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20113, /*discription*/"「ConnecTrip ! 」開催記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20114, /*discription*/"コラボキャンペーンで加入したアイドルです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20115, /*discription*/"「デレステ特訓パズル」キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20116, /*discription*/"「Celebration Night」公開記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20117, /*discription*/"「SSレアアイドル勧誘チャレンジ」のプラチナチャレンジパス追加報酬（信頼度{0}達成）です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20118, /*discription*/"「アイドルマスター特別生配信 19th→20th Special Party!!!!!!」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20119, /*discription*/"「9周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20120, /*discription*/"「祝9周年 ! プラチナチャンス」のミッション達成数{0}で獲得した報酬です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20121, /*discription*/"「祝9周年 ! プラチナチャンス」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20122, /*discription*/"「祝9周年 ! プラチナチャンス」{0}等A賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20123, /*discription*/"「祝9周年 ! プラチナチャンス」{0}等B賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20124, /*discription*/"「祝9周年 ! プラチナチャンス」{0}等C賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20125, /*discription*/"「祝9周年 ! プラチナチャンス」特別賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20126, /*discription*/"「デレステ特訓パズルクエスト」キャンペーンのプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20127, /*discription*/"「STARLIGHT FANTASY連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20128, /*discription*/"「ノスタルジーあにぷち」追加記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20129, /*discription*/"「THE IDOLM@STER CINDERELLA GIRLS アニバーサリー生配信 ～NEXT STEP!!!～」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20130, /*discription*/"「オールアイマス大感謝祭 ～2025年までもう待てない ! 生配信～」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20131, /*discription*/"「Let’s AMUSEMENT!!!連動キャンペーン」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20132, /*discription*/"「アイドルマスター20周年前夜祭生配信」放送記念のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20133, /*discription*/"「ありがとう10周年 ! プラチナチャンス」のミッション達成数{0}で獲得した報酬です。", /*type_1*/90, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20134, /*discription*/"「ありがとう10周年 ! プラチナチャンス」{0}等当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20135, /*discription*/"「ありがとう10周年 ! プラチナチャンス」{0}等A賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20136, /*discription*/"「ありがとう10周年 ! プラチナチャンス」{0}等B賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20137, /*discription*/"「ありがとう10周年 ! プラチナチャンス」{0}等C賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20138, /*discription*/"「ありがとう10周年 ! プラチナチャンス」特別賞当選のプレゼントです。", /*type_1*/32, /*type_2*/0, /*type_3*/0, /*type_4*/0);
INSERT INTO `gift_message` VALUES (/*id*/20139, /*discription*/"「10周年記念!!カウントダウンログインボーナス」のプレゼントです。", /*type_1*/0, /*type_2*/0, /*type_3*/0, /*type_4*/0);
