CREATE TABLE 'idel_vote_idol' ('id' INTEGER NOT NULL, 'campaign_id' INTEGER NOT NULL, 'card_id' INTEGER NOT NULL, 'use_type' INTEGER NOT NULL, 'index' INTEGER NOT NULL, 'description' TEXT NOT NULL, 'insert_word_type' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `idel_vote_idol` VALUES (/*id*/1, /*campaign_id*/10007, /*card_id*/200344, /*use_type*/0, /*index*/1, /*description*/"託された想いを力に変えて、進み続ける……へへっ。\nこういう少年漫画みたいなノリ、燃えてくるじゃないっスか。\n力、貸してほしいっス、{0}プロデューサー !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/2, /*campaign_id*/10007, /*card_id*/100828, /*use_type*/0, /*index*/1, /*description*/"あったかくてお日様みたいな、{0}さんの声……\nふふっ、届いてますよ～。いま、行きますね～。\n私が私らしくステージに立つのを、みんなが待っていますから～。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/3, /*campaign_id*/10007, /*card_id*/300710, /*use_type*/0, /*index*/1, /*description*/"高くて大きな波ほど、乗りこなし甲斐があるのよね。\nまして{0}くんの応援つきならなおさら♪\nこのチャンス、絶対に掴んでみせるわ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/4, /*campaign_id*/10007, /*card_id*/200442, /*use_type*/0, /*index*/1, /*description*/"{0}プロデューサー、見ていてくださいね。\n私こう見えて、期待には応えていきたい人間なので。\nこれまでふたりで歩んできた積み重ねを信じましょう。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/5, /*campaign_id*/10007, /*card_id*/300418, /*use_type*/0, /*index*/1, /*description*/"よっしゃ、祭りやー ! {0}はんも行くで !\nこういうとこはド派手に楽しく、盛り上げたモン勝ちや ! \n参加したみんなを、涙が出るくらい笑かしたるっ ! 覚悟しとき !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/6, /*campaign_id*/10007, /*card_id*/200474, /*use_type*/0, /*index*/1, /*description*/"何かを成功させんのに必要なのは、計画・決断・気合いってな。\nお前が立てた計画で、アタシが腹くくって始めたんだ。\nあとはふたり、最後まで気合いで走り抜けるだけだろ？", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/7, /*campaign_id*/10007, /*card_id*/200222, /*use_type*/0, /*index*/1, /*description*/"ふふっ、{0}さんはやっぱりシューコちゃんを\n応援してくれるんだねー。普段ならとぼけたりもするかもだけど、\n今回はノリノリで行っちゃう♪ ま、どーんと構えててよっ。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/8, /*campaign_id*/10007, /*card_id*/100174, /*use_type*/0, /*index*/1, /*description*/"夢をいくつも叶えながら、ここまで来たけど……\nもっと大きな夢、見ちゃってもいいのかなって思います。\n{0}さんと一緒なら、きっと…… !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/9, /*campaign_id*/10007, /*card_id*/100354, /*use_type*/0, /*index*/1, /*description*/"約束したよね、いつかドーナツだって越えちゃうって。\nだから手をつなごう、{0}プロデューサー !\nせーのであたしを、たかくたか～く揚げてね♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/10, /*campaign_id*/10007, /*card_id*/200366, /*use_type*/0, /*index*/1, /*description*/"{0}さんが示してくれたこの道で、\nまだ誰も見たことない、私だけのロックンロールを\n見つけてみせます ! だから……見ていてください !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/11, /*campaign_id*/10007, /*card_id*/100264, /*use_type*/0, /*index*/1, /*description*/"私、決めたんですっ。私がまだ知らない私、\nもっといっぱい見つけて、もっとたくさんキラキラするんだって。\nだから一緒に走ってください、{0}さんっ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/12, /*campaign_id*/10007, /*card_id*/200096, /*use_type*/0, /*index*/1, /*description*/"今の私があるのは、私の中にたくさんの可能性が眠っていると\n{0}さんが教えてくれたからです。\nこの先の新しい可能性も、ふたりで一緒に見つけていきましょう !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/13, /*campaign_id*/10007, /*card_id*/300518, /*use_type*/0, /*index*/1, /*description*/"この旅の先に何が待ってるのか、どんな出会いがあるのか……\nワクワクするね、{0}プロデューサー !\n一緒に、素敵な景色を目指して進んでみよう♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/14, /*campaign_id*/10007, /*card_id*/300502, /*use_type*/0, /*index*/1, /*description*/"{0}Pちゃんにはたくさん投資してもろてる。\nせやからアタシも、たまにはちゃーんと恩返しせんとね♪\n一緒に勝って、バリバリ稼いで……目指せ、ふたりでwin-winや !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/15, /*campaign_id*/10007, /*card_id*/300848, /*use_type*/0, /*index*/1, /*description*/"ひらめきましたよ、{0}プロデューサー !\nファンのみんなを爆笑の渦に巻き込む、とっておきのギャグが !\nさぁさぁ、さっそく作戦会議をしましょうっ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/16, /*campaign_id*/10007, /*card_id*/200850, /*use_type*/0, /*index*/1, /*description*/"時代の記憶を残す博物館に、アイドルもその名を連ねていると\nしたら……私も胸を張って、そこに並ぶ存在になりたいです。\n{0}さんが選んでくれたアイドルとして……。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/17, /*campaign_id*/10007, /*card_id*/300528, /*use_type*/0, /*index*/1, /*description*/"準備はできとるかね、{0}しゃん !\nウチらのスズホワールドはまだまだ終わりじゃなか。\nここから続く新しい世界……一緒に見に行かんね !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/18, /*campaign_id*/10007, /*card_id*/200868, /*use_type*/0, /*index*/1, /*description*/"{0}さんが後押ししてくれるのを感じるとね、\n何でもできるって思えるのよ。ふふ、自惚れじゃないわ。\nだから期待していて。それに応えるだけの努力はしてきたから。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/19, /*campaign_id*/10007, /*card_id*/100092, /*use_type*/0, /*index*/1, /*description*/"もっとお仕事だよ、{0}チャン !\nパワーアップしたねこチャンスタイルで、\nどんな期待にだって応えちゃう♪いまのみくはノリノリにゃあ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/20, /*campaign_id*/10007, /*card_id*/300696, /*use_type*/0, /*index*/1, /*description*/"フフッ、アリガト、マイダーリン♪\n{0}と磨いたアタシだもの、不安はないワ !\n最高にエレガントなレディの姿を、みんなに見せちゃいまショ♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/21, /*campaign_id*/10007, /*card_id*/100190, /*use_type*/0, /*index*/1, /*description*/"お天道さん、お星さん、そして{0}はん。\nみんなに願いをかけて、おひとつ、きばっていきまひょか。\nまだまだぎょうさんの出会いが、うちを呼んではりますよって♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/22, /*campaign_id*/10007, /*card_id*/200772, /*use_type*/0, /*index*/1, /*description*/"{0}さんは、私の良さを伝えることに\n誰よりも長けている、ソムリエのような人。そんな貴方の応援なら\n何より心強いわ。さあ行きましょう、世界中を楽しませに。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/23, /*campaign_id*/10007, /*card_id*/100814, /*use_type*/0, /*index*/1, /*description*/"ちょっとオ・ト・ナのスタイルで、自分らしく魅せちゃうっ♪\n絶対できるよねぇ。{0}プロデューサーと、\nママの自慢のみやびぃだもん♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/24, /*campaign_id*/10007, /*card_id*/100832, /*use_type*/0, /*index*/1, /*description*/"今日よりも明日はもっと、多くの人々へ元気と癒しを。\n{0}さんと手を取り合うと決めた日から、\n変わらない私の生き方です。さあ、行きましょうか♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/25, /*campaign_id*/10007, /*card_id*/100318, /*use_type*/0, /*index*/1, /*description*/"レディたるもの、つねに高みを目指さなければ。\n{0}ちゃま、エスコートしてくださいまし。\nそばにいるあなたの言葉が、わたくしの自信の源ですもの♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/26, /*campaign_id*/10007, /*card_id*/200374, /*use_type*/0, /*index*/1, /*description*/"{0}サンがここに連れてきてくれたから\nアタシはこうして毎日自分の想いを歌えてるんだ。\n後悔なんてさせやしない、アタシの歌う世界を信じてよ。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/27, /*campaign_id*/10007, /*card_id*/100384, /*use_type*/0, /*index*/1, /*description*/"アタシってやっぱ、めちゃいい人たちに囲まれてんね☆\n{0}プロデューサーとみんなから、あったかい\n応援、受けまくりんぐ ! リナリナ、ガチ勝負モードぽよ☆", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/28, /*campaign_id*/10007, /*card_id*/100456, /*use_type*/0, /*index*/1, /*description*/"ふわふわ～ってお空に昇っていっちゃいそう～？\nでも、離れないでください～。{0}さんが\nそばにいてくれるから、小春、も～っとお姫様になれるんです～ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/29, /*campaign_id*/10007, /*card_id*/300570, /*use_type*/0, /*index*/1, /*description*/"やっぱ大きなステージってテンションアガる～っ !\n{0}の応援も心に真っ直ぐきたし……\nこれはもう全力で踊って、みんなで盛り上がるっきゃないっ♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/30, /*campaign_id*/10007, /*card_id*/200332, /*use_type*/0, /*index*/1, /*description*/"{0}プロデューサーさん……もりくぼはやっぱり\nこういう目立つ企画は……みなさんの期待……そうですか……。\nじゃあ、もう少し頑張って……明るい場所、目指してみます……。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/31, /*campaign_id*/10007, /*card_id*/300288, /*use_type*/0, /*index*/1, /*description*/"闇夜の中、ライトの中……どちらも極めてこそ、私の道。\n{0}殿と忍ドルを歩む中で、そう感じました。\nならば、わたくしが目指すべきはただひとつ。この先の勝利です !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/32, /*campaign_id*/10007, /*card_id*/200420, /*use_type*/0, /*index*/1, /*description*/"人の想いを受け止めて、己の力とするのがアイドルの道……。\nこれは珠美の剣の神髄にも、必ずどこかで繋がるでしょう。\n{0}殿、どうかご期待ください !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/33, /*campaign_id*/10007, /*card_id*/300442, /*use_type*/0, /*index*/1, /*description*/"勝ち上がって栄光を掴む、かぁ……くーっ、ワクワクする !\nしかも{0}さんとの協力プレー、\n最高に燃えてくるよ ! 一緒に目指そう、トップランカー !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/34, /*campaign_id*/10007, /*card_id*/200258, /*use_type*/0, /*index*/1, /*description*/"{0}さんと歩み出してから、私は変われました。\n今の私は、俯いてしまった人も笑顔にできるような存在。\nそしてこれから、もっと多くの人を照らしていきたいです…… !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/35, /*campaign_id*/10007, /*card_id*/300202, /*use_type*/0, /*index*/1, /*description*/"日菜子の夢は、もう日菜子だけのものじゃありません。\n{0}さんと一緒なら、もっと大きな夢に……\nむふふ♪この希望は、決して夢のままじゃ終わりませんよ～♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/36, /*campaign_id*/10007, /*card_id*/300454, /*use_type*/0, /*index*/1, /*description*/"イェ～イ ! {0}ちゃん、ノってんね☆\nんじゃ、ゆいも思いっきりがんばっちゃお♪\nこーゆーのは楽しいのが一番じゃん？テンションアゲてこ☆", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/37, /*campaign_id*/10007, /*card_id*/200778, /*use_type*/0, /*index*/1, /*description*/"私の歌を、初めて世界中に聞かせたいと言ってくれたのは\n{0}さんでした……。私の宝物の思い出。\nその想いに……きっと応えてみせますから、見守ってください。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/38, /*campaign_id*/10007, /*card_id*/300666, /*use_type*/0, /*index*/1, /*description*/"なるほど、Pの推しは凪。しかし、押してもつついても凪は凪。\nゴーイングマイウェイ、風任せ、無風というものです。\nならば凪は凪のまま、推されるのも悪くないな。むふー。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/39, /*campaign_id*/10007, /*card_id*/100620, /*use_type*/0, /*index*/1, /*description*/"さてと、どのカードを切ろうかしら……♪\n{0}さんとふたりで準備してきた手札、\n惜しみなくすべて使うわ。勝負事なら得意よ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/40, /*campaign_id*/10007, /*card_id*/300744, /*use_type*/0, /*index*/1, /*description*/"っしゃーー ! ! 応援されて、気合い入りまくり !\nいくぜ、{0}プロデューサー ! \nアタシらはここにいるぞって、大声で叫ぶぞーーっ ! !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/41, /*campaign_id*/10007, /*card_id*/200678, /*use_type*/0, /*index*/1, /*description*/"{0}さんは私に、新しい自分と向き合える場所を\n作ってくれました。そんな人の後押しがあるから、今の私が居ます。\n見ていてください。最高の私を表現してみせますから…… !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/42, /*campaign_id*/10007, /*card_id*/200830, /*use_type*/0, /*index*/1, /*description*/"アタシが万全の状態で、{0}がセコンドにいる。\nこの組み合わせで勝負に出ない選択肢は無いだろ？\nちゃんと見てなよ……最高にアツい想いをさせてやるからさ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/43, /*campaign_id*/10007, /*card_id*/300474, /*use_type*/0, /*index*/1, /*description*/"今、この場で、私にかける言葉があると思う？\nわかっているなら働きなさい、{0}。\n自分の価値くらい、己の手で生み出してみせなさいな。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/44, /*campaign_id*/10007, /*card_id*/300676, /*use_type*/0, /*index*/1, /*description*/"目指すゴールは見えてるよ。だから、あとは走るだけっ !\n{0}Pさんもちゃんとついてきてね？\n一緒にテープを切ったら、きっと最高の景色が待ってるから♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/45, /*campaign_id*/10007, /*card_id*/200414, /*use_type*/0, /*index*/1, /*description*/"{0}殿が後方支援についてくださるならば、\nどんな難しい戦局も乗り切れますな。\nその信頼に応えるべく、日頃の鍛錬の成果を発揮しましょう !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/46, /*campaign_id*/10007, /*card_id*/100856, /*use_type*/0, /*index*/1, /*description*/"わだす、たくさんの人に知ってもらいてぇです。\n変わりたいって勇気さあれば、人は誰でも変われるんだってこと。\nへば、{0}さんがくれた魔法、見せてきますね !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/47, /*campaign_id*/10007, /*card_id*/300550, /*use_type*/0, /*index*/1, /*description*/"{0}プロデューサーの願い、感じたぞ !\nヒーローはいつだって、みんなの想いを力に変えるんだ !\n今のアタシは限界の先だって越えられる ! 越えてみせるっ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/48, /*campaign_id*/10008, /*card_id*/200892, /*use_type*/0, /*index*/1, /*description*/"時代が求めるヘレンの姿……それこそが今の私、今のヘレン。\n{0}はこの先の時代にどんなヘレンを\n見ているのかしら。確かめてみなさい、一番間近でね !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/49, /*campaign_id*/10008, /*card_id*/300080, /*use_type*/0, /*index*/1, /*description*/"うぇへへ、{0}ちゃん応援ありがと☆\nおかげできらり、い～っぱいはぴはぴできるんだよ。\nだからありがとうの気持ちも、ここからい～っぱいお返しすゆっ☆", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/50, /*campaign_id*/10008, /*card_id*/100644, /*use_type*/0, /*index*/1, /*description*/"{0}ぷろでゅーしゃーや、優しい人たちに\n囲まれて、くるみ、とっても楽しいのぉ♪ ……ぐしゅっ♪\nみんなで歌えるように、くるみもいっぱい頑張るよぉ。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/51, /*campaign_id*/10008, /*card_id*/100690, /*use_type*/0, /*index*/1, /*description*/"ほわぁ～？ あま～い香りが、私を呼んでいますの～♪\n{0}さん、一緒に行っちゃいましょう～。\n私、我慢はしないので～♪ えへへぇ～♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/52, /*campaign_id*/10008, /*card_id*/100422, /*use_type*/0, /*index*/1, /*description*/"辛いことはあっても、後悔したことはひとつもないんです。\n{0}さんに出会ってから、今日までずっと……。\nだからまた、思いたいです……挑戦してよかった、って…… !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/53, /*campaign_id*/10008, /*card_id*/200708, /*use_type*/0, /*index*/1, /*description*/"{0}さんが教えてくれた、アイドルの輝きは……\n夜明けの海を照らす太陽のように、私の世界を広げたわ。\nその光に魅せられた、人魚の歌声……どうか聞いていてね。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/54, /*campaign_id*/10008, /*card_id*/200308, /*use_type*/0, /*index*/1, /*description*/"受け継いだ技と想いを作品へ練り上げるのが陶芸であるように、\n伝えられた技と想いで自身を磨くのがアイドルなのだと思います。\n{0}さんの想いも、私の中に息づいています。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/55, /*campaign_id*/10008, /*card_id*/200836, /*use_type*/0, /*index*/1, /*description*/"{0}プロデューサーと一緒にtopに立つ……\nそんなmiracleも、本当に起こせるって信じてマスヨ。\n私たちの全力で、行ける所までGoGo ! デスネ♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/56, /*campaign_id*/10008, /*card_id*/200758, /*use_type*/0, /*index*/1, /*description*/"{0}さんと出会って目にしたこの世界の輝きは、\n唯一無二のもの。一度きりの人生を、最高のものにしてくれるの。\n感謝しているわ。さあ、次は何を見せてくれるのかしら？", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/57, /*campaign_id*/10008, /*card_id*/100546, /*use_type*/0, /*index*/1, /*description*/"待っていたぞ、{0} !\nさあ、ステージの大発明をみんなに見せつけるぞ !\nもちろん、ふたりでだ。天才はひとりでは成り立たないものさ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/58, /*campaign_id*/10008, /*card_id*/100728, /*use_type*/0, /*index*/1, /*description*/"ゆくさきはまだわかりません。でも{0}さんが\n手を引いてくれる場所なら、きっと光が溢れてるって思うんです。\nだから勇気を持って、まずは一歩を踏み出します…… !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/59, /*campaign_id*/10008, /*card_id*/100838, /*use_type*/0, /*index*/1, /*description*/"見たことのないミステリーが待っているようですね。\nとなれば、ふっふっふ……おなじみ名探偵の出番でしょう。\n{0}さん、私の閃きについてこられますか !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/60, /*campaign_id*/10008, /*card_id*/200702, /*use_type*/0, /*index*/1, /*description*/"{0}さんの信頼に応えて、最高のステージに\n立ってみせる。それが今の私の夢、一番の目標よ。\n任せておいて。私、夢中になったら結果を出すまで止まらないもの。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/61, /*campaign_id*/10008, /*card_id*/200230, /*use_type*/0, /*index*/1, /*description*/"{0}さん、眼鏡を新調する準備をお願いします !\nだってこれから、新たな眼鏡神話が始まるんですからね。\n相応の装いをして、新しい世界を見に行きましょう !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/62, /*campaign_id*/10008, /*card_id*/300184, /*use_type*/0, /*index*/1, /*description*/"来たな。私と{0}の、絆が試される時……。\nでも、きっと大丈夫。ふたりなら無敵だからな。\nだから……飛ばしていくぜェェェ ! ヒャッハアアアアア !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/63, /*campaign_id*/10008, /*card_id*/300310, /*use_type*/0, /*index*/1, /*description*/"やっぱプロデューサーもはぁとのことが気になる？ わかるー☆\nんじゃそういうことで、こっからは一蓮托生な♪\n崖っぷちだろうとなんだろうと、ふたりで根性見せてくぞ☆", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/64, /*campaign_id*/10008, /*card_id*/200806, /*use_type*/0, /*index*/1, /*description*/"うふふ、{0}さんは、あやかの良さを\n一番よくわかってる人だもんねぇ。ありがと、すっごく嬉しい♪\nこのままナンバーワンまで一緒に行こうねぇ♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/65, /*campaign_id*/10008, /*card_id*/300806, /*use_type*/0, /*index*/1, /*description*/"身も心も磨いて、今回のフライトに備えてきたの。\n準備はできてるわよね、{0}さん♪\n行き先はもちろん、頂上のその先 ! 一番の絶景が見れる場所よ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/66, /*campaign_id*/10008, /*card_id*/100714, /*use_type*/0, /*index*/1, /*description*/"「好き」は推したい ! 共有したい ! それが人のサガなんだわ。\n{0}さんのことはユリユリが推すじぇ !\n推して推されて、ダイマしあって、そんな世界が理想郷 !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/67, /*campaign_id*/10008, /*card_id*/300844, /*use_type*/0, /*index*/1, /*description*/"{0}プロデューサー、ありがと !\n最高の結果でおもてなしできたら、きっとみんなも嬉しいけん。\n料理を作る時みたいに、真心こめて……しんけん頑張るよ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/68, /*campaign_id*/10008, /*card_id*/200206, /*use_type*/0, /*index*/1, /*description*/"{0}さんの信頼に応えたいという想い。\nこれは、私の中でずっと育ててきた、確かな気持ちです。\nですから、えへへ……期待、していてくださいね。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/69, /*campaign_id*/10008, /*card_id*/100624, /*use_type*/0, /*index*/1, /*description*/"{0}プロデューサーと一緒に、\nまた新しいものをいっぱい見られるんだって思うと……\n私、わくわくしちゃうんですっ ! 跳ねちゃいたいくらい♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/70, /*campaign_id*/10008, /*card_id*/100206, /*use_type*/0, /*index*/1, /*description*/"アイドルの私も、愛情込めてお料理中ですっ !\n美味しい匂いで、みんなが集まってくれますようにっ♪\n{0}さん、一緒にお出迎えの準備ですよ♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/71, /*campaign_id*/10008, /*card_id*/100370, /*use_type*/0, /*index*/1, /*description*/"また新しいキラキラを、{0}さんと\n目指せるんだね。その場所から、何が見えるのかな。\n考えると、ドキドキして……でもそれ以上に、嬉しくなるんだ。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/72, /*campaign_id*/10008, /*card_id*/100684, /*use_type*/0, /*index*/1, /*description*/"このひとときを{0}さんも楽しみませんこと？\n優雅に上品に、そして、おもてなしの心を忘れずに。\nそうすれば……よい香りはおのずから漂うものですわ♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/73, /*campaign_id*/10008, /*card_id*/300694, /*use_type*/0, /*index*/1, /*description*/"{0}さんの起こす風はいつも、\nウチをとびっきりの絶景へと連れてってくれるんだ。\n行こう、どこまでも遠くへ。ウチも背中を預けるからさ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/74, /*campaign_id*/10008, /*card_id*/200468, /*use_type*/0, /*index*/1, /*description*/"おー。{0}殿はライラさんに、たくさん\nがんばってほしいのですねー。ライラさん、期待に応える子で\nございますので、お祝いのごはんをお願いしますですよー。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/75, /*campaign_id*/10008, /*card_id*/200562, /*use_type*/0, /*index*/1, /*description*/"七海はいろんな釣り場で大物を釣ってきたれすからね。\nアイドル海でも、おっきな魚拓を取りたいのれす～。\nプロデューサーとの航海なら、きっと大漁なのれすよ～ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/76, /*campaign_id*/10008, /*card_id*/300362, /*use_type*/0, /*index*/1, /*description*/"{0}くんはあたしをご指名ね♪\nなら当然、あたしも張り切って応えなきゃ !\nさぁ、世界中のみんなの心を捕まえに行きましょ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/77, /*campaign_id*/10008, /*card_id*/200482, /*use_type*/0, /*index*/1, /*description*/"幸運体質みたいによく言われますけれど、私にとっては\n{0}プロデューサーと出会えたことが\n最高の幸運なんですよ。この先もずっと、です。ふふっ♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/78, /*campaign_id*/10008, /*card_id*/200834, /*use_type*/0, /*index*/1, /*description*/"{0}さんは、まだ私の知らない私がいることを\n教えてくれる。こんなに楽しい旅路なら、どこまでも行けるわね。\n次はどんな景色が見られるかしら。ふふ、心が躍っているわ。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/79, /*campaign_id*/10008, /*card_id*/200822, /*use_type*/0, /*index*/1, /*description*/"{0}プロデューサーが期待していてくれるなら、\n私は今の自分にできる最高の笑顔で応えたいんです。\nそしてみんなに伝えます。心からの笑顔は幸せをくれるって…… !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/80, /*campaign_id*/10008, /*card_id*/200108, /*use_type*/0, /*index*/1, /*description*/"私の物語の中には、{0}さんの存在があります。\n紡ぎ手である私の人生に、欠かせない登場人物ですから。\nこれからもどうか、この素敵な物語を彩ってください。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/81, /*campaign_id*/10008, /*card_id*/100154, /*use_type*/0, /*index*/1, /*description*/"ふ～ん、キミってばまた面白そーなことやってるんだね～。\nまだ見たことないとびっきりの化学反応、期待してもいい？\n志希ちゃんはとっくに準備オッケー♪ もう待ちきれな～い♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/82, /*campaign_id*/10008, /*card_id*/100680, /*use_type*/0, /*index*/1, /*description*/"はじまりは、{0}様に見出された音。\nその音は、さらなる高みを目指し、輝きつづけております。\nたどり着いてみせますわ。瞬く星を見あげて……花の誇りを胸に。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/83, /*campaign_id*/10008, /*card_id*/300274, /*use_type*/0, /*index*/1, /*description*/"ムムムーンッ ! 感じますよ、{0}さん !\n私たちにさいきっくエネルギーがどんどん集まってます !\nこのパワーがあれば、エスパーユッコは無敵ですね !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/84, /*campaign_id*/10008, /*card_id*/300792, /*use_type*/0, /*index*/1, /*description*/"女子力もアイドル力も、コツコツ積み重ねるのが大事ですよねぇ♪\nそういうのは、あたしも自信があるんです。\nだって、{0}さんと一緒に磨いてきましたから☆", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/85, /*campaign_id*/10008, /*card_id*/100506, /*use_type*/0, /*index*/1, /*description*/"もっとそばまで行って、ニコニコ笑顔を届けたいんですぅ !\nきっとみんな、待ってるって思うからっ♪\n{0}プロデューサーさん、一緒に行きましょぉ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/86, /*campaign_id*/10008, /*card_id*/200524, /*use_type*/0, /*index*/1, /*description*/"エースストライカーの役目はチームの期待を背負うことだろ？\n安心しろって{0}、しっかり決めてくるからさ。\nへへっ、オレの活躍、一瞬でも見逃すんじゃねーぞ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/87, /*campaign_id*/10008, /*card_id*/200072, /*use_type*/0, /*index*/1, /*description*/"ちゃんと見ててね、{0}プロデューサー。\nあの時一緒に踏み出したアイドルの世界で……\n自分がどこまで行けるのか、確かめてみたいんだ。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/88, /*campaign_id*/10008, /*card_id*/200764, /*use_type*/0, /*index*/1, /*description*/"グラフィティ。アイドル。エンタメは笑顔を作るのが役割っす。\n大切なのは「楽しい」を作品に込めて伝えること。\n{0}さんとアタシなら、きっとできるっすね♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/89, /*campaign_id*/10008, /*card_id*/300244, /*use_type*/0, /*index*/1, /*description*/"たくさんの人がくれる応援は、私にとっての幸せの花なんだ。\n{0}さんの言葉もそう。\n私の心の真ん中で、いつも元気と勇気を運んでくれるんだよ♪", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/90, /*campaign_id*/10008, /*card_id*/200490, /*use_type*/0, /*index*/1, /*description*/"{0}さんが背中を押してくれるから、\n私はいつも冒険の中でかけがえのない宝物に出会えました。\n私たちならどんな困難だって素敵な冒険に変えられます !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/91, /*campaign_id*/10008, /*card_id*/100536, /*use_type*/0, /*index*/1, /*description*/"パンパカパーン ! アイドルみちるのベーカリー、\nパパーンと店舗拡大中ですよ ! もっと美味しいあたしの焼き方、\n見つけてくださいね、{0}プロデューサー !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/92, /*campaign_id*/10008, /*card_id*/100446, /*use_type*/0, /*index*/1, /*description*/"世界をひとつ知るたび、その広さをさらに実感いたしますわ。\n{0}様、私をもっと先へと導いてくださいませ。\nまだまだ多くの人々に、多くの歌に、私は出会いたいのです。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/93, /*campaign_id*/10008, /*card_id*/200878, /*use_type*/0, /*index*/1, /*description*/"物は買えないけれど、貰うと嬉しいエンは何か、わかるかしら？\n……そう。応援よ。特に{0}君の、ね。\nこんなにたっぷりもらえたなら、もう怖いものなんてないわ。", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/94, /*campaign_id*/10008, /*card_id*/100436, /*use_type*/0, /*index*/1, /*description*/"{0}プロデューサーとふたりで作ってきた\nいっぱいのメモ、わたしは信じます。\nずっとずっとそうやって、この場所までたどり着いたから…… !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/95, /*campaign_id*/10008, /*card_id*/300842, /*use_type*/0, /*index*/1, /*description*/"この高揚感、なんだか試合前を思い出すねッ !\n{0}プロデューサーもワクワクするでしょ？\nこの気持ちのまま、最後の一秒まで楽しんでいこうッ !", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/96, /*campaign_id*/10009, /*card_id*/100462, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/97, /*campaign_id*/10009, /*card_id*/100338, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/98, /*campaign_id*/10009, /*card_id*/200786, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/99, /*campaign_id*/10009, /*card_id*/200752, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/100, /*campaign_id*/10009, /*card_id*/200214, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/101, /*campaign_id*/10009, /*card_id*/300828, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/102, /*campaign_id*/10009, /*card_id*/300648, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/103, /*campaign_id*/10009, /*card_id*/200382, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/104, /*campaign_id*/10009, /*card_id*/100702, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/105, /*campaign_id*/10009, /*card_id*/300328, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/106, /*campaign_id*/10009, /*card_id*/300218, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/107, /*campaign_id*/10009, /*card_id*/200532, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/108, /*campaign_id*/10009, /*card_id*/300432, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/109, /*campaign_id*/10009, /*card_id*/300624, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/110, /*campaign_id*/10009, /*card_id*/300816, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/111, /*campaign_id*/10009, /*card_id*/300768, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/112, /*campaign_id*/10009, /*card_id*/100594, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/113, /*campaign_id*/10009, /*card_id*/200872, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/114, /*campaign_id*/10009, /*card_id*/200514, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/115, /*campaign_id*/10009, /*card_id*/100780, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/116, /*campaign_id*/10009, /*card_id*/300778, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/117, /*campaign_id*/10009, /*card_id*/200668, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/118, /*campaign_id*/10009, /*card_id*/100166, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/119, /*campaign_id*/10009, /*card_id*/100742, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/120, /*campaign_id*/10009, /*card_id*/300810, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/121, /*campaign_id*/10009, /*card_id*/300124, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/122, /*campaign_id*/10009, /*card_id*/100756, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/123, /*campaign_id*/10009, /*card_id*/300350, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/124, /*campaign_id*/10009, /*card_id*/300728, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/125, /*campaign_id*/10009, /*card_id*/200788, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/126, /*campaign_id*/10009, /*card_id*/100802, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/127, /*campaign_id*/10009, /*card_id*/200158, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/128, /*campaign_id*/10009, /*card_id*/100766, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/129, /*campaign_id*/10009, /*card_id*/200820, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/130, /*campaign_id*/10009, /*card_id*/100276, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/131, /*campaign_id*/10009, /*card_id*/200184, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/132, /*campaign_id*/10009, /*card_id*/100252, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/133, /*campaign_id*/10009, /*card_id*/300226, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/134, /*campaign_id*/10009, /*card_id*/200550, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/135, /*campaign_id*/10009, /*card_id*/200636, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/136, /*campaign_id*/10009, /*card_id*/200890, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/137, /*campaign_id*/10009, /*card_id*/100350, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/138, /*campaign_id*/10009, /*card_id*/100124, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/139, /*campaign_id*/10009, /*card_id*/200398, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/140, /*campaign_id*/10009, /*card_id*/100870, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/141, /*campaign_id*/10009, /*card_id*/100664, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/142, /*campaign_id*/10009, /*card_id*/100076, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/143, /*campaign_id*/10010, /*card_id*/200846, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/144, /*campaign_id*/10010, /*card_id*/100744, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/145, /*campaign_id*/10010, /*card_id*/200792, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/146, /*campaign_id*/10010, /*card_id*/100486, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/147, /*campaign_id*/10010, /*card_id*/100568, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/148, /*campaign_id*/10010, /*card_id*/100730, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/149, /*campaign_id*/10010, /*card_id*/100796, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/150, /*campaign_id*/10010, /*card_id*/300708, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/151, /*campaign_id*/10010, /*card_id*/200292, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/152, /*campaign_id*/10010, /*card_id*/300718, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/153, /*campaign_id*/10010, /*card_id*/100476, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/154, /*campaign_id*/10010, /*card_id*/100804, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/155, /*campaign_id*/10010, /*card_id*/100242, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/156, /*campaign_id*/10010, /*card_id*/300598, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/157, /*campaign_id*/10010, /*card_id*/300108, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/158, /*campaign_id*/10010, /*card_id*/300410, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/159, /*campaign_id*/10010, /*card_id*/200074, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/160, /*campaign_id*/10010, /*card_id*/300322, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/161, /*campaign_id*/10010, /*card_id*/200720, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/162, /*campaign_id*/10010, /*card_id*/200198, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/163, /*campaign_id*/10010, /*card_id*/100078, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/164, /*campaign_id*/10010, /*card_id*/100794, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/165, /*campaign_id*/10010, /*card_id*/100398, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/166, /*campaign_id*/10010, /*card_id*/100808, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/167, /*campaign_id*/10010, /*card_id*/200430, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/168, /*campaign_id*/10010, /*card_id*/100308, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/169, /*campaign_id*/10010, /*card_id*/300534, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/170, /*campaign_id*/10010, /*card_id*/300388, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/171, /*campaign_id*/10010, /*card_id*/300266, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/172, /*campaign_id*/10010, /*card_id*/300078, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/173, /*campaign_id*/10010, /*card_id*/100792, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/174, /*campaign_id*/10010, /*card_id*/300164, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/175, /*campaign_id*/10010, /*card_id*/100408, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/176, /*campaign_id*/10010, /*card_id*/300148, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/177, /*campaign_id*/10010, /*card_id*/200496, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/178, /*campaign_id*/10010, /*card_id*/200138, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/179, /*campaign_id*/10010, /*card_id*/300488, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/180, /*campaign_id*/10010, /*card_id*/100662, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/181, /*campaign_id*/10010, /*card_id*/300498, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/182, /*campaign_id*/10010, /*card_id*/300682, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/183, /*campaign_id*/10010, /*card_id*/100496, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/184, /*campaign_id*/10010, /*card_id*/300192, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/185, /*campaign_id*/10010, /*card_id*/100390, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/186, /*campaign_id*/10010, /*card_id*/300398, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/187, /*campaign_id*/10010, /*card_id*/200734, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/188, /*campaign_id*/10010, /*card_id*/200354, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/189, /*campaign_id*/10010, /*card_id*/300120, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
INSERT INTO `idel_vote_idol` VALUES (/*id*/190, /*campaign_id*/10010, /*card_id*/200676, /*use_type*/0, /*index*/1, /*description*/"", /*insert_word_type*/0);
CREATE INDEX 'idel_vote_idol_0_campaign_id' on 'idel_vote_idol'('campaign_id');
CREATE INDEX 'idel_vote_idol_0_campaign_id_1_card_id' on 'idel_vote_idol'('campaign_id','card_id');
