CREATE TABLE 'ignore_card' ('card_id' INTEGER NOT NULL, 'card_name' TEXT NOT NULL, PRIMARY KEY('card_id'));
INSERT INTO `ignore_card` VALUES (/*card_id*/201375, /*card_name*/"星街すいせい");
INSERT INTO `ignore_card` VALUES (/*card_id*/201376, /*card_name*/"星街すいせい＋");
INSERT INTO `ignore_card` VALUES (/*card_id*/201381, /*card_name*/"［スターライト・ハーモニー］星街すいせい");
INSERT INTO `ignore_card` VALUES (/*card_id*/201382, /*card_name*/"［スターライト・ハーモニー］星街すいせい＋");
INSERT INTO `ignore_card` VALUES (/*card_id*/201383, /*card_name*/"［ジュビリー］星街すいせい");
INSERT INTO `ignore_card` VALUES (/*card_id*/201384, /*card_name*/"［ジュビリー］星街すいせい＋");
INSERT INTO `ignore_card` VALUES (/*card_id*/201385, /*card_name*/"［ジュビリー］高垣楓");
INSERT INTO `ignore_card` VALUES (/*card_id*/201386, /*card_name*/"［ジュビリー］高垣楓＋");
INSERT INTO `ignore_card` VALUES (/*card_id*/201465, /*card_name*/"［ありすとワンダーランド］橘ありす");
INSERT INTO `ignore_card` VALUES (/*card_id*/201466, /*card_name*/"［ありすとワンダーランド］橘ありす＋");
