CREATE TABLE 'individual_tutorial' ('id' INTEGER NOT NULL, 'img' INTEGER NOT NULL, 'discription' TEXT NOT NULL)
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/1, /*discription*/"ガシャを引くことでアイドルが新しく加入します。\nガシャには「プラチナオーディションガシャ」と\n「ローカルオーディションガシャ」の2種類があります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/1, /*discription*/"プラチナオーディションガシャはスタージュエルを消費して、\nレア以上の強力なアイドルを獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/2, /*discription*/"ガシャでSSレアアイドルを獲得すると、\nルームで使用できるアイドルのポスターが\nプレゼントに送られます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/2, /*discription*/"さらに、SSレアアイドルは特別な衣装で\n3DLIVEのパフォーマンスを行います。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/3, /*discription*/"特定のSレア以上のアイドルをユニット編成で\nセンターに設定することで、LIVEの「お願い ! シンデレラ」を\nソロ歌唱で楽しめます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10003, /*img*/1, /*discription*/"ローカルオーディションガシャは友情ptを消費して、\nアイドルやトレーニングチケットを獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11001, /*img*/1, /*discription*/"スペシャルガシャセットは期間限定販売です。\n購入すると「スカウトチケット」と「プラチナ10連ガシャ\nチケット」を1枚ずつ獲得できます。\n※有償スタージュエルでのみ購入することができます");
INSERT INTO `individual_tutorial` VALUES (/*id*/11001, /*img*/2, /*discription*/"「スカウトチケット」はレア、Sレア、SSレアのアイドル\nをスカウトできるチケットです。\nスカウトできるアイドルは、「対象アイドル」ボタンから\nご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11001, /*img*/3, /*discription*/"「プラチナ10連ガシャチケット」は、チケット使用時に\n開催中のプラチナ10連ガシャを引けるチケットです。\nプラチナガシャと同様に、Sレア以上のアイドル1人が\n確定で出現します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11002, /*img*/1, /*discription*/"スペシャルガシャセットは期間限定販売です。\n購入すると「スカウトチケット」と「プラチナ10連ガシャ\nチケット」を1枚ずつ獲得できます。\n※有償スタージュエルでのみ購入することができます");
INSERT INTO `individual_tutorial` VALUES (/*id*/11002, /*img*/2, /*discription*/"「スカウトチケット」はレア、Sレア、SSレアのアイドル\nをスカウトできるチケットです。\nスカウトできるアイドルは、「対象アイドル」ボタンから\nご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11002, /*img*/3, /*discription*/"「プラチナ10連ガシャチケット」は、チケット使用時に\n開催中のプラチナ10連ガシャを引けるチケットです。\nプラチナガシャと同様に、Sレア以上のアイドル1人が\n確定で出現します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20001, /*img*/1, /*discription*/"ルームはお気に入りメンバーが集う場所です。\nいろいろなルームアイテムを配置して、\nあなた好みの空間を作りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20001, /*img*/2, /*discription*/"ルームアイテムの中には設置する事で、\n様々な効果を発揮する物があります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20001, /*img*/2, /*discription*/"さらに、一部の効果付きルームアイテムは、\nマニーを使ってレベルアップできます。\n効果付きルームアイテムでLIVEを有利にしましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20001, /*img*/3, /*discription*/"ルームアイテムの中には、設置していると一定時間ごとに\nアイテムが届くものがあります。\n時々ルームを覗いて、届いたアイテムを受け取りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20002, /*img*/1, /*discription*/"ショップでは、マニーを使ってルームアイテムを購入できます。\nカテゴリタブを切り替えて欲しいルームアイテムを探したら、\n「購入」ボタンを押しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20002, /*img*/2, /*discription*/"ルームアイテムをタップで移動して、置く場所を決めたら\n「設置」で購入が完了します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20002, /*img*/2, /*discription*/"あとで設置したい場合は「収納」を押せば倉庫に収納されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20003, /*img*/1, /*discription*/"倉庫には収納されたルームアイテムが保管されています。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20003, /*img*/2, /*discription*/"「設置」ボタンを押せば、倉庫内のルームアイテムを\nルームに設置できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20003, /*img*/3, /*discription*/"いらなくなったルームアイテムは「売却」ボタンで、\n売却してマニーに変える事ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20004, /*img*/1, /*discription*/"Like情報ではLikeの履歴を確認できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20004, /*img*/1, /*discription*/"「ルーム訪問」から、いろいろな人のルームに\n遊びに行ってみましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20005, /*img*/1, /*discription*/"「ルーム効果」では、現在発動しているルーム効果を\n確認できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20005, /*img*/1, /*discription*/"「詳細」タブでは、効果を発揮しているルームアイテムを\n見る事ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20006, /*img*/1, /*discription*/"VIEWモードでは、ルームが拡大して表示され、\nガイド線より手前のルームアイテムが見えなくなります。\n重なったルームアイテムを操作する場合などに便利です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20007, /*img*/1, /*discription*/"ギフトアイテムをアイドルに渡すと親愛度が上がります。\nそのアイドルに合ったギフトアイテムを渡すと、\nより多くの親愛度が上がります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20008, /*img*/1, /*discription*/"VIEWモードでは、表示領域とミニウィンドウが表示され、\n表示領域の外側のルームアイテムが見えなくなります。\n重なったルームアイテムを操作する場合などに便利です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20008, /*img*/2, /*discription*/"表示領域はミニウィンドウ上で移動することができます。\nミニウィンドウでルーム全体を見渡しながら\n編集したい箇所に表示領域を合わせることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20008, /*img*/3, /*discription*/"ミニウィンドウは左側に収納したり、\n上側に移動したりすることができます。\n編集箇所に応じてミニウィンドウを移動させましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20008, /*img*/4, /*discription*/"「－」、「＋」ボタンで表示領域のサイズを\n変更することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20009, /*img*/1, /*discription*/"ルーム画面のレイアウトを変更しました。\nショップや倉庫へは右側の矢印ボタンを\nタップすると表示されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20009, /*img*/2, /*discription*/"ルームに名前を付けられるようになりました。\nルーム名はいつでも自由に変更できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20009, /*img*/3, /*discription*/"「一括受取」ボタンで宅配ボックスや\nチケットボードに届いているアイテムを\nまとめて受け取ることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20010, /*img*/1, /*discription*/"より自由にルームアイテムの設置が行える\nフリールームが追加されました。\n「ルーム移動」ボタンをタップすると\nフリールームへ移動できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20010, /*img*/2, /*discription*/"ルーム名変更ボタンから\nメインに設定するルームを設定することができます。\n自分や同僚がルームに入った際に、\nメイン設定を行っているルームが最初に表示されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20010, /*img*/3, /*discription*/"別のルームに設置中のアイテムは、\nルームアイテム一覧から直接移動できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20010, /*img*/4, /*discription*/"「お気に入り編成」から、事務所とフリールームに\n登場するアイドルを個別に設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20011, /*img*/1, /*discription*/"「一括収納」ボタンで設置中のルームアイテムを\nまとめて倉庫に収納することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20099, /*img*/1, /*discription*/"ニコニコ生放送「デレステNIGHT☆☆☆☆☆☆」にて、\n制作が決定した「エンジェルウィング」が登場!!");
INSERT INTO `individual_tutorial` VALUES (/*id*/20101, /*img*/1, /*discription*/"ルームはお気に入りメンバーが集う場所です。\nいろいろなルームアイテムを配置して、\nあなた好みの空間を作りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20101, /*img*/2, /*discription*/"ルームアイテムの中には設置する事で、\n様々な効果を発揮する物があります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20101, /*img*/2, /*discription*/"さらに、一部の効果付きルームアイテムは、\nマニーを使ってレベルアップできます。\n効果付きルームアイテムでLIVEを有利にしましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20101, /*img*/3, /*discription*/"ルームアイテムの中には、設置していると一定時間ごとに\nアイテムが届くものがあります。\n時々ルームを覗いて、届いたアイテムを受け取りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20102, /*img*/1, /*discription*/"ショップでは、マニーを使ってルームアイテムを購入できます。\nカテゴリタブを切り替えて欲しいルームアイテムを探したら、\n「購入」ボタンを押しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20102, /*img*/2, /*discription*/"ルームアイテムをタップで移動して、置く場所を決めたら\n「設置」で購入が完了します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20102, /*img*/2, /*discription*/"あとで設置したい場合は「収納」を押せば倉庫に収納されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20103, /*img*/1, /*discription*/"倉庫には収納されたルームアイテムが保管されています。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20103, /*img*/2, /*discription*/"「設置」ボタンを押せば、倉庫内のルームアイテムを\nルームに設置できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20103, /*img*/3, /*discription*/"いらなくなったルームアイテムは「売却」ボタンで、\n売却してマニーに変える事ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20104, /*img*/1, /*discription*/"Like情報ではLikeの履歴を確認できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20104, /*img*/1, /*discription*/"「ルーム訪問」から、いろいろな人のルームに\n遊びに行ってみましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30001, /*img*/1, /*discription*/"LIVEでは、ミュージックセレクタ右上の動作設定ボタンから\nLIVEの背景演出を変更することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30001, /*img*/1, /*discription*/"LIVEプレイ中のSE再生設定もここから変更できます。\nSEをオフにすることで、動作が軽くなる場合があります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30002, /*img*/1, /*discription*/"ユニット確認画面では、右上のLIVE設定ボタンから\nリズムゲームプレイ中の設定をカスタマイズできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30002, /*img*/1, /*discription*/"リズムアイコンの流れてくる速度や、ボイスの音量など、\nプレイしやすいように調整してみましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/1, /*discription*/"LIVEに登場するユニットを編成することができます。\nユニットは5人編成で、5人未満ではLIVEに参加できません。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/1, /*discription*/"最大9ユニットまで編成することができます。\nメインユニットのセンターアイドルが同僚のゲストや\nプロフィール画面に設定されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/2, /*discription*/"最適化する楽曲タイプやステータスを設定し、\n簡単におすすめ編成をすることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/3, /*discription*/"お気に入りのアイドルを編成することができます。\nお気に入りのアイドルはホームとルームに登場します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/4, /*discription*/"特訓後のアイドルは、特訓前の状態にすることができます。\n切り替えを行うと、ホームやルームで登場するアイドルが\n特訓前の状態になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/1, /*discription*/"レッスンを行うことでExpを獲得することができます。\nExpが一定量に達するとLvアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/2, /*discription*/"レッスンアイドルとパートナーにするアイドルを選択します。\nパートナーは最大20人まで選択する事ができます。\nパートナーはいなくなってしまうので注意してください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/3, /*discription*/"パートナーやトレーナーは、おすすめ選択をすることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/4, /*discription*/"同じタイプのアイドル同士でレッスンを行うと\n獲得Expがアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/4, /*discription*/"特技を持っているアイドルをパートナーにすると\n特技Lv上昇確率がアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/5, /*discription*/"トレーナーとのレッスンでは\nExpを大量に獲得することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40003, /*img*/1, /*discription*/"親愛度がMAXになったアイドルは特訓をすることができます。\n特訓でアイドルを新しいステップに導きましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40003, /*img*/1, /*discription*/"特訓を行うとエピソードコミュが解放されます。\nエピソードコミュを視聴すると報酬を獲得することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40003, /*img*/2, /*discription*/"特訓を行ったアイドルは、衣装がステージ衣装に変化し、\nLv上限や一部ステータスが上昇します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40003, /*img*/3, /*discription*/"特訓には専用のアイテムを使用します。\n特訓アイテムは、LIVEやルームで獲得することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40004, /*img*/1, /*discription*/"スターレッスンを行うとスターランクが上がります。\nスターランクが上がるとLIVEでの獲得マニー量が増加したり、\nLIVEでレア報酬を獲得できる確率が上がります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40004, /*img*/1, /*discription*/"スターランクの効果は、使用中ユニットの\nセンターアイドルの効果が適用されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40004, /*img*/2, /*discription*/"スターレッスンは、同じエピソード同士のアイドルで\n行うことができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/1, /*discription*/"アイドルのポテンシャルを解放すると、\nLIVEで発揮されるアイドルの能力をアップできます !");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/1, /*discription*/"ポテンシャルは「ボーカル」「ダンス」「ビジュアル」「ライフ」\n4種類あり、解放するには、「プロデュースpt」と\n「特訓アイテム」が必要になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/1, /*discription*/"プロデュースptは、アイドルのファン数を増やすことで、\n最大 25 まで獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/2, /*discription*/"ポテンシャル解放による能力アップは、そのアイドルの\n全てのエピソードに適用され、また、アップする能力値は、\nレアリティによって異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/2, /*discription*/"お気に入りのアイドルのファンを集めて、\nポテンシャルを解放し、LIVEで大活躍させましょう !");
INSERT INTO `individual_tutorial` VALUES (/*id*/40101, /*img*/1, /*discription*/"最大9ユニットまで編成することができます。\nメインユニットのセンターアイドルが同僚のゲストや\nプロフィール画面に設定されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40101, /*img*/2, /*discription*/"最適化する楽曲タイプやステータスを設定し、\n簡単におすすめ編成をすることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40101, /*img*/3, /*discription*/"お気に入りのアイドルを編成することができます。\nお気に入りのアイドルはホームとルームに登場します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40101, /*img*/4, /*discription*/"特訓後のアイドルは、特訓前の状態にすることができます。\n切り替えを行うと、ホームやルームで登場するアイドルが\n特訓前の状態になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40201, /*img*/1, /*discription*/"新3D衣装「アクロス・ザ・スターズ」登場 !\n3DLIVEでアイドルたちの衣装を\n変更することができるようになりました !");
INSERT INTO `individual_tutorial` VALUES (/*id*/40201, /*img*/2, /*discription*/"3D衣装の変更はアイドル編成と\nMVモードのユニット確認画面で\n切り替えることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40301, /*img*/1, /*discription*/"女子寮には、アイドルを入寮させることができます。\n※入寮中のアイドルは、LIVEへの参加や、レッスン等は行えません");
INSERT INTO `individual_tutorial` VALUES (/*id*/40301, /*img*/2, /*discription*/"入寮中のアイドルは、直接他の寮へ移動することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40301, /*img*/3, /*discription*/"女子寮はショップからスタージュエルを使用して\n追加することができます。\n※女子寮機能公開後、第1女子寮は無条件で使用できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/50001, /*img*/1, /*discription*/"ストーリーコミュでは、アイドルたちが\n織り成すストーリーが描かれています。\n解放条件を達成することで解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/50001, /*img*/1, /*discription*/"ストーリー中に行われるコミュLIVEでは、\n新たなコミュは解放されません。\nLIVEで特定の難易度でのクリアが必要となります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/50002, /*img*/1, /*discription*/"メモリアルコミュでは、アイドル一人ひとりの\nアイドルとしての活動の軌跡が描かれています。\nLIVEでファン数を増やすことで解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/50003, /*img*/1, /*discription*/"エピソードコミュでは、アイドルたちが特訓を通じて\n成長していくエピソードが描かれています。\n特訓をすることで解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60001, /*img*/1, /*discription*/"手に入れたアイドルはアルバムに登録され\nアイドルのプロフィール、ステータス、\n親愛度演出やコミュを確認することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60002, /*img*/1, /*discription*/"ローディング中に表示される1コマ劇場やウワサで\nアイドルの意外な一面を知ることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60002, /*img*/1, /*discription*/"一度見た1コマ劇場とウワサは、\nアイドルトピックスで確認することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60003, /*img*/1, /*discription*/"LIVEでファンを増やしていくことで、\nプロデューサーのランクが上がります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60003, /*img*/1, /*discription*/"ランクアップ時にはトロフィーが獲得できます。\n特定ランク到達時には楽曲が獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60004, /*img*/1, /*discription*/"あなた自身のプロフィールです。\n名前と自己紹介文はいつでも変更が可能です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60005, /*img*/1, /*discription*/"他のプロデューサーと同僚になることができます。\n同僚になるとLIVEでゲスト候補に多く登場したり、\nゲスト選択した際に友情ptが多く得られます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60006, /*img*/1, /*discription*/"ミッションを1つクリアするごとに様々な報酬を\n獲得できます。\nまた、9つのミッション全てをクリアすると、\nLIVE楽曲を解放できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60007, /*img*/1, /*discription*/"ミッションをクリアすることで様々な報酬を獲得することが\nできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60007, /*img*/1, /*discription*/"デイリーは毎日0時、ウィークリーは毎週月曜の0時に\n更新されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60008, /*img*/1, /*discription*/"ミッションで称号を手に入れたら、自由に変更させることが\nできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60008, /*img*/1, /*discription*/"獲得方法を確認し、たくさんの称号を集めましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/1, /*discription*/"名刺機能は、オリジナルの名刺を作ることができる機能です。\n\n名刺編集から、好きなデザインを選んで保存することで、\nあなたのプロデューサーとしての名刺を作ることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/2, /*discription*/"名刺編集では、Sレア以上のアイドルを設定していると、\n名刺の背景をアイドルのフルサイズイラストに設定できます。\nフルサイズ表示は、アイドル全画面設定からフルサイズ表示をONに\nすることにより設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/3, /*discription*/"フルサイズ表示の場合、イラストをスワイプすることで名刺に\n表示させる位置を調整できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/4, /*discription*/"作った名刺は他のプロデューサーと交換する事ができます。\n名刺の交換は名刺ページの名刺交換画面や、他のプロデューサーの\nプロフィールページから行う事ができます。\n※自分と相手のいずれかが名刺を作成していない場合、\n交換依頼は行えません。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/5, /*discription*/"作った名刺は、あなたのTwitterに投稿する事ができます。\n名刺ページ左下のTwitterアイコンから投稿できます。\n※Twitterアイコンは名刺を作成済みの場合のみ表示されます。\n※画像の投稿には、公式のTwitterアプリが必要となります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60011, /*img*/1, /*discription*/"PランクSS以上かつPRP1000以上のプロデューサーのみ\n参加可能な「月間獲得ファン数ランキング」で1000位内に\n入賞することで、PランクSSSに昇格できます !");
INSERT INTO `individual_tutorial` VALUES (/*id*/60011, /*img*/2, /*discription*/"PランクSSまでとは異なり、PランクSSSは、1ヶ月の任期制となり、\n毎月1日の 0:00 に、PランクSSSのプロデューサーも\n全員ランクSSに戻ります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60011, /*img*/2, /*discription*/"集計後、ランキングの上位1000人が、新たにPランクSSSに\n昇格します。沢山のファンを獲得し、「アイドルマスター」を\n目指しましょう !");
INSERT INTO `individual_tutorial` VALUES (/*id*/60012, /*img*/1, /*discription*/"特訓アイテム交換では、所持している特訓アイテムを\n他の特訓アイテムに交換することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60013, /*img*/1, /*discription*/"マニーショップでは、マニーを消費して\nアイテムを購入することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60013, /*img*/1, /*discription*/"アイテムは、それぞれ購入できる上限数が決まっています。\nなお、一部のアイテムは一定期間で購入制限がリセットされます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/1, /*discription*/"「イベントptランキング報酬」、「達成pt報酬」、\n「ハイスコアランキング報酬」で、イベント限定の\nSレアアイドルやルームアイテムを手にいれましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/2, /*discription*/"イベントptランキングで50万位に入賞すると、\n自分の順位が入ったイベント称号を獲得できます。\n各称号のデザインは順位によって異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/3, /*discription*/"通常楽曲をプレイすると、パタパタイコとイベントptを獲得\nできます。パタパタイコは、スタミナ消費量と\nSCOREランクが高いほど多く獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/4, /*discription*/"イベント楽曲は、スタミナではなくパタパタイコを消費して\nプレイします。通常楽曲よりも多くイベントptを獲得できます。\nイベント楽曲は、イベント期間中のみプレイできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/5, /*discription*/"通常楽曲でパタパタイコを集め、\nイベント楽曲で大量にptを獲得しましょう。\nランキング入賞を目指して頑張りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80002, /*img*/1, /*discription*/"パタパタイコ消費数を2倍、または4倍に\n設定することができます。\n消費数に応じて、イベントptを多く獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/1, /*discription*/"「イベントptランキング報酬」、「達成pt報酬」、\n「ハイスコアランキング報酬」で、イベント限定の\nSレアアイドルやルームアイテムを手にいれましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/2, /*discription*/"イベントptランキングで50万位に入賞すると、\n自分の順位が入ったイベント称号を獲得できます。\n各称号のデザインは順位によって異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/3, /*discription*/"通常楽曲をプレイすると、パタパタイコとイベントptを獲得\nできます。パタパタイコは、スタミナ消費量と\nSCOREランクが高いほど多く獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/4, /*discription*/"イベント楽曲は、スタミナではなくパタパタイコを消費して\nプレイします。通常楽曲よりも多くイベントptを獲得できます。\nイベント楽曲は、イベント期間中のみプレイできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/5, /*discription*/"通常楽曲でパタパタイコを集め、\nイベント楽曲で大量にptを獲得しましょう。\nランキング入賞を目指して頑張りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/6, /*discription*/"パタパタイコ消費数を2倍、または4倍に\n設定することができます。\n消費数に応じて、イベントptを多く獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/1, /*discription*/"イベント期間中にLIVEをプレイすると、\n限定のアイドルを確率で手に入れることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/2, /*discription*/"日によって限定アイドルの出現率がアップする楽曲が\n決まっています。キュート、クール、パッション、全タイプ楽曲の\nいずれかのタイプの全ての楽曲が対象になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/2, /*discription*/"また、全楽曲出現率アップ日には、すべての楽曲が\n出現率アップの対象になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/3, /*discription*/"イベント期間中は、センターアイドルのスターランクが\n高ければ高いほど、LIVE報酬を獲得しやすくなります。\n※ユニットに参加していても、センターアイドル以外の\nアイドルのスターランクの効果は発揮されません。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/4, /*discription*/"イベント追加報酬から、アイテム「キャラバンメダル」が\n登場します。「キャラバンメダル」を集めると、\n限定アイドルのスカウトや、アイテムとの交換ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/1, /*discription*/"「達成pt報酬」、「イベントptランキング報酬」、\n「ハイスコアランキング報酬」で、イベント限定の\nSレアアイドルやルームアイテムが貰えるだけでなく、\nイベント限定楽曲をイベント終了後もプレイできるようになります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/2, /*discription*/"イベントptランキングで50万位に入賞すると、\n自分の順位が入ったイベント称号を獲得できます。\n各称号のデザインは順位によって異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/3, /*discription*/"難易度を選択すると、「Cute Groove」「Cool Groove」\n「Passion Groove」のいずれかが選択され、\n一致するタイプの楽曲がランダムでセットされます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/3, /*discription*/"LIVE Grooveでは、その3曲で連続してLIVEを行います。\n※3曲の間ライフは引き継がれます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/4, /*discription*/"LIVE中、盛り上がりに応じて「ハコユレLv」が計測されます。\n3曲合わせた「ハコユレLv」が17以上になると、\nアンコールが発生します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/5, /*discription*/"難易度がMASTERで、ハコユレLvが21以上の場合、\nアンコール楽曲の難易度で「MASTER+」が選択できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/6, /*discription*/"LIVE Groove Dance burstでは、ダンスのアピール値が\n通常よりアップします。\nダンスアピールが高いアイドルを編成して、\nイベント上位を目指しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/1, /*discription*/"「達成pt報酬」で、イベント限定のSレアアイドルや\nルームアイテムを手にいれましょう。\nまた期間中にイベントのLIVEをプレイすると、\n限定のアイドルを確率で手に入れることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/2, /*discription*/"同じ難易度を選んだプロデューサー5人でマッチングが行われ、\nマッチングされたメンバーと協力してLIVEを行います。\n楽曲はランダムで選曲され、\nメンバー全員が同時にその楽曲でLIVEを行います。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/3, /*discription*/"本イベントは、専用ユニットでLIVEを行います。ユニットには5つの「ポジション」があります。\n各プロデューサーのアイドルが、ポジションを1つずつ担当し、5人の共通ユニットが編成されます。\n※自分のアイドルがどのポジションを担当するかはランダムで決定されます。\n※楽曲タイプとポジションごとにアイドルを設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/4, /*discription*/"各メンバーの状況はLIVE画面の左側のエリアで確認できます。\nまた本イベントでは、ライフが0になった場合も、LIVEは継続となります。\n\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/4, /*discription*/"獲得できるptは「メンバー全員の合計スコア」と「LIVEでの貢献度」\nによって変化します。メンバー全員で高スコアを目指しましょう !\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/4, /*discription*/"貢献度は自身が獲得したスコアのほか、LIVEに出演したアイドルの\n「アピール値の高さ」、「特技」をもとに算出します。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/5, /*discription*/"本イベントのLIVE報酬では、「協力報酬」と「個人報酬」が獲得できます。\n協力報酬は、メンバー全員のスコアの合計が高いほど、\n良い報酬が出現しやすくなります。\n獲得できる協力報酬は全メンバー共通で、必ず全員が獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/5, /*discription*/"個人報酬は、自分の貢献度が高いほど、良い報酬が出現しやすくなります。\n※個人報酬は、一定の確率で1～2個出現します。\n\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/6, /*discription*/"LIVEの開始前と終了後には、マッチングされたメンバーと\nチャットスタンプでコミュニケーションがとれます。\n使用するスタンプはイベントページ内の「チャット設定」で\n設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80401, /*img*/1, /*discription*/"イベント編成では、イベントのLIVEを行うアイドルの設定をします。\n楽曲のタイプごとに1つずつ、合計4つの設定が行えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80501, /*img*/1, /*discription*/"チャット設定では、LIVE開始前と終了後に使用する\nスタンプの設定が行えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80501, /*img*/1, /*discription*/"まず「セット中スタンプ」の中から、変更したいスタンプを選択し、\n次にスタンプの一覧から、設定したいスタンプを選択しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80501, /*img*/2, /*discription*/"スタンプの設定が済んだら、最後に「保存」ボタンを押しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80501, /*img*/2, /*discription*/"スタンプの設定を初期状態に戻したい場合は、\n「初期設定」ボタンを押しましょう。\nイベント開始時のおすすめのスタンプ設定が適用されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/1, /*discription*/"「達成pt報酬」、「観客動員数報酬」、\n「ハイスコアランキング報酬」で、イベント限定の\nSレアアイドルやルームアイテムが貰えるだけでなく、\nイベント限定楽曲をイベント終了後もプレイできるようになります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/2, /*discription*/"全国各地で公演を行い、LIVEツアーを盛り上げましょう。\n公演目標を達成してLIVEをクリアすると、\n新しい公演が解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/3, /*discription*/"公演の目標が達成できるように、楽曲やユニットを選びましょう。\n公演によって消費スタミナやLIVEを行う曲数が異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/4, /*discription*/"公演を行うと、観客動員数が増加します。\n対象のエリアの観客動員数が一定値に到達すると、\n新しいエリアが解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/4, /*discription*/"エリア3、4に到達すると、イベント楽曲のMASTER+の\n難易度が選曲可能となります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/5, /*discription*/"日替わりで切り替わる「流行曲」を含めて公演を行ったり、\nマニーを使用して「LIVEオプション」を設定すると、\nエリアの観客動員数がさらにアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/5, /*discription*/"また観客動員数の多いエリアで公演を行うと、\n獲得できるファン数がアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/6, /*discription*/"イベント設定では、公演の準備画面の「おすすめ設定」で\n選曲される楽曲のLvを調整できます。\nまたツアーのタイトルを自由に変更できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90101, /*img*/1, /*discription*/"アイドルのファン数を増やすことで、ポテンシャルを解放し、\nアイドルのステータスを強化することができる機能です。\n（ポテンシャル解放では特訓アイテムを消費します）\n※各数値は開発中のものです。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90102, /*img*/1, /*discription*/"PランクSS、PRP1000以上のプロデューサーのみ参加可能な\nランキングで、上位入賞することで、PランクSSSに昇格します。\n（PランクSSSは、1ヶ月の任期制となります）\n    ");
INSERT INTO `individual_tutorial` VALUES (/*id*/90103, /*img*/1, /*discription*/"新3D衣装「アクロス・ザ・スターズ」登場 !\n3DLIVEでアイドルたちの衣装を\n変更することができるようになりました !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90103, /*img*/2, /*discription*/"3D衣装の変更はアイドル編成と\nMVモードのユニット確認画面で\n切り替えることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/3, /*discription*/"ルームでアイドルからスタミナ回復アイテム\n「手作りショートケーキ」を受け取ろう !\n詳細はお知らせをご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/4, /*discription*/"キャンペーン開催期間中の初回ログイン時に\n「スタージュエル 2500個」をプレゼント");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/4, /*discription*/"さらに毎日「スタージュエル 50個」を\nプレゼントする「1周年記念ログイン\nボーナスキャンペーン」");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/1, /*discription*/"ローカルオーディションガシャからレッスンに\n効果的なアイテムが出やすい「育成強化キャンペーン」");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/1, /*discription*/"レッスン大成功確率が通常の3倍になる\n「レッスン大成功確率アップキャンペーン」");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/2, /*discription*/"LIVEコンティニューに必要なスタージュエルが\n「50個」から「10個」になる「LIVEチャレンジ\nキャンペーン」");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/2, /*discription*/"LIVE成功時にティアラと魔法のドレスの\nドロップ率がアップする「特訓支援キャンペーン」\n期間などの詳細はお知らせよりご確認ください。");
