CREATE TABLE 'individual_tutorial' ('id' INTEGER NOT NULL, 'img' INTEGER NOT NULL, 'discription' TEXT NOT NULL)
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/1, /*discription*/"ガシャを引くことでアイドルが新しく加入します。\nガシャには「プラチナオーディションガシャ」と\n「ローカルオーディションガシャ」の2種類があります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/1, /*discription*/"プラチナオーディションガシャはスタージュエルを消費して、\nレア以上の強力なアイドルを獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/2, /*discription*/"ガシャでSSレアアイドルを獲得すると、\nルームで使用できるアイドルのポスターが\nプレゼントに送られます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/2, /*discription*/"さらに、SSレアアイドルは特別な衣装で\n3DLIVEのパフォーマンスを行います。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10001, /*img*/3, /*discription*/"特定のSレア以上のアイドルをユニット編成で\nセンターに設定することで、LIVEの「お願い ! シンデレラ」を\nソロ歌唱で楽しめます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10003, /*img*/1, /*discription*/"ローカルオーディションガシャは友情ptを消費して、\nアイドルやトレーニングチケットを獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10004, /*img*/1, /*discription*/"プラチナオーディションガシャを引くと、\n『スターシャイン』が獲得できます。\n※『スターシャイン』は提供期間が決まっています。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10004, /*img*/2, /*discription*/"期間中に『スターシャイン』を必要数獲得すると、\n対象のアイドルを1人スカウトすることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10004, /*img*/3, /*discription*/"提供期間を過ぎた『スターシャイン』は、\n『スターピース』に自動で変換されます。\n『スターピース』は、アイテムと交換することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/10005, /*img*/1, /*discription*/"「イベント限定アイドルスカウトチケット」は過去に開催\nされた期間限定イベントに登場したアイドルから、好きな\nアイドルをスカウトできるチケットです。スカウトできる\nアイドルは、「対象アイドル」ボタンからご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11001, /*img*/1, /*discription*/"スペシャルガシャセットは期間限定販売です。\n購入すると「スカウトチケット」と「プラチナ10連ガシャ\nチケット」を1枚ずつ獲得できます。\n※有償スタージュエルでのみ購入することができます");
INSERT INTO `individual_tutorial` VALUES (/*id*/11001, /*img*/2, /*discription*/"「スカウトチケット」はレア、Sレア、SSレアのアイドル\nをスカウトできるチケットです。\nスカウトできるアイドルは、「対象アイドル」ボタンから\nご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11001, /*img*/3, /*discription*/"「プラチナ10連ガシャチケット」は、チケット使用時に\n開催中のプラチナ10連ガシャを引けるチケットです。\nプラチナガシャと同様に、Sレア以上のアイドル1人が\n確定で出現します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11002, /*img*/1, /*discription*/"スペシャルガシャセットは期間限定販売です。\n購入すると「スカウトチケット」と「プラチナ10連ガシャ\nチケット」を1枚ずつ獲得できます。\n※有償スタージュエルでのみ購入することができます");
INSERT INTO `individual_tutorial` VALUES (/*id*/11002, /*img*/2, /*discription*/"「スカウトチケット」はレア、Sレア、SSレアのアイドル\nをスカウトできるチケットです。\nスカウトできるアイドルは、「対象アイドル」ボタンから\nご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11002, /*img*/3, /*discription*/"「プラチナ10連ガシャチケット」は、チケット使用時に\n開催中のプラチナ10連ガシャを引けるチケットです。\nプラチナガシャと同様に、Sレア以上のアイドル1人が\n確定で出現します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11003, /*img*/1, /*discription*/"スペシャルガシャセットは期間限定販売です。\n購入すると「スカウトチケット」と「プラチナ10連ガシャ\nチケット」を1枚ずつ獲得できます。\n※有償スタージュエルでのみ購入することができます");
INSERT INTO `individual_tutorial` VALUES (/*id*/11003, /*img*/2, /*discription*/"「スカウトチケット」はレア、Sレア、SSレアのアイドル\nをスカウトできるチケットです。\nスカウトできるアイドルは、「対象アイドル」ボタンから\nご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11003, /*img*/3, /*discription*/"「プラチナ10連ガシャチケット」は、チケット使用時に\n開催中のプラチナ10連ガシャを引けるチケットです。\nプラチナガシャと同様に、Sレア以上のアイドル1人が\n確定で出現します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11006, /*img*/1, /*discription*/"スペシャルガシャセットは期間限定販売です。\n購入すると「スカウトチケット」と「プラチナ10連ガシャ\nチケット」を1枚ずつ獲得できます。\n※有償スタージュエルでのみ購入することができます");
INSERT INTO `individual_tutorial` VALUES (/*id*/11006, /*img*/2, /*discription*/"「スカウトチケット」はレア、Sレア、SSレアのアイドル\nをスカウトできるチケットです。\nスカウトできるアイドルは、「対象アイドル」ボタンから\nご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11006, /*img*/3, /*discription*/"「プラチナ10連ガシャチケット」は、チケット使用時に\n開催中のプラチナ10連ガシャを引けるチケットです。\nプラチナガシャと同様に、Sレア以上のアイドル1人が\n確定で出現します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11007, /*img*/1, /*discription*/"スペシャルガシャセットは期間限定販売です。\n購入すると2種類の「スカウトチケット」と「プラチナ\n10連ガシャチケット」を1枚ずつ獲得できます。\n※有償スタージュエルでのみ購入することができます");
INSERT INTO `individual_tutorial` VALUES (/*id*/11007, /*img*/2, /*discription*/"「スカウトチケット」はアイドルをスカウトできるチケット\nです。スカウトできるアイドルは、「対象アイドル」ボタン\nからご確認ください。※スカウトチケットの種類によって\nスカウトできるアイドルは異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11007, /*img*/3, /*discription*/"「プラチナ10連ガシャチケット」は、チケット使用時に\n開催中のプラチナ10連ガシャを引けるチケットです。\nプラチナガシャと同様に、Sレア以上のアイドル1人が\n確定で出現します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11010, /*img*/1, /*discription*/"スペシャルガシャセットは期間限定販売です。\n購入すると2種類の「スカウトチケット」と「プラチナ\n10連ガシャチケット」を1枚ずつ獲得できます。\n※有償スタージュエルでのみ購入することができます");
INSERT INTO `individual_tutorial` VALUES (/*id*/11010, /*img*/2, /*discription*/"「スカウトチケット」はアイドルをスカウトできるチケット\nです。スカウトできるアイドルは、「対象アイドル」ボタン\nからご確認ください。※スカウトチケットの種類によって\nスカウトできるアイドルは異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/11010, /*img*/3, /*discription*/"「プラチナ10連ガシャチケット」は、チケット使用時に\n開催中のプラチナ10連ガシャを引けるチケットです。\nプラチナガシャと同様に、Sレア以上のアイドル1人が\n確定で出現します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20001, /*img*/1, /*discription*/"ルームはお気に入りメンバーが集う場所です。\nいろいろなルームアイテムを配置して、\nあなた好みの空間を作りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20001, /*img*/2, /*discription*/"ルームアイテムの中には設置する事で、\n様々な効果を発揮する物があります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20001, /*img*/2, /*discription*/"さらに、一部の効果付きルームアイテムは、\nマニーを使ってレベルアップできます。\n効果付きルームアイテムでLIVEを有利にしましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20001, /*img*/3, /*discription*/"ルームアイテムの中には、設置していると一定時間ごとに\nアイテムが届くものがあります。\n時々ルームを覗いて、届いたアイテムを受け取りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20002, /*img*/1, /*discription*/"ショップでは、マニーを使ってルームアイテムを購入できます。\nカテゴリタブを切り替えて欲しいルームアイテムを探したら、\n「購入」ボタンを押しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20002, /*img*/2, /*discription*/"ルームアイテムをタップで移動して、置く場所を決めたら\n「設置」で購入が完了します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20002, /*img*/2, /*discription*/"あとで設置したい場合は「収納」を押せば倉庫に収納されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20003, /*img*/1, /*discription*/"倉庫には収納されたルームアイテムが保管されています。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20003, /*img*/2, /*discription*/"「設置」ボタンを押せば、倉庫内のルームアイテムを\nルームに設置できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20003, /*img*/3, /*discription*/"いらなくなったルームアイテムは「売却」ボタンで、\n売却してマニーに変える事ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20004, /*img*/1, /*discription*/"Like情報ではLikeの履歴を確認できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20004, /*img*/1, /*discription*/"「ルーム訪問」から、いろいろな人のルームに\n遊びに行ってみましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20005, /*img*/1, /*discription*/"「ルーム効果」では、現在発動しているルーム効果を\n確認できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20005, /*img*/1, /*discription*/"「詳細」タブでは、効果を発揮しているルームアイテムを\n見る事ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20006, /*img*/1, /*discription*/"VIEWモードでは、ルームが拡大して表示され、\nガイド線より手前のルームアイテムが見えなくなります。\n重なったルームアイテムを操作する場合などに便利です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20007, /*img*/1, /*discription*/"ギフトアイテムをアイドルに渡すと親愛度が上がります。\nそのアイドルに合ったギフトアイテムを渡すと、\nより多くの親愛度が上がります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20008, /*img*/1, /*discription*/"VIEWモードでは、表示領域とミニウィンドウが表示され、\n表示領域の外側のルームアイテムが見えなくなります。\n重なったルームアイテムを操作する場合などに便利です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20008, /*img*/2, /*discription*/"表示領域はミニウィンドウ上で移動することができます。\nミニウィンドウでルーム全体を見渡しながら\n編集したい箇所に表示領域を合わせることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20008, /*img*/3, /*discription*/"ミニウィンドウは左側に収納したり、\n上側に移動したりすることができます。\n編集箇所に応じてミニウィンドウを移動させましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20008, /*img*/4, /*discription*/"「－」、「＋」ボタンで表示領域のサイズを\n変更することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20009, /*img*/1, /*discription*/"ルーム画面のレイアウトを変更しました。\nショップや倉庫へは右側の矢印ボタンを\nタップすると表示されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20009, /*img*/2, /*discription*/"ルームに名前を付けられるようになりました。\nルーム名はいつでも自由に変更できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20009, /*img*/3, /*discription*/"「一括受取」ボタンで宅配ボックスや\nチケットボードに届いているアイテムを\nまとめて受け取ることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20010, /*img*/1, /*discription*/"より自由にルームアイテムの設置が行える\nフリールームが追加されました。\n「ルーム移動」ボタンをタップすると\nフリールームへ移動できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20010, /*img*/2, /*discription*/"ルーム名変更ボタンから\nメインに設定するルームを設定することができます。\n自分や同僚がルームに入った際に、\nメイン設定を行っているルームが最初に表示されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20010, /*img*/3, /*discription*/"別のルームに設置中のアイテムは、\nルームアイテム一覧から直接移動できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20010, /*img*/4, /*discription*/"「お気に入り編成」から、事務所とフリールームに\n登場するアイドルを個別に設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20011, /*img*/1, /*discription*/"「一括収納」ボタンで設置中のルームアイテムを\nまとめて倉庫に収納することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20012, /*img*/1, /*discription*/"ルームのレイアウトをマイセットに保存することができます。\n保存したマイセットはいつでも配置することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20013, /*img*/1, /*discription*/"レイアウト済みのルームアイテムがセットになった\n「コーデ」をルームショップにて販売開始 !\n購入した「コーデ」はそのまま配置することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20013, /*img*/1, /*discription*/"既に所持しているルームアイテムがコーデに含まれる場合、\nそのルームアイテムは購入されず、コーデの販売価格から\n差し引かれます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20013, /*img*/2, /*discription*/"購入したコーデはレイアウトの「テーマ」に保存され、\nいつでも自由に配置することができます !");
INSERT INTO `individual_tutorial` VALUES (/*id*/20099, /*img*/1, /*discription*/"ルームでアイドルからスタミナ回復アイテム\n「手作りチョコレート～2018～」を受け取ろう !\n詳細はお知らせをご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20101, /*img*/1, /*discription*/"ルームはお気に入りメンバーが集う場所です。\nいろいろなルームアイテムを配置して、\nあなた好みの空間を作りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20101, /*img*/2, /*discription*/"ルームアイテムの中には設置する事で、\n様々な効果を発揮する物があります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20101, /*img*/2, /*discription*/"さらに、一部の効果付きルームアイテムは、\nマニーを使ってレベルアップできます。\n効果付きルームアイテムでLIVEを有利にしましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20101, /*img*/3, /*discription*/"ルームアイテムの中には、設置していると一定時間ごとに\nアイテムが届くものがあります。\n時々ルームを覗いて、届いたアイテムを受け取りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20102, /*img*/1, /*discription*/"ショップでは、マニーを使ってルームアイテムを購入できます。\nカテゴリタブを切り替えて欲しいルームアイテムを探したら、\n「購入」ボタンを押しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20102, /*img*/2, /*discription*/"ルームアイテムをタップで移動して、置く場所を決めたら\n「設置」で購入が完了します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20102, /*img*/2, /*discription*/"あとで設置したい場合は「収納」を押せば倉庫に収納されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20103, /*img*/1, /*discription*/"倉庫には収納されたルームアイテムが保管されています。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20103, /*img*/2, /*discription*/"「設置」ボタンを押せば、倉庫内のルームアイテムを\nルームに設置できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20103, /*img*/3, /*discription*/"いらなくなったルームアイテムは「売却」ボタンで、\n売却してマニーに変える事ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20104, /*img*/1, /*discription*/"Like情報ではLikeの履歴を確認できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/20104, /*img*/1, /*discription*/"「ルーム訪問」から、いろいろな人のルームに\n遊びに行ってみましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30001, /*img*/1, /*discription*/"LIVEでは、ミュージックセレクタ右上の動作設定ボタンから\nLIVEの背景演出を変更することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30001, /*img*/1, /*discription*/"LIVEプレイ中のSE再生設定もここから変更できます。\nSEをオフにすることで、動作が軽くなる場合があります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30002, /*img*/1, /*discription*/"ユニット確認画面では、右上のLIVE設定ボタンから\nリズムゲームプレイ中の設定をカスタマイズできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30002, /*img*/1, /*discription*/"リズムアイコンの流れてくる速度や、ボイスの音量など、\nプレイしやすいように調整してみましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30003, /*img*/1, /*discription*/"LIVEの新たな難易度「MASTER+」を追加しました。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30003, /*img*/1, /*discription*/"難易度「MASTER+」は、楽曲選択画面でカテゴリタブを\n「MASTER+」に変更することでプレイできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30003, /*img*/2, /*discription*/"「MASTER+」がプレイできる楽曲は、一定期間ごとに変化します。\n対象となる楽曲や期間は「詳細」ボタンから確認できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30003, /*img*/3, /*discription*/"「MASTER+」をプレイするには、専用の「MASTER+チケット」が必要です。\n「MASTER+チケット」はミッション達成やマニーショップなどで\n獲得することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30003, /*img*/4, /*discription*/"難易度「MASTER+」には、新たなリズムアイコン\n「スライド」が出現することがあります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30003, /*img*/4, /*discription*/"リズムアイコンがラインに重なっている間、\nタップしつづけながら、帯の流れに合わせて\n指を左右にスライドしましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30004, /*img*/1, /*discription*/"新機能「ぴにゃリクエスト」を追加しました。\nDJぴにゃが選んだ楽曲をプレイする機能です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30004, /*img*/1, /*discription*/"楽曲選択画面の「ぴにゃリクエスト」にカーソルをあわせ、\n難易度を選択してから「決定」ボタンをタップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30004, /*img*/2, /*discription*/"表示されるポップアップで、遊びたい楽曲のタイプを選択し\n「条件決定」をタップすると、DJぴにゃがプレイ楽曲を決定します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30004, /*img*/2, /*discription*/"スタミナは条件決定をしたタイミングで消費されます。\n楽曲決定後に選曲画面に戻ることはできませんのでご注意ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30004, /*img*/3, /*discription*/"リクエストされた楽曲を見事クリアすると、\n通常のLIVE報酬に追加で、特別な報酬が獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30005, /*img*/1, /*discription*/"LIVEに新モード「SMART LIVE」を追加しました。\n対応楽曲で、端末を縦に持って片手でプレイできる、新しいスタイルの\nリズムゲームです。まずは練習してみましょう ! ");
INSERT INTO `individual_tutorial` VALUES (/*id*/30006, /*img*/1, /*discription*/"「MVプレイリスト機能」を追加しました。\n実際に開催されたLIVEのセットリストに沿って、\n楽曲のMVを続けて鑑賞することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30006, /*img*/1, /*discription*/"「リピート」はプレイリストの最後のMVが終了した時、\nプレイリストの最初からもう一度再生します。\n「シャッフル」はプレイリストの楽曲順を\nランダムに並び替える機能です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30006, /*img*/2, /*discription*/"「リスト選択」ボタンをタップすると\n公演名が記載されたプレイリストの一覧が表示されます。\n一覧からプレイリストを選択し、公演を振り返りましょう！");
INSERT INTO `individual_tutorial` VALUES (/*id*/30006, /*img*/3, /*discription*/"MV再生中に画面をタップするとポーズメニューが表示されます。\nポーズメニューでは「リスト」タブと「メニュー」タブを\n切り替えることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30006, /*img*/3, /*discription*/"「リスト」タブではプレイリストの楽曲を選択して再生できます。\n「メニュー」タブでは楽曲情報を確認できる他、\n「リピート」や「シャッフル」のON/OFFを設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/30099, /*img*/1, /*discription*/"「バレンタインスペシャルLIVEキャンペーン」\n開催中 ! 期間中にLIVEをクリアすると、\n期間限定のアイテムを獲得できます !");
INSERT INTO `individual_tutorial` VALUES (/*id*/30099, /*img*/2, /*discription*/"「特訓支援キャンペーン」開催中 ! !\nLIVE成功時にティアラと魔法のドレスのドロップ率が\nアップします ! 詳細はお知らせよりご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/1, /*discription*/"LIVEに登場するユニットを編成することができます。\nユニットは5人編成で、5人未満ではLIVEに参加できません。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/1, /*discription*/"最大9ユニットまで編成することができます。\nメインユニットのセンターアイドルが同僚のゲストや\nプロフィール画面に設定されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/2, /*discription*/"最適化する楽曲タイプやステータスを設定し、\n簡単におすすめ編成をすることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/3, /*discription*/"お気に入りのアイドルを編成することができます。\nお気に入りのアイドルはホームとルームに登場します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40001, /*img*/4, /*discription*/"特訓後のアイドルは、特訓前の状態にすることができます。\n切り替えを行うと、ホームやルームで登場するアイドルが\n特訓前の状態になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/1, /*discription*/"レッスンを行うことでExpを獲得することができます。\nExpが一定量に達するとLvアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/2, /*discription*/"レッスンアイドルとパートナーにするアイドルを選択します。\nパートナーは最大20人まで選択する事ができます。\nパートナーはいなくなってしまうので注意してください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/3, /*discription*/"パートナーやトレーナーは、おすすめ選択をすることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/4, /*discription*/"同じタイプのアイドル同士でレッスンを行うと\n獲得Expがアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/4, /*discription*/"特技を持っているアイドルをパートナーにすると\n特技Lv上昇確率がアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40002, /*img*/5, /*discription*/"トレーナーとのレッスンでは\nExpを大量に獲得することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40003, /*img*/1, /*discription*/"親愛度がMAXになったアイドルは特訓をすることができます。\n特訓でアイドルを新しいステップに導きましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40003, /*img*/1, /*discription*/"特訓を行うとエピソードコミュが解放されます。\nエピソードコミュを視聴すると報酬を獲得することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40003, /*img*/2, /*discription*/"特訓を行ったアイドルは、衣装がステージ衣装に変化し、\nLv上限や一部ステータスが上昇します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40003, /*img*/3, /*discription*/"特訓には専用のアイテムを使用します。\n特訓アイテムは、LIVEやルームで獲得することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40004, /*img*/1, /*discription*/"スターレッスンを行うとスターランクが上がります。\nスターランクが上がるとLIVEでの獲得マニー量が増加したり、\nLIVEでレア報酬を獲得できる確率が上がります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40004, /*img*/1, /*discription*/"スターランクの効果は、使用中ユニットの\nセンターアイドルの効果が適用されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40004, /*img*/2, /*discription*/"スターレッスンは、同じエピソード同士のアイドルで\n行うことができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/1, /*discription*/"アイドルのポテンシャルを解放すると、\nLIVEで発揮されるアイドルの能力をアップできます !");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/1, /*discription*/"ポテンシャルは「ボーカル」「ダンス」「ビジュアル」「ライフ」\n4種類あり、解放するには、「プロデュースpt」と\n「特訓アイテム」が必要になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/1, /*discription*/"プロデュースptは、アイドルのファン数を増やすことで、\n最大 25 まで獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/2, /*discription*/"ポテンシャル解放による能力アップは、そのアイドルの\n全てのエピソードに適用され、また、アップする能力値は、\nレアリティによって異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40005, /*img*/2, /*discription*/"お気に入りのアイドルのファンを集めて、\nポテンシャルを解放し、LIVEで大活躍させましょう !");
INSERT INTO `individual_tutorial` VALUES (/*id*/40006, /*img*/1, /*discription*/"レッスンパートナーにアイドルとトレーナーを\n同時に選択してレッスンすることもできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40101, /*img*/1, /*discription*/"最大9ユニットまで編成することができます。\nメインユニットのセンターアイドルが同僚のゲストや\nプロフィール画面に設定されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40101, /*img*/2, /*discription*/"最適化する楽曲タイプやステータスを設定し、\n簡単におすすめ編成をすることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40101, /*img*/3, /*discription*/"お気に入りのアイドルを編成することができます。\nお気に入りのアイドルはホームとルームに登場します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40101, /*img*/4, /*discription*/"特訓後のアイドルは、特訓前の状態にすることができます。\n切り替えを行うと、ホームやルームで登場するアイドルが\n特訓前の状態になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40201, /*img*/1, /*discription*/"新3D衣装「アクロス・ザ・スターズ」登場 !\n3DLIVEでアイドルたちの衣装を\n変更することができるようになりました !");
INSERT INTO `individual_tutorial` VALUES (/*id*/40201, /*img*/2, /*discription*/"3D衣装の変更はアイドル編成と\nMVモードのユニット確認画面で\n切り替えることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40202, /*img*/1, /*discription*/"「MVオリジナルユニット」機能を追加しました。\n各楽曲を歌唱しているアイドルのユニットを\n簡単に設定できる機能です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40202, /*img*/1, /*discription*/"機能に対応した楽曲では、MVのユニット確認画面の上部に\n「MVオリジナル」タブが表示されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40202, /*img*/1, /*discription*/"「MVオリジナル」タブに切り替えると、楽曲に合わせた\nアイドルと衣装が自動で編成されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40202, /*img*/1, /*discription*/"アイドルをタップして自由に編成しなおすこともできます。\n「MVオリジナル」の編成状態は、各楽曲ごとに保存されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40301, /*img*/1, /*discription*/"女子寮には、アイドルを入寮させることができます。\n※入寮中のアイドルは、LIVEへの参加や、レッスン等は行えません");
INSERT INTO `individual_tutorial` VALUES (/*id*/40301, /*img*/2, /*discription*/"入寮中のアイドルは、直接他の寮へ移動することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40301, /*img*/3, /*discription*/"女子寮はショップからスタージュエルを使用して\n追加することができます。\n※女子寮機能公開後、第1女子寮は無条件で使用できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40401, /*img*/1, /*discription*/"ユニットの編成可能数が「18」になりました。\n「切り替えボタン」を押すと表示するユニットの切り替えができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/40401, /*img*/2, /*discription*/"LIVEでは、左下の「ユニットボタン」を押すことで\n表示するユニットの切り替えができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/50001, /*img*/1, /*discription*/"ストーリーコミュでは、アイドルたちが\n織り成すストーリーが描かれています。\n解放条件を達成することで解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/50001, /*img*/1, /*discription*/"ストーリー中に行われるコミュLIVEでは、\n新たなコミュは解放されません。\nLIVEで特定の難易度でのクリアが必要となります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/50002, /*img*/1, /*discription*/"メモリアルコミュでは、アイドル一人ひとりの\nアイドルとしての活動の軌跡が描かれています。\nLIVEでファン数を増やすことで解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/50003, /*img*/1, /*discription*/"エピソードコミュでは、アイドルたちが特訓を通じて\n成長していくエピソードが描かれています。\n特訓をすることで解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60001, /*img*/1, /*discription*/"手に入れたアイドルはアルバムに登録され\nアイドルのプロフィール、ステータス、\n親愛度演出やコミュを確認することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60002, /*img*/1, /*discription*/"ローディング中に表示される1コマ劇場やウワサで\nアイドルの意外な一面を知ることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60002, /*img*/1, /*discription*/"一度見た1コマ劇場とウワサは、\nアイドルトピックスで確認することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60003, /*img*/1, /*discription*/"LIVEでファンを増やしていくことで、\nプロデューサーのランクが上がります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60003, /*img*/1, /*discription*/"ランクアップ時にはトロフィーが獲得できます。\n特定ランク到達時には楽曲が獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60004, /*img*/1, /*discription*/"あなた自身のプロフィールです。\n名前と自己紹介文はいつでも変更が可能です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60005, /*img*/1, /*discription*/"他のプロデューサーと同僚になることができます。\n同僚になるとLIVEでゲスト候補に多く登場したり、\nゲスト選択した際に友情ptが多く得られます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60006, /*img*/1, /*discription*/"ミッションを1つクリアするごとに様々な報酬を\n獲得できます。\nまた、9つのミッション全てをクリアすると、\nLIVE楽曲を解放できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60007, /*img*/1, /*discription*/"ミッションをクリアすることで様々な報酬を獲得することが\nできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60007, /*img*/1, /*discription*/"デイリーは毎日0時、ウィークリーは毎週月曜の0時に\n更新されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60008, /*img*/1, /*discription*/"ミッションで称号を手に入れたら、自由に変更させることが\nできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60008, /*img*/1, /*discription*/"獲得方法を確認し、たくさんの称号を集めましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/1, /*discription*/"名刺機能は、オリジナルの名刺を作ることができる機能です。\n\n名刺編集から、好きなデザインを選んで保存することで、\nあなたのプロデューサーとしての名刺を作ることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/2, /*discription*/"名刺編集では、設定しているアイドルをフルサイズで\n表示することができます。フルサイズ表示は、\n表示アイドル設定からONにすることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/3, /*discription*/"フルサイズ表示の場合、イラストをスワイプすることで名刺に\n表示させる位置を調整できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/4, /*discription*/"作った名刺は他のプロデューサーと交換する事ができます。\n名刺の交換は名刺ページの名刺交換画面や、他のプロデューサーの\nプロフィールページから行う事ができます。\n※自分と相手のいずれかが名刺を作成していない場合、\n交換依頼は行えません。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60009, /*img*/5, /*discription*/"作った名刺は、あなたのTwitterに投稿する事ができます。\n名刺ページ左下のTwitterアイコンから投稿できます。\n※Twitterアイコンは名刺を作成済みの場合のみ表示されます。\n※画像の投稿には、公式のTwitterアプリが必要となります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60010, /*img*/1, /*discription*/"簡単に名刺交換できる機能を追加しました。\n名刺交換依頼の自動設定は、名刺設定画面から、\n名刺一括交換は、同僚リスト画面から行えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60011, /*img*/1, /*discription*/"PランクSS以上かつPRP1000以上のプロデューサーのみ\n参加可能な「月間獲得ファン数ランキング」で2000位内に\n入賞することで、PランクSSSに昇格できます !");
INSERT INTO `individual_tutorial` VALUES (/*id*/60011, /*img*/2, /*discription*/"PランクSSまでとは異なり、PランクSSSは、1ヶ月の任期制となり、\n毎月1日の 0:00 に、PランクSSSのプロデューサーも\n全員ランクSSに戻ります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60011, /*img*/2, /*discription*/"集計後、ランキングの上位2000人が、新たにPランクSSSに\n昇格します。沢山のファンを獲得し、「アイドルマスター」を\n目指しましょう !");
INSERT INTO `individual_tutorial` VALUES (/*id*/60012, /*img*/1, /*discription*/"特訓アイテム交換では、所持している特訓アイテムを\n他の特訓アイテムに交換することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60013, /*img*/1, /*discription*/"マニーショップでは、マニーを消費して\nアイテムを購入することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60013, /*img*/1, /*discription*/"アイテムは、それぞれ購入できる上限数が決まっています。\nなお、一部のアイテムは一定期間で購入制限がリセットされます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60014, /*img*/1, /*discription*/"リーダーアイドルを自由に設定できるようになりました。\nリーダーアイドルは、同僚リストなどで\n代表して表示されるアイドルです。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60014, /*img*/2, /*discription*/"ゲスト参戦アイドルを設定できるようになりました。\n他プロデューサーのゲストとして参加するアイドルを、\n楽曲タイプごとに設定することができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60015, /*img*/1, /*discription*/"ドレスショップがオープンしました！島村卯月、本田未央、\n渋谷凛、上条春菜、大槻唯が着用できる新3D衣装\n「プレゼントオブスノウ」を販売中！");
INSERT INTO `individual_tutorial` VALUES (/*id*/60015, /*img*/2, /*discription*/"ドレスショップで購入した3D衣装は、アイドル編成と\nMVモードのユニット確認画面から選択することがで\nきます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60016, /*img*/1, /*discription*/"マニーショップにアイテム売却機能が追加されました。\n画面右上のボタンから売却画面に切り替えることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60016, /*img*/1, /*discription*/"所持アイテムを売却することで、マニーを獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60018, /*img*/1, /*discription*/"スターピースとアイテムを交換できます。\n対象のアイテムによって必要なスターピースの数は\n異なります。 ");
INSERT INTO `individual_tutorial` VALUES (/*id*/60019, /*img*/1, /*discription*/"誕生日特設ページでは、アイドルの誕生日を\nお祝いすることができます。\n誕生日アイドルがいない日は誕生日の確認などができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60019, /*img*/2, /*discription*/"バースデーカード作成ボタンを押すと、誕生日アイドルの\nバースデーカードを作ることができます。\nバースデーカード編集から、好きなデザインを選んで、\nオリジナルのバースデーカードを作りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60019, /*img*/3, /*discription*/"バースデーカードに表示させるイラストやコメントは、\nスワイプすることで位置を自由に調整できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60019, /*img*/4, /*discription*/"作ったバースデーカードは、あなたのTwitterに投稿する事が\nできます。バースデーカードページ左下のTwitterアイコンから\n投稿できます。\n※画像の投稿には、公式のTwitterアプリが必要となります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60019, /*img*/5, /*discription*/"誕生日アイドルをユニットに入れてLIVEをクリアすると、\nファンからプレゼントが貰えます !");
INSERT INTO `individual_tutorial` VALUES (/*id*/60020, /*img*/1, /*discription*/"「フォトスタジオ」を追加しました。\n自由にカメラを操作しながら、楽曲にあわせたダンスや\nポーズをアイドルに「オーダー」できる機能です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60020, /*img*/1, /*discription*/"プロデュースノートからアイドルを選び\n右下の「フォトスタジオ」ボタンをタップ、\n撮影スポットを選択します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60020, /*img*/2, /*discription*/"フォトスタジオでは、画面が縦方向になります。\n画面をスワイプでカメラの移動、\nピンチイン・アウトでズームができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60020, /*img*/2, /*discription*/"画面を連続タップするとメニューが開き、\n「オーダー」でアイドルに呼びかけたり、\n「衣装変更」することができます。\n「撮影終了」でフォトスタジオを終了します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/1, /*discription*/"「LIVE PARTY!!」では、協力LIVEを行うことで、\n「スターエンブレム」が獲得できます。\n「スターエンブレム」を集めると、過去イベントの報酬や、\nアイテムとの交換ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/2, /*discription*/"同じ難易度を選んだプロデューサー5人でマッチングが行われ、\nマッチングされたメンバーと協力してLIVEを行います。\n楽曲はランダムで選曲され、\nメンバー全員が同時にその楽曲でLIVEを行います。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/3, /*discription*/"本機能では、専用ユニットでLIVEを行います。ユニットには5つの「ポジション」があります。\n各プロデューサーのアイドルが、ポジションを1つずつ担当し、5人の共通ユニットが編成されます。\n※自分のアイドルがどのポジションを担当するかはランダムで決定されます。\n※楽曲タイプとポジションごとにアイドルを設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/4, /*discription*/"各メンバーの状況はLIVE画面の左側のエリアで確認できます。\nまた本機能では、ライフが0になった場合も、LIVEは継続となります。\n\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/4, /*discription*/"獲得できるスターエンブレムは、\n「メンバー全員の合計スコア」と「LIVEでの貢献度」\nによって変化します。\nメンバー全員で高スコアを目指しましょう !");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/4, /*discription*/"貢献度は自身が獲得したスコアのほか、LIVEに出演したアイドルの\n「アピール値の高さ」、「特技」をもとに算出します。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/5, /*discription*/"本機能のLIVE報酬では、「協力報酬」と「個人報酬」が獲得できます。\n協力報酬は、メンバー全員のスコアの合計が高いほど、\n良い報酬が出現しやすくなります。\n獲得できる協力報酬は全メンバー共通で、必ず全員が獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/5, /*discription*/"個人報酬は、自分の貢献度が高いほど、良い報酬が出現しやすくなります。\n※個人報酬は、一定の確率で1～2個出現します。\n\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/6, /*discription*/"LIVEの開始前や終了後には、マッチングされたメンバーと\nチャットスタンプでコミュニケーションがとれます。\n使用するスタンプはイベントページ内の「チャット設定」で\n設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/7, /*discription*/"マッチングルームは任意のメンバーで、\n協力してLIVEを行える機能です。\n1部屋に最大5人まで入室できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/7, /*discription*/"マッチングルームは新規にルームを作る「ルーム作成」、\n既にあるルームに入る「ルーム入室」のどちらかの方法で\n利用できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/7, /*discription*/"マッチングルームでは、ホスト以外のメンバーは、\n「スタミナ消費なし」でLIVEを行うこともできます。\n※「スタミナ消費なし」でLIVEを行う場合、獲得できる\n報酬の量が減少し、一部報酬は獲得できなくなります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60100, /*img*/8, /*discription*/"友情ptを使用し、同僚や他のルームに「フラワースタンド」を贈ることが\nできます。贈られた合計数によって、フラワースタンドの見た目が変化します。\n※フラワースタンドの状態は、LIVEや報酬内容に対して影響しません。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60101, /*img*/1, /*discription*/"PARTY編成では、協力LIVEを行うアイドルの設定をします。\n楽曲のタイプごとに1つずつ、合計4つの設定が行えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60102, /*img*/1, /*discription*/"チャット設定では、LIVE開始前や終了後、\nマッチングルームで使用するスタンプの設定が行えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60102, /*img*/1, /*discription*/"まず「セット中スタンプ」の中から、変更したいスタンプを選択し、\n次にスタンプの一覧から、設定したいスタンプを選択しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60102, /*img*/2, /*discription*/"スタンプの設定が済んだら、最後に「保存」ボタンを押しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60102, /*img*/2, /*discription*/"スタンプの設定を初期状態に戻したい場合は、\n「初期設定」ボタンを押しましょう。\nおすすめのスタンプ設定が適用されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/60103, /*img*/1, /*discription*/"マッチングルームでホストが楽曲タイプを選択できるように\nなりました。楽曲タイプの変更は、マッチングルーム内\n「ルーム設定」からも行えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/1, /*discription*/"「イベントptランキング報酬」、「達成pt報酬」、\n「ハイスコアランキング報酬」で、イベント限定の\nSレアアイドルやルームアイテムを手にいれましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/2, /*discription*/"イベントptランキングで50万位に入賞すると、\n自分の順位が入ったイベント称号を獲得できます。\n各称号のデザインは順位によって異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/3, /*discription*/"通常楽曲をプレイすると、羽衣小町エンブレムと\nイベントptを獲得できます。\n羽衣小町エンブレムは、スタミナ消費量と\nSCOREランクが高いほど多く獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/4, /*discription*/"イベント楽曲は、スタミナではなく\n羽衣小町エンブレムを消費してプレイします。\n通常楽曲よりも多くイベントptを獲得できます。\nイベント楽曲は、イベント期間中のみプレイできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80001, /*img*/5, /*discription*/"通常楽曲で羽衣小町エンブレムを集め、\nイベント楽曲で大量にptを獲得しましょう。\nランキング入賞を目指して頑張りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80002, /*img*/1, /*discription*/"羽衣小町エンブレム消費数を2倍、または4倍に\n設定することができます。\n消費数に応じて、イベントptを多く獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/1, /*discription*/"「イベントptランキング報酬」、「達成pt報酬」、\n「ハイスコアランキング報酬」で、イベント限定の\nSレアアイドルやルームアイテムを手にいれましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/2, /*discription*/"イベントptランキングで50万位に入賞すると、\n自分の順位が入ったイベント称号を獲得できます。\n各称号のデザインは順位によって異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/3, /*discription*/"通常楽曲をプレイすると、羽衣小町エンブレムと\nイベントptを獲得できます。\n羽衣小町エンブレムは、スタミナ消費量と\nSCOREランクが高いほど多く獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/4, /*discription*/"イベント楽曲は、スタミナではなく\n羽衣小町エンブレムを消費してプレイします。\n通常楽曲よりも多くイベントptを獲得できます。\nイベント楽曲は、イベント期間中のみプレイできます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/5, /*discription*/"通常楽曲で羽衣小町エンブレムを集め、\nイベント楽曲で大量にptを獲得しましょう。\nランキング入賞を目指して頑張りましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80003, /*img*/6, /*discription*/"羽衣小町エンブレム消費数を2倍、または4倍に\n設定することができます。\n消費数に応じて、イベントptを多く獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/1, /*discription*/"イベント期間中にLIVEをプレイすると、\n限定のアイドルを確率で手に入れることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/2, /*discription*/"日によって限定アイドルの出現率がアップする楽曲が\n決まっています。キュート、クール、パッション、全タイプ楽曲の\nいずれかのタイプの全ての楽曲が対象になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/2, /*discription*/"また、全楽曲出現率アップ日には、すべての楽曲が\n出現率アップの対象になります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/3, /*discription*/"イベント期間中は、センターアイドルのスターランクが\n高ければ高いほど、LIVE報酬を獲得しやすくなります。\n※ユニットに参加していても、センターアイドル以外の\nアイドルのスターランクの効果は発揮されません。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80101, /*img*/4, /*discription*/"イベント追加報酬から、アイテム「キャラバンメダル」が\n登場します。「キャラバンメダル」を集めると、\n限定アイドルのスカウトや、アイテムとの交換ができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/1, /*discription*/"「達成pt報酬」、「イベントptランキング報酬」、\n「ハイスコアランキング報酬」で、イベント限定の\nSレアアイドルやルームアイテムが貰えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/2, /*discription*/"イベントptランキングで50万位に入賞すると、\n自分の順位が入ったイベント称号を獲得できます。\n各称号のデザインは順位によって異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/3, /*discription*/"難易度を選択すると、「Cute Groove」「Cool Groove」\n「Passion Groove」のいずれかが選択され、\n一致するタイプの楽曲がランダムでセットされます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/3, /*discription*/"LIVE Grooveでは、その3曲で連続してLIVEを行います。\n※3曲の間ライフは引き継がれます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/4, /*discription*/"LIVE中、盛り上がりに応じて「ハコユレLv」が計測されます。\n3曲合わせた「ハコユレLv」が17以上になると、\nアンコールが発生します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/5, /*discription*/"難易度がMASTERで、ハコユレLvが21以上の場合、\nアンコール楽曲の難易度で「MASTER+」が選択できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80201, /*img*/6, /*discription*/"LIVE Groove Visual burstでは、ビジュアルのアピール値が\n通常よりアップします。\nビジュアルアピールが高いアイドルを編成して、\nイベント上位を目指しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/1, /*discription*/"「達成pt報酬」で、イベント限定のSレアアイドルや\nルームアイテムを手にいれましょう。\nまた期間中にイベントのLIVEをプレイすると、\n限定のアイドルを確率で手に入れることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/2, /*discription*/"同じ難易度を選んだプロデューサー5人でマッチングが行われ、\nマッチングされたメンバーと協力してLIVEを行います。\n楽曲はランダムで選曲され、\nメンバー全員が同時にその楽曲でLIVEを行います。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/3, /*discription*/"本イベントは、専用ユニットでLIVEを行います。ユニットには5つの「ポジション」があります。\n各プロデューサーのアイドルが、ポジションを1つずつ担当し、5人の共通ユニットが編成されます。\n※自分のアイドルがどのポジションを担当するかはランダムで決定されます。\n※楽曲タイプとポジションごとにアイドルを設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/4, /*discription*/"各メンバーの状況はLIVE画面の左側のエリアで確認できます。\nまた本イベントでは、ライフが0になった場合も、LIVEは継続となります。\n\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/4, /*discription*/"獲得できるptは「メンバー全員の合計スコア」と「LIVEでの貢献度」\nによって変化します。メンバー全員で高スコアを目指しましょう !\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/4, /*discription*/"貢献度は自身が獲得したスコアのほか、LIVEに出演したアイドルの\n「アピール値の高さ」、「特技」をもとに算出します。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/5, /*discription*/"本イベントのLIVE報酬では、「協力報酬」と「個人報酬」が獲得できます。\n協力報酬は、メンバー全員のスコアの合計が高いほど、\n良い報酬が出現しやすくなります。\n獲得できる協力報酬は全メンバー共通で、必ず全員が獲得できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/5, /*discription*/"個人報酬は、自分の貢献度が高いほど、良い報酬が出現しやすくなります。\n※個人報酬は、一定の確率で1～2個出現します。\n\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/6, /*discription*/"LIVEの開始前や終了後には、マッチングされたメンバーと\nチャットスタンプでコミュニケーションがとれます。\n使用するスタンプはイベントページ内の「チャット設定」で\n設定できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/7, /*discription*/"マッチングルームは任意のメンバーで\n協力してLIVEを行える機能です。\n１部屋に最大5人まで入室できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80301, /*img*/7, /*discription*/"マッチングルームは新規にルームを作る「ルーム作成」、\n既にあるルームに入る「ルーム入室」のどちらかの方法で\n利用できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80401, /*img*/1, /*discription*/"イベント編成では、イベントのLIVEを行うアイドルの設定をします。\n楽曲のタイプごとに1つずつ、合計4つの設定が行えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80501, /*img*/1, /*discription*/"チャット設定では、LIVE開始前や終了後、\nマッチングルームで使用するスタンプの設定が行えます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80501, /*img*/1, /*discription*/"まず「セット中スタンプ」の中から、変更したいスタンプを選択し、\n次にスタンプの一覧から、設定したいスタンプを選択しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80501, /*img*/2, /*discription*/"スタンプの設定が済んだら、最後に「保存」ボタンを押しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80501, /*img*/2, /*discription*/"スタンプの設定を初期状態に戻したい場合は、\n「初期設定」ボタンを押しましょう。\nイベント開始時のおすすめのスタンプ設定が適用されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/1, /*discription*/"「達成pt報酬」、「観客動員数報酬」、\n「ハイスコアランキング報酬」で、イベント限定の\nSレアアイドルやルームアイテムが貰えるだけでなく、\nイベント限定楽曲をイベント終了後もプレイできるようになります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/2, /*discription*/"全国各地で公演を行い、LIVEツアーを盛り上げましょう。\n公演目標を達成してLIVEをクリアすると、\n新しい公演が解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/3, /*discription*/"公演の目標が達成できるように、楽曲やユニットを選びましょう。\n公演によって消費スタミナやLIVEを行う曲数が異なります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/4, /*discription*/"公演を行うと、観客動員数が増加します。\n対象のエリアの観客動員数が一定値に到達すると、\n新しいエリアが解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/4, /*discription*/"エリア2、3に到達すると、イベント楽曲のMASTER+の\n難易度が選曲可能となります。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/5, /*discription*/"日替わりで切り替わる「流行曲」を含めて公演を行ったり、\nマニーを使用して「LIVEオプション」を設定すると、\nエリアの観客動員数がさらにアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/5, /*discription*/"また観客動員数の多いエリアで公演を行うと、\n獲得できるファン数がアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80601, /*img*/6, /*discription*/"イベント設定では、公演の準備画面の「おすすめ設定」で\n選曲される楽曲のLvを調整できます。\nまたツアーのタイトルを自由に変更できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80701, /*img*/1, /*discription*/"「イベント参加ボーナス」、「MAP報酬」、「課題クリア報酬」\nで、イベント限定のSレアアイドルやルームアイテムを\n手にいれましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80701, /*img*/2, /*discription*/"本イベントでは、LIVEを行うことでアイドルたちが\nMAPを進んでいきます。楽曲の難易度やLIVEの\n結果に応じて、進行できるマス数が変化します。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80701, /*img*/2, /*discription*/"また、ルートはイベント限定アイドルごとに分かれており、\nそれぞれストーリーや報酬が異なります。\n※「首藤葵」ルートのMAP1をクリアすると、\n「遊佐こずえ」ルートが解放されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80701, /*img*/3, /*discription*/"MAPやマスごとの条件を満たしてLIVEを行うと、\nMAP進行ボーナスが発生し、進行できるマス数がアップします。");
INSERT INTO `individual_tutorial` VALUES (/*id*/80701, /*img*/3, /*discription*/"MAP進行ボーナスは、MAPにあわせたアイドルを編成したり、\n現在止まっているマスの色に応じた楽曲でLIVEを行うことで発生します。\nボーナス条件はイベントTOPや楽曲の選択画面等で確認できます。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80701, /*img*/4, /*discription*/"ゴールに到着すると、トレーナーからMAPごとの課題が出されます。\n※課題の達成状況は累積でカウントされるため、1回のLIVEでクリアできない場合、\n複数回LIVEをすることで達成できます。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80701, /*img*/5, /*discription*/"MAPを進行していると、たまに「進行2倍ボーナス」が\n発生することがあります。進行2倍ボーナスが発生すると、\n次回のLIVEクリア時に進行できるマス数が2倍になります。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/80701, /*img*/6, /*discription*/"楽曲選択画面の並べ替えメニューで「イベントボーナス」を\n選択すると、現在止まっているマスに適した楽曲を\n簡単に絞り込むことができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90101, /*img*/1, /*discription*/"アイドルのファン数を増やすことで、ポテンシャルを解放し、\nアイドルのステータスを強化することができる機能です。\n（ポテンシャル解放では特訓アイテムを消費します）\n※各数値は開発中のものです。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90102, /*img*/1, /*discription*/"PランクSS、PRP1000以上のプロデューサーのみ参加可能な\nランキングで、上位入賞することで、PランクSSSに昇格します。\n（PランクSSSは、1ヶ月の任期制となります）\n    ");
INSERT INTO `individual_tutorial` VALUES (/*id*/90103, /*img*/1, /*discription*/"新3D衣装「アクロス・ザ・スターズ」登場 !\n3DLIVEでアイドルたちの衣装を\n変更することができるようになりました !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90103, /*img*/2, /*discription*/"3D衣装の変更はアイドル編成と\nMVモードのユニット確認画面で\n切り替えることができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/3, /*discription*/"ルームでアイドルからスタミナ回復アイテム\n「手作りショートケーキ」を受け取ろう !\n詳細はお知らせをご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/4, /*discription*/"キャンペーン開催期間中の初回ログイン時に\n「スタージュエル 2500個」をプレゼント");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/4, /*discription*/"さらに毎日「スタージュエル 50個」を\nプレゼントする「1周年記念ログイン\nボーナスキャンペーン」");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/1, /*discription*/"ローカルオーディションガシャからレッスンに\n効果的なアイテムが出やすい「育成強化キャンペーン」");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/1, /*discription*/"レッスン大成功確率が通常の3倍になる\n「レッスン大成功確率アップキャンペーン」");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/2, /*discription*/"LIVEコンティニューに必要なスタージュエルが\n「50個」から「10個」になる「LIVEチャレンジ\nキャンペーン」");
INSERT INTO `individual_tutorial` VALUES (/*id*/90104, /*img*/2, /*discription*/"LIVE成功時にティアラと魔法のドレスの\nドロップ率がアップする「特訓支援キャンペーン」\n期間などの詳細はお知らせよりご確認ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90105, /*img*/1, /*discription*/"「LIVE PARTY!!」がいつでも遊べるようになります !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90105, /*img*/1, /*discription*/"専用のアイテムを集めることで、過去のイベントに登場した\nアイドルやルームアイテムを獲得できます !\n※各報酬は、LIVE PARTY!!以外でも、\n今後獲得可能になる予定です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90106, /*img*/1, /*discription*/"LIVEのMV設定に、新たに「縦画面モード」を追加予定です。\n対応楽曲では、端末を縦にしてMVを再生できます。\n※「縦画面モード」対応楽曲は順次追加予定です。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90106, /*img*/2, /*discription*/"LIVEに新モード「SMART LIVE」を追加予定です。\n対応楽曲で、端末を縦に持って片手でプレイ可能な\n新しいスタイルのリズムゲームです。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90106, /*img*/3, /*discription*/"「MVプレイリスト」機能を追加予定です。\n実際に開催されたLIVEのセットリストに沿って、\n楽曲のMVを鑑賞することができます。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90107, /*img*/1, /*discription*/"LIVEのMV設定に、新たに「縦画面モード」を追加しました。\n対応楽曲では、端末を縦にしてMVを再生できます。\n※「縦画面モード」対応楽曲は順次追加予定です。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90107, /*img*/2, /*discription*/"LIVEに新モード「SMART LIVE」を追加予定です。\n対応楽曲で、端末を縦に持って片手でプレイ可能な\n新しいスタイルのリズムゲームです。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90107, /*img*/3, /*discription*/"「MVプレイリスト」機能を追加予定です。\n実際に開催されたLIVEのセットリストに沿って、\n楽曲のMVを鑑賞することができます。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90108, /*img*/1, /*discription*/"LIVEのMV設定に、新たに「縦画面モード」を追加しました。\n対応楽曲では、端末を縦にしてMVを再生できます。\n※「縦画面モード」対応楽曲は順次追加予定です。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90108, /*img*/2, /*discription*/"LIVEに新モード「SMART LIVE」を追加予定です。\n対応楽曲で、端末を縦に持って片手でプレイ可能な\n新しいスタイルのリズムゲームです。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90108, /*img*/3, /*discription*/"「MVプレイリスト」機能を追加しました。\n実際に開催されたLIVEのセットリストに沿って、\n楽曲のMVを鑑賞することができます。\n");
INSERT INTO `individual_tutorial` VALUES (/*id*/90110, /*img*/1, /*discription*/"「プラチナオーディションガシャ\n1日1回10連無料キャンペーン」を開催中 !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90110, /*img*/1, /*discription*/"キャンペーン期間中1日1回無料で\n10連ガシャを引くことができます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90110, /*img*/1, /*discription*/"1日1回無料で引ける10連ガシャは\n毎日24時にリセットされます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90111, /*img*/1, /*discription*/"レイアウト済みのルームアイテムを\nそのまま購入、配置できる「コーデ」を追加 !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90111, /*img*/1, /*discription*/"「コーデ」は9/3 15:00以降に\nルームショップで購入できます !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90112, /*img*/1, /*discription*/"2周年を記念して、\n宝くじキャンペーンを開催中です。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90112, /*img*/1, /*discription*/"ログインやミッションで宝くじを集めて\n豪華な景品を獲得しましょう !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90113, /*img*/1, /*discription*/"宝くじの配布は終了しました。\n結果発表までお楽しみに !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90114, /*img*/1, /*discription*/"現在抽選結果を発表中です。\n配布期間中に宝くじを獲得した方は\n抽選結果を確認しましょう !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90115, /*img*/1, /*discription*/"デレステ2周年記念 ! 「レッツプレゼントキャンペーン」開催中 !\n最大賞金1000万円ほか、豪華賞品プレゼントが抽選で当たる !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90115, /*img*/2, /*discription*/"さらに、キャンペーン開催を記念して、\nルームアイテム「純金ぴにゃ像」をプレゼント !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90115, /*img*/2, /*discription*/"キャンペーンはキャンペーンページからアクセスできる、\n特設サイトよりご応募ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90201, /*img*/1, /*discription*/"本キャンペーンは宝くじ獲得可能期間に「宝くじチケット」を\n集めることで参加できます ! 獲得可能期間終了後に\n獲得した「宝くじチケット」毎に景品の抽選を行います。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90201, /*img*/2, /*discription*/"抽選の結果によって、「スカウトチケット」など豪華景品を\nGETできます ! ※1等から8等までは抽選条件があります。\n詳しくはヘルプをご覧ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90202, /*img*/1, /*discription*/"本キャンペーンは宝くじ獲得可能期間に「宝くじチケット」を\n集めることで参加できます ! 獲得可能期間終了後に\n獲得した「宝くじチケット」毎に景品の抽選を行います。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90202, /*img*/2, /*discription*/"抽選の結果によって、「スカウトチケット」など豪華景品を\nGETできます ! ※1等から8等までは抽選条件があります。\n詳しくはヘルプをご覧ください。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90301, /*img*/1, /*discription*/"「楽曲総選挙」が始まりました !\nお気に入りの楽曲に投票しましょう。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90301, /*img*/2, /*discription*/"投票できるのは、ソロ楽曲部門とユニット楽曲部門の2部門 !\n各部門1日1回投票できます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90301, /*img*/3, /*discription*/"受賞楽曲は、\nmobage「アイドルマスター シンデレラガールズ」\n第6回シンデレラガール総選挙と連動して楽曲化 !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90401, /*img*/1, /*discription*/"オールスターカウントダウンLIVE開催 !\n開催期間は2017年12月31日0時～24時です。\nみんなでLIVEを楽しみながら1年を締めくくりましょう !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90401, /*img*/2, /*discription*/"全プロデューサーで対象楽曲をクリアして、「全体ミッション」を達成しま\nしょう ! 対象楽曲がクリアされた回数によって獲得できる報酬が決定します !\n※全体ミッションの達成報酬は、\n1月1日12時にまとめて配布されます。");
INSERT INTO `individual_tutorial` VALUES (/*id*/90401, /*img*/4, /*discription*/"「オールスターカウントダウンLIVE」には、「全体ミッション」のほかに\n「個人ミッション」があります。「宝くじチケット」や\n「イベント限定アイドルスカウトチケット」などを含む、\n豪華景品をご用意しておりますので忘れずにチェックしてくださいね !");
INSERT INTO `individual_tutorial` VALUES (/*id*/90401, /*img*/5, /*discription*/"特設ページ内「次のコミュ解放」横に表示されている時間になると、\nアイドルたちがMCを務めるコミュが解放されます。\n後半には「あの曲」も登場・・・ ! ？");
