CREATE TABLE 'item_category' ('category_type' INTEGER NOT NULL, 'category_name' TEXT NOT NULL, PRIMARY KEY('category_type'));
INSERT INTO `item_category` VALUES (/*category_type*/1, /*category_name*/"回復アイテム");
INSERT INTO `item_category` VALUES (/*category_type*/2, /*category_name*/"特訓アイテム");
INSERT INTO `item_category` VALUES (/*category_type*/3, /*category_name*/"ガシャチケット");
INSERT INTO `item_category` VALUES (/*category_type*/4, /*category_name*/"トレーナー");
INSERT INTO `item_category` VALUES (/*category_type*/5, /*category_name*/"イベントアイテム");
INSERT INTO `item_category` VALUES (/*category_type*/6, /*category_name*/"リハーサルチケット");
INSERT INTO `item_category` VALUES (/*category_type*/7, /*category_name*/"ギフトアイテム");
INSERT INTO `item_category` VALUES (/*category_type*/8, /*category_name*/"スカウトチケット");
INSERT INTO `item_category` VALUES (/*category_type*/9, /*category_name*/"宝くじチケット");
INSERT INTO `item_category` VALUES (/*category_type*/10, /*category_name*/"交換アイテム");
INSERT INTO `item_category` VALUES (/*category_type*/11, /*category_name*/"イベントスカウトチケット");
INSERT INTO `item_category` VALUES (/*category_type*/12, /*category_name*/"総選挙の投票券");
INSERT INTO `item_category` VALUES (/*category_type*/13, /*category_name*/"プラチナメダル");
INSERT INTO `item_category` VALUES (/*category_type*/14, /*category_name*/"プラチナメダル専用スカウトチケット");
INSERT INTO `item_category` VALUES (/*category_type*/15, /*category_name*/"フォトスタジオ・背景");
INSERT INTO `item_category` VALUES (/*category_type*/16, /*category_name*/"フォトスタジオ・ポーズ");
INSERT INTO `item_category` VALUES (/*category_type*/17, /*category_name*/"衣装交換チケット");
