CREATE TABLE 'latte_art_target' ('id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'latte_id' INTEGER NOT NULL, 'val_id' INTEGER NOT NULL, 'card_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `latte_art_target` VALUES (/*id*/1, /*type*/3, /*latte_id*/19, /*val_id*/7007000, /*card_id*/0);
INSERT INTO `latte_art_target` VALUES (/*id*/2, /*type*/3, /*latte_id*/32, /*val_id*/7008000, /*card_id*/0);
INSERT INTO `latte_art_target` VALUES (/*id*/3, /*type*/3, /*latte_id*/56, /*val_id*/7009000, /*card_id*/0);
INSERT INTO `latte_art_target` VALUES (/*id*/4, /*type*/3, /*latte_id*/74, /*val_id*/6, /*card_id*/0);
INSERT INTO `latte_art_target` VALUES (/*id*/5, /*type*/3, /*latte_id*/104, /*val_id*/7010000, /*card_id*/0);
INSERT INTO `latte_art_target` VALUES (/*id*/6, /*type*/3, /*latte_id*/128, /*val_id*/7012000, /*card_id*/0);
INSERT INTO `latte_art_target` VALUES (/*id*/7, /*type*/3, /*latte_id*/203, /*val_id*/13, /*card_id*/0);
INSERT INTO `latte_art_target` VALUES (/*id*/8, /*type*/2, /*latte_id*/221, /*val_id*/2031, /*card_id*/0);
CREATE INDEX 'latte_art_target_0_type_1_val_id' on 'latte_art_target'('type','val_id');
