CREATE TABLE 'live_data_replace' ('id' INTEGER NOT NULL, 'live_data_id' INTEGER NOT NULL, 'new_live_data_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'value_1' INTEGER NOT NULL, 'value_2' INTEGER NOT NULL, 'value_3' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `live_data_replace` VALUES (/*id*/1, /*live_data_id*/36, /*new_live_data_id*/10036, /*type*/1, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/2, /*live_data_id*/404, /*new_live_data_id*/404, /*type*/4, /*value_1*/7, /*value_2*/12, /*value_3*/7);
INSERT INTO `live_data_replace` VALUES (/*id*/3, /*live_data_id*/605, /*new_live_data_id*/605, /*type*/3, /*value_1*/7, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/4, /*live_data_id*/419, /*new_live_data_id*/419, /*type*/5, /*value_1*/16, /*value_2*/12, /*value_3*/7);
INSERT INTO `live_data_replace` VALUES (/*id*/5, /*live_data_id*/621, /*new_live_data_id*/621, /*type*/5, /*value_1*/16, /*value_2*/12, /*value_3*/7);
INSERT INTO `live_data_replace` VALUES (/*id*/6, /*live_data_id*/404, /*new_live_data_id*/404, /*type*/4, /*value_1*/17, /*value_2*/12, /*value_3*/7);
INSERT INTO `live_data_replace` VALUES (/*id*/7, /*live_data_id*/632, /*new_live_data_id*/10632, /*type*/6, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/8, /*live_data_id*/857, /*new_live_data_id*/10857, /*type*/6, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/9, /*live_data_id*/441, /*new_live_data_id*/10441, /*type*/6, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/10, /*live_data_id*/642, /*new_live_data_id*/10642, /*type*/6, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/11, /*live_data_id*/862, /*new_live_data_id*/10862, /*type*/7, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/12, /*live_data_id*/19, /*new_live_data_id*/10019, /*type*/1, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/13, /*live_data_id*/419, /*new_live_data_id*/419, /*type*/5, /*value_1*/29, /*value_2*/12, /*value_3*/7);
INSERT INTO `live_data_replace` VALUES (/*id*/14, /*live_data_id*/867, /*new_live_data_id*/10867, /*type*/9, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/15, /*live_data_id*/389, /*new_live_data_id*/10389, /*type*/1, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/16, /*live_data_id*/493, /*new_live_data_id*/916, /*type*/10, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/17, /*live_data_id*/493, /*new_live_data_id*/915, /*type*/11, /*value_1*/0, /*value_2*/0, /*value_3*/0);
INSERT INTO `live_data_replace` VALUES (/*id*/18, /*live_data_id*/404, /*new_live_data_id*/404, /*type*/4, /*value_1*/42, /*value_2*/12, /*value_3*/7);
INSERT INTO `live_data_replace` VALUES (/*id*/19, /*live_data_id*/1320, /*new_live_data_id*/1320, /*type*/5, /*value_1*/44, /*value_2*/12, /*value_3*/7);
INSERT INTO `live_data_replace` VALUES (/*id*/20, /*live_data_id*/1509, /*new_live_data_id*/1509, /*type*/5, /*value_1*/44, /*value_2*/12, /*value_3*/7);
CREATE INDEX 'live_data_replace_0_live_data_id' on 'live_data_replace'('live_data_id');
