CREATE TABLE 'lottery_mission_achievement_reward' ('id' INTEGER NOT NULL, 'campaign_id' INTEGER NOT NULL, 'mission_id' INTEGER NOT NULL, 'need_num' INTEGER NOT NULL, 'reward_type' INTEGER NOT NULL, 'reward_id' INTEGER NOT NULL, 'reward_num' INTEGER NOT NULL, 'add_value_1' INTEGER NOT NULL, 'add_value_2' INTEGER NOT NULL, 'add_value_3' INTEGER NOT NULL, 'message_id' INTEGER NOT NULL, 'icon_path' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `lottery_mission_achievement_reward` VALUES (/*id*/1013, /*campaign_id*/10014, /*mission_id*/1013, /*need_num*/1, /*reward_type*/5, /*reward_id*/10032, /*reward_num*/3, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0, /*message_id*/20102, /*icon_path*/"");
INSERT INTO `lottery_mission_achievement_reward` VALUES (/*id*/1014, /*campaign_id*/10014, /*mission_id*/1014, /*need_num*/5, /*reward_type*/5, /*reward_id*/5, /*reward_num*/3, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0, /*message_id*/20102, /*icon_path*/"");
INSERT INTO `lottery_mission_achievement_reward` VALUES (/*id*/1015, /*campaign_id*/10014, /*mission_id*/1015, /*need_num*/10, /*reward_type*/5, /*reward_id*/30007, /*reward_num*/1, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0, /*message_id*/20102, /*icon_path*/"");
INSERT INTO `lottery_mission_achievement_reward` VALUES (/*id*/1016, /*campaign_id*/10014, /*mission_id*/1016, /*need_num*/15, /*reward_type*/5, /*reward_id*/1002, /*reward_num*/1, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0, /*message_id*/20102, /*icon_path*/"");
INSERT INTO `lottery_mission_achievement_reward` VALUES (/*id*/1017, /*campaign_id*/10014, /*mission_id*/1017, /*need_num*/20, /*reward_type*/5, /*reward_id*/5903, /*reward_num*/1, /*add_value_1*/1, /*add_value_2*/0, /*add_value_3*/0, /*message_id*/20102, /*icon_path*/"Lottery/chanceticket_000");
INSERT INTO `lottery_mission_achievement_reward` VALUES (/*id*/1018, /*campaign_id*/10014, /*mission_id*/1018, /*need_num*/25, /*reward_type*/4, /*reward_id*/0, /*reward_num*/250, /*add_value_1*/0, /*add_value_2*/0, /*add_value_3*/0, /*message_id*/20102, /*icon_path*/"");
CREATE INDEX 'lottery_mission_achievement_reward_0_campaign_id' on 'lottery_mission_achievement_reward'('campaign_id');
CREATE INDEX 'lottery_mission_achievement_reward_0_mission_id' on 'lottery_mission_achievement_reward'('mission_id');
