CREATE TABLE 'meetup_memory_area_filter' ('id' INTEGER NOT NULL, 'filter_name' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/0, /*filter_name*/"なし");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/1, /*filter_name*/"まずは海へ");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/2, /*filter_name*/"寿司屋");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/3, /*filter_name*/"調理中♡");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/4, /*filter_name*/"VTR♡\n団地");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/5, /*filter_name*/"VTR♡\n住宅街");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/6, /*filter_name*/"まずは\n国外へ");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/7, /*filter_name*/"試作中");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/8, /*filter_name*/"調理中♡");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/9, /*filter_name*/"VTR♡\n団地");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/10, /*filter_name*/"VTR♡\n出迎え");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/11, /*filter_name*/"その他");
