CREATE TABLE 'meetup_memory_area_filter' ('id' INTEGER NOT NULL, 'filter_name' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/0, /*filter_name*/"なし");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/1, /*filter_name*/"廃ビル");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/2, /*filter_name*/"逃走、\n遊園地");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/3, /*filter_name*/"来ちゃった\n山頂");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/4, /*filter_name*/"山越えて海");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/5, /*filter_name*/"日常の朝");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/6, /*filter_name*/"廃ビル");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/7, /*filter_name*/"逃走、\n遊園地");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/8, /*filter_name*/"来ちゃった\n山頂");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/9, /*filter_name*/"山越えて海");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/10, /*filter_name*/"日常の朝");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/11, /*filter_name*/"その他");
