CREATE TABLE 'meetup_memory_area_filter' ('id' INTEGER NOT NULL, 'filter_name' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/0, /*filter_name*/"なし");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/1, /*filter_name*/"君と、\n学校生活");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/2, /*filter_name*/"君と、\n試験勉強");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/3, /*filter_name*/"君と、\nふたりで");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/4, /*filter_name*/"君の背を\n眺めて");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/5, /*filter_name*/"君に、\nこの声を");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/6, /*filter_name*/"君と、\n学校生活");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/7, /*filter_name*/"君と、\n試験勉強");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/8, /*filter_name*/"君と、\nふたりで");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/9, /*filter_name*/"君の瞳を\n見て");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/10, /*filter_name*/"君に、\nワガママ");
INSERT INTO `meetup_memory_area_filter` VALUES (/*id*/11, /*filter_name*/"その他");
