CREATE TABLE 'memorial_story_open' ('chapter' INTEGER NOT NULL, 'open_fan_num' INTEGER NOT NULL, PRIMARY KEY('chapter'));
INSERT INTO `memorial_story_open` VALUES (/*chapter*/1, /*open_fan_num*/0);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/2, /*open_fan_num*/2000);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/3, /*open_fan_num*/10000);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/4, /*open_fan_num*/20000);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/5, /*open_fan_num*/30000);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/6, /*open_fan_num*/40000);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/7, /*open_fan_num*/50000);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/8, /*open_fan_num*/60000);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/9, /*open_fan_num*/70000);
INSERT INTO `memorial_story_open` VALUES (/*chapter*/10, /*open_fan_num*/80000);
