CREATE TABLE 'mille_feuille_card_comment' ('id' INTEGER NOT NULL, 'comment_id' INTEGER NOT NULL, 'use_type' INTEGER NOT NULL, 'index' INTEGER NOT NULL, 'voice_flag' INTEGER NOT NULL, 'description' TEXT NOT NULL, 'insert_word_type' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/1, /*comment_id*/900015, /*use_type*/1, /*index*/1, /*voice_flag*/1, /*description*/"ハピネシウム集めにしゅっぱーつ ! グラッシー帝国に気をつけるにぃ !", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/2, /*comment_id*/900015, /*use_type*/1, /*index*/2, /*voice_flag*/1, /*description*/"3大幹部…手強い相手だにぃ。でも、きらりたちならきっと大丈夫 !", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/3, /*comment_id*/900017, /*use_type*/1, /*index*/1, /*voice_flag*/1, /*description*/"みんなの帰る場所を…取り戻して、くれ…ガクッ…zzz……", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/4, /*comment_id*/900017, /*use_type*/1, /*index*/2, /*voice_flag*/1, /*description*/"グラッシー帝国…恐ろしい相手だよ…死んだふりしてやり過ごしたけど…", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/5, /*comment_id*/900015, /*use_type*/2, /*index*/1, /*voice_flag*/1, /*description*/"グラッシーハルナ ! きらりたちのはぴはぴの力、見せてあげる !", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/6, /*comment_id*/900015, /*use_type*/2, /*index*/2, /*voice_flag*/1, /*description*/"いっけぇ ! きらりんロボ ! みんなの笑顔を、取り戻すんだゆー !", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/7, /*comment_id*/900017, /*use_type*/2, /*index*/1, /*voice_flag*/1, /*description*/"きらりんロボが、あんな相手に負けるわけない ! やれやれーっ !", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/8, /*comment_id*/900017, /*use_type*/2, /*index*/2, /*voice_flag*/1, /*description*/"最終決戦だ ! 杏もやっと家のお布団で寝れる ! はやくはやく !", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/9, /*comment_id*/900015, /*use_type*/3, /*index*/1, /*voice_flag*/1, /*description*/"モロボシティのはぴはぴは、これからもきらりんロボが守る !", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/10, /*comment_id*/900015, /*use_type*/3, /*index*/2, /*voice_flag*/1, /*description*/"みんなを助けてくれて、ありがとにぃ。きらりも、はっぴはぴ !", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/11, /*comment_id*/900017, /*use_type*/3, /*index*/1, /*voice_flag*/1, /*description*/"やっぱり平和が一番だよ…これが幸せ…おやすみ……", /*insert_word_type*/0);
INSERT INTO `mille_feuille_card_comment` VALUES (/*id*/12, /*comment_id*/900017, /*use_type*/3, /*index*/2, /*voice_flag*/1, /*description*/"ま、勝てたのは杏のサポートあってこそだね。だから、ご褒美に飴を…", /*insert_word_type*/0);
CREATE INDEX 'mille_feuille_card_comment_0_comment_id' on 'mille_feuille_card_comment'('comment_id');
