CREATE TABLE 'mille_feuille_story_detail' ('id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'next_detail_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3243, /*type*/0, /*next_detail_id*/3244);
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3244, /*type*/1, /*next_detail_id*/3245);
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3245, /*type*/2, /*next_detail_id*/3246);
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3246, /*type*/3, /*next_detail_id*/3247);
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3247, /*type*/4, /*next_detail_id*/3248);
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3248, /*type*/5, /*next_detail_id*/3249);
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3249, /*type*/6, /*next_detail_id*/3250);
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3250, /*type*/7, /*next_detail_id*/3251);
INSERT INTO `mille_feuille_story_detail` VALUES (/*id*/3251, /*type*/8, /*next_detail_id*/0);
