CREATE TABLE 'music_data' ('id' INTEGER NOT NULL, 'name' TEXT NOT NULL, 'bpm' INTEGER NOT NULL, 'composer' TEXT NOT NULL, 'lyricist' TEXT NOT NULL, 'sound_offset' INTEGER NOT NULL, 'sound_length' INTEGER NOT NULL, PRIMARY KEY('id'))
INSERT INTO `music_data` VALUES (/*id*/1001, /*name*/"お願い ! シンデレラ", /*bpm*/175, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/57508, /*sound_length*/20937);
INSERT INTO `music_data` VALUES (/*id*/1002, /*name*/"輝く世界の魔法", /*bpm*/172, /*composer*/"小西裕子", /*lyricist*/"yura", /*sound_offset*/69274, /*sound_length*/23335);
INSERT INTO `music_data` VALUES (/*id*/1003, /*name*/"We're the friends!", /*bpm*/178, /*composer*/"藤末樹", /*lyricist*/"森由里子", /*sound_offset*/60794, /*sound_length*/26158);
INSERT INTO `music_data` VALUES (/*id*/1004, /*name*/"メッセージ", /*bpm*/170, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"遠藤フビト", /*sound_offset*/81901, /*sound_length*/11634);
INSERT INTO `music_data` VALUES (/*id*/1005, /*name*/"ススメ☆オトメ \n～jewel parade～", /*bpm*/130, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/62779, /*sound_length*/15559);
INSERT INTO `music_data` VALUES (/*id*/1006, /*name*/"ススメ☆オトメ \n～jewel parade～", /*bpm*/130, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/62779, /*sound_length*/15559);
INSERT INTO `music_data` VALUES (/*id*/1007, /*name*/"ススメ☆オトメ \n～jewel parade～", /*bpm*/130, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/62779, /*sound_length*/15559);
INSERT INTO `music_data` VALUES (/*id*/1008, /*name*/"ススメ☆オトメ \n～jewel parade～", /*bpm*/130, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/62779, /*sound_length*/15559);
INSERT INTO `music_data` VALUES (/*id*/1009, /*name*/"アタシポンコツ\nアンドロイド", /*bpm*/135, /*composer*/"ササキトモコ", /*lyricist*/"ササキトモコ", /*sound_offset*/58721, /*sound_length*/15129);
INSERT INTO `music_data` VALUES (/*id*/1010, /*name*/"Nation Blue", /*bpm*/157, /*composer*/"遠山明孝", /*lyricist*/"遠山明孝", /*sound_offset*/80190, /*sound_length*/25000);
INSERT INTO `music_data` VALUES (/*id*/1011, /*name*/"Orange Sapphire", /*bpm*/162, /*composer*/"Funta7", /*lyricist*/"Funta3", /*sound_offset*/81413, /*sound_length*/27000);
INSERT INTO `music_data` VALUES (/*id*/1012, /*name*/"オルゴールの小箱", /*bpm*/186, /*composer*/"高橋浩平", /*lyricist*/"森由里子", /*sound_offset*/74731, /*sound_length*/29000);
INSERT INTO `music_data` VALUES (/*id*/1013, /*name*/"絶対特権\n主張しますっ !", /*bpm*/200, /*composer*/"山崎真吾", /*lyricist*/"坂井⻯⼆", /*sound_offset*/46487, /*sound_length*/25000);
INSERT INTO `music_data` VALUES (/*id*/1014, /*name*/"パステルピンクな恋", /*bpm*/175, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/61676, /*sound_length*/16000);
INSERT INTO `music_data` VALUES (/*id*/1015, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由⾥⼦", /*sound_offset*/63768, /*sound_length*/26000);
INSERT INTO `music_data` VALUES (/*id*/1016, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由⾥⼦", /*sound_offset*/63768, /*sound_length*/26000);
INSERT INTO `music_data` VALUES (/*id*/1017, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由⾥⼦", /*sound_offset*/63768, /*sound_length*/26000);
INSERT INTO `music_data` VALUES (/*id*/1018, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由⾥⼦", /*sound_offset*/63768, /*sound_length*/26000);
INSERT INTO `music_data` VALUES (/*id*/1019, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由⾥⼦", /*sound_offset*/63768, /*sound_length*/26000);
INSERT INTO `music_data` VALUES (/*id*/1020, /*name*/"Absolute NIne", /*bpm*/175, /*composer*/"hisakuni", /*lyricist*/"hisakuni", /*sound_offset*/66904, /*sound_length*/39000);
INSERT INTO `music_data` VALUES (/*id*/3001, /*name*/"S(mile)ING!", /*bpm*/178, /*composer*/"BNSI（Yoshi）", /*lyricist*/"BNSI（八城雄太）", /*sound_offset*/52279, /*sound_length*/18828);
INSERT INTO `music_data` VALUES (/*id*/3002, /*name*/"Never say never", /*bpm*/156, /*composer*/"BNEI（遠山明孝）", /*lyricist*/"BNEI（遠山明孝・八城雄太）", /*sound_offset*/61305, /*sound_length*/11520);
INSERT INTO `music_data` VALUES (/*id*/3003, /*name*/"ミツボシ☆☆★", /*bpm*/175, /*composer*/"BNSI（kyo）", /*lyricist*/"BNSI（八城雄太）", /*sound_offset*/51889, /*sound_length*/10195);
INSERT INTO `music_data` VALUES (/*id*/3004, /*name*/"風色メロディ", /*bpm*/90, /*composer*/"BNSI（トリ音）", /*lyricist*/"BNSI（トリ音）", /*sound_offset*/65087, /*sound_length*/20628);
INSERT INTO `music_data` VALUES (/*id*/3005, /*name*/"華蕾夢ミル狂詩曲 \n～魂ノ導～", /*bpm*/184, /*composer*/"BNSI（浩川卿中二）", /*lyricist*/"BNSI（東ノ獄彩）", /*sound_offset*/60743, /*sound_length*/20425);
INSERT INTO `music_data` VALUES (/*id*/3006, /*name*/"ましゅまろ☆キッス", /*bpm*/93, /*composer*/"BNSI（トリ音）", /*lyricist*/"BNSI（トリ音）", /*sound_offset*/77276, /*sound_length*/21718);
INSERT INTO `music_data` VALUES (/*id*/3007, /*name*/"あんずのうた", /*bpm*/195, /*composer*/"佐藤貴文", /*lyricist*/"八城雄太、佐藤貴文", /*sound_offset*/69880, /*sound_length*/24830);
INSERT INTO `music_data` VALUES (/*id*/3008, /*name*/"You're stars \nshine on me", /*bpm*/96, /*composer*/"BNSI（小林啓樹）", /*lyricist*/"貝田由里子", /*sound_offset*/83553, /*sound_length*/27000);
INSERT INTO `music_data` VALUES (/*id*/3009, /*name*/"DOKIDOKIリズム", /*bpm*/180, /*composer*/"BNEI（佐藤貴文）", /*lyricist*/"BNEI（佐藤貴文）", /*sound_offset*/54450, /*sound_length*/26189);
INSERT INTO `music_data` VALUES (/*id*/3010, /*name*/"おねだり\nShall We ～?", /*bpm*/148, /*composer*/"BNSI（佐藤貴文）", /*lyricist*/"BNSI（佐藤貴文）", /*sound_offset*/64586, /*sound_length*/16065);
INSERT INTO `music_data` VALUES (/*id*/3011, /*name*/"ヴィーナス\nシンドローム", /*bpm*/151, /*composer*/"BNSI（kyo）", /*lyricist*/"古屋真", /*sound_offset*/53134, /*sound_length*/28000);
INSERT INTO `music_data` VALUES (/*id*/3012, /*name*/"Romantic Now", /*bpm*/170, /*composer*/"BNSI（Taku Inoue）", /*lyricist*/"BNSI（MC TC）", /*sound_offset*/81183, /*sound_length*/26000);
INSERT INTO `music_data` VALUES (/*id*/3013, /*name*/"ショコラ・ティアラ", /*bpm*/133, /*composer*/"BNEI（kyo）", /*lyricist*/"古屋真", /*sound_offset*/93588, /*sound_length*/16660);
INSERT INTO `music_data` VALUES (/*id*/3014, /*name*/"Twilight Sky", /*bpm*/176, /*composer*/"BNSI（渡辺量）", /*lyricist*/"BNSI（渡辺量）", /*sound_offset*/59652, /*sound_length*/18549);
INSERT INTO `music_data` VALUES (/*id*/3015, /*name*/"TOKIMEKI\nエスカレート", /*bpm*/140, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/68119, /*sound_length*/29000);
INSERT INTO `music_data` VALUES (/*id*/3017, /*name*/"Naked Romance", /*bpm*/168, /*composer*/"BNSI（遠山明孝）", /*lyricist*/"BNSI（遠山明孝）", /*sound_offset*/62809, /*sound_length*/25000);
INSERT INTO `music_data` VALUES (/*id*/3018, /*name*/"アップルパイ・\nプリンセス", /*bpm*/178, /*composer*/"BNSI（おおくぼひろし）", /*lyricist*/"BNSI（MC TC・おおくぼひろし）", /*sound_offset*/52636, /*sound_length*/22000);
INSERT INTO `music_data` VALUES (/*id*/3019, /*name*/"Angel Breeze", /*bpm*/150, /*composer*/"百引一", /*lyricist*/"高瀬愛虹", /*sound_offset*/57539, /*sound_length*/27000);
INSERT INTO `music_data` VALUES (/*id*/3023, /*name*/"エヴリデイドリーム", /*bpm*/157, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"BNEI（八城雄太）", /*sound_offset*/66086, /*sound_length*/30000);
INSERT INTO `music_data` VALUES (/*id*/3029, /*name*/"花簪 \nHANAKANZASHI", /*bpm*/125, /*composer*/"ARM（IOSYS）", /*lyricist*/"夕野ヨシミ（IOSYS）", /*sound_offset*/57459, /*sound_length*/35000);
INSERT INTO `music_data` VALUES (/*id*/3031, /*name*/"Bright Blue", /*bpm*/105, /*composer*/"BNSI（kyo）", /*lyricist*/"marhy", /*sound_offset*/75411, /*sound_length*/38000);
INSERT INTO `music_data` VALUES (/*id*/5001, /*name*/"Star!!", /*bpm*/178, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/63785, /*sound_length*/24412);
INSERT INTO `music_data` VALUES (/*id*/5002, /*name*/"夕映えプレゼント", /*bpm*/175, /*composer*/"BNSI（Yoshi）", /*lyricist*/"遠藤フビト", /*sound_offset*/52767, /*sound_length*/27386);
INSERT INTO `music_data` VALUES (/*id*/5003, /*name*/"GOIN'!!!", /*bpm*/178, /*composer*/"宮崎まゆ", /*lyricist*/"森由里子", /*sound_offset*/80700, /*sound_length*/23314);
INSERT INTO `music_data` VALUES (/*id*/5004, /*name*/"できたて \nEvo! Revo! Generation!", /*bpm*/174, /*composer*/"BNSI（kyo）", /*lyricist*/"三重野瞳", /*sound_offset*/45836, /*sound_length*/29579);
INSERT INTO `music_data` VALUES (/*id*/5005, /*name*/"Happy×2 Days", /*bpm*/130, /*composer*/"木村有希", /*lyricist*/"木村有希", /*sound_offset*/56157, /*sound_length*/35061);
INSERT INTO `music_data` VALUES (/*id*/5006, /*name*/"-LEGNE- \n仇なす剣 光の旋律", /*bpm*/189, /*composer*/"隠田遼平", /*lyricist*/"BNSI（東ノ獄彩）", /*sound_offset*/57631, /*sound_length*/22866);
INSERT INTO `music_data` VALUES (/*id*/5007, /*name*/"Memories", /*bpm*/130, /*composer*/"ESTi", /*lyricist*/"貝田由里子", /*sound_offset*/69631, /*sound_length*/14729);
INSERT INTO `music_data` VALUES (/*id*/5008, /*name*/"ØωØver!!", /*bpm*/180, /*composer*/"小野貴光", /*lyricist*/"前川みく（高森奈津美）、多田李衣菜（青木瑠璃子）", /*sound_offset*/56505, /*sound_length*/22483);
INSERT INTO `music_data` VALUES (/*id*/5009, /*name*/"LET'S GO HAPPY!!", /*bpm*/192, /*composer*/"ARM（IOSYS）", /*lyricist*/"夕野ヨシミ（IOSYS）", /*sound_offset*/49784, /*sound_length*/11667);
INSERT INTO `music_data` VALUES (/*id*/5010, /*name*/"Shine!!", /*bpm*/174, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"森由里子", /*sound_offset*/64645, /*sound_length*/24133);
INSERT INTO `music_data` VALUES (/*id*/5011, /*name*/"夢色ハーモニー", /*bpm*/178, /*composer*/"BNSI（内田哲也）", /*lyricist*/"遠藤フビト", /*sound_offset*/61665, /*sound_length*/25000);
INSERT INTO `music_data` VALUES (/*id*/5015, /*name*/"Rockin' Emotion", /*bpm*/177, /*composer*/"小野貴光", /*lyricist*/"磯谷佳江", /*sound_offset*/61564, /*sound_length*/32000);
INSERT INTO `music_data` VALUES (/*id*/5021, /*name*/"Trancing Pulse", /*bpm*/143, /*composer*/"上松範康（Elements Garden）", /*lyricist*/"AJURIKA", /*sound_offset*/76089, /*sound_length*/28000);
INSERT INTO `music_data` VALUES (/*id*/5024, /*name*/"流れ星キセキ", /*bpm*/174, /*composer*/"渡部チェル", /*lyricist*/"⼩⾦井つくも", /*sound_offset*/52397, /*sound_length*/27000);
INSERT INTO `music_data` VALUES (/*id*/5025, /*name*/"M@GIC☆", /*bpm*/178, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由⾥⼦", /*sound_offset*/60948, /*sound_length*/22000);
INSERT INTO `music_data` VALUES (/*id*/9001, /*name*/"とどけ ! アイドル", /*bpm*/180, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/60650, /*sound_length*/24250);
INSERT INTO `music_data` VALUES (/*id*/9002, /*name*/"Snow Wings", /*bpm*/167, /*composer*/"俊龍", /*lyricist*/"俊龍", /*sound_offset*/65785, /*sound_length*/30000);
INSERT INTO `music_data` VALUES (/*id*/9003, /*name*/"Tulip", /*bpm*/154, /*composer*/"石濱翔（MONACA）", /*lyricist*/"森由⾥⼦", /*sound_offset*/52929, /*sound_length*/25000);
