CREATE TABLE 'music_info' ('id' INTEGER NOT NULL, 'discription' TEXT NOT NULL, PRIMARY KEY('id'))
INSERT INTO `music_info` VALUES (/*id*/1001, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS\n\n島村卯月（CV：大橋彩香）\n小日向美穂（CV：津田美波）\n三村かな子（CV：大坪由佳）\n渋谷凛（CV：福原綾香）\n多田李衣菜（CV：青木瑠璃子）\n神崎蘭子（CV：内田真礼）\n本田未央（CV：原紗友里）\n城ヶ崎美嘉（CV：佳村はるか）\n城ヶ崎莉嘉（CV：山本希望）\n\n\n作詞：marhy\n作曲・編曲：BNSI（内田哲也）\nギター：後藤貴徳\nバイオリン：越川歩\nトランペット：鈴木正則\nコーラス：marhy");
INSERT INTO `music_info` VALUES (/*id*/1002, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS!\n\n神崎蘭子（CV：内田真礼）\nアナスタシア（CV：上坂すみれ）\n高垣楓（CV：早見沙織）\n輿水幸子（CV：竹達彩奈）\n渋谷凛（CV：福原綾香）\n\n\n作詞：yura\n作曲：小西裕子\n編曲：原田ナオ\nギター・プログラミング：原田ナオ");
INSERT INTO `music_info` VALUES (/*id*/1003, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS!!\n\n渋谷凛（CV：福原綾香）\n鷺沢文香（CV：M・A・O）\n高垣楓（CV：早見沙織）\n安部菜々（CV：三宅麻理恵）\n緒方智絵里（CV：大空直美）\n島村卯月（CV：大橋彩香）\n本田未央（CV：原紗友里）\n姫川友紀（CV：杜野まこ）\n高森藍子（CV：金子有希）\n\n\n作詞：森由里子\n作曲・編曲：藤末樹");
INSERT INTO `music_info` VALUES (/*id*/1004, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS for BEST5!\n\n渋谷凛（CV：福原綾香）\n安部菜々（CV：三宅麻理恵）\n緒方智絵里（CV：大空直美）\n島村卯月（CV：大橋彩香）\n本田未央（CV：原紗友里）\n\n\n作詞：遠藤フビト\n作曲・編曲：滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1005, /*discription*/"双葉杏（CV：五十嵐裕美）\n前川みく（CV：高森奈津美）\n島村卯月（CV：大橋彩香）\n小日向美穂（CV：津田美波）\n安部菜々（CV：三宅麻理恵）\n\n\n作詞：森由里子\n作曲・編曲：田中秀和（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/1006, /*discription*/"渋谷凛（CV：福原綾香）\n高垣楓（CV：早見沙織）\n神崎蘭子（CV：内田真礼）\n多田李衣菜（CV：青木瑠璃子）\n新田美波（CV：洲崎綾）\n\n\n作詞：森由里子\n作曲・編曲：田中秀和（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/1007, /*discription*/"城ヶ崎莉嘉（CV：山本希望）\n諸星きらり（CV：松嵜麗）\n城ヶ崎美嘉（CV：佳村はるか）\n本田未央（CV：原紗友里）\n赤城みりあ（CV：黒沢ともよ）\n\n\n作詞：森由里子\n作曲・編曲：田中秀和（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/1008, /*discription*/"CINDERELLA PROJECT\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n双葉杏（CV：五十嵐裕美）\n三村かな子（CV：大坪由佳）\n城ヶ崎莉嘉（CV：山本希望）\n神崎蘭子（CV：内田真礼）\n前川みく（CV：高森奈津美）\n諸星きらり（CV：松嵜麗）\n多田李衣菜（CV：青木瑠璃子）\n赤城みりあ（CV：黒沢ともよ）\n新田美波（CV：洲崎綾）\n緒方智絵里（CV：大空直美）\nアナスタシア（CV：上坂すみれ）\n\n\n作詞：森由里子\n作曲・編曲：田中秀和（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/1009, /*discription*/"双葉杏（CV：五十嵐裕美）\n前川みく（CV：高森奈津美）\n島村卯月（CV：大橋彩香）\n小日向美穂（CV：津田美波）\n安部菜々（CV：三宅麻理恵）\n\n\n作詞・作曲・編曲：ササキトモコ");
INSERT INTO `music_info` VALUES (/*id*/1010, /*discription*/"渋谷凛（CV：福原綾香）\n高垣楓（CV：早見沙織）\n神崎蘭子（CV：内田真礼）\n多田李衣菜（CV：青木瑠璃子）\n新田美波（CV：洲崎綾）\n\n\n作詞・作曲・編曲：遠山明孝");
INSERT INTO `music_info` VALUES (/*id*/1011, /*discription*/"城ヶ崎莉嘉（CV：山本希望）\n諸星きらり（CV：松嵜麗）\n城ヶ崎美嘉（CV：佳村はるか）\n本田未央（CV：原紗友里）\n赤城みりあ（CV：黒沢ともよ）\n\n\n作詞：Funta3\n作曲・編曲：Funta7");
INSERT INTO `music_info` VALUES (/*id*/1012, /*discription*/"川島瑞樹（CV：東山奈央）\n白坂小梅（CV：桜咲千依）\nアナスタシア（CV：上坂すみれ）\n神谷奈緒（CV：松井恵理子）\n北条加蓮（CV：渕上舞）\n\n\n作詞：森由里子\n作曲・編曲：高橋浩平");
INSERT INTO `music_info` VALUES (/*id*/1013, /*discription*/"十時愛梨（CV：原田ひとみ）\n日野茜（CV：赤﨑千夏）\n高森藍子（CV：金子有希）\n星輝子（CV：松田颯水）\n堀裕子（CV：鈴木絵理）\n\n\n作詞：坂井⻯⼆\n作曲・編曲：山崎真吾");
INSERT INTO `music_info` VALUES (/*id*/1014, /*discription*/"三村かな子（CV：大坪由佳）\n輿水幸子（CV：竹達彩奈）\n佐久間まゆ（CV：牧野由依）\n緒方智絵里（CV：大空直美）\n小早川紗枝（CV：立花理香）\n\n\n作詞：marhy\n作曲・編曲：BNSI（内田哲也）");
INSERT INTO `music_info` VALUES (/*id*/1015, /*discription*/"三村かな子（CV：大坪由佳）\n輿水幸子（CV：竹達彩奈）\n佐久間まゆ（CV：牧野由依）\n緒方智絵里（CV：大空直美）\n小早川紗枝（CV：立花理香）\n\n\n作詞：森由⾥⼦\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/1016, /*discription*/"川島瑞樹（CV：東山奈央）\n白坂小梅（CV：桜咲千依）\nアナスタシア（CV：上坂すみれ）\n神谷奈緒（CV：松井恵理子）\n北条加蓮（CV：渕上舞）\n\n\n作詞：森由⾥⼦\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/1017, /*discription*/"十時愛梨（CV：原田ひとみ）\n日野茜（CV：赤﨑千夏）\n高森藍子（CV：金子有希）\n星輝子（CV：松田颯水）\n堀裕子（CV：鈴木絵理）\n\n\n作詞：森由⾥⼦\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/1018, /*discription*/"三村かな子（CV：大坪由佳）\n輿水幸子（CV：竹達彩奈）\n佐久間まゆ（CV：牧野由依）\n緒方智絵里（CV：大空直美）\n小早川紗枝（CV：立花理香）\n川島瑞樹（CV：東山奈央）\n白坂小梅（CV：桜咲千依）\nアナスタシア（CV：上坂すみれ）\n神谷奈緒（CV：松井恵理子）\n北条加蓮（CV：渕上舞）\n十時愛梨（CV：原田ひとみ）\n日野茜（CV：赤﨑千夏）\n高森藍子（CV：金子有希）\n星輝子（CV：松田颯水）\n堀裕子（CV：鈴木絵理）\n\n\n作詞：森由⾥⼦\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/1019, /*discription*/"本田未央（CV：原紗友里）\n多田李衣菜（CV：青木瑠璃子）\n渋谷凛（CV：福原綾香）\n安部菜々（CV：三宅麻理恵）\n姫川友紀（CV：杜野まこ）\n\n\n作詞：森由⾥⼦\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/1020, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS!!\n\n塩見周子（CV：ルゥ ティン）\n高垣楓（CV：早見沙織）\n渋谷凛（CV：福原綾香）\n前川みく（CV：高森奈津美）\n一ノ瀬志希（CV：藍原ことみ）\n島村卯月（CV：大橋彩香）\n相葉夕美（CV：木村珠莉）\n城ヶ崎美嘉（CV：佳村はるか）\n向井拓海（CV：原優子）\n\n\n作詞・作曲・編曲：hisakuni");
INSERT INTO `music_info` VALUES (/*id*/1021, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS for BEST5!\n\n塩見周子（CV：ルゥ ティン）\n前川みく（CV：高森奈津美）\n高垣楓（CV：早見沙織）\n相葉夕美（CV：木村珠莉）\n一ノ瀬志希（CV：藍原ことみ）\n\n\n作詞：桜アス恵\n作曲・編曲：滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1022, /*discription*/"中野有香（CV：下地紫野）\n一ノ瀬志希（CV：藍原ことみ）\n五十嵐響子（CV：種﨑敦美）\n櫻井桃華（CV：照井春佳）\n宮本フレデリカ（CV：高野麻美）\n\n\n作詞：Funta3\n作曲・編曲：Funta7");
INSERT INTO `music_info` VALUES (/*id*/1023, /*discription*/"塩見周子（CV：ルゥ ティン）\n橘ありす（CV：佐藤亜美菜）\n鷺沢文香（CV：M・A・O）\n速水奏（CV：飯田友子）\n二宮飛鳥（CV：青木志貴）\n\n\n作詞・作曲：俊龍\n編曲：Sizuk");
INSERT INTO `music_info` VALUES (/*id*/1024, /*discription*/"市原仁奈（CV：久野美咲）\n大槻唯（CV：山下七海）\n片桐早苗（CV：和氣あず未）\n姫川友紀（CV：杜野まこ）\n相葉夕美（CV：木村珠莉）\n\n\n作詞：Apis（TRYTONELABO）\n作曲・編曲：滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1025, /*discription*/"中野有香（CV：下地紫野）\n一ノ瀬志希（CV：藍原ことみ）\n五十嵐響子（CV：種﨑敦美）\n櫻井桃華（CV：照井春佳）\n宮本フレデリカ（CV：高野麻美）\n\n\n作詞・作曲・編曲：AJURIKA");
INSERT INTO `music_info` VALUES (/*id*/1026, /*discription*/"塩見周子（CV：ルゥ ティン）\n橘ありす（CV：佐藤亜美菜）\n鷺沢文香（CV：M・A・O）\n速水奏（CV：飯田友子）\n二宮飛鳥（CV：青木志貴）\n\n\n作詞・作曲・編曲：AJURIKA");
INSERT INTO `music_info` VALUES (/*id*/1027, /*discription*/"市原仁奈（CV：久野美咲）\n大槻唯（CV：山下七海）\n片桐早苗（CV：和氣あず未）\n姫川友紀（CV：杜野まこ）\n相葉夕美（CV：木村珠莉）\n\n\n作詞・作曲・編曲：AJURIKA");
INSERT INTO `music_info` VALUES (/*id*/1028, /*discription*/"中野有香（CV：下地紫野）\n一ノ瀬志希（CV：藍原ことみ）\n五十嵐響子（CV：種﨑敦美）\n櫻井桃華（CV：照井春佳）\n宮本フレデリカ（CV：高野麻美）\n塩見周子（CV：ルゥ ティン）\n橘ありす（CV：佐藤亜美菜）\n鷺沢文香（CV：M・A・O）\n速水奏（CV：飯田友子）\n二宮飛鳥（CV：青木志貴）\n市原仁奈（CV：久野美咲）\n大槻唯（CV：山下七海）\n片桐早苗（CV：和氣あず未）\n姫川友紀（CV：杜野まこ）\n相葉夕美（CV：木村珠莉）\n\n\n作詞・作曲・編曲：AJURIKA");
INSERT INTO `music_info` VALUES (/*id*/1029, /*discription*/"城ヶ崎美嘉（CV：佳村はるか）\n神崎蘭子（CV：内田真礼）\n前川みく（CV：高森奈津美）\n二宮飛鳥（CV：青木志貴）\n一ノ瀬志希（CV：藍原ことみ）\n\n\n作詞：森由里子\n作曲・編曲：田中秀和（MONACA）・\n滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1030, /*discription*/"島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n城ヶ崎美嘉（CV：佳村はるか）\n多田李衣菜（CV：青木瑠璃子）\n\n\n作詞：デレパジ（福原綾香、大橋彩香、\n佳村はるか、原紗友里、青木瑠璃子）\n作曲・編曲：滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1031, /*discription*/"前川みく（CV：高森奈津美）\n依田芳乃（CV：高田憂希）\n森久保乃々（CV：高橋花林）\n佐藤心（CV：花守ゆみり）\n三船美優（CV：原田彩楓）\n\n\n作詞：渡部紫緒\n作曲・編曲：坂部剛");
INSERT INTO `music_info` VALUES (/*id*/1032, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS!!\n\n高垣楓（CV：早見沙織）\n三船美優（CV：原田彩楓）\n森久保乃々（CV：高橋花林）\n島村卯月（CV：大橋彩香）\n安部菜々（CV：三宅麻理恵）\n前川みく（CV：高森奈津美）\n依田芳乃（CV：高田憂希）\n本田未央（CV：原紗友里）\n佐藤心（CV：花守ゆみり）\n\n\n作詞：渡部紫緒\n作曲・編曲：坂部剛");
INSERT INTO `music_info` VALUES (/*id*/1033, /*discription*/"浜口あやめ（CV：田澤茉純）\n道明寺歌鈴（CV：新田ひより）\n脇山珠美（CV：嘉山未紗）\n\n\n作詞：荘野ジュリ\n作曲：坪田修平（TRYTONELABO）\n編曲：宮原慶太");
INSERT INTO `music_info` VALUES (/*id*/1034, /*discription*/"乙倉悠貴（CV：中島由貴）\n安部菜々（CV：三宅麻理恵）\n前川みく（CV：高森奈津美）\n\n\n作詞：磯谷佳江\n作曲：岡野裕次郎（TRYTONELABO）\n編曲：岡野裕次郎（TRYTONELABO）、\nTAKT（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1035, /*discription*/"多田李衣菜（CV：青木瑠璃子）\n中野有香（CV：下地紫野）\n相葉夕美（CV：木村珠莉）\n\n\n作詞：森由里子\n作曲：BNSI（Yoshi）\n編曲：若林タカツグ");
INSERT INTO `music_info` VALUES (/*id*/1036, /*discription*/"関裕美（CV：会沢紗弥）\n藤原肇（CV：鈴木みのり）\n喜多見柚（CV：武田羅梨沙多胡）\n荒木比奈（CV：田辺留依）\n村上巴（CV：花井美春）\n\n\n作詞・作曲・編曲：ESTi");
INSERT INTO `music_info` VALUES (/*id*/1037, /*discription*/"片桐早苗（CV：和氣あず未）\n難波笑美（CV：伊達朱里紗）\n姫川友紀（CV：杜野まこ）\n\n\n作詞：朝倉路\n作曲・編曲：石濱翔（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/1038, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS for BEST5!\n\n島村卯月（CV：大橋彩香）\n高垣楓（CV：早見沙織）\n三船美優（CV：原田彩楓）\n森久保乃々（CV：高橋花林）\n依田芳乃（CV：高田憂希）\n\n\n作詞：荘野ジュリ\n作曲：坪田修平（TRYTONELABO）\n編曲：宮原慶太");
INSERT INTO `music_info` VALUES (/*id*/1039, /*discription*/"高垣楓（CV：早見沙織）\n\n\n作詞：貝田由里子\n作曲・編曲：椎名豪");
INSERT INTO `music_info` VALUES (/*id*/1040, /*discription*/"関裕美（CV：会沢紗弥）\n荒木比奈（CV：田辺留依）\n村上巴（CV：花井美春）\n藤原肇（CV：鈴木みのり）\n喜多見柚（CV：武田羅梨沙多胡）\n\n\n作詞・作曲：藤田麻衣子\n編曲：滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1041, /*discription*/"神谷奈緒（CV：松井恵理子）\n神崎蘭子（CV：内田真礼）\n脇山珠美（CV：嘉山未紗）\n\n\n作詞：ミズノゲンキ\n作曲・編曲：睦月周平");
INSERT INTO `music_info` VALUES (/*id*/1042, /*discription*/"小日向美穂（CV：津田美波）\n城ヶ崎美嘉（CV：佳村はるか）\n速水奏（CV：飯田友子）\n\n\n作詞：森由里子\n作曲・編曲：滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1047, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS!!\n\n高垣楓（CV：早見沙織）\n本田未央（CV：原紗友里）\n藤原肇（CV：鈴木みのり）\n荒木比奈（CV：田辺留依）\n喜多見柚（CV：武田羅梨沙多胡）\n佐久間まゆ（CV：牧野由依）\n村上巴（CV：花井美春）\n関裕美（CV：会沢紗弥）\n緒方智絵里（CV：大空直美）\n\n\n作詞・作曲・編曲：ESTi");
INSERT INTO `music_info` VALUES (/*id*/1048, /*discription*/"THE IDOLM@STER CINDERELLA GIRLS for BEST5!\n\n高垣楓（CV：早見沙織）\n本田未央（CV：原紗友里）\n藤原肇（CV：鈴木みのり）\n荒木比奈（CV：田辺留依）\n喜多見柚（CV：武田羅梨沙多胡）\n\n\n作詞・作曲：藤田麻衣子\n編曲：滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/1901, /*discription*/"千川ちひろ（CV：佐藤利奈）\n\n\n作詞：marhy\n作曲・編曲：BNSI（内田哲也）\nギター：後藤貴徳\nバイオリン：越川歩\nトランペット：鈴木正則\nコーラス：marhy");
INSERT INTO `music_info` VALUES (/*id*/1902, /*discription*/"島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n\n\n作詞：八城雄太\n作曲・編曲：石濱翔（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/1911, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1912, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1913, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1914, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1915, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1916, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1917, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1918, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1919, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1920, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1921, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1922, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1923, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1924, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1925, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1926, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1927, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1928, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1929, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1930, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1931, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1932, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1933, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1934, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1935, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1936, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1937, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1938, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1939, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1940, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1941, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1942, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1943, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1944, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1945, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1946, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/1947, /*discription*/"？");
INSERT INTO `music_info` VALUES (/*id*/2001, /*discription*/"島村卯月（CV：大橋彩香）\n小日向美穂（CV：津田美波）\n五十嵐響子（CV：種﨑敦美）\n\n\n作詞：桜アス恵（TRYTONELABO）\n作曲・編曲：岡野裕次郎（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/2002, /*discription*/"多田李衣菜（CV：青木瑠璃子）\n木村夏樹（CV：安野希世乃）\n\n\n作詞：磯谷佳江\n作曲・編曲：IMAJO");
INSERT INTO `music_info` VALUES (/*id*/2003, /*discription*/"双葉杏（CV：五十嵐裕美）\n諸星きらり（CV：松嵜麗）\n\n\n作詞・作曲・編曲：ヒゲドライバー");
INSERT INTO `music_info` VALUES (/*id*/2004, /*discription*/"本田未央（CV：原紗友里）\n日野茜（CV：赤﨑千夏）\n高森藍子（CV：金子有希）\n\n\n作詞・作曲・編曲：no_my");
INSERT INTO `music_info` VALUES (/*id*/2005, /*discription*/"早坂美玲（CV：朝井彩加）\n森久保乃々（CV：高橋花林）\n星輝子（CV：松田颯水）\n\n\n作詞：ミズノゲンキ\n作曲・編曲：睦月周平");
INSERT INTO `music_info` VALUES (/*id*/2006, /*discription*/"堀裕子（CV：鈴木絵理）\n片桐早苗（CV：和氣あず未）\n及川雫（CV：のぐちゆり）\n\n\n作詞：fumi\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/2007, /*discription*/"中野有香（CV：下地紫野）\n水本ゆかり（CV：藤田茜）\n椎名法子（CV：都丸ちよ）\n\n\n作詞：八城雄太\n作曲・編曲：石濱翔（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/2008, /*discription*/"神崎蘭子（CV：内田真礼）\n二宮飛鳥（CV：青木志貴）\n\n\n作詞：マチゲリータ、烏屋茶房\n作曲・編曲：Powerless");
INSERT INTO `music_info` VALUES (/*id*/2009, /*discription*/"城ヶ崎美嘉（CV：佳村はるか）\n城ヶ崎莉嘉（CV：山本希望）\n\n\n作詞：八城雄太\n作曲：内海孝彰（TRYTONELABO）\n編曲：Lucas（TRYTONELABO）、\n内海孝彰（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/2010, /*discription*/"渋谷凛（CV：福原綾香）\n北条加蓮（CV：渕上舞）\n神谷奈緒（CV：松井恵理子）\n\n\n作詞：奥井雅美\n作曲：上松範康（Elements Garden）\n編曲：藤永龍太郎（Elements Garden）");
INSERT INTO `music_info` VALUES (/*id*/2011, /*discription*/"小早川紗枝（CV：立花理香）\n塩見周子（CV：ルゥ ティン）\n\n\n作詞：野口圭\n作曲・編曲：渡部チェル");
INSERT INTO `music_info` VALUES (/*id*/3001, /*discription*/"島村卯月（CV：大橋彩香）\n\n\n作詞：BNSI（八城雄太）\n作曲・編曲：BNSI（Yoshi）\nコーラス：Mitsu（BNSI）\nギター：後藤貴徳\nバイオリン：Bloom Quartet & Ensemble");
INSERT INTO `music_info` VALUES (/*id*/3002, /*discription*/"渋谷凛（CV：福原綾香）\n\n\n作詞・作曲：BNEI（遠山明孝・八城雄太）\n作曲：BNEI（遠山明孝）\n編曲：関淳二郎\nギター・コーラス：関淳二郎");
INSERT INTO `music_info` VALUES (/*id*/3003, /*discription*/"本田未央（CV：原紗友里）\n\n\n作詞：BNSI（八城雄太）\n作曲・編曲：BNSI（kyo）\nギター：後藤貴徳");
INSERT INTO `music_info` VALUES (/*id*/3004, /*discription*/"緒方智絵里（CV：大空直美）\n\n\n作詞・作曲・編曲：BNSI（トリ音）\nギター：前原孝紀\nバイオリン：伊藤友馬､張大赫\nビオラ：舘泉礼一\nチェロ：田草川亮太");
INSERT INTO `music_info` VALUES (/*id*/3005, /*discription*/"神崎蘭子（CV：内田真礼）\n\n\n作詞：BNSI（東ノ獄彩）\n作曲：BNSI（浩川卿中二）\n編曲：BNSI（浩川卿中二・淵ヶ谷増二）\nギター：後藤貴徳\nベース：黒須克彦\nバイオリン：Bloom Quartet & Ensemble\nピアノ：宇杉健一");
INSERT INTO `music_info` VALUES (/*id*/3006, /*discription*/"諸星きらり（CV：松嵜麗）\n\n\n作詞・作曲・編曲：BNSI（トリ音）\nギター：前原孝紀");
INSERT INTO `music_info` VALUES (/*id*/3007, /*discription*/"双葉杏（CV：五十嵐裕美）\n\n\n作詞：BNEI（八城雄太・佐藤貴文）\n作曲・編曲：BNEI（佐藤貴文）\nコーラス：佐々木恵梨");
INSERT INTO `music_info` VALUES (/*id*/3008, /*discription*/"アナスタシア（CV：上坂すみれ）\n\n\n作詞：貝田由里子\n作曲・編曲：BNSI（小林啓樹）\nギター：関淳二郎\nバイオリン：伊藤友馬､張大赫､粕谷吏､榊渚\nコーラス：貝田由里子");
INSERT INTO `music_info` VALUES (/*id*/3009, /*discription*/"城ヶ崎莉嘉（CV：山本希望）\n\n\n作詞・作曲・編曲：BNEI（佐藤貴文）\nコーラス：佐々木恵梨\nギター：後藤貴徳");
INSERT INTO `music_info` VALUES (/*id*/3010, /*discription*/"前川みく（CV：高森奈津美）\n\n\n作詞・作曲・編曲：BNSI（佐藤貴文）\nコーラス：佐々木恵梨\nトランペット・トロンボーン：湯本淳希\nサックスセッション：渡辺将也\nピアノ：宇杉健一");
INSERT INTO `music_info` VALUES (/*id*/3011, /*discription*/"新田美波（CV：洲崎綾）\n\n\n作詞：古屋真\n作曲・編曲：BNSI（kyo）\nギター：後藤貴徳\nコーラス：kyo（BNSI）");
INSERT INTO `music_info` VALUES (/*id*/3012, /*discription*/"赤城みりあ（CV：黒沢ともよ）\n\n\n作詞：BNSI（MC TC）\n作曲・編曲：BNSI（Taku Inoue）\nコーラス：Shoko（BNSI）、Taku Inoue（BNSI）\nかけ声：ナムコサウンドシスターズ（BNSI）");
INSERT INTO `music_info` VALUES (/*id*/3013, /*discription*/"三村かな子（CV：大坪由佳）\n\n\n作詞：古屋真\n作曲・編曲：BNEI（kyo）\nギター：後藤貴徳");
INSERT INTO `music_info` VALUES (/*id*/3014, /*discription*/"多田李衣菜（CV：青木瑠璃子）\n\n\n作詞・作曲・編曲：BNSI（渡辺量）\nギター・ベース：後藤貴徳");
INSERT INTO `music_info` VALUES (/*id*/3015, /*discription*/"城ヶ崎美嘉（CV：佳村はるか）\n\n\n作詞：marhy\n作曲・編曲：BNSI（内田哲也）");
INSERT INTO `music_info` VALUES (/*id*/3016, /*discription*/"高垣楓（CV：早見沙織）\n\n\n作詞：貝田由里子\n作曲・編曲：BNSI（椎名豪）\nコーラス：貝田由里子\n合唱：森千紗、山口詩織、\n中川澪、牛窪彩乃（ひまわりキッズ）\nバイオリン、ビオラ：真部裕\nチェロ：古川麻生\nピッコロ、オーボエ、ファゴット、\nコントラファゴット：谷本浩一\nピアノ、ベース：ただすけ\nホルン：佐々木歩美");
INSERT INTO `music_info` VALUES (/*id*/3017, /*discription*/"小日向美穂（CV：津田美波）\n\n\n作詞・作曲・編曲：BNSI（遠山明孝）\nギター：後藤貴徳");
INSERT INTO `music_info` VALUES (/*id*/3018, /*discription*/"十時愛梨（CV：原田ひとみ）\n\n\n作詞：BNSI（MC TC・おおくぼひろし）\n作曲・編曲：BNSI（おおくぼひろし）\nギター：豊嶋健太郎（バリウスカプセルズ）\nテナーサックス、バリトンサックス、\nトランペット、トロンボーン：Jesahm（BNSI）\nコーラス：Mitsu（BNSI）\nかけ声：ナムコサウンドシスターズ");
INSERT INTO `music_info` VALUES (/*id*/3019, /*discription*/"川島瑞樹（CV：東山奈央）\n\n\n作詞：高瀬愛虹\n作曲・編曲：百引一\nコーラス：A.m.u.（ZIZZ STUDIO）\nギター：伊藤ヒロム");
INSERT INTO `music_info` VALUES (/*id*/3020, /*discription*/"日野茜（CV：赤﨑千夏）\n\n\n作詞：mft\n作曲：BNSI（Jesahm）\n編曲：日比野裕史\nAll Instruments：日比野裕史");
INSERT INTO `music_info` VALUES (/*id*/3021, /*discription*/"安部菜々（CV：三宅麻理恵）\n\n\n作詞：夕野ヨシミ（IOSYS）\n作曲・編曲：ARM（IOSYS）");
INSERT INTO `music_info` VALUES (/*id*/3022, /*discription*/"輿水幸子（CV：竹達彩奈）\n\n\n作詞：BNSI（Mitsu）\n作曲：BNSI（平井克明）\n編曲：橋本由香利\nキーボード＆プログラミング：橋本由香利\nギター：八橋義幸\nベース：大山徹也");
INSERT INTO `music_info` VALUES (/*id*/3023, /*discription*/"佐久間まゆ（CV：牧野由依）\n\n\n作詞：BNEI（八城雄太）\n作曲・編曲：滝澤俊輔（TRYTONELABO）\nギター＆ベース：岡野裕次郎（TRYTONELABO）\nバイオリン：伊藤友馬、張大赫\nビオラ：舘泉礼一\nチェロ：田草川亮太");
INSERT INTO `music_info` VALUES (/*id*/3024, /*discription*/"白坂小梅（CV：桜咲千依）\n\n\n作詞：BNEI（八城雄太）・BNSI（佐藤貴文）\n作曲・編曲：BNSI（佐藤貴文）\nギター＆ベース：後藤貴徳");
INSERT INTO `music_info` VALUES (/*id*/3025, /*discription*/"高森藍子（CV：金子有希）\n\n\n作詞・作曲：イズミカワソラ\n編曲：今泉洋\nギター：今泉洋");
INSERT INTO `music_info` VALUES (/*id*/3026, /*discription*/"星輝子（CV：松田颯水）\n\n\n作詞：BNSI（LindaAI-CUE）、桜アス恵\n作曲・編曲：BNSI（LindaAI-CUE）\nギター：後藤貴徳\nベース：濱本理央（BNSI）\nコーラス：平野瑶子、ある☆まじろう（BNSI）、\n大槻博信（BNSI）、戸塚秀一（BNSI）、\nLindaAI-CUE（BNSI）");
INSERT INTO `music_info` VALUES (/*id*/3027, /*discription*/"神谷奈緒（CV：松井恵理子）\n\n\n作詞・作曲・編曲：ESTi\nコーラス：Sanch");
INSERT INTO `music_info` VALUES (/*id*/3028, /*discription*/"北条加蓮（CV：渕上舞）\n\n\n作詞：いつきおと\n作曲・編曲：泉典孝\nギター：須藤直也\nピアノ：Mari Ishida\nキーボード＆プログラミング：泉典孝\nバイオリン：伊藤友馬、法常奈緒子\nビオラ：舘泉礼一\nチェロ：原口梓");
INSERT INTO `music_info` VALUES (/*id*/3029, /*discription*/"小早川紗枝（CV：立花理香）\n\n\n作詞：夕野ヨシミ（IOSYS）\n作曲・編曲：ARM（IOSYS）\nギター：ジュクチョー（アドレナ義塾）");
INSERT INTO `music_info` VALUES (/*id*/3030, /*discription*/"堀裕子（CV：鈴木絵理）\n\n\n作詞・作曲・編曲：日暮裕紀\nギター：芥田貴弘");
INSERT INTO `music_info` VALUES (/*id*/3031, /*discription*/"鷺沢文香（CV：M・A・O）\n\n\n作詞：marhy\n作曲・編曲：BNSI（kyo）");
INSERT INTO `music_info` VALUES (/*id*/3032, /*discription*/"姫川友紀（CV：杜野まこ）\n\n\n作詞：Funta3\n作曲・編曲：Funta7\nギター：Funta7\nトランペット：鈴木正則\nトロンボーン：鹿討奏\nテナーサックス：鈴木直樹\nコーラス：仁科薫理");
INSERT INTO `music_info` VALUES (/*id*/3033, /*discription*/"宮本フレデリカ（CV：高野麻美）\n\n\n作詞：BNSI（Mitsu）\n作曲：BNSI（Yoshi）\n編曲：BNSI（Yoshi）、\n平清⼗郎（TRYTONELABO）\nベース：平清⼗郎（TRYTONELABO）\nコーラス：本橋愛美");
INSERT INTO `music_info` VALUES (/*id*/3034, /*discription*/"速水奏（CV：飯田友子）\n\n\n作詞：BNSI（MC TC）\n作曲・編曲：BNSI（Taku Inoue）");
INSERT INTO `music_info` VALUES (/*id*/3035, /*discription*/"市原仁奈（CV：久野美咲）\n\n\n作詞・作曲・編曲：BNSI（佐藤貴文）\nコーラス：ひまわりキッズ");
INSERT INTO `music_info` VALUES (/*id*/3036, /*discription*/"橘ありす（CV：佐藤亜美菜）\n\n\n作詞・作曲：Maiko Fujita\n編曲：川田瑠夏\nキーボード＆プログラミング：川田瑠夏\nギター：宮崎誠\nストリングス：大先生室屋ストリングス");
INSERT INTO `music_info` VALUES (/*id*/3037, /*discription*/"片桐早苗（CV：和氣あず未）\n\n\n作詞：磯谷佳江\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/3038, /*discription*/"一ノ瀬志希（CV：藍原ことみ）\n\n\n作詞・作曲・編曲：ササキトモコ");
INSERT INTO `music_info` VALUES (/*id*/3039, /*discription*/"塩見周子（CV：ルゥ ティン）\n\n\n作詞：夕野ヨシミ（IOSYS）\n作曲・編曲：ARM（IOSYS）\nギター：コバヤシユウヤ（IOSYS）\nベース：john=hive\n尺八：狐夢想（COOL&CREATE）");
INSERT INTO `music_info` VALUES (/*id*/3040, /*discription*/"櫻井桃華（CV：照井春佳）\n\n\n作詞：小金井つくも\n作曲・編曲：渡部チェル\nギター：川瀬智\nオール・インストゥルメンツ＆コーラス\n渡部チェル\nコーラス：くゆり");
INSERT INTO `music_info` VALUES (/*id*/3041, /*discription*/"大槻唯（CV：山下七海）\n\n\n作詞：BNSI（MC TC）\n作曲・編曲：BNSI（Taku Inoue）\nコーラス：Mitsu（BNSI）、Interior M");
INSERT INTO `music_info` VALUES (/*id*/3042, /*discription*/"中野有香（CV：下地紫野）\n\n\n作詞：ミズノゲンキ\n作曲・編曲：睦月周平\nギター＆プログラミング：睦月周平\nストリングス：矢野小百合ストリングス");
INSERT INTO `music_info` VALUES (/*id*/3043, /*discription*/"二宮飛鳥（CV：青木志貴）\n\n\n作詞・作曲・編曲：烏屋茶房\nベース：プロ（ヒゲドライVAN）");
INSERT INTO `music_info` VALUES (/*id*/3044, /*discription*/"相葉夕美（CV：木村珠莉）\n\n\n作詞・作曲・編曲：橋本由香利\nキーボード＆プログラミング：橋本由香利\nギター：宮崎誠\nベース：川島弘光\nドラム：一ノ瀬久");
INSERT INTO `music_info` VALUES (/*id*/3045, /*discription*/"五十嵐響子（CV：種﨑敦美）\n\n\n作詞・作曲：BNSI（柿埜嘉奈子）\n編曲：BNSI（kyo）\nギター：後藤貴徳\nコーラス：美弥（BNSI）");
INSERT INTO `music_info` VALUES (/*id*/3046, /*discription*/"乙倉悠貴（CV：中島由貴）\n\n\n作詞：ミズノゲンキ\n作曲：HONY、Shouya Namai\n編曲：宮崎誠\nインストゥルメンツ：宮崎誠");
INSERT INTO `music_info` VALUES (/*id*/5001, /*discription*/"CINDERELLA PROJECT\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n双葉杏（CV：五十嵐裕美）\n三村かな子（CV：大坪由佳）\n城ヶ崎莉嘉（CV：山本希望）\n神崎蘭子（CV：内田真礼）\n前川みく（CV：高森奈津美）\n諸星きらり（CV：松嵜麗）\n多田李衣菜（CV：青木瑠璃子）\n赤城みりあ（CV：黒沢ともよ）\n新田美波（CV：洲崎綾）\n緒方智絵里（CV：大空直美）\nアナスタシア（CV：上坂すみれ）\n\n\n作詞：森由里子\n作曲・編曲：田中秀和（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/5002, /*discription*/"CINDERELLA PROJECT\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n双葉杏（CV：五十嵐裕美）\n三村かな子（CV：大坪由佳）\n城ヶ崎莉嘉（CV：山本希望）\n神崎蘭子（CV：内田真礼）\n前川みく（CV：高森奈津美）\n諸星きらり（CV：松嵜麗）\n多田李衣菜（CV：青木瑠璃子）\n赤城みりあ（CV：黒沢ともよ）\n新田美波（CV：洲崎綾）\n緒方智絵里（CV：大空直美）\nアナスタシア（CV：上坂すみれ）\n\n\n作詞：遠藤フビト\n作曲：BNSI（Yoshi）\n編曲：BNSI（Yoshi）、\n滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/5003, /*discription*/"CINDERELLA PROJECT\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n双葉杏（CV：五十嵐裕美）\n三村かな子（CV：大坪由佳）\n城ヶ崎莉嘉（CV：山本希望）\n神崎蘭子（CV：内田真礼）\n前川みく（CV：高森奈津美）\n諸星きらり（CV：松嵜麗）\n多田李衣菜（CV：青木瑠璃子）\n赤城みりあ（CV：黒沢ともよ）\n新田美波（CV：洲崎綾）\n緒方智絵里（CV：大空直美）\nアナスタシア（CV：上坂すみれ）\n\n\n作詞：森由里子\n作曲：宮崎まゆ\n編曲：宮崎誠");
INSERT INTO `music_info` VALUES (/*id*/5004, /*discription*/"new generations\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n\n\n作詞：三重野瞳\n作曲・編曲：BNSI（kyo）");
INSERT INTO `music_info` VALUES (/*id*/5005, /*discription*/"CANDY ISLAND\n\n双葉杏（CV：五十嵐裕美）\n三村かな子（CV：大坪由佳）\n緒方智絵里（CV：大空直美）\n\n\n作詞・作曲：木村有希\n編曲：岡野裕次郎（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/5006, /*discription*/"Rosenburg Engel\n\n神崎蘭子（CV：内田真礼）\n\n\n作詞：BNSI（東ノ獄彩）\n作曲：隠田遼平\n編曲：TAKT（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/5007, /*discription*/"LOVE LAIKA\n\n新田美波（CV：洲崎綾）\nアナスタシア（CV：上坂すみれ）\n\n\n作詞：貝田由里子\n作曲：ESTi\n編曲：ESTi､BNSI（kyo）");
INSERT INTO `music_info` VALUES (/*id*/5008, /*discription*/"＊(Asterisk)\n\n前川みく（CV：高森奈津美）\n多田李衣菜（CV：青木瑠璃子）\n\n\n作詞：前川みく（高森奈津美）、\n多田李衣菜（青木瑠璃子）\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/5009, /*discription*/"凸レーション\n\n城ヶ崎莉嘉（CV：山本希望）\n諸星きらり（CV：松嵜麗）\n赤城みりあ（CV：黒沢ともよ）\n\n\n作詞：夕野ヨシミ（IOSYS）\n作曲・編曲：ARM（IOSYS）");
INSERT INTO `music_info` VALUES (/*id*/5010, /*discription*/"CINDERELLA PROJECT\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n双葉杏（CV：五十嵐裕美）\n三村かな子（CV：大坪由佳）\n城ヶ崎莉嘉（CV：山本希望）\n神崎蘭子（CV：内田真礼）\n前川みく（CV：高森奈津美）\n諸星きらり（CV：松嵜麗）\n多田李衣菜（CV：青木瑠璃子）\n赤城みりあ（CV：黒沢ともよ）\n新田美波（CV：洲崎綾）\n緒方智絵里（CV：大空直美）\nアナスタシア（CV：上坂すみれ）\n\n\n作詞：森由里子\n作曲・編曲：滝澤俊輔 （TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/5011, /*discription*/"CINDERELLA PROJECT\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n双葉杏（CV：五十嵐裕美）\n三村かな子（CV：大坪由佳）\n城ヶ崎莉嘉（CV：山本希望）\n神崎蘭子（CV：内田真礼）\n前川みく（CV：高森奈津美）\n諸星きらり（CV：松嵜麗）\n多田李衣菜（CV：青木瑠璃子）\n赤城みりあ（CV：黒沢ともよ）\n新田美波（CV：洲崎綾）\n緒方智絵里（CV：大空直美）\nアナスタシア（CV：上坂すみれ）\n\n\n作詞：遠藤フビト\n作曲：BNSI（内田哲也）\n編曲：滝澤俊輔（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/5013, /*discription*/"凸レーション with 城ヶ崎美嘉\n\n城ヶ崎莉嘉（CV：山本希望）\n諸星きらり（CV：松嵜麗）\n赤城みりあ（CV：黒沢ともよ）\n城ヶ崎美嘉（CV：佳村はるか）\n\n\n作詞：朝倉路\n作曲・編曲：渡部チェル");
INSERT INTO `music_info` VALUES (/*id*/5015, /*discription*/"木村夏樹（CV：安野希世乃）\n\n\n作詞：磯谷佳江\n作曲：小野貴光\n編曲：玉木千尋\nギター：IMAJO（PSYCHIC LOVER）");
INSERT INTO `music_info` VALUES (/*id*/5017, /*discription*/"＊(Asterisk) with なつなな\n\n前川みく（CV：高森奈津美）\n多田李衣菜（CV：青木瑠璃子）\n安部菜々（CV：三宅麻理恵）\n木村夏樹（CV：安野希世乃）\n\n\n作詞：磯谷佳江\n作曲：小野貴光\n編曲：玉木千尋\nギター：IMAJO（PSYCHIC LOVER）");
INSERT INTO `music_info` VALUES (/*id*/5018, /*discription*/"LOVE LAIKA with Rosenburg Engel\n\n新田美波（CV：洲崎綾）\nアナスタシア（CV：上坂すみれ）\n神崎蘭子（CV：内田真礼）\n\n\n作詞：Funta3\n作曲・編曲：Funta7");
INSERT INTO `music_info` VALUES (/*id*/5021, /*discription*/"Triad Primus\n\n渋谷凛（CV：福原綾香）\n神谷奈緒（CV：松井恵理子）\n北条加蓮（CV：渕上舞）\n\n\n作詞：AJURIKA\n作曲：上松範康（Elements Garden）\n編曲：藤永龍太郎（Elements Garden）");
INSERT INTO `music_info` VALUES (/*id*/5024, /*discription*/"new generations\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n\n\n作詞：小金井つくも\n作曲・編曲：渡部チェル");
INSERT INTO `music_info` VALUES (/*id*/5025, /*discription*/"CINDERELLA PROJECT\n\n島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n双葉杏（CV：五十嵐裕美）\n三村かな子（CV：大坪由佳）\n城ヶ崎莉嘉（CV：山本希望）\n神崎蘭子（CV：内田真礼）\n前川みく（CV：高森奈津美）\n諸星きらり（CV：松嵜麗）\n多田李衣菜（CV：青木瑠璃子）\n赤城みりあ（CV：黒沢ともよ）\n新田美波（CV：洲崎綾）\n緒方智絵里（CV：大空直美）\nアナスタシア（CV：上坂すみれ）\n\n\n作詞：森由里子\n作曲・編曲：田中秀和（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/5026, /*discription*/"高垣楓（CV：早見沙織）\n川島瑞樹（CV：東山奈央）\n松永涼（CV：千菅春香）\n速水奏（CV：飯田友子）\n新田美波（CV：洲崎綾）\n\n\n作詞・作曲・編曲：AJURIKA");
INSERT INTO `music_info` VALUES (/*id*/5027, /*discription*/"小日向美穂（CV：津田美波）\n城ヶ崎美嘉（CV：佳村はるか）\n相葉夕美（CV：木村珠莉）\n上条春菜（CV：長島光那）\n赤城みりあ（CV：黒沢ともよ）\n\n\n作詞：木村有希\n作曲：滝澤俊輔（TRYTONELABO）\n編曲：関淳⼆郎");
INSERT INTO `music_info` VALUES (/*id*/5028, /*discription*/"渋谷凛（CV：福原綾香）\n島村卯月（CV：大橋彩香）\n本田未央（CV：原紗友里）\n神谷奈緒（CV：松井恵理子）\n北条加蓮（CV：渕上舞）\n\n\n作詞：森由里子\n作曲・編曲：田中秀和（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/5029, /*discription*/"佐久間まゆ（CV：牧野由依）\n小早川紗枝（CV：立花理香）\n水本ゆかり（CV：藤田茜）\n三村かな子（CV：大坪由佳）\n速水奏（CV：飯田友子）\n\n\n作詞・作曲・編曲：田村歩美");
INSERT INTO `music_info` VALUES (/*id*/5030, /*discription*/"日野茜（CV：赤﨑千夏）\n高森藍子（CV：金子有希）\n及川雫（CV：のぐちゆり）\n脇山珠美（CV：嘉山未紗）\n道明寺歌鈴（CV：新田ひより）\n\n\n作詞・作曲・編曲：ミト");
INSERT INTO `music_info` VALUES (/*id*/5031, /*discription*/"星輝子（CV：松田颯水）\n白坂小梅（CV：桜咲千依）\n輿水幸子（CV：竹達彩奈）\n小早川紗枝（CV：立花理香）\n姫川友紀（CV：杜野まこ）\n\n\n作詞：磯谷佳江\n作曲・編曲：IMAJO（PSYCHIC LOVER）");
INSERT INTO `music_info` VALUES (/*id*/5032, /*discription*/"島村卯月（CV：大橋彩香）\n小日向美穂（CV：津田美波）\n佐久間まゆ（CV：牧野由依）\n櫻井桃華（CV：照井春佳）\n双葉杏（CV：五十嵐裕美）\n\n\n作詞・作曲：ササキトモコ\n編曲：ササキトモコ・蓑部雄崇");
INSERT INTO `music_info` VALUES (/*id*/8001, /*discription*/"前川みく（CV：高森奈津美）\n川島瑞樹（CV：東山奈央）\n白坂小梅（CV：桜咲千依）\n三村かな子（CV：大坪由佳）\n\n\n作詞：Cygames / maimie\n作曲：UEMATSU NOBUO / NARITA TSUTOMU\n補作曲：MAEZAWA HIDENORI（picnic）");
INSERT INTO `music_info` VALUES (/*id*/8002, /*discription*/"緒方智絵里（CV：大空直美）\n多田李衣菜（CV：青木瑠璃子）\n城ヶ崎莉嘉（CV：山本希望）\n\n\n作詞：たかみつようこ\n作曲・編曲：岡部啓一（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/9001, /*discription*/"島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n双葉杏（CV：五十嵐裕美）\n諸星きらり（CV：松嵜麗）\n\n\n作詞：marhy\n作曲・編曲：BNSI（内田哲也）");
INSERT INTO `music_info` VALUES (/*id*/9002, /*discription*/"島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n大槻唯（CV：山下七海）\n上条春菜（CV：長島光那）\n\n\n作詞：俊龍\n作曲：俊龍\n編曲：Sizuk");
INSERT INTO `music_info` VALUES (/*id*/9003, /*discription*/"速水奏（CV：飯田友子）\n塩見周子（CV：ルゥ ティン）\n城ヶ崎美嘉（CV：佳村はるか）\n宮本フレデリカ（CV：高野麻美）\n一ノ瀬志希（CV：藍原ことみ）\n\n\n作詞：森由⾥⼦\n作曲・編曲：石濱翔（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/9004, /*discription*/"佐々木千枝（CV：今井麻夏）\n櫻井桃華（CV：照井春佳）\n市原仁奈（CV：久野美咲）\n龍崎薫（CV：春瀬なつみ）\n赤城みりあ（CV：黒沢ともよ）\n\n\n作詞：宮崎誠\n作曲・編曲：宮崎誠");
INSERT INTO `music_info` VALUES (/*id*/9005, /*discription*/"新田美波（CV：洲崎綾）\n鷺沢文香（CV：M・A・O）\n橘ありす（CV：佐藤亜美菜）\n高森藍子（CV：金子有希）\n相葉夕美（CV：木村珠莉）\n\n\n作詞：朝倉路\n作曲・編曲：渡部チェル");
INSERT INTO `music_info` VALUES (/*id*/9006, /*discription*/"向井拓海（CV：原優子）\n藤本里奈（CV：金子真由美）\n松永涼（CV：千菅春香）\n大和亜季（CV：村中知）\n木村夏樹（CV：安野希世乃）\n\n\n作詞：磯谷佳江\n作曲：小野貴光\n編曲：玉木千尋");
INSERT INTO `music_info` VALUES (/*id*/9007, /*discription*/"佐久間まゆ（CV：牧野由依）\n北条加蓮（CV：渕上舞）\n小日向美穂（CV：津田美波）\n多田李衣菜（CV：青木瑠璃子）\n緒方智絵里（CV：大空直美）\n\n\n作詞：磯谷佳江\n作曲・編曲：BNSI（kyo）");
INSERT INTO `music_info` VALUES (/*id*/9008, /*discription*/"川島瑞樹（CV：東山奈央）\n日野茜（CV：赤﨑千夏）\n堀裕子（CV：鈴木絵理）\n上田鈴帆（CV：春野ななみ）\n難波笑美（CV：伊達朱里紗）\n\n\n作詞：宮崎誠\n作曲・編曲：宮崎誠");
INSERT INTO `music_info` VALUES (/*id*/9009, /*discription*/"城ヶ崎莉嘉（CV：山本希望）\n緒方智絵里（CV：大空直美）\n北条加蓮（CV：渕上舞）\n川島瑞樹（CV：東山奈央）\n大槻唯（CV：山下七海）\n\n\n作詞：八城雄太\n作曲・編曲：石濱翔（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/9010, /*discription*/"高垣楓（CV：早見沙織）\n佐藤心（CV：花守ゆみり）\n三船美優（CV：原田彩楓）\n安部菜々（CV：三宅麻理恵）\n片桐早苗（CV：和氣あず未）\n\n\n作詞：森由里子\n作曲・編曲：TAKT（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/9011, /*discription*/"三村かな子（CV：大坪由佳）\n十時愛梨（CV：原田ひとみ）\n森久保乃々（CV：高橋花林）\n椎名法子（CV：都丸ちよ）\n及川雫（CV：のぐちゆり）\n\n\n作詞・作曲：角本麻衣\n編曲：八木篤史（SUPA LOVE）");
INSERT INTO `music_info` VALUES (/*id*/9012, /*discription*/"依田芳乃（CV：高田憂希）\n小早川紗枝（CV：立花理香）\n道明寺歌鈴（CV：新田ひより）\n浜口あやめ（CV：田澤茉純）\n脇山珠美（CV：嘉山未紗）\n\n\n作詞：桜アス恵（TRYTONELABO）\n作曲：隠田遼平\n編曲：坪田修平（TRYTONELABO）");
INSERT INTO `music_info` VALUES (/*id*/9013, /*discription*/"アナスタシア（CV：上坂すみれ）\n神谷奈緒（CV：松井恵理子）\n中野有香（CV：下地紫野）\n前川みく（CV：高森奈津美）\n星輝子（CV：松田颯水）\n\n\n作詞・作曲・編曲：AJURIKA");
INSERT INTO `music_info` VALUES (/*id*/9014, /*discription*/"五十嵐響子（CV：種﨑敦美）\n乙倉悠貴（CV：中島由貴）\n水本ゆかり（CV：藤田茜）\n諸星きらり（CV：松嵜麗）\n姫川友紀（CV：杜野まこ）\n\n\n作詞：絵伊子\n作曲・編曲：渡部チェル");
INSERT INTO `music_info` VALUES (/*id*/9015, /*discription*/"双葉杏（CV：五十嵐裕美）\n城ヶ崎莉嘉（CV：山本希望）\n二宮飛鳥（CV：青木志貴）\n白坂小梅（CV：桜咲千依）\n早坂美玲（CV：朝井彩加）\n\n\n作詞：ミズノゲンキ\n作曲・編曲：睦月周平");
INSERT INTO `music_info` VALUES (/*id*/9016, /*discription*/"本田未央（CV：原紗友里）\n佐久間まゆ（CV：牧野由依）\n鷺沢文香（CV：M・A・O）\n輿水幸子（CV：竹達彩奈）\n新田美波（CV：洲崎綾）\n\n\n作詞：八城雄太\n作曲・編曲：田中秀和（MONACA）");
INSERT INTO `music_info` VALUES (/*id*/9017, /*discription*/"島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n佐藤心（CV：花守ゆみり）\n三村かな子（CV：大坪由佳）\n\n\n作詞：八城雄太\n作曲：高取ヒデアキ\n編曲：籠島裕昌");
INSERT INTO `music_info` VALUES (/*id*/9901, /*discription*/"佐々木千枝（CV：今井麻夏）\n龍崎薫（CV：春瀬なつみ）\n櫻井桃華（CV：照井春佳）\n赤城みりあ（CV：黒沢ともよ）\n市原仁奈（CV：久野美咲）\n\n\n作詞・作曲：俊龍\n編曲：Sizuk");
INSERT INTO `music_info` VALUES (/*id*/9902, /*discription*/"島村卯月（CV：大橋彩香）\n渋谷凛（CV：福原綾香）\n本田未央（CV：原紗友里）\n赤城みりあ（CV：黒沢ともよ）\n安部菜々（CV：三宅麻理恵）\n\n\n作詞・作曲：俊龍\n編曲：Sizuk");
INSERT INTO `music_info` VALUES (/*id*/90001, /*discription*/"？");
