CREATE TABLE 'music_data' ('id' INTEGER NOT NULL, 'name' TEXT NOT NULL, 'bpm' INTEGER NOT NULL, 'composer' TEXT NOT NULL, 'lyricist' TEXT NOT NULL, 'sound_offset' INTEGER NOT NULL, 'sound_length' INTEGER NOT NULL, 'name_sort' INTEGER NOT NULL, PRIMARY KEY('id'), UNIQUE('name_sort'))
INSERT INTO `music_data` VALUES (/*id*/1001, /*name*/"お願い ! シンデレラ", /*bpm*/175, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/57508, /*sound_length*/20937, /*name_sort*/25);
INSERT INTO `music_data` VALUES (/*id*/1002, /*name*/"輝く世界の魔法", /*bpm*/172, /*composer*/"小西裕子", /*lyricist*/"yura", /*sound_offset*/69274, /*sound_length*/23335, /*name_sort*/29);
INSERT INTO `music_data` VALUES (/*id*/1003, /*name*/"We're the friends!", /*bpm*/178, /*composer*/"藤末樹", /*lyricist*/"森由里子", /*sound_offset*/60794, /*sound_length*/26158, /*name_sort*/14);
INSERT INTO `music_data` VALUES (/*id*/1004, /*name*/"メッセージ", /*bpm*/170, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"遠藤フビト", /*sound_offset*/81901, /*sound_length*/11634, /*name_sort*/114);
INSERT INTO `music_data` VALUES (/*id*/1005, /*name*/"ススメ☆オトメ \n～jewel parade～", /*bpm*/130, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/62779, /*sound_length*/15559, /*name_sort*/59);
INSERT INTO `music_data` VALUES (/*id*/1006, /*name*/"ススメ☆オトメ \n～jewel parade～", /*bpm*/130, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/62779, /*sound_length*/15559, /*name_sort*/60);
INSERT INTO `music_data` VALUES (/*id*/1007, /*name*/"ススメ☆オトメ \n～jewel parade～", /*bpm*/130, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/62779, /*sound_length*/15559, /*name_sort*/61);
INSERT INTO `music_data` VALUES (/*id*/1008, /*name*/"ススメ☆オトメ \n～jewel parade～", /*bpm*/130, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/62779, /*sound_length*/15559, /*name_sort*/62);
INSERT INTO `music_data` VALUES (/*id*/1009, /*name*/"アタシポンコツ\nアンドロイド", /*bpm*/135, /*composer*/"ササキトモコ", /*lyricist*/"ササキトモコ", /*sound_offset*/58721, /*sound_length*/15129, /*name_sort*/4);
INSERT INTO `music_data` VALUES (/*id*/1010, /*name*/"Nation Blue", /*bpm*/157, /*composer*/"遠山明孝", /*lyricist*/"遠山明孝", /*sound_offset*/80190, /*sound_length*/25000, /*name_sort*/93);
INSERT INTO `music_data` VALUES (/*id*/1011, /*name*/"Orange Sapphire", /*bpm*/162, /*composer*/"Funta7", /*lyricist*/"Funta3", /*sound_offset*/81413, /*sound_length*/27000, /*name_sort*/28);
INSERT INTO `music_data` VALUES (/*id*/1012, /*name*/"オルゴールの小箱", /*bpm*/186, /*composer*/"高橋浩平", /*lyricist*/"森由里子", /*sound_offset*/74731, /*sound_length*/29000, /*name_sort*/27);
INSERT INTO `music_data` VALUES (/*id*/1013, /*name*/"絶対特権\n主張しますっ !", /*bpm*/200, /*composer*/"山崎真吾", /*lyricist*/"坂井竜二", /*sound_offset*/46487, /*sound_length*/25000, /*name_sort*/70);
INSERT INTO `music_data` VALUES (/*id*/1014, /*name*/"パステルピンクな恋", /*bpm*/175, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/61676, /*sound_length*/16000, /*name_sort*/100);
INSERT INTO `music_data` VALUES (/*id*/1015, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由里子", /*sound_offset*/63768, /*sound_length*/26000, /*name_sort*/42);
INSERT INTO `music_data` VALUES (/*id*/1016, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由里子", /*sound_offset*/63768, /*sound_length*/26000, /*name_sort*/43);
INSERT INTO `music_data` VALUES (/*id*/1017, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由里子", /*sound_offset*/63768, /*sound_length*/26000, /*name_sort*/44);
INSERT INTO `music_data` VALUES (/*id*/1018, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由里子", /*sound_offset*/63768, /*sound_length*/26000, /*name_sort*/45);
INSERT INTO `music_data` VALUES (/*id*/1019, /*name*/"ゴキゲンParty Night", /*bpm*/175, /*composer*/"小野貴光", /*lyricist*/"森由里子", /*sound_offset*/63768, /*sound_length*/26000, /*name_sort*/46);
INSERT INTO `music_data` VALUES (/*id*/1020, /*name*/"Absolute NIne", /*bpm*/175, /*composer*/"hisakuni", /*lyricist*/"hisakuni", /*sound_offset*/66904, /*sound_length*/39000, /*name_sort*/6);
INSERT INTO `music_data` VALUES (/*id*/1021, /*name*/"つぼみ", /*bpm*/117, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"桜アス恵", /*sound_offset*/59971, /*sound_length*/36000, /*name_sort*/73);
INSERT INTO `music_data` VALUES (/*id*/1022, /*name*/"明日また会えるよね", /*bpm*/145, /*composer*/"Funta7", /*lyricist*/"Funta3", /*sound_offset*/62085, /*sound_length*/25000, /*name_sort*/3);
INSERT INTO `music_data` VALUES (/*id*/1023, /*name*/"咲いてJewel", /*bpm*/176, /*composer*/"俊龍", /*lyricist*/"俊龍", /*sound_offset*/64737, /*sound_length*/27000, /*name_sort*/49);
INSERT INTO `music_data` VALUES (/*id*/1024, /*name*/"きみにいっぱい☆", /*bpm*/132, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"Apis（TRYTONELABO）", /*sound_offset*/47228, /*sound_length*/32000, /*name_sort*/34);
INSERT INTO `music_data` VALUES (/*id*/1025, /*name*/"Near to You", /*bpm*/174, /*composer*/"AJURIKA", /*lyricist*/"AJURIKA", /*sound_offset*/72048, /*sound_length*/21000, /*name_sort*/88);
INSERT INTO `music_data` VALUES (/*id*/1026, /*name*/"Near to You", /*bpm*/174, /*composer*/"AJURIKA", /*lyricist*/"AJURIKA", /*sound_offset*/72048, /*sound_length*/21000, /*name_sort*/89);
INSERT INTO `music_data` VALUES (/*id*/1027, /*name*/"Near to You", /*bpm*/174, /*composer*/"AJURIKA", /*lyricist*/"AJURIKA", /*sound_offset*/72048, /*sound_length*/21000, /*name_sort*/90);
INSERT INTO `music_data` VALUES (/*id*/1028, /*name*/"Near to You", /*bpm*/174, /*composer*/"AJURIKA", /*lyricist*/"AJURIKA", /*sound_offset*/72048, /*sound_length*/21000, /*name_sort*/91);
INSERT INTO `music_data` VALUES (/*id*/1029, /*name*/"EVERMORE", /*bpm*/180, /*composer*/"田中秀和（MONACA）・滝澤俊輔（TRYTONELABO）", /*lyricist*/"森由里子", /*sound_offset*/81375, /*sound_length*/39000, /*name_sort*/18);
INSERT INTO `music_data` VALUES (/*id*/1030, /*name*/"Treasure☆", /*bpm*/128, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"デレパジ", /*sound_offset*/83796, /*sound_length*/34000, /*name_sort*/84);
INSERT INTO `music_data` VALUES (/*id*/1901, /*name*/"お願い ! シンデレラ", /*bpm*/175, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/57508, /*sound_length*/20937, /*name_sort*/132);
INSERT INTO `music_data` VALUES (/*id*/1902, /*name*/"BEYOND \nTHE STARLIGHT", /*bpm*/175, /*composer*/"石濱翔（MONACA）", /*lyricist*/"八城雄太", /*sound_offset*/69811, /*sound_length*/31000, /*name_sort*/134);
INSERT INTO `music_data` VALUES (/*id*/1911, /*name*/"こいかぜ", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/26181, /*name_sort*/1911);
INSERT INTO `music_data` VALUES (/*id*/1912, /*name*/"To my darling...", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/31865, /*name_sort*/1912);
INSERT INTO `music_data` VALUES (/*id*/1913, /*name*/"みんなのきもち", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/27115, /*name_sort*/1913);
INSERT INTO `music_data` VALUES (/*id*/1914, /*name*/"Radio Happy", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/31787, /*name_sort*/1914);
INSERT INTO `music_data` VALUES (/*id*/1915, /*name*/"共鳴世界の存在論", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/23546, /*name_sort*/1915);
INSERT INTO `music_data` VALUES (/*id*/1916, /*name*/"lilac time", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/30067, /*name_sort*/1916);
INSERT INTO `music_data` VALUES (/*id*/1917, /*name*/"追い風Running", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/33806, /*name_sort*/1917);
INSERT INTO `music_data` VALUES (/*id*/1918, /*name*/"One Life", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/30778, /*name_sort*/1918);
INSERT INTO `music_data` VALUES (/*id*/1919, /*name*/"祈りの花", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/36208, /*name_sort*/1919);
INSERT INTO `music_data` VALUES (/*id*/1920, /*name*/"Take me☆Take you", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/34153, /*name_sort*/1920);
INSERT INTO `music_data` VALUES (/*id*/1921, /*name*/"キミのそばでずっと", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/22934, /*name_sort*/1921);
INSERT INTO `music_data` VALUES (/*id*/1922, /*name*/"私色ギフト", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/33822, /*name_sort*/1922);
INSERT INTO `music_data` VALUES (/*id*/1923, /*name*/"Heart Voice", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/29180, /*name_sort*/1923);
INSERT INTO `music_data` VALUES (/*id*/1924, /*name*/"Wonder goes on!!", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/27073, /*name_sort*/1924);
INSERT INTO `music_data` VALUES (/*id*/1925, /*name*/"この空の下", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/32157, /*name_sort*/1925);
INSERT INTO `music_data` VALUES (/*id*/1926, /*name*/"Nebula Sky", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/36938, /*name_sort*/1926);
INSERT INTO `music_data` VALUES (/*id*/1927, /*name*/"心もよう", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/28205, /*name_sort*/1927);
INSERT INTO `music_data` VALUES (/*id*/1928, /*name*/"Nocturne", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/22339, /*name_sort*/1928);
INSERT INTO `music_data` VALUES (/*id*/1929, /*name*/"はにかみdays", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/23317, /*name_sort*/1929);
INSERT INTO `music_data` VALUES (/*id*/1930, /*name*/"AnemoneStar", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/25607, /*name_sort*/1930);
INSERT INTO `music_data` VALUES (/*id*/1931, /*name*/"ステップ !", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/38685, /*name_sort*/1931);
INSERT INTO `music_data` VALUES (/*id*/1932, /*name*/"ニャンと☆スペクタクル", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/21819, /*name_sort*/1932);
INSERT INTO `music_data` VALUES (/*id*/1933, /*name*/"SUPERLOVE☆", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/17454, /*name_sort*/1933);
INSERT INTO `music_data` VALUES (/*id*/1934, /*name*/"NUDIE★", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/36507, /*name_sort*/1934);
INSERT INTO `music_data` VALUES (/*id*/1935, /*name*/"空と風と恋のワルツ", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/33377, /*name_sort*/1935);
INSERT INTO `music_data` VALUES (/*id*/1936, /*name*/"Sparkling Girl", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/25192, /*name_sort*/1936);
INSERT INTO `music_data` VALUES (/*id*/1937, /*name*/"おかしな国のおかし屋さん", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/28159, /*name_sort*/1937);
INSERT INTO `music_data` VALUES (/*id*/1938, /*name*/"Bloody Festa", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/33303, /*name_sort*/1938);
INSERT INTO `music_data` VALUES (/*id*/1939, /*name*/"青空リレーション", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/31599, /*name_sort*/1939);
INSERT INTO `music_data` VALUES (/*id*/1940, /*name*/"PANDEMIC ALONE", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/30610, /*name_sort*/1940);
INSERT INTO `music_data` VALUES (/*id*/1941, /*name*/"にょわにょわーるど☆", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/30052, /*name_sort*/1941);
INSERT INTO `music_data` VALUES (/*id*/1942, /*name*/"cherry*merry*cherry", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/23334, /*name_sort*/1942);
INSERT INTO `music_data` VALUES (/*id*/1943, /*name*/"スローライフ・ファンタジー", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/34297, /*name_sort*/1943);
INSERT INTO `music_data` VALUES (/*id*/1944, /*name*/"Frozen Tears", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/30192, /*name_sort*/1944);
INSERT INTO `music_data` VALUES (/*id*/1945, /*name*/"メルヘン∞メタモルフォーゼ !", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/20460, /*name_sort*/1945);
INSERT INTO `music_data` VALUES (/*id*/1946, /*name*/"薄紅", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/32858, /*name_sort*/1946);
INSERT INTO `music_data` VALUES (/*id*/1947, /*name*/"Yes! Party Time!!", /*bpm*/1, /*composer*/"", /*lyricist*/"", /*sound_offset*/0, /*sound_length*/25044, /*name_sort*/1947);
INSERT INTO `music_data` VALUES (/*id*/2001, /*name*/"ラブレター", /*bpm*/212, /*composer*/"岡野裕次郎（TRYTONELABO）", /*lyricist*/"桜アス恵（TRYTONELABO）", /*sound_offset*/57411, /*sound_length*/26300, /*name_sort*/123);
INSERT INTO `music_data` VALUES (/*id*/2002, /*name*/"Jet to the Future", /*bpm*/180, /*composer*/"IMAJO", /*lyricist*/"磯谷佳江", /*sound_offset*/66710, /*sound_length*/37500, /*name_sort*/52);
INSERT INTO `music_data` VALUES (/*id*/2003, /*name*/"あんきら ! ？狂騒曲", /*bpm*/205, /*composer*/"ヒゲドライバー", /*lyricist*/"ヒゲドライバー", /*sound_offset*/80576, /*sound_length*/27000, /*name_sort*/7);
INSERT INTO `music_data` VALUES (/*id*/2004, /*name*/"情熱\nファンファンファーレ", /*bpm*/180, /*composer*/"no_my", /*lyricist*/"no_my", /*sound_offset*/65829, /*sound_length*/25000, /*name_sort*/56);
INSERT INTO `music_data` VALUES (/*id*/2005, /*name*/"∀NSWER", /*bpm*/178, /*composer*/"睦月周平", /*lyricist*/"ミズノゲンキ", /*sound_offset*/48269, /*sound_length*/28000, /*name_sort*/8);
INSERT INTO `music_data` VALUES (/*id*/2006, /*name*/"モーレツ★\n世直しギルティ !", /*bpm*/162, /*composer*/"小野貴光", /*lyricist*/"fumi", /*sound_offset*/92473, /*sound_length*/29000, /*name_sort*/117);
INSERT INTO `music_data` VALUES (/*id*/2007, /*name*/"Kawaii \nmake MY day!", /*bpm*/133, /*composer*/"石濱翔（MONACA）", /*lyricist*/"八城雄太", /*sound_offset*/67895, /*sound_length*/35000, /*name_sort*/31);
INSERT INTO `music_data` VALUES (/*id*/3001, /*name*/"S(mile)ING!", /*bpm*/178, /*composer*/"BNSI（Yoshi）", /*lyricist*/"BNSI（八城雄太）", /*sound_offset*/52279, /*sound_length*/18828, /*name_sort*/66);
INSERT INTO `music_data` VALUES (/*id*/3002, /*name*/"Never say never", /*bpm*/156, /*composer*/"BNEI（遠山明孝）", /*lyricist*/"BNEI（遠山明孝・八城雄太）", /*sound_offset*/61305, /*sound_length*/11520, /*name_sort*/95);
INSERT INTO `music_data` VALUES (/*id*/3003, /*name*/"ミツボシ☆☆★", /*bpm*/175, /*composer*/"BNSI（kyo）", /*lyricist*/"BNSI（八城雄太）", /*sound_offset*/51889, /*sound_length*/10195, /*name_sort*/111);
INSERT INTO `music_data` VALUES (/*id*/3004, /*name*/"風色メロディ", /*bpm*/90, /*composer*/"BNSI（トリ音）", /*lyricist*/"BNSI（トリ音）", /*sound_offset*/65087, /*sound_length*/20628, /*name_sort*/30);
INSERT INTO `music_data` VALUES (/*id*/3005, /*name*/"華蕾夢ミル狂詩曲 \n～魂ノ導～", /*bpm*/184, /*composer*/"BNSI（浩川卿中二）", /*lyricist*/"BNSI（東ノ獄彩）", /*sound_offset*/60743, /*sound_length*/20425, /*name_sort*/74);
INSERT INTO `music_data` VALUES (/*id*/3006, /*name*/"ましゅまろ☆キッス", /*bpm*/93, /*composer*/"BNSI（トリ音）", /*lyricist*/"BNSI（トリ音）", /*sound_offset*/77276, /*sound_length*/21718, /*name_sort*/110);
INSERT INTO `music_data` VALUES (/*id*/3007, /*name*/"あんずのうた", /*bpm*/195, /*composer*/"佐藤貴文", /*lyricist*/"八城雄太、佐藤貴文", /*sound_offset*/69880, /*sound_length*/24830, /*name_sort*/9);
INSERT INTO `music_data` VALUES (/*id*/3008, /*name*/"You're stars \nshine on me", /*bpm*/96, /*composer*/"BNSI（小林啓樹）", /*lyricist*/"貝田由里子", /*sound_offset*/83553, /*sound_length*/27000, /*name_sort*/118);
INSERT INTO `music_data` VALUES (/*id*/3009, /*name*/"DOKIDOKIリズム", /*bpm*/180, /*composer*/"BNEI（佐藤貴文）", /*lyricist*/"BNEI（佐藤貴文）", /*sound_offset*/54450, /*sound_length*/26189, /*name_sort*/79);
INSERT INTO `music_data` VALUES (/*id*/3010, /*name*/"おねだり \nShall We ～?", /*bpm*/148, /*composer*/"BNSI（佐藤貴文）", /*lyricist*/"BNSI（佐藤貴文）", /*sound_offset*/64586, /*sound_length*/16065, /*name_sort*/26);
INSERT INTO `music_data` VALUES (/*id*/3011, /*name*/"ヴィーナス\nシンドローム", /*bpm*/151, /*composer*/"BNSI（kyo）", /*lyricist*/"古屋真", /*sound_offset*/53134, /*sound_length*/28000, /*name_sort*/15);
INSERT INTO `music_data` VALUES (/*id*/3012, /*name*/"Romantic Now", /*bpm*/170, /*composer*/"BNSI（Taku Inoue）", /*lyricist*/"BNSI（MC TC）", /*sound_offset*/81183, /*sound_length*/26000, /*name_sort*/129);
INSERT INTO `music_data` VALUES (/*id*/3013, /*name*/"ショコラ・ティアラ", /*bpm*/133, /*composer*/"BNEI（kyo）", /*lyricist*/"古屋真", /*sound_offset*/93588, /*sound_length*/16660, /*name_sort*/57);
INSERT INTO `music_data` VALUES (/*id*/3014, /*name*/"Twilight Sky", /*bpm*/176, /*composer*/"BNSI（渡辺量）", /*lyricist*/"BNSI（渡辺量）", /*sound_offset*/59652, /*sound_length*/18549, /*name_sort*/85);
INSERT INTO `music_data` VALUES (/*id*/3015, /*name*/"TOKIMEKI\nエスカレート", /*bpm*/140, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/68119, /*sound_length*/29000, /*name_sort*/80);
INSERT INTO `music_data` VALUES (/*id*/3017, /*name*/"Naked Romance", /*bpm*/168, /*composer*/"BNSI（遠山明孝）", /*lyricist*/"BNSI（遠山明孝）", /*sound_offset*/62809, /*sound_length*/25000, /*name_sort*/92);
INSERT INTO `music_data` VALUES (/*id*/3018, /*name*/"アップルパイ・\nプリンセス", /*bpm*/178, /*composer*/"BNSI（おおくぼひろし）", /*lyricist*/"BNSI（MC TC・おおくぼひろし）", /*sound_offset*/52636, /*sound_length*/22000, /*name_sort*/5);
INSERT INTO `music_data` VALUES (/*id*/3019, /*name*/"Angel Breeze", /*bpm*/150, /*composer*/"百引一", /*lyricist*/"高瀬愛虹", /*sound_offset*/57539, /*sound_length*/27000, /*name_sort*/21);
INSERT INTO `music_data` VALUES (/*id*/3020, /*name*/"熱血乙女A", /*bpm*/174, /*composer*/"BNSI（Jesahm）", /*lyricist*/"mft", /*sound_offset*/64691, /*sound_length*/21000, /*name_sort*/94);
INSERT INTO `music_data` VALUES (/*id*/3021, /*name*/"メルヘンデビュー !", /*bpm*/170, /*composer*/"ARM（IOSYS）", /*lyricist*/"夕野ヨシミ（IOSYS）", /*sound_offset*/73375, /*sound_length*/31000, /*name_sort*/116);
INSERT INTO `music_data` VALUES (/*id*/3022, /*name*/"To my darling...", /*bpm*/127, /*composer*/"BNSI（平井克明）", /*lyricist*/"BNSI（Mitsu）", /*sound_offset*/47182, /*sound_length*/32000, /*name_sort*/78);
INSERT INTO `music_data` VALUES (/*id*/3023, /*name*/"エヴリデイドリーム", /*bpm*/157, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"BNEI（八城雄太）", /*sound_offset*/66086, /*sound_length*/30000, /*name_sort*/17);
INSERT INTO `music_data` VALUES (/*id*/3024, /*name*/"小さな恋の密室事件", /*bpm*/166, /*composer*/"BNSI（佐藤貴文）", /*lyricist*/"BNEI（八城雄太）・BNSI（佐藤貴文）", /*sound_offset*/36050, /*sound_length*/30000, /*name_sort*/71);
INSERT INTO `music_data` VALUES (/*id*/3025, /*name*/"お散歩カメラ", /*bpm*/172, /*composer*/"イズミカワソラ", /*lyricist*/"イズミカワソラ", /*sound_offset*/38893, /*sound_length*/23000, /*name_sort*/24);
INSERT INTO `music_data` VALUES (/*id*/3026, /*name*/"毒茸伝説", /*bpm*/178, /*composer*/"BNSI（LindaAI-CUE）", /*lyricist*/"BNSI（LindaAI-CUE）、桜アス恵", /*sound_offset*/84955, /*sound_length*/21000, /*name_sort*/81);
INSERT INTO `music_data` VALUES (/*id*/3027, /*name*/"2nd SIDE", /*bpm*/133, /*composer*/"ESTi", /*lyricist*/"ESTi", /*sound_offset*/68574, /*sound_length*/32000, /*name_sort*/69);
INSERT INTO `music_data` VALUES (/*id*/3028, /*name*/"薄荷 -ハッカ-", /*bpm*/71, /*composer*/"泉典孝", /*lyricist*/"いつきおと", /*sound_offset*/67572, /*sound_length*/37000, /*name_sort*/101);
INSERT INTO `music_data` VALUES (/*id*/3029, /*name*/"花簪 \nHANAKANZASHI", /*bpm*/125, /*composer*/"ARM（IOSYS）", /*lyricist*/"夕野ヨシミ（IOSYS）", /*sound_offset*/57459, /*sound_length*/35000, /*name_sort*/103);
INSERT INTO `music_data` VALUES (/*id*/3030, /*name*/"ミラクルテレパシー", /*bpm*/173, /*composer*/"日暮裕紀", /*lyricist*/"日暮裕紀", /*sound_offset*/94274, /*sound_length*/36000, /*name_sort*/112);
INSERT INTO `music_data` VALUES (/*id*/3031, /*name*/"Bright Blue", /*bpm*/105, /*composer*/"BNSI（kyo）", /*lyricist*/"marhy", /*sound_offset*/75411, /*sound_length*/38000, /*name_sort*/106);
INSERT INTO `music_data` VALUES (/*id*/3032, /*name*/"気持ちいいよね　\n一等賞 !", /*bpm*/183, /*composer*/"Funta7", /*lyricist*/"Funta3", /*sound_offset*/72899, /*sound_length*/27500, /*name_sort*/35);
INSERT INTO `music_data` VALUES (/*id*/3033, /*name*/"き・ま・ぐ・れ☆\nCafé au lait !", /*bpm*/148, /*composer*/"BNSI（Yoshi）", /*lyricist*/"BNSI（Mitsu）", /*sound_offset*/78599, /*sound_length*/26000, /*name_sort*/32);
INSERT INTO `music_data` VALUES (/*id*/3034, /*name*/"Hotel Moonside", /*bpm*/129, /*composer*/"BNSI（Taku Inoue）", /*lyricist*/"BNSI（MC TC）", /*sound_offset*/72552, /*sound_length*/33000, /*name_sort*/108);
INSERT INTO `music_data` VALUES (/*id*/3035, /*name*/"みんなのきもち", /*bpm*/143, /*composer*/"BNSI（佐藤貴文）", /*lyricist*/"BNSI（佐藤貴文）", /*sound_offset*/80590, /*sound_length*/27300, /*name_sort*/113);
INSERT INTO `music_data` VALUES (/*id*/3036, /*name*/"in fact", /*bpm*/82, /*composer*/"Maiko Fujita", /*lyricist*/"Maiko Fujita", /*sound_offset*/65909, /*sound_length*/28000, /*name_sort*/13);
INSERT INTO `music_data` VALUES (/*id*/3037, /*name*/"Can't Stop!!", /*bpm*/168, /*composer*/"小野貴光", /*lyricist*/"磯谷佳江", /*sound_offset*/42639, /*sound_length*/25000, /*name_sort*/36);
INSERT INTO `music_data` VALUES (/*id*/3038, /*name*/"秘密のトワレ", /*bpm*/143, /*composer*/"ササキトモコ", /*lyricist*/"ササキトモコ", /*sound_offset*/77238, /*sound_length*/28200, /*name_sort*/104);
INSERT INTO `music_data` VALUES (/*id*/3039, /*name*/"青の一番星", /*bpm*/148, /*composer*/"ARM（IOSYS）", /*lyricist*/"夕野ヨシミ（IOSYS）", /*sound_offset*/62613, /*sound_length*/29000, /*name_sort*/2);
INSERT INTO `music_data` VALUES (/*id*/3040, /*name*/"ラヴィアンローズ", /*bpm*/172, /*composer*/"渡部チェル", /*lyricist*/"小金井つくも", /*sound_offset*/83681, /*sound_length*/27000, /*name_sort*/121);
INSERT INTO `music_data` VALUES (/*id*/3041, /*name*/"Radio Happy", /*bpm*/132, /*composer*/"BNSI（Taku Inoue）", /*lyricist*/"BNSI（MC TC）", /*sound_offset*/61834, /*sound_length*/31700, /*name_sort*/127);
INSERT INTO `music_data` VALUES (/*id*/3042, /*name*/"恋色エナジー", /*bpm*/178, /*composer*/"睦月周平", /*lyricist*/"ミズノゲンキ", /*sound_offset*/45791, /*sound_length*/21000, /*name_sort*/38);
INSERT INTO `music_data` VALUES (/*id*/3043, /*name*/"共鳴世界の存在論", /*bpm*/190, /*composer*/"烏屋茶房", /*lyricist*/"烏屋茶房", /*sound_offset*/69373, /*sound_length*/24100, /*name_sort*/37);
INSERT INTO `music_data` VALUES (/*id*/3045, /*name*/"恋のHamburg♪", /*bpm*/170, /*composer*/"BNSI（柿埜嘉奈子）", /*lyricist*/"BNSI（柿埜嘉奈子）", /*sound_offset*/75670, /*sound_length*/29000, /*name_sort*/40);
INSERT INTO `music_data` VALUES (/*id*/5001, /*name*/"Star!!", /*bpm*/178, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/63785, /*sound_length*/24412, /*name_sort*/63);
INSERT INTO `music_data` VALUES (/*id*/5002, /*name*/"夕映えプレゼント", /*bpm*/175, /*composer*/"BNSI（Yoshi）", /*lyricist*/"遠藤フビト", /*sound_offset*/52767, /*sound_length*/27386, /*name_sort*/119);
INSERT INTO `music_data` VALUES (/*id*/5003, /*name*/"GOIN'!!!", /*bpm*/178, /*composer*/"宮崎まゆ", /*lyricist*/"森由里子", /*sound_offset*/80700, /*sound_length*/23314, /*name_sort*/41);
INSERT INTO `music_data` VALUES (/*id*/5004, /*name*/"できたて \nEvo! Revo! Generation!", /*bpm*/174, /*composer*/"BNSI（kyo）", /*lyricist*/"三重野瞳", /*sound_offset*/45836, /*sound_length*/29579, /*name_sort*/77);
INSERT INTO `music_data` VALUES (/*id*/5005, /*name*/"Happy×2 Days", /*bpm*/130, /*composer*/"木村有希", /*lyricist*/"木村有希", /*sound_offset*/56157, /*sound_length*/35061, /*name_sort*/102);
INSERT INTO `music_data` VALUES (/*id*/5006, /*name*/"-LEGNE- \n仇なす剣 光の旋律", /*bpm*/189, /*composer*/"隠田遼平", /*lyricist*/"BNSI（東ノ獄彩）", /*sound_offset*/57631, /*sound_length*/22866, /*name_sort*/19);
INSERT INTO `music_data` VALUES (/*id*/5007, /*name*/"Memories", /*bpm*/130, /*composer*/"ESTi", /*lyricist*/"貝田由里子", /*sound_offset*/69631, /*sound_length*/14729, /*name_sort*/115);
INSERT INTO `music_data` VALUES (/*id*/5008, /*name*/"ØωØver!!", /*bpm*/180, /*composer*/"小野貴光", /*lyricist*/"前川みく（高森奈津美）、多田李衣菜（青木瑠璃子）", /*sound_offset*/56505, /*sound_length*/22483, /*name_sort*/22);
INSERT INTO `music_data` VALUES (/*id*/5009, /*name*/"LET'S GO HAPPY!!", /*bpm*/192, /*composer*/"ARM（IOSYS）", /*lyricist*/"夕野ヨシミ（IOSYS）", /*sound_offset*/49784, /*sound_length*/11667, /*name_sort*/126);
INSERT INTO `music_data` VALUES (/*id*/5010, /*name*/"Shine!!", /*bpm*/174, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"森由里子", /*sound_offset*/64645, /*sound_length*/24133, /*name_sort*/53);
INSERT INTO `music_data` VALUES (/*id*/5011, /*name*/"夢色ハーモニー", /*bpm*/178, /*composer*/"BNSI（内田哲也）", /*lyricist*/"遠藤フビト", /*sound_offset*/61665, /*sound_length*/25000, /*name_sort*/120);
INSERT INTO `music_data` VALUES (/*id*/5015, /*name*/"Rockin' Emotion", /*bpm*/177, /*composer*/"小野貴光", /*lyricist*/"磯谷佳江", /*sound_offset*/61564, /*sound_length*/32000, /*name_sort*/128);
INSERT INTO `music_data` VALUES (/*id*/5018, /*name*/"この空の下", /*bpm*/150, /*composer*/"Funta7", /*lyricist*/"Funta3", /*sound_offset*/60593, /*sound_length*/32000, /*name_sort*/48);
INSERT INTO `music_data` VALUES (/*id*/5021, /*name*/"Trancing Pulse", /*bpm*/143, /*composer*/"上松範康（Elements Garden）", /*lyricist*/"AJURIKA", /*sound_offset*/76089, /*sound_length*/28000, /*name_sort*/83);
INSERT INTO `music_data` VALUES (/*id*/5024, /*name*/"流れ星キセキ", /*bpm*/174, /*composer*/"渡部チェル", /*lyricist*/"小金井つくも", /*sound_offset*/52397, /*sound_length*/27000, /*name_sort*/86);
INSERT INTO `music_data` VALUES (/*id*/5025, /*name*/"M@GIC☆", /*bpm*/178, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/60948, /*sound_length*/22000, /*name_sort*/109);
INSERT INTO `music_data` VALUES (/*id*/5026, /*name*/"Nocturne", /*bpm*/189, /*composer*/"AJURIKA", /*lyricist*/"AJURIKA", /*sound_offset*/43587, /*sound_length*/21900, /*name_sort*/97);
INSERT INTO `music_data` VALUES (/*id*/5027, /*name*/"shabon song", /*bpm*/145, /*composer*/"滝澤俊輔（TRYTONELABO）", /*lyricist*/"木村有希", /*sound_offset*/57097, /*sound_length*/41000, /*name_sort*/54);
INSERT INTO `music_data` VALUES (/*id*/5028, /*name*/"STORY", /*bpm*/148, /*composer*/"田中秀和（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/80670, /*sound_length*/36100, /*name_sort*/64);
INSERT INTO `music_data` VALUES (/*id*/5029, /*name*/"あいくるしい", /*bpm*/84, /*composer*/"田村歩美", /*lyricist*/"田村歩美", /*sound_offset*/75638, /*sound_length*/40000, /*name_sort*/1);
INSERT INTO `music_data` VALUES (/*id*/5030, /*name*/"Flip Flop", /*bpm*/240, /*composer*/"ミト", /*lyricist*/"ミト", /*sound_offset*/67774, /*sound_length*/29000, /*name_sort*/107);
INSERT INTO `music_data` VALUES (/*id*/5031, /*name*/"Lunatic Show", /*bpm*/290, /*composer*/"IMAJO（PSYCHIC LOVER）", /*lyricist*/"磯谷佳江", /*sound_offset*/56099, /*sound_length*/44000, /*name_sort*/125);
INSERT INTO `music_data` VALUES (/*id*/8001, /*name*/"キミとボクのミライ", /*bpm*/178, /*composer*/"UEMATSU NOBUO / NARITA TSUTOMU", /*lyricist*/"Cygames / maimie", /*sound_offset*/66538, /*sound_length*/31000, /*name_sort*/33);
INSERT INTO `music_data` VALUES (/*id*/8002, /*name*/"エンジェル ドリーム", /*bpm*/180, /*composer*/"岡部啓一（MONACA）", /*lyricist*/"たかみつようこ", /*sound_offset*/56812, /*sound_length*/22000, /*name_sort*/20);
INSERT INTO `music_data` VALUES (/*id*/9001, /*name*/"とどけ ! アイドル", /*bpm*/180, /*composer*/"BNSI（内田哲也）", /*lyricist*/"marhy", /*sound_offset*/60650, /*sound_length*/24250, /*name_sort*/82);
INSERT INTO `music_data` VALUES (/*id*/9002, /*name*/"Snow Wings", /*bpm*/167, /*composer*/"俊龍", /*lyricist*/"俊龍", /*sound_offset*/65785, /*sound_length*/30000, /*name_sort*/65);
INSERT INTO `music_data` VALUES (/*id*/9003, /*name*/"Tulip", /*bpm*/154, /*composer*/"石濱翔（MONACA）", /*lyricist*/"森由里子", /*sound_offset*/52929, /*sound_length*/25000, /*name_sort*/72);
INSERT INTO `music_data` VALUES (/*id*/9004, /*name*/"ハイファイ☆デイズ", /*bpm*/191, /*composer*/"宮崎誠", /*lyricist*/"宮崎誠", /*sound_offset*/62341, /*sound_length*/23000, /*name_sort*/99);
INSERT INTO `music_data` VALUES (/*id*/9005, /*name*/"生存本能\nヴァルキュリア", /*bpm*/178, /*composer*/"渡部チェル", /*lyricist*/"朝倉路", /*sound_offset*/63688, /*sound_length*/26500, /*name_sort*/68);
INSERT INTO `music_data` VALUES (/*id*/9006, /*name*/"純情Midnight伝説", /*bpm*/171, /*composer*/"小野貴光", /*lyricist*/"磯谷佳江", /*sound_offset*/60160, /*sound_length*/13000, /*name_sort*/55);
INSERT INTO `music_data` VALUES (/*id*/9007, /*name*/"Love∞Destiny", /*bpm*/115, /*composer*/"BNSI（kyo）", /*lyricist*/"磯谷佳江", /*sound_offset*/51531, /*sound_length*/22000, /*name_sort*/122);
INSERT INTO `music_data` VALUES (/*id*/9008, /*name*/"サマカニ ! !", /*bpm*/185, /*composer*/"宮崎誠", /*lyricist*/"宮崎誠", /*sound_offset*/57000, /*sound_length*/23000, /*name_sort*/51);
INSERT INTO `music_data` VALUES (/*id*/9009, /*name*/"BEYOND \nTHE STARLIGHT", /*bpm*/175, /*composer*/"石濱翔（MONACA）", /*lyricist*/"八城雄太", /*sound_offset*/69811, /*sound_length*/31000, /*name_sort*/105);
INSERT INTO `music_data` VALUES (/*id*/9010, /*name*/"命燃やして恋せよ乙女", /*bpm*/112, /*composer*/"TAKT（TRYTONELABO）", /*lyricist*/"森由里子", /*sound_offset*/82782, /*sound_length*/22000, /*name_sort*/12);
INSERT INTO `music_data` VALUES (/*id*/9011, /*name*/"Sweet Witches' Night \n～6人目はだぁれ～", /*bpm*/152, /*composer*/"角本麻衣", /*lyricist*/"角本麻衣", /*sound_offset*/95950, /*sound_length*/26000, /*name_sort*/58);
INSERT INTO `music_data` VALUES (/*id*/9012, /*name*/"桜の頃", /*bpm*/82, /*composer*/"隠田遼平", /*lyricist*/"桜アス恵（TRYTONELABO）", /*sound_offset*/56900, /*sound_length*/34000, /*name_sort*/50);
INSERT INTO `music_data` VALUES (/*id*/9013, /*name*/"Nothing but You", /*bpm*/167, /*composer*/"AJURIKA", /*lyricist*/"AJURIKA", /*sound_offset*/68328, /*sound_length*/22000, /*name_sort*/87);
INSERT INTO `music_data` VALUES (/*id*/9014, /*name*/"With Love", /*bpm*/154, /*composer*/"渡部チェル", /*lyricist*/"絵伊子", /*sound_offset*/45947, /*sound_length*/28000, /*name_sort*/16);
INSERT INTO `music_data` VALUES (/*id*/9015, /*name*/"リトルリドル", /*bpm*/132, /*composer*/"睦月周平", /*lyricist*/"ミズノゲンキ", /*sound_offset*/63162, /*sound_length*/33000, /*name_sort*/124);
INSERT INTO `music_data` VALUES (/*id*/9901, /*name*/"Yes! Party Time!!", /*bpm*/148, /*composer*/"俊龍", /*lyricist*/"俊龍", /*sound_offset*/54477, /*sound_length*/25000, /*name_sort*/10);
INSERT INTO `music_data` VALUES (/*id*/9902, /*name*/"Yes! Party Time!!", /*bpm*/148, /*composer*/"俊龍", /*lyricist*/"俊龍", /*sound_offset*/54477, /*sound_length*/25000, /*name_sort*/11);
INSERT INTO `music_data` VALUES (/*id*/90001, /*name*/"ぴにゃリクエスト", /*bpm*/1, /*composer*/"?", /*lyricist*/"?", /*sound_offset*/0, /*sound_length*/70000, /*name_sort*/999);
