CREATE TABLE 'party_detail' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'difficulty_type' INTEGER NOT NULL, 'score_rate' INTEGER NOT NULL, 'get_pt_rate' INTEGER NOT NULL, 'scramble_pt_rate' INTEGER NOT NULL, 'failure_penalty_rate' INTEGER NOT NULL, 'single_penalty_rate' INTEGER NOT NULL, 'ceiling_score' INTEGER NOT NULL, 'rare_drop_rate' INTEGER NOT NULL, 'rare_drop_odds' TEXT NOT NULL, 'rare_drop_level' INTEGER NOT NULL, 'drop_s_type' INTEGER NOT NULL, 'drop_s_level' INTEGER NOT NULL, 'drop_a_type' INTEGER NOT NULL, 'drop_b_type' INTEGER NOT NULL, 'drop_c_type' INTEGER NOT NULL, PRIMARY KEY('id'))
INSERT INTO `party_detail` VALUES (/*id*/1, /*event_id*/94001, /*type*/1, /*difficulty_type*/1, /*score_rate*/900, /*get_pt_rate*/900, /*scramble_pt_rate*/700, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/200000, /*rare_drop_rate*/3, /*rare_drop_odds*/"r_cute", /*rare_drop_level*/1, /*drop_s_type*/22, /*drop_s_level*/4, /*drop_a_type*/22, /*drop_b_type*/22, /*drop_c_type*/22);
INSERT INTO `party_detail` VALUES (/*id*/2, /*event_id*/94001, /*type*/1, /*difficulty_type*/2, /*score_rate*/920, /*get_pt_rate*/920, /*scramble_pt_rate*/400, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/400000, /*rare_drop_rate*/5, /*rare_drop_odds*/"r_cute", /*rare_drop_level*/3, /*drop_s_type*/26, /*drop_s_level*/6, /*drop_a_type*/26, /*drop_b_type*/26, /*drop_c_type*/26);
INSERT INTO `party_detail` VALUES (/*id*/3, /*event_id*/94001, /*type*/1, /*difficulty_type*/3, /*score_rate*/920, /*get_pt_rate*/920, /*scramble_pt_rate*/300, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/700000, /*rare_drop_rate*/7, /*rare_drop_odds*/"r_cute", /*rare_drop_level*/5, /*drop_s_type*/30, /*drop_s_level*/11, /*drop_a_type*/30, /*drop_b_type*/30, /*drop_c_type*/30);
INSERT INTO `party_detail` VALUES (/*id*/4, /*event_id*/94001, /*type*/1, /*difficulty_type*/4, /*score_rate*/940, /*get_pt_rate*/940, /*scramble_pt_rate*/200, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/1200000, /*rare_drop_rate*/10, /*rare_drop_odds*/"r_cute", /*rare_drop_level*/10, /*drop_s_type*/34, /*drop_s_level*/14, /*drop_a_type*/34, /*drop_b_type*/34, /*drop_c_type*/34);
INSERT INTO `party_detail` VALUES (/*id*/5, /*event_id*/94001, /*type*/2, /*difficulty_type*/1, /*score_rate*/900, /*get_pt_rate*/900, /*scramble_pt_rate*/700, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/200000, /*rare_drop_rate*/3, /*rare_drop_odds*/"r_cool", /*rare_drop_level*/1, /*drop_s_type*/23, /*drop_s_level*/4, /*drop_a_type*/23, /*drop_b_type*/23, /*drop_c_type*/23);
INSERT INTO `party_detail` VALUES (/*id*/6, /*event_id*/94001, /*type*/2, /*difficulty_type*/2, /*score_rate*/920, /*get_pt_rate*/920, /*scramble_pt_rate*/400, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/400000, /*rare_drop_rate*/5, /*rare_drop_odds*/"r_cool", /*rare_drop_level*/3, /*drop_s_type*/27, /*drop_s_level*/6, /*drop_a_type*/27, /*drop_b_type*/27, /*drop_c_type*/27);
INSERT INTO `party_detail` VALUES (/*id*/7, /*event_id*/94001, /*type*/2, /*difficulty_type*/3, /*score_rate*/920, /*get_pt_rate*/920, /*scramble_pt_rate*/300, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/700000, /*rare_drop_rate*/7, /*rare_drop_odds*/"r_cool", /*rare_drop_level*/5, /*drop_s_type*/31, /*drop_s_level*/11, /*drop_a_type*/31, /*drop_b_type*/31, /*drop_c_type*/31);
INSERT INTO `party_detail` VALUES (/*id*/8, /*event_id*/94001, /*type*/2, /*difficulty_type*/4, /*score_rate*/940, /*get_pt_rate*/940, /*scramble_pt_rate*/200, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/1200000, /*rare_drop_rate*/10, /*rare_drop_odds*/"r_cool", /*rare_drop_level*/10, /*drop_s_type*/35, /*drop_s_level*/14, /*drop_a_type*/35, /*drop_b_type*/35, /*drop_c_type*/35);
INSERT INTO `party_detail` VALUES (/*id*/9, /*event_id*/94001, /*type*/3, /*difficulty_type*/1, /*score_rate*/900, /*get_pt_rate*/900, /*scramble_pt_rate*/700, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/200000, /*rare_drop_rate*/3, /*rare_drop_odds*/"r_passion", /*rare_drop_level*/1, /*drop_s_type*/24, /*drop_s_level*/4, /*drop_a_type*/24, /*drop_b_type*/24, /*drop_c_type*/24);
INSERT INTO `party_detail` VALUES (/*id*/10, /*event_id*/94001, /*type*/3, /*difficulty_type*/2, /*score_rate*/920, /*get_pt_rate*/920, /*scramble_pt_rate*/400, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/400000, /*rare_drop_rate*/5, /*rare_drop_odds*/"r_passion", /*rare_drop_level*/3, /*drop_s_type*/28, /*drop_s_level*/6, /*drop_a_type*/28, /*drop_b_type*/28, /*drop_c_type*/28);
INSERT INTO `party_detail` VALUES (/*id*/11, /*event_id*/94001, /*type*/3, /*difficulty_type*/3, /*score_rate*/920, /*get_pt_rate*/920, /*scramble_pt_rate*/300, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/700000, /*rare_drop_rate*/7, /*rare_drop_odds*/"r_passion", /*rare_drop_level*/5, /*drop_s_type*/32, /*drop_s_level*/11, /*drop_a_type*/32, /*drop_b_type*/32, /*drop_c_type*/32);
INSERT INTO `party_detail` VALUES (/*id*/12, /*event_id*/94001, /*type*/3, /*difficulty_type*/4, /*score_rate*/940, /*get_pt_rate*/940, /*scramble_pt_rate*/200, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/1200000, /*rare_drop_rate*/10, /*rare_drop_odds*/"r_passion", /*rare_drop_level*/10, /*drop_s_type*/36, /*drop_s_level*/14, /*drop_a_type*/36, /*drop_b_type*/36, /*drop_c_type*/36);
INSERT INTO `party_detail` VALUES (/*id*/13, /*event_id*/94001, /*type*/4, /*difficulty_type*/1, /*score_rate*/900, /*get_pt_rate*/900, /*scramble_pt_rate*/700, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/200000, /*rare_drop_rate*/3, /*rare_drop_odds*/"r_all", /*rare_drop_level*/1, /*drop_s_type*/21, /*drop_s_level*/4, /*drop_a_type*/21, /*drop_b_type*/21, /*drop_c_type*/21);
INSERT INTO `party_detail` VALUES (/*id*/14, /*event_id*/94001, /*type*/4, /*difficulty_type*/2, /*score_rate*/920, /*get_pt_rate*/920, /*scramble_pt_rate*/400, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/400000, /*rare_drop_rate*/5, /*rare_drop_odds*/"r_all", /*rare_drop_level*/3, /*drop_s_type*/25, /*drop_s_level*/6, /*drop_a_type*/25, /*drop_b_type*/25, /*drop_c_type*/25);
INSERT INTO `party_detail` VALUES (/*id*/15, /*event_id*/94001, /*type*/4, /*difficulty_type*/3, /*score_rate*/920, /*get_pt_rate*/920, /*scramble_pt_rate*/300, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/700000, /*rare_drop_rate*/7, /*rare_drop_odds*/"r_all", /*rare_drop_level*/5, /*drop_s_type*/29, /*drop_s_level*/11, /*drop_a_type*/29, /*drop_b_type*/29, /*drop_c_type*/29);
INSERT INTO `party_detail` VALUES (/*id*/16, /*event_id*/94001, /*type*/4, /*difficulty_type*/4, /*score_rate*/940, /*get_pt_rate*/940, /*scramble_pt_rate*/200, /*failure_penalty_rate*/900, /*single_penalty_rate*/900, /*ceiling_score*/1200000, /*rare_drop_rate*/10, /*rare_drop_odds*/"r_all", /*rare_drop_level*/10, /*drop_s_type*/33, /*drop_s_level*/14, /*drop_a_type*/33, /*drop_b_type*/33, /*drop_c_type*/33);
