CREATE TABLE 'premium_sc_detail' ('item_id' INTEGER NOT NULL, 'jewel_shop_id' INTEGER NOT NULL, 'use_period_day' INTEGER NOT NULL, 'all_user_use_end_date' TEXT NOT NULL, 'is_cartoon' INTEGER NOT NULL, PRIMARY KEY('item_id'));
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80001, /*jewel_shop_id*/1, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80002, /*jewel_shop_id*/2, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80003, /*jewel_shop_id*/3, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80004, /*jewel_shop_id*/6, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80005, /*jewel_shop_id*/7, /*use_period_day*/8, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80006, /*jewel_shop_id*/7, /*use_period_day*/8, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80007, /*jewel_shop_id*/10, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80008, /*jewel_shop_id*/10, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80009, /*jewel_shop_id*/14, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80010, /*jewel_shop_id*/14, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80011, /*jewel_shop_id*/15, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80012, /*jewel_shop_id*/15, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80013, /*jewel_shop_id*/18, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80014, /*jewel_shop_id*/18, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80015, /*jewel_shop_id*/22, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80016, /*jewel_shop_id*/22, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80017, /*jewel_shop_id*/24, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80018, /*jewel_shop_id*/24, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80019, /*jewel_shop_id*/27, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80020, /*jewel_shop_id*/27, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80021, /*jewel_shop_id*/30, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80022, /*jewel_shop_id*/30, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80023, /*jewel_shop_id*/31, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80024, /*jewel_shop_id*/31, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80025, /*jewel_shop_id*/36, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80026, /*jewel_shop_id*/36, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80027, /*jewel_shop_id*/40, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80028, /*jewel_shop_id*/40, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80029, /*jewel_shop_id*/43, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80030, /*jewel_shop_id*/43, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80031, /*jewel_shop_id*/46, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80032, /*jewel_shop_id*/46, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80033, /*jewel_shop_id*/49, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80034, /*jewel_shop_id*/49, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80035, /*jewel_shop_id*/50, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80036, /*jewel_shop_id*/50, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80037, /*jewel_shop_id*/55, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80038, /*jewel_shop_id*/55, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80039, /*jewel_shop_id*/58, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80040, /*jewel_shop_id*/58, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80041, /*jewel_shop_id*/60, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80042, /*jewel_shop_id*/60, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80043, /*jewel_shop_id*/61, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80044, /*jewel_shop_id*/61, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80045, /*jewel_shop_id*/65, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80046, /*jewel_shop_id*/65, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80047, /*jewel_shop_id*/66, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80048, /*jewel_shop_id*/66, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80049, /*jewel_shop_id*/71, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80050, /*jewel_shop_id*/71, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80051, /*jewel_shop_id*/72, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/1);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80052, /*jewel_shop_id*/74, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80053, /*jewel_shop_id*/74, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80054, /*jewel_shop_id*/75, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80055, /*jewel_shop_id*/75, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80056, /*jewel_shop_id*/78, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/1);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80057, /*jewel_shop_id*/78, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80058, /*jewel_shop_id*/79, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/1);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80059, /*jewel_shop_id*/79, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80060, /*jewel_shop_id*/84, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80061, /*jewel_shop_id*/84, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80062, /*jewel_shop_id*/85, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80063, /*jewel_shop_id*/85, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80064, /*jewel_shop_id*/90, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80065, /*jewel_shop_id*/90, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80066, /*jewel_shop_id*/94, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80067, /*jewel_shop_id*/94, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80068, /*jewel_shop_id*/96, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80069, /*jewel_shop_id*/96, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81001, /*jewel_shop_id*/4, /*use_period_day*/0, /*all_user_use_end_date*/"2017-02-28 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81002, /*jewel_shop_id*/5, /*use_period_day*/0, /*all_user_use_end_date*/"2017-02-28 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81003, /*jewel_shop_id*/8, /*use_period_day*/0, /*all_user_use_end_date*/"2017-11-10 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81004, /*jewel_shop_id*/9, /*use_period_day*/0, /*all_user_use_end_date*/"2017-11-10 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81005, /*jewel_shop_id*/11, /*use_period_day*/0, /*all_user_use_end_date*/"2018-03-06 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81006, /*jewel_shop_id*/12, /*use_period_day*/0, /*all_user_use_end_date*/"2018-03-06 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81007, /*jewel_shop_id*/16, /*use_period_day*/0, /*all_user_use_end_date*/"2018-11-09 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81008, /*jewel_shop_id*/17, /*use_period_day*/0, /*all_user_use_end_date*/"2018-11-09 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81009, /*jewel_shop_id*/19, /*use_period_day*/0, /*all_user_use_end_date*/"2019-03-06 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81010, /*jewel_shop_id*/20, /*use_period_day*/0, /*all_user_use_end_date*/"2019-03-06 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81011, /*jewel_shop_id*/28, /*use_period_day*/0, /*all_user_use_end_date*/"2019-11-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81012, /*jewel_shop_id*/29, /*use_period_day*/0, /*all_user_use_end_date*/"2019-11-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81013, /*jewel_shop_id*/34, /*use_period_day*/0, /*all_user_use_end_date*/"2020-03-06 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81014, /*jewel_shop_id*/33, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81015, /*jewel_shop_id*/35, /*use_period_day*/0, /*all_user_use_end_date*/"2020-03-06 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81016, /*jewel_shop_id*/47, /*use_period_day*/0, /*all_user_use_end_date*/"2020-11-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81017, /*jewel_shop_id*/48, /*use_period_day*/0, /*all_user_use_end_date*/"2020-11-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81018, /*jewel_shop_id*/53, /*use_period_day*/0, /*all_user_use_end_date*/"2021-03-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81019, /*jewel_shop_id*/54, /*use_period_day*/0, /*all_user_use_end_date*/"2021-03-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81020, /*jewel_shop_id*/63, /*use_period_day*/0, /*all_user_use_end_date*/"2021-11-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81021, /*jewel_shop_id*/64, /*use_period_day*/0, /*all_user_use_end_date*/"2021-11-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81022, /*jewel_shop_id*/69, /*use_period_day*/0, /*all_user_use_end_date*/"2022-03-07 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81023, /*jewel_shop_id*/70, /*use_period_day*/0, /*all_user_use_end_date*/"2022-03-07 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81024, /*jewel_shop_id*/80, /*use_period_day*/0, /*all_user_use_end_date*/"2022-11-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81025, /*jewel_shop_id*/81, /*use_period_day*/0, /*all_user_use_end_date*/"2022-11-08 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81026, /*jewel_shop_id*/87, /*use_period_day*/0, /*all_user_use_end_date*/"2023-03-13 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81027, /*jewel_shop_id*/88, /*use_period_day*/0, /*all_user_use_end_date*/"2023-03-13 23:59:59", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84001, /*jewel_shop_id*/25, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84002, /*jewel_shop_id*/26, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84003, /*jewel_shop_id*/32, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84004, /*jewel_shop_id*/44, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84005, /*jewel_shop_id*/45, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84006, /*jewel_shop_id*/52, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84007, /*jewel_shop_id*/59, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84008, /*jewel_shop_id*/62, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84009, /*jewel_shop_id*/67, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84010, /*jewel_shop_id*/73, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84011, /*jewel_shop_id*/77, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84012, /*jewel_shop_id*/86, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84013, /*jewel_shop_id*/93, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84014, /*jewel_shop_id*/101, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/85001, /*jewel_shop_id*/41, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/85002, /*jewel_shop_id*/42, /*use_period_day*/7, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/87001, /*jewel_shop_id*/51, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/87002, /*jewel_shop_id*/68, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/87003, /*jewel_shop_id*/82, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/89001, /*jewel_shop_id*/91, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/89002, /*jewel_shop_id*/97, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/89003, /*jewel_shop_id*/98, /*use_period_day*/0, /*all_user_use_end_date*/"", /*is_cartoon*/0);
CREATE INDEX 'premium_sc_detail_0_jewel_shop_id' on 'premium_sc_detail'('jewel_shop_id');
