CREATE TABLE 'premium_sc_detail' ('item_id' INTEGER NOT NULL, 'jewel_shop_id' INTEGER NOT NULL, 'use_period_day' INTEGER NOT NULL, 'all_user_use_end_date' TEXT NOT NULL, PRIMARY KEY('item_id'));
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80001, /*jewel_shop_id*/1, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80002, /*jewel_shop_id*/2, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80003, /*jewel_shop_id*/3, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80004, /*jewel_shop_id*/6, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80005, /*jewel_shop_id*/7, /*use_period_day*/8, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80006, /*jewel_shop_id*/7, /*use_period_day*/8, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80007, /*jewel_shop_id*/10, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80008, /*jewel_shop_id*/10, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80009, /*jewel_shop_id*/14, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80010, /*jewel_shop_id*/14, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80011, /*jewel_shop_id*/15, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80012, /*jewel_shop_id*/15, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80013, /*jewel_shop_id*/18, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80014, /*jewel_shop_id*/18, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80015, /*jewel_shop_id*/22, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80016, /*jewel_shop_id*/22, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80017, /*jewel_shop_id*/24, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80018, /*jewel_shop_id*/24, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80019, /*jewel_shop_id*/27, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80020, /*jewel_shop_id*/27, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80021, /*jewel_shop_id*/30, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80022, /*jewel_shop_id*/30, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80023, /*jewel_shop_id*/31, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80024, /*jewel_shop_id*/31, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80025, /*jewel_shop_id*/36, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80026, /*jewel_shop_id*/36, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80027, /*jewel_shop_id*/40, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80028, /*jewel_shop_id*/40, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80029, /*jewel_shop_id*/43, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80030, /*jewel_shop_id*/43, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80031, /*jewel_shop_id*/46, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80032, /*jewel_shop_id*/46, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80033, /*jewel_shop_id*/49, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80034, /*jewel_shop_id*/49, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80035, /*jewel_shop_id*/50, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/80036, /*jewel_shop_id*/50, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81001, /*jewel_shop_id*/4, /*use_period_day*/0, /*all_user_use_end_date*/"2017-02-28 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81002, /*jewel_shop_id*/5, /*use_period_day*/0, /*all_user_use_end_date*/"2017-02-28 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81003, /*jewel_shop_id*/8, /*use_period_day*/0, /*all_user_use_end_date*/"2017-11-10 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81004, /*jewel_shop_id*/9, /*use_period_day*/0, /*all_user_use_end_date*/"2017-11-10 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81005, /*jewel_shop_id*/11, /*use_period_day*/0, /*all_user_use_end_date*/"2018-03-06 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81006, /*jewel_shop_id*/12, /*use_period_day*/0, /*all_user_use_end_date*/"2018-03-06 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81007, /*jewel_shop_id*/16, /*use_period_day*/0, /*all_user_use_end_date*/"2018-11-09 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81008, /*jewel_shop_id*/17, /*use_period_day*/0, /*all_user_use_end_date*/"2018-11-09 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81009, /*jewel_shop_id*/19, /*use_period_day*/0, /*all_user_use_end_date*/"2019-03-06 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81010, /*jewel_shop_id*/20, /*use_period_day*/0, /*all_user_use_end_date*/"2019-03-06 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81011, /*jewel_shop_id*/28, /*use_period_day*/0, /*all_user_use_end_date*/"2019-11-08 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81012, /*jewel_shop_id*/29, /*use_period_day*/0, /*all_user_use_end_date*/"2019-11-08 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81013, /*jewel_shop_id*/34, /*use_period_day*/0, /*all_user_use_end_date*/"2020-03-06 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81014, /*jewel_shop_id*/33, /*use_period_day*/0, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81015, /*jewel_shop_id*/35, /*use_period_day*/0, /*all_user_use_end_date*/"2020-03-06 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81016, /*jewel_shop_id*/47, /*use_period_day*/0, /*all_user_use_end_date*/"2020-11-08 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/81017, /*jewel_shop_id*/48, /*use_period_day*/0, /*all_user_use_end_date*/"2020-11-08 23:59:59");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84001, /*jewel_shop_id*/25, /*use_period_day*/0, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84002, /*jewel_shop_id*/26, /*use_period_day*/0, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84003, /*jewel_shop_id*/32, /*use_period_day*/0, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84004, /*jewel_shop_id*/44, /*use_period_day*/0, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84005, /*jewel_shop_id*/45, /*use_period_day*/0, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/84006, /*jewel_shop_id*/52, /*use_period_day*/0, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/85001, /*jewel_shop_id*/41, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/85002, /*jewel_shop_id*/42, /*use_period_day*/7, /*all_user_use_end_date*/"");
INSERT INTO `premium_sc_detail` VALUES (/*item_id*/87001, /*jewel_shop_id*/51, /*use_period_day*/0, /*all_user_use_end_date*/"");
CREATE INDEX 'premium_sc_detail_0_jewel_shop_id' on 'premium_sc_detail'('jewel_shop_id');
