CREATE TABLE 'questionnaire_data' ('questionnaire_id' INTEGER NOT NULL, 'name' TEXT NOT NULL, 'questionnaire_type' INTEGER NOT NULL, 'questionnaire_start' TEXT NOT NULL, 'second_half_start' TEXT NOT NULL, 'questionnaire_end' TEXT NOT NULL, 'calc_start' TEXT NOT NULL, 'result_start' TEXT NOT NULL, 'result_end' TEXT NOT NULL, 'item_id' TEXT , 'reward_type' TEXT , 'reward_id' TEXT , 'reward_value' TEXT , 'reward_message' INTEGER NOT NULL, 'open_type_1' INTEGER NOT NULL, 'open_id_1' INTEGER NOT NULL, 'open_value_1' INTEGER NOT NULL, 'open_type_2' INTEGER NOT NULL, 'open_id_2' INTEGER NOT NULL, 'open_value_2' INTEGER NOT NULL, 'open_type_3' INTEGER NOT NULL, 'open_id_3' INTEGER NOT NULL, 'open_value_3' INTEGER NOT NULL, 'limit_type_1' INTEGER NOT NULL, 'limit_value_1' INTEGER NOT NULL, 'limit_type_2' INTEGER NOT NULL, 'limit_value_2' INTEGER NOT NULL, 'text_top_title' TEXT NOT NULL, 'text_top_subtitle' TEXT , 'text_top_btn_total' TEXT NOT NULL, 'text_survey_title' TEXT NOT NULL, 'text_survey_subtitle' TEXT , 'text_survey_title_total' TEXT NOT NULL, 'text_survey_subtitle_total' TEXT , 'text_result_title' TEXT NOT NULL, 'text_result_subtitle' TEXT , 'text_all_vote' TEXT NOT NULL, 'text_survey_info' TEXT NOT NULL, 'text_survey_detail' TEXT NOT NULL, 'text_survey_number' TEXT NOT NULL, 'text_survey_null' TEXT NOT NULL, 'text_twitter_main' TEXT NOT NULL, 'text_top_resulttime' TEXT , PRIMARY KEY('questionnaire_id'));
INSERT INTO `questionnaire_data` VALUES (/*questionnaire_id*/1, /*name*/"セレクトショップアナザーサイズリクエスト", /*questionnaire_type*/102, /*questionnaire_start*/"2023-02-14 15:00:00", /*second_half_start*/"2023-02-14 15:00:00", /*questionnaire_end*/"2023-02-21 23:59:59", /*calc_start*/"2023-02-22 00:00:00", /*result_start*/"2023-02-24 22:00:00", /*result_end*/"2023-03-02 23:59:59", /*item_id*/8501, /*reward_type*/5, /*reward_id*/1005, /*reward_value*/20, /*reward_message*/20092, /*open_type_1*/101, /*open_id_1*/0, /*open_value_1*/20, /*open_type_2*/102, /*open_id_2*/0, /*open_value_2*/2, /*open_type_3*/0, /*open_id_3*/0, /*open_value_3*/0, /*limit_type_1*/0, /*limit_value_1*/0, /*limit_type_2*/0, /*limit_value_2*/0, /*text_top_title*/"セレクトショップアナザーサイズリクエスト", /*text_top_subtitle*/"", /*text_top_btn_total*/"衣装確認", /*text_survey_title*/"投票衣装選択", /*text_survey_subtitle*/"タップで詳細を確認できます", /*text_survey_title_total*/"投票衣装確認", /*text_survey_subtitle_total*/"タップで詳細を確認できます", /*text_result_title*/"セレクトショップアナザーサイズリクエスト", /*text_result_subtitle*/"", /*text_all_vote*/"投票", /*text_survey_info*/"衣装情報", /*text_survey_detail*/"衣装デザインは一部変更になる場合があります。", /*text_survey_number*/"票", /*text_survey_null*/"対象の衣装がありません", /*text_twitter_main*/"全てのアイドルが着られるように追加オーダー ! 
セレクトショップ #アナザーサイズリクエスト 開催中!!
{0}にリクエスト投票したよ!!
#デレステ", /*text_top_resulttime*/"");
INSERT INTO `questionnaire_data` VALUES (/*questionnaire_id*/2, /*name*/"カウントダウンLIVE ドレスショーケース", /*questionnaire_type*/101, /*questionnaire_start*/"2023-04-29 15:00:00", /*second_half_start*/"2023-04-29 15:00:00", /*questionnaire_end*/"2023-05-06 23:59:59", /*calc_start*/"2023-05-07 00:00:00", /*result_start*/"2023-05-11 15:00:00", /*result_end*/"2023-05-17 23:59:59", /*item_id*/8502, /*reward_type*/4, /*reward_id*/0, /*reward_value*/50, /*reward_message*/20092, /*open_type_1*/101, /*open_id_1*/0, /*open_value_1*/20, /*open_type_2*/102, /*open_id_2*/0, /*open_value_2*/2, /*open_type_3*/0, /*open_id_3*/0, /*open_value_3*/0, /*limit_type_1*/0, /*limit_value_1*/0, /*limit_type_2*/0, /*limit_value_2*/0, /*text_top_title*/"カウントダウンLIVE ドレスショーケース", /*text_top_subtitle*/"", /*text_top_btn_total*/"ドレス確認", /*text_survey_title*/"投票ドレス選択", /*text_survey_subtitle*/"タップで詳細を確認できます", /*text_survey_title_total*/"投票ドレス確認", /*text_survey_subtitle_total*/"タップで詳細を確認できます", /*text_result_title*/"カウントダウンLIVE ドレスショーケース", /*text_result_subtitle*/"", /*text_all_vote*/"投票", /*text_survey_info*/"ドレス詳細", /*text_survey_detail*/"ドレスデザインは一部変更になる場合があります。", /*text_survey_number*/"票", /*text_survey_null*/"対象のドレスがありません", /*text_twitter_main*/"2023年年末にゲーム内で実施予定の「カウントダウンLIVE」で獲得できるドレスを投票で決定！
「カウントダウンLIVE #ドレスショーケース 」開催中!!
{0}に投票したよ!!
#デレステ", /*text_top_resulttime*/"");
