CREATE TABLE 'rail_area' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'name' TEXT NOT NULL, 'group_id' INTEGER NOT NULL, 'rap_id' INTEGER NOT NULL, 'total_circle' INTEGER NOT NULL, 'release_area_id' INTEGER NOT NULL, 'loop_flag' INTEGER NOT NULL, 'bg_id' INTEGER NOT NULL, 'map_type_1' INTEGER NOT NULL, 'map_value_1' INTEGER NOT NULL, 'map_type_2' INTEGER NOT NULL, 'map_value_2' INTEGER NOT NULL, 'target_type_1' INTEGER NOT NULL, 'target_value_1' INTEGER NOT NULL, 'target_type_2' INTEGER NOT NULL, 'target_value_2' INTEGER NOT NULL, 'target_type_3' INTEGER NOT NULL, 'target_value_3' INTEGER NOT NULL, 'target_obj_id' INTEGER NOT NULL, 'step_bonus' INTEGER NOT NULL, 'chara_id' INTEGER NOT NULL, 'chara_bonus' INTEGER NOT NULL, PRIMARY KEY('id'))
INSERT INTO `rail_area` VALUES (/*id*/1, /*event_id*/6001, /*name*/"首藤葵・MAP1", /*group_id*/1, /*rap_id*/1, /*total_circle*/10, /*release_area_id*/7, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/1, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/1, /*target_value_1*/100000, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/30001, /*step_bonus*/0, /*chara_id*/295, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/2, /*event_id*/6001, /*name*/"首藤葵・MAP2", /*group_id*/1, /*rap_id*/2, /*total_circle*/30, /*release_area_id*/0, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/2, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/1, /*target_value_1*/170000, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/30001, /*step_bonus*/50, /*chara_id*/295, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/3, /*event_id*/6001, /*name*/"首藤葵・MAP3", /*group_id*/1, /*rap_id*/3, /*total_circle*/30, /*release_area_id*/0, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/3, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/4, /*target_value_1*/250, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/30002, /*step_bonus*/50, /*chara_id*/295, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/4, /*event_id*/6001, /*name*/"首藤葵・MAP4", /*group_id*/1, /*rap_id*/4, /*total_circle*/30, /*release_area_id*/0, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/4, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/2, /*target_value_1*/300, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/30003, /*step_bonus*/50, /*chara_id*/295, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/5, /*event_id*/6001, /*name*/"首藤葵・MAP5", /*group_id*/1, /*rap_id*/5, /*total_circle*/40, /*release_area_id*/0, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/5, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/6, /*target_value_1*/26, /*target_type_2*/9, /*target_value_2*/1, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/1, /*step_bonus*/50, /*chara_id*/295, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/6, /*event_id*/6001, /*name*/"首藤葵・MAP Ex", /*group_id*/1, /*rap_id*/6, /*total_circle*/50, /*release_area_id*/0, /*loop_flag*/1, /*bg_id*/5990, /*map_type_1*/1, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/0, /*target_value_1*/0, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/0, /*step_bonus*/150, /*chara_id*/295, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/7, /*event_id*/6001, /*name*/"遊佐こずえ・MAP1", /*group_id*/2, /*rap_id*/1, /*total_circle*/40, /*release_area_id*/0, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/2, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/1, /*target_value_1*/200000, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/30001, /*step_bonus*/50, /*chara_id*/124, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/8, /*event_id*/6001, /*name*/"遊佐こずえ・MAP2", /*group_id*/2, /*rap_id*/2, /*total_circle*/40, /*release_area_id*/0, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/3, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/4, /*target_value_1*/300, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/30002, /*step_bonus*/50, /*chara_id*/124, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/9, /*event_id*/6001, /*name*/"遊佐こずえ・MAP3", /*group_id*/2, /*rap_id*/3, /*total_circle*/40, /*release_area_id*/0, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/4, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/2, /*target_value_1*/400, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/30003, /*step_bonus*/50, /*chara_id*/124, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/10, /*event_id*/6001, /*name*/"遊佐こずえ・MAP4", /*group_id*/2, /*rap_id*/4, /*total_circle*/50, /*release_area_id*/0, /*loop_flag*/0, /*bg_id*/5990, /*map_type_1*/5, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/6, /*target_value_1*/28, /*target_type_2*/9, /*target_value_2*/1, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/1, /*step_bonus*/50, /*chara_id*/124, /*chara_bonus*/120);
INSERT INTO `rail_area` VALUES (/*id*/11, /*event_id*/6001, /*name*/"遊佐こずえ・MAP Ex", /*group_id*/2, /*rap_id*/5, /*total_circle*/100, /*release_area_id*/0, /*loop_flag*/1, /*bg_id*/5990, /*map_type_1*/1, /*map_value_1*/0, /*map_type_2*/0, /*map_value_2*/0, /*target_type_1*/0, /*target_value_1*/0, /*target_type_2*/0, /*target_value_2*/0, /*target_type_3*/0, /*target_value_3*/0, /*target_obj_id*/0, /*step_bonus*/150, /*chara_id*/124, /*chara_bonus*/120);
