CREATE TABLE 'rail_condition_text' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'use_type' INTEGER NOT NULL, 'condition_type' INTEGER NOT NULL, 'description' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `rail_condition_text` VALUES (/*id*/1, /*event_id*/6027, /*use_type*/1, /*condition_type*/1, /*description*/"ユニットのスターランク合計値が高いほど、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/2, /*event_id*/6027, /*use_type*/1, /*condition_type*/2, /*description*/"ユニットのボーカル合計値が高いほど、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/3, /*event_id*/6027, /*use_type*/1, /*condition_type*/3, /*description*/"ユニットのダンス合計値が高いほど、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/4, /*event_id*/6027, /*use_type*/1, /*condition_type*/4, /*description*/"ユニットのビジュアル合計値が高いほど、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/5, /*event_id*/6027, /*use_type*/1, /*condition_type*/5, /*description*/"ユニットの全アピール合計値が高いほど、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/6, /*event_id*/6027, /*use_type*/2, /*condition_type*/1, /*description*/"合計スコア{0}以上");
INSERT INTO `rail_condition_text` VALUES (/*id*/7, /*event_id*/6027, /*use_type*/2, /*condition_type*/2, /*description*/"MAXコンボ合計数{0}以上");
INSERT INTO `rail_condition_text` VALUES (/*id*/8, /*event_id*/6027, /*use_type*/2, /*condition_type*/3, /*description*/"BAD、missが合計{0}回以内");
INSERT INTO `rail_condition_text` VALUES (/*id*/9, /*event_id*/6027, /*use_type*/2, /*condition_type*/4, /*description*/"PERFECT、GREATが合計{0}回以上");
INSERT INTO `rail_condition_text` VALUES (/*id*/10, /*event_id*/6027, /*use_type*/2, /*condition_type*/5, /*description*/"残ライフ{0}％以上で全曲クリア");
INSERT INTO `rail_condition_text` VALUES (/*id*/11, /*event_id*/6027, /*use_type*/2, /*condition_type*/6, /*description*/"合計楽曲Lv{0}以上");
INSERT INTO `rail_condition_text` VALUES (/*id*/12, /*event_id*/6027, /*use_type*/2, /*condition_type*/7, /*description*/"合計リズムアイコン数{0}以上");
INSERT INTO `rail_condition_text` VALUES (/*id*/13, /*event_id*/6027, /*use_type*/2, /*condition_type*/8, /*description*/"合計リズムアイコン数{0}以下");
INSERT INTO `rail_condition_text` VALUES (/*id*/14, /*event_id*/6027, /*use_type*/2, /*condition_type*/9, /*description*/"フルコンボを{0}回以上");
INSERT INTO `rail_condition_text` VALUES (/*id*/15, /*event_id*/6027, /*use_type*/3, /*condition_type*/1, /*description*/"キュートタイプの楽曲をプレイで、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/16, /*event_id*/6027, /*use_type*/3, /*condition_type*/2, /*description*/"クールタイプの楽曲をプレイで、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/17, /*event_id*/6027, /*use_type*/3, /*condition_type*/3, /*description*/"パッションタイプの楽曲をプレイで、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/18, /*event_id*/6027, /*use_type*/3, /*condition_type*/4, /*description*/"全タイプの楽曲をプレイで、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/19, /*event_id*/6027, /*use_type*/3, /*condition_type*/5, /*description*/"どの楽曲をプレイしても、MAP進行数がアップ");
INSERT INTO `rail_condition_text` VALUES (/*id*/20, /*event_id*/6027, /*use_type*/4, /*condition_type*/0, /*description*/"「{0}」を編成してLIVEクリアで、MAP進行数がアップ");
CREATE INDEX 'rail_condition_text_0_event_id' on 'rail_condition_text'('event_id');
