CREATE TABLE 'rail_card_comment' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'comment_id' INTEGER NOT NULL, 'use_type' INTEGER NOT NULL, 'index' INTEGER NOT NULL, 'description' TEXT NOT NULL, 'insert_word_type' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `rail_card_comment` VALUES (/*id*/1, /*event_id*/6002, /*comment_id*/100529, /*use_type*/0, /*index*/1, /*description*/"事件が私を呼んでいます ! さぁ、急ぎましょう !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/2, /*event_id*/6002, /*comment_id*/100529, /*use_type*/0, /*index*/2, /*description*/"どんな小さな証拠も都の目は見逃しませんよ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/3, /*event_id*/6002, /*comment_id*/100529, /*use_type*/0, /*index*/3, /*description*/"この先から匂いますね…ええ、謎の匂いです !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/4, /*event_id*/6002, /*comment_id*/100529, /*use_type*/1, /*index*/1, /*description*/"アイドル探偵の推理パートは可愛らしい曲で決まりですね !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/5, /*event_id*/6002, /*comment_id*/100529, /*use_type*/2, /*index*/1, /*description*/"クールな曲で、思考を一度冷やしてみましょう !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/6, /*event_id*/6002, /*comment_id*/100529, /*use_type*/3, /*index*/1, /*description*/"元気な曲を聴けば、推理も楽しくはかどります !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/7, /*event_id*/6002, /*comment_id*/100529, /*use_type*/4, /*index*/1, /*description*/"全員で歌えば切り拓ける道もあるはずです。さぁ一緒に !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/8, /*event_id*/6002, /*comment_id*/100529, /*use_type*/5, /*index*/1, /*description*/"どんな歌でも必ず盛り上げる ! アイドル探偵の名にかけて !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/9, /*event_id*/6002, /*comment_id*/100529, /*use_type*/100, /*index*/1, /*description*/"真実はもう目の前です。最後まで油断せず行きましょう !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/10, /*event_id*/6002, /*comment_id*/100529, /*use_type*/101, /*index*/1, /*description*/"新たな謎が発生したようです。探偵の本気、お見せします !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/11, /*event_id*/6002, /*comment_id*/100529, /*use_type*/102, /*index*/1, /*description*/"はっ ! 思考が冴え渡っている… !\n今ならどんな難問でも解決できそうな気がします !\nチャンスですよ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/12, /*event_id*/6002, /*comment_id*/100529, /*use_type*/102, /*index*/2, /*description*/"探偵の勘が告げています。\n今こそ、事件の真相に迫る大チャンス !\nこの機会を逃す手はありませんよ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/13, /*event_id*/6002, /*comment_id*/100529, /*use_type*/102, /*index*/3, /*description*/"フッフッフ…そろそろ私の本気を見せる時が来たようですね。\nどんな小さな痕跡も見逃さないこの観察眼で、\n一気に犯人を追いつめますよ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/14, /*event_id*/6002, /*comment_id*/300495, /*use_type*/0, /*index*/1, /*description*/"もっと遊びたいし、もっと踊りたーいっ ! 早く早く !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/15, /*event_id*/6002, /*comment_id*/300495, /*use_type*/0, /*index*/2, /*description*/"見てみたくない？この先に何があるのか。一緒に行こうよ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/16, /*event_id*/6002, /*comment_id*/300495, /*use_type*/0, /*index*/3, /*description*/"早く踊りたいんだ ! 最高に熱いステージで !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/17, /*event_id*/6002, /*comment_id*/300495, /*use_type*/1, /*index*/1, /*description*/"カワイイ曲って少し照れるけど……全力でいくよ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/18, /*event_id*/6002, /*comment_id*/300495, /*use_type*/2, /*index*/1, /*description*/"最高にかっこよくキメてくからさ、見ててよ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/19, /*event_id*/6002, /*comment_id*/300495, /*use_type*/3, /*index*/1, /*description*/"明るく元気な曲ってアタシにぴったりだと思うんだよね♪", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/20, /*event_id*/6002, /*comment_id*/300495, /*use_type*/4, /*index*/1, /*description*/"みんなでノレる曲ってよくない？盛り上がってくよー !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/21, /*event_id*/6002, /*comment_id*/300495, /*use_type*/5, /*index*/1, /*description*/"どんな歌でもアタシらしく魅せるしかないでしょ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/22, /*event_id*/6002, /*comment_id*/300495, /*use_type*/100, /*index*/1, /*description*/"もうちょっとでゴールだね ! 気合い入れなおしてこ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/23, /*event_id*/6002, /*comment_id*/300495, /*use_type*/101, /*index*/1, /*description*/"課題があると、燃えるよね ! ダンスならなおさら !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/24, /*event_id*/6002, /*comment_id*/300495, /*use_type*/102, /*index*/1, /*description*/"トロピカルジュースでリフレッシュしたし\nいつもよりアツい踊りができそう !\nさ、盛り上げていくよーっ ! !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/25, /*event_id*/6002, /*comment_id*/300495, /*use_type*/102, /*index*/2, /*description*/"ダンスバカの本気、\n見ててよ、プロデューサー !\nバリのみんなと一緒にすごいステージにするからさ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/26, /*event_id*/6002, /*comment_id*/300495, /*use_type*/102, /*index*/3, /*description*/"見てみたくない？\nアタシとバリのみんなで作る最高のLIVE !\n気合い入れて、ガンガン踊るからさ ! ついてきてよ♪", /*insert_word_type*/0);
