CREATE TABLE 'rail_area_comment' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'group_id' INTEGER NOT NULL, 'rap_id' INTEGER NOT NULL, 'comment_id' INTEGER NOT NULL, 'use_type' INTEGER NOT NULL, 'description' TEXT NOT NULL, 'insert_word_type' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `rail_area_comment` VALUES (/*id*/1, /*event_id*/6012, /*group_id*/1, /*rap_id*/1, /*comment_id*/30001, /*use_type*/1, /*description*/"さぁ、まずは小手調べですよっ !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/2, /*event_id*/6012, /*group_id*/1, /*rap_id*/2, /*comment_id*/30001, /*use_type*/1, /*description*/"わたしからの課題は、これですっ !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/3, /*event_id*/6012, /*group_id*/1, /*rap_id*/3, /*comment_id*/30002, /*use_type*/1, /*description*/"妹よりは、厳しめにいきますよ !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/4, /*event_id*/6012, /*group_id*/1, /*rap_id*/4, /*comment_id*/30003, /*use_type*/1, /*description*/"さぁ、君たちの力を見せてみろ !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/5, /*event_id*/6012, /*group_id*/1, /*rap_id*/5, /*comment_id*/1, /*use_type*/1, /*description*/"トップを目指す覚悟、見せてもらおうか !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/6, /*event_id*/6012, /*group_id*/1, /*rap_id*/1, /*comment_id*/30001, /*use_type*/2, /*description*/"お見事ですっ ! このままどんどん進みましょう !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/7, /*event_id*/6012, /*group_id*/1, /*rap_id*/2, /*comment_id*/30001, /*use_type*/2, /*description*/"わわっ、みなさんには簡単すぎましたか？", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/8, /*event_id*/6012, /*group_id*/1, /*rap_id*/3, /*comment_id*/30002, /*use_type*/2, /*description*/"日頃のレッスンのたまものですね !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/9, /*event_id*/6012, /*group_id*/1, /*rap_id*/4, /*comment_id*/30003, /*use_type*/2, /*description*/"私の課題を超えた君たちなら、次も大丈夫だ !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/10, /*event_id*/6012, /*group_id*/1, /*rap_id*/5, /*comment_id*/1, /*use_type*/2, /*description*/"よくやった ! 特製ドリンクはいるか？", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/11, /*event_id*/6012, /*group_id*/2, /*rap_id*/1, /*comment_id*/30001, /*use_type*/1, /*description*/"みなさんなら、クリアできますよね !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/12, /*event_id*/6012, /*group_id*/2, /*rap_id*/2, /*comment_id*/30002, /*use_type*/1, /*description*/"この課題、クリアできますか？", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/13, /*event_id*/6012, /*group_id*/2, /*rap_id*/3, /*comment_id*/30003, /*use_type*/1, /*description*/"このスペシャルプラン、こなしてみせろ !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/14, /*event_id*/6012, /*group_id*/2, /*rap_id*/4, /*comment_id*/1, /*use_type*/1, /*description*/"時には厳しい試練も必要だ。さぁ、いくぞ !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/15, /*event_id*/6012, /*group_id*/2, /*rap_id*/1, /*comment_id*/30001, /*use_type*/2, /*description*/"みなさんの力、見せていただきましたっ !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/16, /*event_id*/6012, /*group_id*/2, /*rap_id*/2, /*comment_id*/30002, /*use_type*/2, /*description*/"よ～し、じゃあ、次のステップですね !", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/17, /*event_id*/6012, /*group_id*/2, /*rap_id*/3, /*comment_id*/30003, /*use_type*/2, /*description*/"やるじゃないか。君たちの想い、見せてもらった", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/18, /*event_id*/6012, /*group_id*/2, /*rap_id*/4, /*comment_id*/1, /*use_type*/2, /*description*/"君たちの成長が見れるこの瞬間が、私は好きだ", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/19, /*event_id*/6012, /*group_id*/1, /*rap_id*/1, /*comment_id*/100753, /*use_type*/3, /*description*/"残念。この手は防がれるのね。じゃあ、次の手を試しましょ", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/20, /*event_id*/6012, /*group_id*/1, /*rap_id*/2, /*comment_id*/100753, /*use_type*/3, /*description*/"簡単にできるなら、この世にプロの居場所はないわ。違う？", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/21, /*event_id*/6012, /*group_id*/1, /*rap_id*/3, /*comment_id*/100753, /*use_type*/3, /*description*/"ふふ、熱くなるわね♪でも、冷静さは忘れないように…ね", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/22, /*event_id*/6012, /*group_id*/1, /*rap_id*/4, /*comment_id*/100753, /*use_type*/3, /*description*/"残念。この手は防がれるのね。じゃあ、次の手を試しましょ", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/23, /*event_id*/6012, /*group_id*/1, /*rap_id*/5, /*comment_id*/100753, /*use_type*/3, /*description*/"簡単にできるなら、この世にプロの居場所はないわ。違う？", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/24, /*event_id*/6012, /*group_id*/2, /*rap_id*/1, /*comment_id*/200755, /*use_type*/3, /*description*/"フローを一緒に見直そう。必ず、論理的に解けるはずだよ", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/25, /*event_id*/6012, /*group_id*/2, /*rap_id*/2, /*comment_id*/200755, /*use_type*/3, /*description*/"進捗状況は順調だね。このまま、計画的に積み重ねていこう", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/26, /*event_id*/6012, /*group_id*/2, /*rap_id*/3, /*comment_id*/200755, /*use_type*/3, /*description*/"息抜きも大事だよ。ね、カフェラテ、一緒に飲まない？", /*insert_word_type*/0);
INSERT INTO `rail_area_comment` VALUES (/*id*/27, /*event_id*/6012, /*group_id*/2, /*rap_id*/4, /*comment_id*/200755, /*use_type*/3, /*description*/"フローを一緒に見直そう。必ず、論理的に解けるはずだよ", /*insert_word_type*/0);
CREATE INDEX 'rail_area_comment_0_event_id' on 'rail_area_comment'('event_id');
CREATE INDEX 'rail_area_comment_0_group_id' on 'rail_area_comment'('group_id');
