CREATE TABLE 'rail_card_comment' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'comment_id' INTEGER NOT NULL, 'use_type' INTEGER NOT NULL, 'index' INTEGER NOT NULL, 'description' TEXT NOT NULL, 'insert_word_type' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `rail_card_comment` VALUES (/*id*/1, /*event_id*/6012, /*comment_id*/100753, /*use_type*/0, /*index*/1, /*description*/"ただ回数を重ねるだけじゃダメ。一手一手、考えながらね", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/2, /*event_id*/6012, /*comment_id*/100753, /*use_type*/0, /*index*/2, /*description*/"たくさん歩けば、ディナーのお酒がもっと美味しくなるかも♪", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/3, /*event_id*/6012, /*comment_id*/100753, /*use_type*/0, /*index*/3, /*description*/"少しずつ、実力を重ねていく感じ…。ふふっ、たまらないわね", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/4, /*event_id*/6012, /*comment_id*/100753, /*use_type*/1, /*index*/1, /*description*/"キュートなオトナの魅力、みんなに教えてあげちゃう♪", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/5, /*event_id*/6012, /*comment_id*/100753, /*use_type*/2, /*index*/1, /*description*/"ポーカーフェイスはギャンブラーの必須技能。見せてあげる", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/6, /*event_id*/6012, /*comment_id*/100753, /*use_type*/3, /*index*/1, /*description*/"表情は変えずに、心は燃やす…。私の情熱を、感じて… !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/7, /*event_id*/6012, /*comment_id*/100753, /*use_type*/4, /*index*/1, /*description*/"人の数だけ戦略がある。だから大人数のゲームっていいわよね", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/8, /*event_id*/6012, /*comment_id*/100753, /*use_type*/5, /*index*/1, /*description*/"どんなことでも、こなせるのがプロ。実践してみせるわ", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/9, /*event_id*/6012, /*comment_id*/100753, /*use_type*/100, /*index*/1, /*description*/"勝ちが見えても、手に入るとは限らないわ。集中しましょ", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/10, /*event_id*/6012, /*comment_id*/100753, /*use_type*/101, /*index*/1, /*description*/"やりがいがある。それだけで、挑戦する理由には十分よ", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/11, /*event_id*/6012, /*comment_id*/100753, /*use_type*/102, /*index*/1, /*description*/"ゆっくり進むのも悪くないわ。\nでも、やっぱり私はスピード感のあるほうが好きみたい。\nだって、そのほうがゾクゾクするんだもの♪", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/12, /*event_id*/6012, /*comment_id*/100753, /*use_type*/102, /*index*/2, /*description*/"いいタイミングが巡ってきたみたい。\nここは思い切って攻めましょ。\n幸運を掴むには、大胆にいかないとね。", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/13, /*event_id*/6012, /*comment_id*/100753, /*use_type*/102, /*index*/3, /*description*/"ふふっ、流れが来てるわね。こういうのは肌でわかるの。\nさぁ、ここからが腕の見せ所よ。\n流れを生かすも殺すも貴方次第…期待してるわ。", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/14, /*event_id*/6012, /*comment_id*/200755, /*use_type*/0, /*index*/1, /*description*/"プログラミングは設計が大事。全体を見渡して計画的にね", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/15, /*event_id*/6012, /*comment_id*/200755, /*use_type*/0, /*index*/2, /*description*/"浮かれてるように見えるかな。ふふ、だって毎日が楽しいもの", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/16, /*event_id*/6012, /*comment_id*/200755, /*use_type*/0, /*index*/3, /*description*/"みんなと並んでいたいんだ。だから、この道の先へ… !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/17, /*event_id*/6012, /*comment_id*/200755, /*use_type*/1, /*index*/1, /*description*/"私の笑顔も誰かを笑顔にする…友だちが気づかせてくれたの", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/18, /*event_id*/6012, /*comment_id*/200755, /*use_type*/2, /*index*/1, /*description*/"冷静に分析すれば、ミスなくいけるよね。私の得意分野 !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/19, /*event_id*/6012, /*comment_id*/200755, /*use_type*/3, /*index*/1, /*description*/"動くことが、勇気になるの。友だちを見てると、思うんだ", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/20, /*event_id*/6012, /*comment_id*/200755, /*use_type*/4, /*index*/1, /*description*/"さあ、いこう。３色の波がそろえば、無敵だから !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/21, /*event_id*/6012, /*comment_id*/200755, /*use_type*/5, /*index*/1, /*description*/"楽しいね。私たちには、いろんな可能性があるんだ !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/22, /*event_id*/6012, /*comment_id*/200755, /*use_type*/100, /*index*/1, /*description*/"リリースは目前。バグを出さないように、詰めていこう", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/23, /*event_id*/6012, /*comment_id*/200755, /*use_type*/101, /*index*/1, /*description*/"オーバーヒートしないように。おやつでも食べながら、ね", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/24, /*event_id*/6012, /*comment_id*/200755, /*use_type*/102, /*index*/1, /*description*/"生まれたての気持ちで、胸がいっぱい…。\nオーバーフローしそうなくらい。\n私、もっと…もっと、先へ行きたい… !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/25, /*event_id*/6012, /*comment_id*/200755, /*use_type*/102, /*index*/2, /*description*/"上げていくのは、心のクロック数だよね。\nドキドキが倍になれば、\n進める距離も、きっと倍になるはずだから… !", /*insert_word_type*/0);
INSERT INTO `rail_card_comment` VALUES (/*id*/26, /*event_id*/6012, /*comment_id*/200755, /*use_type*/102, /*index*/3, /*description*/"ふたりが、みんなが、プロデューサーがいてくれる。\nあのね、手を引いて…ほしいな…なんて。\nワガママ言っちゃうような私でも、いいかな？", /*insert_word_type*/0);
CREATE INDEX 'rail_card_comment_0_event_id' on 'rail_card_comment'('event_id');
