CREATE TABLE 'rm_assets' ('id' INTEGER NOT NULL, 'name' TEXT NOT NULL, PRIMARY KEY('id'))
INSERT INTO `rm_assets` VALUES (/*id*/1, /*name*/"title_bg_50001.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/2, /*name*/"title_bg_50002.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/3, /*name*/"title_bg_50003.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/4, /*name*/"title_bg_50004.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/5, /*name*/"title_bg_50007.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/6, /*name*/"title_bg_50008.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/7, /*name*/"title_bg_50009.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/8, /*name*/"title_bg_50010.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/9, /*name*/"title_bg_50011.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/10, /*name*/"title_bg_50012.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/11, /*name*/"title_bg_50013.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/12, /*name*/"title_bg_50014.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/13, /*name*/"title_bg_50015.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/14, /*name*/"title_bg_50016.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/15, /*name*/"title_bg_50017.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/16, /*name*/"title_bg_50018.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/17, /*name*/"title_bg_50019.unity3d");
INSERT INTO `rm_assets` VALUES (/*id*/18, /*name*/"title_bg_50020.unity3d");
