CREATE TABLE 'room_idol_extension' ('card_id' INTEGER NOT NULL, 'is_spine' INTEGER NOT NULL, PRIMARY KEY('card_id'));
INSERT INTO `room_idol_extension` VALUES (/*card_id*/100424, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/100474, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/100598, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/200400, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/200565, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/200598, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300314, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300418, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300468, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300527, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300528, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300550, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300556, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300572, /*is_spine*/1);
INSERT INTO `room_idol_extension` VALUES (/*card_id*/300604, /*is_spine*/1);
