CREATE TABLE 'room_item_event_effect' ('event_id' INTEGER NOT NULL, 'room_item_ids' TEXT NOT NULL, PRIMARY KEY('event_id'));
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7004, /*room_item_ids*/"3354,3455,3714");
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7005, /*room_item_ids*/4034);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7006, /*room_item_ids*/4126);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7007, /*room_item_ids*/4374);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7008, /*room_item_ids*/4664);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7009, /*room_item_ids*/4826);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7010, /*room_item_ids*/5104);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7011, /*room_item_ids*/5284);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7012, /*room_item_ids*/5494);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7013, /*room_item_ids*/5764);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7014, /*room_item_ids*/5994);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7015, /*room_item_ids*/6254);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7016, /*room_item_ids*/6544);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7017, /*room_item_ids*/6714);
INSERT INTO `room_item_event_effect` VALUES (/*event_id*/7018, /*room_item_ids*/6874);
