CREATE TABLE 'room_item_category' ('id' INTEGER NOT NULL, 'category_name' TEXT NOT NULL, 'name' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO `room_item_category` VALUES (/*id*/101, /*category_name*/"家具", /*name*/"机");
INSERT INTO `room_item_category` VALUES (/*id*/102, /*category_name*/"家具", /*name*/"椅子");
INSERT INTO `room_item_category` VALUES (/*id*/103, /*category_name*/"家具", /*name*/"収納");
INSERT INTO `room_item_category` VALUES (/*id*/104, /*category_name*/"家具", /*name*/"スペース");
INSERT INTO `room_item_category` VALUES (/*id*/199, /*category_name*/"家具", /*name*/"その他");
INSERT INTO `room_item_category` VALUES (/*id*/201, /*category_name*/"家電・雑貨", /*name*/"家電");
INSERT INTO `room_item_category` VALUES (/*id*/202, /*category_name*/"家電・雑貨", /*name*/"雑貨");
INSERT INTO `room_item_category` VALUES (/*id*/203, /*category_name*/"家電・雑貨", /*name*/"ホビー");
INSERT INTO `room_item_category` VALUES (/*id*/204, /*category_name*/"家電・雑貨", /*name*/"トロフィー");
INSERT INTO `room_item_category` VALUES (/*id*/299, /*category_name*/"家電・雑貨", /*name*/"その他");
INSERT INTO `room_item_category` VALUES (/*id*/301, /*category_name*/"装飾", /*name*/"壁飾り");
INSERT INTO `room_item_category` VALUES (/*id*/302, /*category_name*/"装飾", /*name*/"敷き物");
INSERT INTO `room_item_category` VALUES (/*id*/303, /*category_name*/"装飾", /*name*/"衝立");
INSERT INTO `room_item_category` VALUES (/*id*/901, /*category_name*/"テーマ", /*name*/"床");
INSERT INTO `room_item_category` VALUES (/*id*/902, /*category_name*/"テーマ", /*name*/"壁");
INSERT INTO `room_item_category` VALUES (/*id*/903, /*category_name*/"テーマ", /*name*/"背景");
