CREATE TABLE 'serial_code_reward_set' ('id' INTEGER NOT NULL, 'reward_set_id' INTEGER NOT NULL, 'reward_index' INTEGER NOT NULL, 'reward_type' INTEGER NOT NULL, 'reward_id' INTEGER NOT NULL, 'reward_value' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `serial_code_reward_set` VALUES (/*id*/1, /*reward_set_id*/1, /*reward_index*/1, /*reward_type*/5, /*reward_id*/89006, /*reward_value*/2);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/2, /*reward_set_id*/1, /*reward_index*/2, /*reward_type*/5, /*reward_id*/89007, /*reward_value*/2);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/3, /*reward_set_id*/1, /*reward_index*/3, /*reward_type*/5, /*reward_id*/89008, /*reward_value*/2);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/4, /*reward_set_id*/1, /*reward_index*/4, /*reward_type*/5, /*reward_id*/30030, /*reward_value*/190);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/5, /*reward_set_id*/1, /*reward_index*/5, /*reward_type*/5, /*reward_id*/30007, /*reward_value*/190);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/6, /*reward_set_id*/1, /*reward_index*/6, /*reward_type*/5, /*reward_id*/1003, /*reward_value*/10);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/7, /*reward_set_id*/1, /*reward_index*/7, /*reward_type*/5, /*reward_id*/21007, /*reward_value*/10);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/8, /*reward_set_id*/1, /*reward_index*/8, /*reward_type*/5, /*reward_id*/3001, /*reward_value*/190);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/9, /*reward_set_id*/1, /*reward_index*/9, /*reward_type*/7, /*reward_id*/6990, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/10, /*reward_set_id*/1, /*reward_index*/10, /*reward_type*/7, /*reward_id*/6991, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/11, /*reward_set_id*/1, /*reward_index*/11, /*reward_type*/7, /*reward_id*/6992, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/12, /*reward_set_id*/1, /*reward_index*/12, /*reward_type*/7, /*reward_id*/6993, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/13, /*reward_set_id*/1, /*reward_index*/13, /*reward_type*/7, /*reward_id*/6994, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/14, /*reward_set_id*/1, /*reward_index*/14, /*reward_type*/7, /*reward_id*/6995, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/15, /*reward_set_id*/1, /*reward_index*/15, /*reward_type*/7, /*reward_id*/6996, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/16, /*reward_set_id*/1, /*reward_index*/16, /*reward_type*/7, /*reward_id*/6997, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/17, /*reward_set_id*/1, /*reward_index*/17, /*reward_type*/7, /*reward_id*/6998, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/18, /*reward_set_id*/1, /*reward_index*/18, /*reward_type*/29, /*reward_id*/11000, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/19, /*reward_set_id*/1, /*reward_index*/19, /*reward_type*/29, /*reward_id*/11001, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/20, /*reward_set_id*/1, /*reward_index*/20, /*reward_type*/29, /*reward_id*/11002, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/21, /*reward_set_id*/1, /*reward_index*/21, /*reward_type*/29, /*reward_id*/11003, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/22, /*reward_set_id*/1, /*reward_index*/22, /*reward_type*/29, /*reward_id*/11004, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/23, /*reward_set_id*/1, /*reward_index*/23, /*reward_type*/29, /*reward_id*/11005, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/24, /*reward_set_id*/1, /*reward_index*/24, /*reward_type*/29, /*reward_id*/11006, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/25, /*reward_set_id*/1, /*reward_index*/25, /*reward_type*/29, /*reward_id*/11007, /*reward_value*/1);
INSERT INTO `serial_code_reward_set` VALUES (/*id*/26, /*reward_set_id*/1, /*reward_index*/26, /*reward_type*/29, /*reward_id*/11008, /*reward_value*/1);
CREATE INDEX 'serial_code_reward_set_0_reward_set_id' on 'serial_code_reward_set'('reward_set_id');
