CREATE TABLE 'skill_levelup' ('diff_rarity' INTEGER NOT NULL, 'skill_up_value' INTEGER NOT NULL, PRIMARY KEY('diff_rarity'));
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/1, /*skill_up_value*/1000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/2, /*skill_up_value*/2500);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/3, /*skill_up_value*/5000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/4, /*skill_up_value*/10000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/5, /*skill_up_value*/20000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/6, /*skill_up_value*/30000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/7, /*skill_up_value*/40000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/8, /*skill_up_value*/50000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/9, /*skill_up_value*/60000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/10, /*skill_up_value*/80000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/11, /*skill_up_value*/100000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/12, /*skill_up_value*/120000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/13, /*skill_up_value*/140000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/14, /*skill_up_value*/160000);
INSERT INTO `skill_levelup` VALUES (/*diff_rarity*/15, /*skill_up_value*/200000);
