CREATE TABLE 'skill_boost_type' ('id' INTEGER NOT NULL, 'skill_value' INTEGER NOT NULL, 'target_type' INTEGER NOT NULL, 'boost_value_1' INTEGER NOT NULL, 'boost_value_2' INTEGER NOT NULL, 'boost_value_3' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO `skill_boost_type` VALUES (/*id*/1, /*skill_value*/1, /*target_type*/1, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/2, /*skill_value*/1, /*target_type*/2, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/3, /*skill_value*/1, /*target_type*/3, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/4, /*skill_value*/1, /*target_type*/4, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/5, /*skill_value*/1, /*target_type*/5, /*boost_value_1*/1, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/6, /*skill_value*/1, /*target_type*/6, /*boost_value_1*/1, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/7, /*skill_value*/1, /*target_type*/7, /*boost_value_1*/1, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/8, /*skill_value*/1, /*target_type*/8, /*boost_value_1*/1, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/9, /*skill_value*/1, /*target_type*/9, /*boost_value_1*/1, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/10, /*skill_value*/1, /*target_type*/10, /*boost_value_1*/1, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/11, /*skill_value*/1, /*target_type*/11, /*boost_value_1*/1, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/12, /*skill_value*/1, /*target_type*/12, /*boost_value_1*/1, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/13, /*skill_value*/1, /*target_type*/14, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/14, /*skill_value*/1, /*target_type*/15, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/15, /*skill_value*/1, /*target_type*/17, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/16, /*skill_value*/1, /*target_type*/18, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/17, /*skill_value*/1, /*target_type*/19, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/18, /*skill_value*/1, /*target_type*/21, /*boost_value_1*/1200, /*boost_value_2*/1200, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/19, /*skill_value*/1, /*target_type*/22, /*boost_value_1*/1200, /*boost_value_2*/1200, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/20, /*skill_value*/1, /*target_type*/23, /*boost_value_1*/1200, /*boost_value_2*/1200, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/21, /*skill_value*/1, /*target_type*/24, /*boost_value_1*/1200, /*boost_value_2*/1200, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/22, /*skill_value*/1, /*target_type*/16, /*boost_value_1*/0, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/23, /*skill_value*/1, /*target_type*/25, /*boost_value_1*/1200, /*boost_value_2*/0, /*boost_value_3*/0);
INSERT INTO `skill_boost_type` VALUES (/*id*/24, /*skill_value*/1, /*target_type*/26, /*boost_value_1*/1200, /*boost_value_2*/1200, /*boost_value_3*/1200);
CREATE INDEX 'skill_boost_type_0_skill_value_1_target_type' on 'skill_boost_type'('skill_value','target_type');
