CREATE TABLE 'sp_gacha_dress' ('id' INTEGER NOT NULL, 'dress_id' INTEGER NOT NULL, 'pos_no' INTEGER NOT NULL, 'chara_id' INTEGER NOT NULL, 'pose_id' INTEGER NOT NULL, PRIMARY KEY('id'), UNIQUE('dress_id','pos_no','chara_id'));
INSERT INTO `sp_gacha_dress` VALUES (/*id*/1, /*dress_id*/7051000, /*pos_no*/1, /*chara_id*/272, /*pose_id*/1);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/2, /*dress_id*/7051000, /*pos_no*/2, /*chara_id*/167, /*pose_id*/1);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/3, /*dress_id*/7051000, /*pos_no*/3, /*chara_id*/101, /*pose_id*/1);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/4, /*dress_id*/7051000, /*pos_no*/4, /*chara_id*/154, /*pose_id*/1);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/5, /*dress_id*/7051000, /*pos_no*/5, /*chara_id*/201, /*pose_id*/1);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/6, /*dress_id*/7051000, /*pos_no*/6, /*chara_id*/198, /*pose_id*/2);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/7, /*dress_id*/7051000, /*pos_no*/7, /*chara_id*/220, /*pose_id*/4);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/8, /*dress_id*/7051000, /*pos_no*/8, /*chara_id*/197, /*pose_id*/2);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/9, /*dress_id*/7051000, /*pos_no*/9, /*chara_id*/234, /*pose_id*/4);
INSERT INTO `sp_gacha_dress` VALUES (/*id*/10, /*dress_id*/7051000, /*pos_no*/10, /*chara_id*/189, /*pose_id*/4);
