CREATE TABLE 'sp_login_position' ('day_count' INTEGER NOT NULL, 'chara_index' INTEGER NOT NULL, 'frame_type' INTEGER NOT NULL, 'frame_position_x' INTEGER NOT NULL, 'frame_position_y' INTEGER NOT NULL, 'text_data' TEXT NOT NULL, PRIMARY KEY('day_count','chara_index'))
INSERT INTO `sp_login_position` VALUES (/*day_count*/1, /*chara_index*/1, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"私はP.C.Sのみんなと\n『ラブレター』を\n歌いました♪");
INSERT INTO `sp_login_position` VALUES (/*day_count*/1, /*chara_index*/2, /*frame_type*/4, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"3人で教室で\n踊っていたよね。\n可愛いMVだったよ");
INSERT INTO `sp_login_position` VALUES (/*day_count*/2, /*chara_index*/1, /*frame_type*/4, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"Jet to the \nAnniversary ! !");
INSERT INTO `sp_login_position` VALUES (/*day_count*/2, /*chara_index*/2, /*frame_type*/5, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"準備はOK？\nプロデューサーさん !");
INSERT INTO `sp_login_position` VALUES (/*day_count*/3, /*chara_index*/1, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"美嘉チャンって、\nはじめてのステージは\n憶えてる？");
INSERT INTO `sp_login_position` VALUES (/*day_count*/3, /*chara_index*/2, /*frame_type*/5, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"あったりまえじゃん★\n大切な思い出は\n忘れないよ");
INSERT INTO `sp_login_position` VALUES (/*day_count*/4, /*chara_index*/1, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/-20, /*text_data*/"なんかさ、アンカケ\n食べたくなって\nこない～？");
INSERT INTO `sp_login_position` VALUES (/*day_count*/4, /*chara_index*/2, /*frame_type*/5, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"ん？\nアンキモじゃないの？\n杏ちゃん !");
INSERT INTO `sp_login_position` VALUES (/*day_count*/5, /*chara_index*/1, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"乃々ちゃん、\nクッキー食べる？\nはい、どうぞ♪");
INSERT INTO `sp_login_position` VALUES (/*day_count*/5, /*chara_index*/2, /*frame_type*/4, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"有無を言わさずぅ…\nもぐ…おいしいぃ…♪");
INSERT INTO `sp_login_position` VALUES (/*day_count*/6, /*chara_index*/1, /*frame_type*/5, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"えへへ、また、みんなで\nどこか遊びに\n行きたいねっ");
INSERT INTO `sp_login_position` VALUES (/*day_count*/6, /*chara_index*/2, /*frame_type*/5, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"行きましょう !\nなんなら\n今からでもっ !");
INSERT INTO `sp_login_position` VALUES (/*day_count*/7, /*chara_index*/1, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/-20, /*text_data*/"ショーコ、今日は\nキノコって言っとか\nなくていいのか？");
INSERT INTO `sp_login_position` VALUES (/*day_count*/7, /*chara_index*/2, /*frame_type*/5, /*frame_position_x*/0, /*frame_position_y*/-20, /*text_data*/"え？じゃあせっかく\nなので…オホン…\nキノコォーッ !…フヒ");
INSERT INTO `sp_login_position` VALUES (/*day_count*/8, /*chara_index*/1, /*frame_type*/4, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"アーニャ、記念日って\nロシア語で\n何て言うんだ？");
INSERT INTO `sp_login_position` VALUES (/*day_count*/8, /*chara_index*/2, /*frame_type*/4, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"ガダフシーナ、\nですね。いっしょに\n言ってみましょう♪");
INSERT INTO `sp_login_position` VALUES (/*day_count*/9, /*chara_index*/1, /*frame_type*/5, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"雫ちゃんの実家、\nどんどん有名に\nなってますねっ");
INSERT INTO `sp_login_position` VALUES (/*day_count*/9, /*chara_index*/2, /*frame_type*/5, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"うふふー、全部\nみなさんの\nおかげですー♪");
INSERT INTO `sp_login_position` VALUES (/*day_count*/10, /*chara_index*/1, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"次に花嫁衣裳を\n着るのは、いつに\nなるかなぁ…");
INSERT INTO `sp_login_position` VALUES (/*day_count*/10, /*chara_index*/2, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"お仕事なのか、\nそれとも…ドキドキ\nしちゃいますっ");
INSERT INTO `sp_login_position` VALUES (/*day_count*/11, /*chara_index*/1, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"有香ちゃん、\nこないだ新しい服\n買ったんだって !");
INSERT INTO `sp_login_position` VALUES (/*day_count*/11, /*chara_index*/2, /*frame_type*/3, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"あれからも、\n私たちのカワイイ道は\n続いています♪");
INSERT INTO `sp_login_position` VALUES (/*day_count*/12, /*chara_index*/1, /*frame_type*/4, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"我が友よ、\n甘美な祝盃を ! ");
INSERT INTO `sp_login_position` VALUES (/*day_count*/12, /*chara_index*/2, /*frame_type*/4, /*frame_position_x*/0, /*frame_position_y*/0, /*text_data*/"記念日にキミは何を\n想う。歓喜？感慨？\nそれとも…フフ");
