CREATE TABLE sqlite_stat1(tbl,idx,stat)
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"leader_skill_boost_rate_re", /*idx*/"leader_skill_boost_rate_re_0_position", /*stat*/"66 14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00005", /*idx*/"room_set_detail00005_0_set_id", /*stat*/"30 30");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"exchange_shop_term", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00004", /*idx*/"room_set_detail00004_0_set_id", /*stat*/"37 37");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"normal_mission", /*idx*/"normal_mission_0_normal_mission_id", /*stat*/"1171 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"normal_mission", /*idx*/"normal_mission_0_step_group_id_1_step_order", /*stat*/"1171 7 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"mv_list_performer", /*idx*/"mv_list_performer_0_stage_id", /*stat*/"417 19");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_theme_preset_0002", /*idx*/"", /*stat*/17);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_live_item", /*idx*/"tour_live_item_0_event_id", /*stat*/"3 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_audience_reward", /*idx*/"tour_audience_reward_0_event_id", /*stat*/"56 56");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_point_rank_reward", /*idx*/"atapon_point_rank_reward_0_event_id", /*stat*/"25 25");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"caravan_data", /*idx*/"caravan_data_0_event_id_1_date_order", /*stat*/"123 8 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"caravan_data", /*idx*/"caravan_data_0_event_id", /*stat*/"123 8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gallery_stage_list", /*idx*/"", /*stat*/7);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_point_rank_disp", /*idx*/"", /*stat*/8);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_beta_data", /*idx*/"event_beta_data_0_type", /*stat*/"2 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"individual_tutorial", /*idx*/"individual_tutorial_0_id", /*stat*/"282 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_available", /*idx*/"event_available_0_event_id", /*stat*/"169 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_available", /*idx*/"sqlite_autoindex_event_available_1", /*stat*/"169 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sp_campaign_reward", /*idx*/"sp_campaign_reward_0_campaign_id_1_rank", /*stat*/"57 29 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sp_campaign_reward", /*idx*/"sp_campaign_reward_0_campaign_id", /*stat*/"57 29");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00001", /*idx*/"room_set_detail00001_0_set_id", /*stat*/"57 57");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_point_reward", /*idx*/"party_point_reward_0_event_id", /*stat*/"22 22");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sp_campaign_data", /*idx*/"", /*stat*/2);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"namecard_bg", /*idx*/"", /*stat*/13);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sp_login_position", /*idx*/"sqlite_autoindex_sp_login_position_1", /*stat*/"25 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gallery_music_list", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_data", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_give_present", /*idx*/"", /*stat*/21);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sp_login_bonus_before", /*idx*/"", /*stat*/13);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_vibration_change", /*idx*/"medley_vibration_change_0_event_id_1_difficulty_type", /*stat*/"25 25 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_vibration_change", /*idx*/"sqlite_autoindex_medley_vibration_change_1", /*stat*/"25 25 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gift_message", /*idx*/"", /*stat*/126);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_detail", /*idx*/"login_bonus_detail_0_campaign_id_1_rap_2_count", /*stat*/"328 13 13 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_l_group", /*idx*/"", /*stat*/35);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_vibration_rank", /*idx*/"medley_vibration_rank_0_event_id_1_difficulty_type", /*stat*/"245 245 49");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_sp_effect", /*idx*/"gacha_sp_effect_0_card_id", /*stat*/"13 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_sp_effect", /*idx*/"gacha_sp_effect_0_gacha_id", /*stat*/"13 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_sp_effect", /*idx*/"sqlite_autoindex_gacha_sp_effect_1", /*stat*/"13 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"premium_sc_list", /*idx*/"premium_sc_list_0_cost_id", /*stat*/"2220 222");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_data", /*idx*/"", /*stat*/9);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_term", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_access_reward", /*idx*/"", /*stat*/21);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_preset", /*idx*/"room_item_preset_0_event_id", /*stat*/"27 27");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gallery_pose_list", /*idx*/"", /*stat*/5);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"panel_mission_comp_reward", /*idx*/"panel_mission_comp_reward_0_campaign_id_1_rap", /*stat*/"3 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"panel_mission_comp_reward", /*idx*/"panel_mission_comp_reward_0_campaign_id", /*stat*/"3 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_data", /*idx*/"gacha_data_0_base_id", /*stat*/"465 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_detail", /*idx*/"sqlite_autoindex_room_item_detail_1", /*stat*/"1321 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_data_elcp", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_live_exclude", /*idx*/"sqlite_autoindex_medley_live_exclude_1", /*stat*/"95 95 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_collision", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_live_detail", /*idx*/"tour_live_detail_0_event_id_1_area_id_2_area_index", /*stat*/"35 35 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_live_detail", /*idx*/"tour_live_detail_0_event_id", /*stat*/"35 35");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_data", /*idx*/"event_data_0_type", /*stat*/"79 16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_announcement", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0010", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0009", /*idx*/"", /*stat*/5);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"el_live_data", /*idx*/"", /*stat*/135);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"title_pattern", /*idx*/"", /*stat*/134);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"limited_mission", /*idx*/"limited_mission_0_limited_mission_id", /*stat*/"1230 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_offset", /*idx*/"sqlite_autoindex_room_item_offset_1", /*stat*/"985 2 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"master_plus_group_1", /*idx*/"", /*stat*/21);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00003", /*idx*/"room_set_detail00003_0_set_id", /*stat*/"44 44");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_point_reward", /*idx*/"tour_point_reward_0_event_id", /*stat*/"73 73");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_vocalist", /*idx*/"music_vocalist_0_chara_id", /*stat*/"538 8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_vocalist", /*idx*/"music_vocalist_0_music_data_id", /*stat*/"538 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_vocalist", /*idx*/"sqlite_autoindex_music_vocalist_1", /*stat*/"538 4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"lottery_resource", /*idx*/"", /*stat*/2);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_l_e_list", /*idx*/"gacha_l_e_list_0_g_id", /*stat*/"485 14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"master_plus_term", /*idx*/"", /*stat*/24);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_info", /*idx*/"", /*stat*/176);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_data", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_step", /*idx*/"sqlite_autoindex_gacha_step_1", /*stat*/"3 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_data", /*idx*/"sqlite_autoindex_live_data_4", /*stat*/"226 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_data", /*idx*/"sqlite_autoindex_live_data_3", /*stat*/"226 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_data", /*idx*/"sqlite_autoindex_live_data_2", /*stat*/"226 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_data", /*idx*/"sqlite_autoindex_live_data_1", /*stat*/"226 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_bg_replace", /*idx*/"live_bg_replace_0_season_id", /*stat*/"1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"mv_list_data", /*idx*/"", /*stat*/23);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0007", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"loading_data", /*idx*/"loading_data_0_group_id", /*stat*/"1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quality_android", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_3dchara_spring", /*idx*/"live_3dchara_spring_0_music_id_1_chara_id", /*stat*/"37 5 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_3dchara_spring", /*idx*/"sqlite_autoindex_live_3dchara_spring_1", /*stat*/"37 5 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0006", /*idx*/"", /*stat*/5);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_detail", /*idx*/"party_detail_0_event_id", /*stat*/"16 16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_detail", /*idx*/"", /*stat*/1091);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"cyalume_color", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"user_rank", /*idx*/"", /*stat*/8);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"exchange_shop_item_bonus", /*idx*/"", /*stat*/6);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_bgm", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"user_level", /*idx*/"", /*stat*/300);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"mv_list_detail", /*idx*/"", /*stat*/557);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_theme", /*idx*/"", /*stat*/2);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_idol_extension", /*idx*/"", /*stat*/5);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_exchange_data", /*idx*/"", /*stat*/436);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0012", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"master_plus_group_3", /*idx*/"", /*stat*/21);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_tutorial", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"onetime_story", /*idx*/"onetime_story_0_story_id", /*stat*/"22 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"onetime_story", /*idx*/"sqlite_autoindex_onetime_story_1", /*stat*/"22 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_get_point_encore_rate", /*idx*/"sqlite_autoindex_medley_get_point_encore_rate_1", /*stat*/"5 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"master_plus_group_2", /*idx*/"", /*stat*/21);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_daily_bonus_drop", /*idx*/"", /*stat*/239);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_level_table", /*idx*/"", /*stat*/100);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0002", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_live_correction", /*idx*/"tour_live_correction_0_event_id_1_difficulty", /*stat*/"5 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"total_login_bonus", /*idx*/"", /*stat*/31);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_anime", /*idx*/"sqlite_autoindex_room_item_anime_1", /*stat*/"1502 6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"potential_value_vi", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_login_detail", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"leader_boost_rate_re", /*idx*/"leader_boost_rate_re_0_term_id", /*stat*/"63 21");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"stamp_data", /*idx*/"", /*stat*/61);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_bet_rate", /*idx*/"atapon_bet_rate_0_bet_type_id", /*stat*/"3 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shop", /*idx*/"", /*stat*/7);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_grid_data", /*idx*/"sqlite_autoindex_room_item_grid_data_1", /*stat*/"1 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_data_re", /*idx*/"party_data_re_0_type", /*stat*/"4 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_rate", /*idx*/"sqlite_autoindex_gacha_rate_1", /*stat*/"197 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_face_position", /*idx*/"sqlite_autoindex_chara_face_position_1", /*stat*/"336 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00009", /*idx*/"room_set_detail00009_0_set_id", /*stat*/"23 23");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"caravan_main_idol", /*idx*/"caravan_main_idol_0_main_idol", /*stat*/"17 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_storage_data", /*idx*/"", /*stat*/5);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_score_rank_reward", /*idx*/"medley_score_rank_reward_0_event_id", /*stat*/"3 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_available", /*idx*/"gacha_available_0_gacha_id", /*stat*/"33672 171");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_available", /*idx*/"sqlite_autoindex_gacha_available_1", /*stat*/"33672 171 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_daily_bonus_param", /*idx*/"", /*stat*/2);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_image_position", /*idx*/"", /*stat*/1284);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_evolve_item", /*idx*/"", /*stat*/12);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"exchange_shop_item", /*idx*/"", /*stat*/197);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_data", /*idx*/"item_data_0_item_category", /*stat*/"147 14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_category", /*idx*/"", /*stat*/15);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"leader_skill_data", /*idx*/"", /*stat*/76);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00006", /*idx*/"room_set_detail00006_0_set_id", /*stat*/"18 18");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"el_department", /*idx*/"", /*stat*/2);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_detail", /*idx*/"sqlite_autoindex_medley_detail_1", /*stat*/"15 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"weekly_mission", /*idx*/"weekly_mission_0_weekly_mission_id", /*stat*/"6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"text_data", /*idx*/"sqlite_autoindex_text_data_1", /*stat*/"1041 41 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_idol_present", /*idx*/"", /*stat*/2);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"potential_condition_fan", /*idx*/"", /*stat*/25);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_lv_type", /*idx*/"", /*stat*/12);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_story_detail", /*idx*/"tour_story_detail_0_event_id_1_type", /*stat*/"70 9 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"caravan_detail", /*idx*/"sqlite_autoindex_caravan_detail_1", /*stat*/"6 6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dress_color_data", /*idx*/"dress_color_data_0_chara_id_1_model_type", /*stat*/"42 2 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dress_color_data", /*idx*/"sqlite_autoindex_dress_color_data_1", /*stat*/"42 2 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0005", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"birthday_frame", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_trend_live", /*idx*/"tour_trend_live_0_event_id", /*stat*/"10 10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_main_idol", /*idx*/"party_main_idol_0_main_idol", /*stat*/"8 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_score_rank_disp", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_extension", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_data", /*idx*/"card_data_0_chara_id", /*stat*/"1284 8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_data", /*idx*/"card_data_0_solo_live", /*stat*/"1284 642");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_data", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"mission_target_live", /*idx*/"", /*stat*/7);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"special_card_skill_data", /*idx*/"", /*stat*/13);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"rm_assets", /*idx*/"rm_assets_0_name", /*stat*/"1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00007", /*idx*/"room_set_detail00007_0_set_id", /*stat*/"40 40");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_score_rank_disp", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_get_point_rate", /*idx*/"sqlite_autoindex_medley_get_point_rate_1", /*stat*/"5 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_item_num_rate", /*idx*/"", /*stat*/21);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"panel_mission_detail", /*idx*/"panel_mission_detail_0_campaign_id_1_rap", /*stat*/"27 27 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"panel_mission_detail", /*idx*/"panel_mission_detail_0_campaign_id", /*stat*/"27 27");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_theme", /*idx*/"", /*stat*/7);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_comments", /*idx*/"sqlite_autoindex_card_comments_1", /*stat*/"40754 28 6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"stamp_data_re", /*idx*/"", /*stat*/57);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_area", /*idx*/"tour_area_0_event_id", /*stat*/"7 7");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"leader_boost_rate", /*idx*/"leader_boost_rate_0_event_id", /*stat*/"21 21");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"banner", /*idx*/"", /*stat*/326);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"available_time_type", /*idx*/"", /*stat*/5);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00008", /*idx*/"room_set_detail00008_0_set_id", /*stat*/"23 23");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_boost_type", /*idx*/"skill_boost_type_0_skill_value_1_target_type", /*stat*/"21 21 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_category", /*idx*/"sqlite_autoindex_story_category_1", /*stat*/"288 72 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_set_detail00002", /*idx*/"room_set_detail00002_0_set_id", /*stat*/"38 38");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem", /*idx*/"", /*stat*/914);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_login_detail", /*idx*/"", /*stat*/464);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_location", /*idx*/"", /*stat*/445);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0004", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_score_rank_disp", /*idx*/"", /*stat*/3);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"daily_mission", /*idx*/"daily_mission_0_daily_mission_id", /*stat*/"4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"potential_value_vo", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"probability_type", /*idx*/"", /*stat*/5);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"potential_growth_condition", /*idx*/"potential_growth_condition_0_attribute", /*stat*/"30 10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"potential_growth_condition", /*idx*/"potential_growth_condition_0_potential_level", /*stat*/"30 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0011", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0008", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_point_reward", /*idx*/"atapon_point_reward_0_event_id", /*stat*/"79 79");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_achievement_reward", /*idx*/"live_achievement_reward_0_type_id", /*stat*/"108 12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tips", /*idx*/"", /*stat*/574);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"potential_value_da", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"potential_value_li", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_data", /*idx*/"", /*stat*/28);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_gift", /*idx*/"room_item_gift_0_id_1_room_item_id", /*stat*/"3 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_gift", /*idx*/"room_item_gift_0_room_item_id", /*stat*/"3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_data", /*idx*/"sqlite_autoindex_music_data_1", /*stat*/"176 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_rarity", /*idx*/"", /*stat*/8);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_score_rank_reward", /*idx*/"tour_score_rank_reward_0_event_id", /*stat*/"3 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"leader_skill_boost_rate", /*idx*/"leader_skill_boost_rate_0_position", /*stat*/"66 14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"prp_reward", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"jewel_shop", /*idx*/"jewel_shop_0_view_value", /*stat*/"9 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_category", /*idx*/"", /*stat*/11);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"premium_sc_detail", /*idx*/"premium_sc_detail_0_jewel_shop_id", /*stat*/"10 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_gallery_motion", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_detail_re", /*idx*/"party_detail_re_0_term_id", /*stat*/"48 16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"special_skill_data", /*idx*/"", /*stat*/7);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"announce_data", /*idx*/"", /*stat*/75);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"exchange_data", /*idx*/"", /*stat*/237);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_bonus", /*idx*/"", /*stat*/57);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"star_lesson_type", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_theme_preset_0001", /*idx*/"", /*stat*/21);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_live_exclude", /*idx*/"tour_live_exclude_0_event_id", /*stat*/"94 94");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tour_live_exclude", /*idx*/"sqlite_autoindex_tour_live_exclude_1", /*stat*/"94 94 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_groove_change", /*idx*/"sqlite_autoindex_medley_groove_change_1", /*stat*/"3 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"mo_p_rank_reward", /*idx*/"", /*stat*/36);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dress_data", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_story_detail", /*idx*/"medley_story_detail_0_event_id_1_type", /*stat*/"139 10 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_score_rate", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_data", /*idx*/"", /*stat*/562);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_point_rank_reward", /*idx*/"medley_point_rank_reward_0_event_id", /*stat*/"25 25");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_guest_character", /*idx*/"", /*stat*/4);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_notes_number", /*idx*/"sqlite_autoindex_live_notes_number_1", /*stat*/"857 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_grow", /*idx*/"", /*stat*/600);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_data", /*idx*/"chara_data_0_birth_month", /*stat*/"187 15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0003", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dress_target", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_levelup", /*idx*/"", /*stat*/15);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_flower_preset_type_0001", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_point_reward", /*idx*/"medley_point_reward_0_event_id", /*stat*/"81 81");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_point_rank_disp", /*idx*/"", /*stat*/8);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_data_position", /*idx*/"", /*stat*/169);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_levelup_item", /*idx*/"", /*stat*/20);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_score_rank_reward", /*idx*/"atapon_score_rank_reward_0_event_id", /*stat*/"3 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"live_season_data", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"memorial_story_open", /*idx*/"", /*stat*/10);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"party_exchange_data", /*idx*/"", /*stat*/124);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"star_rank_effect", /*idx*/"", /*stat*/20);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_story_detail", /*idx*/"atapon_story_detail_0_event_id_1_type", /*stat*/"241 9 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_effect", /*idx*/"", /*stat*/17);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"index_skill_data", /*idx*/"", /*stat*/13);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"birthday_bg", /*idx*/"", /*stat*/13);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"medley_data", /*idx*/"", /*stat*/1);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_detail", /*idx*/"atapon_detail_0_event_id_1_live_detail_id", /*stat*/"5 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"atapon_detail", /*idx*/"atapon_detail_0_event_id", /*stat*/"5 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sp_login_bonus_detail", /*idx*/"sp_login_bonus_detail_0_type", /*stat*/"12 12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"index_leader_skill_data", /*idx*/"", /*stat*/8);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"card_level", /*idx*/"", /*stat*/90);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_detail", /*idx*/"story_detail_0_category_id", /*stat*/"3013 11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_detail", /*idx*/"story_detail_0_story_detail_type", /*stat*/"3013 377");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_detail", /*idx*/"story_detail_0_open_chara_id_1_chapter", /*stat*/"3013 17 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_detail", /*idx*/"sqlite_autoindex_story_detail_1", /*stat*/"3013 1");
CREATE INDEX 'card_data_0_solo_live' on 'card_data'('solo_live')CREATE INDEX 'card_data_0_chara_id' on 'card_data'('chara_id')CREATE INDEX 'skill_boost_type_0_skill_value_1_target_type' on 'skill_boost_type'('skill_value','target_type')CREATE INDEX 'chara_data_0_birth_month' on 'chara_data'('birth_month')CREATE INDEX 'potential_growth_condition_0_potential_level' on 'potential_growth_condition'('potential_level')CREATE INDEX 'potential_growth_condition_0_attribute' on 'potential_growth_condition'('attribute')CREATE INDEX 'dress_color_data_0_chara_id_1_model_type' on 'dress_color_data'('chara_id','model_type')CREATE INDEX 'skill_life_value_0_life_value' on 'skill_life_value'('life_value')CREATE INDEX 'story_detail_0_open_chara_id_1_chapter' on 'story_detail'('open_chara_id','chapter')CREATE INDEX 'story_detail_0_story_detail_type' on 'story_detail'('story_detail_type')CREATE INDEX 'story_detail_0_category_id' on 'story_detail'('category_id')CREATE INDEX 'onetime_story_0_story_id' on 'onetime_story'('story_id')CREATE INDEX 'live_3dchara_spring_0_music_id_1_chara_id' on 'live_3dchara_spring'('music_id','chara_id')CREATE INDEX 'live_achievement_reward_0_type_id' on 'live_achievement_reward'('type_id')CREATE INDEX 'live_bg_replace_0_season_id' on 'live_bg_replace'('season_id')CREATE INDEX 'music_vocalist_0_music_data_id' on 'music_vocalist'('music_data_id')CREATE INDEX 'music_vocalist_0_chara_id' on 'music_vocalist'('chara_id')CREATE INDEX 'room_item_gift_0_room_item_id' on 'room_item_gift'('room_item_id')CREATE INDEX 'room_item_gift_0_id_1_room_item_id' on 'room_item_gift'('id','room_item_id')CREATE INDEX 'room_item_preset_0_event_id' on 'room_item_preset'('event_id')CREATE INDEX 'gacha_available_0_gacha_id' on 'gacha_available'('gacha_id')CREATE INDEX 'gacha_data_0_base_id' on 'gacha_data'('base_id')CREATE INDEX 'premium_sc_list_0_cost_id' on 'premium_sc_list'('cost_id')CREATE INDEX 'premium_sc_detail_0_jewel_shop_id' on 'premium_sc_detail'('jewel_shop_id')CREATE INDEX 'gacha_sp_effect_0_gacha_id' on 'gacha_sp_effect'('gacha_id')CREATE INDEX 'gacha_sp_effect_0_card_id' on 'gacha_sp_effect'('card_id')CREATE INDEX 'gacha_l_e_list_0_g_id' on 'gacha_l_e_list'('g_id')CREATE INDEX 'login_bonus_detail_0_campaign_id_1_rap_2_count' on 'login_bonus_detail'('campaign_id','rap','count')CREATE INDEX 'sp_login_bonus_detail_0_type' on 'sp_login_bonus_detail'('type')CREATE INDEX 'item_data_0_item_category' on 'item_data'('item_category')CREATE INDEX 'sp_campaign_reward_0_campaign_id' on 'sp_campaign_reward'('campaign_id')CREATE INDEX 'sp_campaign_reward_0_campaign_id_1_rank' on 'sp_campaign_reward'('campaign_id','rank')CREATE INDEX 'cookie_swap_mission_0_mission_id' on 'cookie_swap_mission'('mission_id')CREATE INDEX 'jewel_shop_0_view_value' on 'jewel_shop'('view_value')CREATE INDEX 'individual_tutorial_0_id' on 'individual_tutorial'('id')CREATE INDEX 'event_available_0_event_id' on 'event_available'('event_id')CREATE INDEX 'event_data_0_type' on 'event_data'('type')CREATE INDEX 'event_beta_data_0_type' on 'event_beta_data'('type')CREATE INDEX 'leader_boost_rate_0_event_id' on 'leader_boost_rate'('event_id')CREATE INDEX 'caravan_data_0_event_id' on 'caravan_data'('event_id')CREATE INDEX 'caravan_data_0_event_id_1_date_order' on 'caravan_data'('event_id','date_order')CREATE INDEX 'caravan_main_idol_0_main_idol' on 'caravan_main_idol'('main_idol')CREATE INDEX 'daily_mission_0_daily_mission_id' on 'daily_mission'('daily_mission_id')CREATE INDEX 'weekly_mission_0_weekly_mission_id' on 'weekly_mission'('weekly_mission_id')CREATE INDEX 'normal_mission_0_step_group_id_1_step_order' on 'normal_mission'('step_group_id','step_order')CREATE INDEX 'normal_mission_0_normal_mission_id' on 'normal_mission'('normal_mission_id')CREATE INDEX 'limited_mission_0_limited_mission_id' on 'limited_mission'('limited_mission_id')CREATE INDEX 'panel_mission_comp_reward_0_campaign_id' on 'panel_mission_comp_reward'('campaign_id')CREATE INDEX 'panel_mission_comp_reward_0_campaign_id_1_rap' on 'panel_mission_comp_reward'('campaign_id','rap')CREATE INDEX 'panel_mission_detail_0_campaign_id' on 'panel_mission_detail'('campaign_id')CREATE INDEX 'panel_mission_detail_0_campaign_id_1_rap' on 'panel_mission_detail'('campaign_id','rap')CREATE INDEX 'atapon_bet_rate_0_bet_type_id' on 'atapon_bet_rate'('bet_type_id')CREATE INDEX 'atapon_detail_0_event_id' on 'atapon_detail'('event_id')CREATE INDEX 'atapon_detail_0_event_id_1_live_detail_id' on 'atapon_detail'('event_id','live_detail_id')CREATE INDEX 'atapon_point_rank_reward_0_event_id' on 'atapon_point_rank_reward'('event_id')CREATE INDEX 'atapon_point_reward_0_event_id' on 'atapon_point_reward'('event_id')CREATE INDEX 'atapon_score_rank_reward_0_event_id' on 'atapon_score_rank_reward'('event_id')CREATE INDEX 'atapon_story_detail_0_event_id_1_type' on 'atapon_story_detail'('event_id','type')CREATE INDEX 'medley_point_rank_reward_0_event_id' on 'medley_point_rank_reward'('event_id')CREATE INDEX 'medley_point_reward_0_event_id' on 'medley_point_reward'('event_id')CREATE INDEX 'medley_score_rank_reward_0_event_id' on 'medley_score_rank_reward'('event_id')CREATE INDEX 'medley_story_detail_0_event_id_1_type' on 'medley_story_detail'('event_id','type')CREATE INDEX 'medley_vibration_change_0_event_id_1_difficulty_type' on 'medley_vibration_change'('event_id','difficulty_type')CREATE INDEX 'medley_vibration_rank_0_event_id_1_difficulty_type' on 'medley_vibration_rank'('event_id','difficulty_type')CREATE INDEX 'party_detail_0_event_id' on 'party_detail'('event_id')CREATE INDEX 'party_main_idol_0_main_idol' on 'party_main_idol'('main_idol')CREATE INDEX 'party_point_reward_0_event_id' on 'party_point_reward'('event_id')CREATE INDEX 'leader_skill_boost_rate_0_position' on 'leader_skill_boost_rate'('position')CREATE INDEX 'tour_point_reward_0_event_id' on 'tour_point_reward'('event_id')CREATE INDEX 'tour_audience_reward_0_event_id' on 'tour_audience_reward'('event_id')CREATE INDEX 'tour_live_correction_0_event_id_1_difficulty' on 'tour_live_correction'('event_id','difficulty')CREATE INDEX 'tour_story_detail_0_event_id_1_type' on 'tour_story_detail'('event_id','type')CREATE INDEX 'tour_area_0_event_id' on 'tour_area'('event_id')CREATE INDEX 'tour_live_detail_0_event_id' on 'tour_live_detail'('event_id')CREATE INDEX 'tour_live_detail_0_event_id_1_area_id_2_area_index' on 'tour_live_detail'('event_id','area_id','area_index')CREATE INDEX 'tour_trend_live_0_event_id' on 'tour_trend_live'('event_id')CREATE INDEX 'tour_live_exclude_0_event_id' on 'tour_live_exclude'('event_id')CREATE INDEX 'tour_score_rank_reward_0_event_id' on 'tour_score_rank_reward'('event_id')CREATE INDEX 'tour_live_item_0_event_id' on 'tour_live_item'('event_id')CREATE INDEX 'announce_anim_detail_data_0_id' on 'announce_anim_detail_data'('id')CREATE INDEX 'loading_data_0_group_id' on 'loading_data'('group_id')CREATE INDEX 'party_data_re_0_type' on 'party_data_re'('type')CREATE INDEX 'party_detail_re_0_term_id' on 'party_detail_re'('term_id')CREATE INDEX 'leader_skill_boost_rate_re_0_position' on 'leader_skill_boost_rate_re'('position')CREATE INDEX 'leader_boost_rate_re_0_term_id' on 'leader_boost_rate_re'('term_id')CREATE INDEX 'room_set_detail00001_0_set_id' on 'room_set_detail00001'('set_id')CREATE INDEX 'room_set_detail00002_0_set_id' on 'room_set_detail00002'('set_id')CREATE INDEX 'room_set_detail00003_0_set_id' on 'room_set_detail00003'('set_id')CREATE INDEX 'room_set_detail00004_0_set_id' on 'room_set_detail00004'('set_id')CREATE INDEX 'room_set_detail00005_0_set_id' on 'room_set_detail00005'('set_id')CREATE INDEX 'room_set_detail00006_0_set_id' on 'room_set_detail00006'('set_id')CREATE INDEX 'room_set_detail00007_0_set_id' on 'room_set_detail00007'('set_id')CREATE INDEX 'room_set_detail00008_0_set_id' on 'room_set_detail00008'('set_id')CREATE INDEX 'room_set_detail00009_0_set_id' on 'room_set_detail00009'('set_id')CREATE INDEX 'mv_list_performer_0_stage_id' on 'mv_list_performer'('stage_id')CREATE INDEX 'rm_assets_0_name' on 'rm_assets'('name')