CREATE TABLE 'story_category' ('id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'chara_type' INTEGER NOT NULL, 'chara_id' INTEGER NOT NULL, 'title' TEXT NOT NULL, 'sub_title' TEXT NOT NULL, 'disp_order' INTEGER NOT NULL, PRIMARY KEY('id'), UNIQUE('type','disp_order'))
INSERT INTO `story_category` VALUES (/*id*/1, /*type*/2, /*chara_type*/1, /*chara_id*/101, /*title*/"島村卯月", /*sub_title*/"", /*disp_order*/1);
INSERT INTO `story_category` VALUES (/*id*/2, /*type*/2, /*chara_type*/1, /*chara_id*/102, /*title*/"中野有香", /*sub_title*/"", /*disp_order*/2);
INSERT INTO `story_category` VALUES (/*id*/3, /*type*/2, /*chara_type*/1, /*chara_id*/103, /*title*/"水本ゆかり", /*sub_title*/"", /*disp_order*/3);
INSERT INTO `story_category` VALUES (/*id*/4, /*type*/2, /*chara_type*/1, /*chara_id*/104, /*title*/"福山舞", /*sub_title*/"", /*disp_order*/4);
INSERT INTO `story_category` VALUES (/*id*/5, /*type*/2, /*chara_type*/1, /*chara_id*/105, /*title*/"椎名法子", /*sub_title*/"", /*disp_order*/5);
INSERT INTO `story_category` VALUES (/*id*/6, /*type*/2, /*chara_type*/1, /*chara_id*/106, /*title*/"今井加奈", /*sub_title*/"", /*disp_order*/6);
INSERT INTO `story_category` VALUES (/*id*/7, /*type*/2, /*chara_type*/1, /*chara_id*/107, /*title*/"持田亜里沙", /*sub_title*/"", /*disp_order*/7);
INSERT INTO `story_category` VALUES (/*id*/8, /*type*/2, /*chara_type*/1, /*chara_id*/108, /*title*/"三村かな子", /*sub_title*/"", /*disp_order*/8);
INSERT INTO `story_category` VALUES (/*id*/9, /*type*/2, /*chara_type*/1, /*chara_id*/109, /*title*/"奥山沙織", /*sub_title*/"", /*disp_order*/9);
INSERT INTO `story_category` VALUES (/*id*/10, /*type*/2, /*chara_type*/1, /*chara_id*/110, /*title*/"間中美里", /*sub_title*/"", /*disp_order*/10);
INSERT INTO `story_category` VALUES (/*id*/11, /*type*/2, /*chara_type*/1, /*chara_id*/111, /*title*/"小日向美穂", /*sub_title*/"", /*disp_order*/11);
INSERT INTO `story_category` VALUES (/*id*/12, /*type*/2, /*chara_type*/1, /*chara_id*/112, /*title*/"緒方智絵里", /*sub_title*/"", /*disp_order*/12);
INSERT INTO `story_category` VALUES (/*id*/13, /*type*/2, /*chara_type*/1, /*chara_id*/113, /*title*/"五十嵐響子", /*sub_title*/"", /*disp_order*/13);
INSERT INTO `story_category` VALUES (/*id*/14, /*type*/2, /*chara_type*/1, /*chara_id*/114, /*title*/"柳瀬美由紀", /*sub_title*/"", /*disp_order*/14);
INSERT INTO `story_category` VALUES (/*id*/15, /*type*/2, /*chara_type*/1, /*chara_id*/115, /*title*/"櫻井桃華", /*sub_title*/"", /*disp_order*/15);
INSERT INTO `story_category` VALUES (/*id*/16, /*type*/2, /*chara_type*/1, /*chara_id*/116, /*title*/"江上椿", /*sub_title*/"", /*disp_order*/16);
INSERT INTO `story_category` VALUES (/*id*/17, /*type*/2, /*chara_type*/1, /*chara_id*/117, /*title*/"長富蓮実", /*sub_title*/"", /*disp_order*/17);
INSERT INTO `story_category` VALUES (/*id*/18, /*type*/2, /*chara_type*/1, /*chara_id*/118, /*title*/"横山千佳", /*sub_title*/"", /*disp_order*/18);
INSERT INTO `story_category` VALUES (/*id*/19, /*type*/2, /*chara_type*/1, /*chara_id*/119, /*title*/"関裕美", /*sub_title*/"", /*disp_order*/19);
INSERT INTO `story_category` VALUES (/*id*/20, /*type*/2, /*chara_type*/1, /*chara_id*/120, /*title*/"太田優", /*sub_title*/"", /*disp_order*/20);
INSERT INTO `story_category` VALUES (/*id*/21, /*type*/2, /*chara_type*/1, /*chara_id*/121, /*title*/"棟方愛海", /*sub_title*/"", /*disp_order*/21);
INSERT INTO `story_category` VALUES (/*id*/22, /*type*/2, /*chara_type*/1, /*chara_id*/122, /*title*/"藤本里奈", /*sub_title*/"", /*disp_order*/22);
INSERT INTO `story_category` VALUES (/*id*/23, /*type*/2, /*chara_type*/1, /*chara_id*/123, /*title*/"大原みちる", /*sub_title*/"", /*disp_order*/23);
INSERT INTO `story_category` VALUES (/*id*/24, /*type*/2, /*chara_type*/1, /*chara_id*/124, /*title*/"遊佐こずえ", /*sub_title*/"", /*disp_order*/24);
INSERT INTO `story_category` VALUES (/*id*/25, /*type*/2, /*chara_type*/1, /*chara_id*/125, /*title*/"大沼くるみ", /*sub_title*/"", /*disp_order*/25);
INSERT INTO `story_category` VALUES (/*id*/26, /*type*/2, /*chara_type*/1, /*chara_id*/126, /*title*/"一ノ瀬志希", /*sub_title*/"", /*disp_order*/26);
INSERT INTO `story_category` VALUES (/*id*/27, /*type*/2, /*chara_type*/1, /*chara_id*/127, /*title*/"前川みく", /*sub_title*/"", /*disp_order*/27);
INSERT INTO `story_category` VALUES (/*id*/28, /*type*/2, /*chara_type*/1, /*chara_id*/128, /*title*/"赤西瑛梨華", /*sub_title*/"", /*disp_order*/28);
INSERT INTO `story_category` VALUES (/*id*/29, /*type*/2, /*chara_type*/1, /*chara_id*/129, /*title*/"松原早耶", /*sub_title*/"", /*disp_order*/29);
INSERT INTO `story_category` VALUES (/*id*/30, /*type*/2, /*chara_type*/1, /*chara_id*/130, /*title*/"相原雪乃", /*sub_title*/"", /*disp_order*/30);
INSERT INTO `story_category` VALUES (/*id*/31, /*type*/2, /*chara_type*/1, /*chara_id*/131, /*title*/"宮本フレデリカ", /*sub_title*/"", /*disp_order*/31);
INSERT INTO `story_category` VALUES (/*id*/32, /*type*/2, /*chara_type*/1, /*chara_id*/132, /*title*/"小早川紗枝", /*sub_title*/"", /*disp_order*/32);
INSERT INTO `story_category` VALUES (/*id*/33, /*type*/2, /*chara_type*/1, /*chara_id*/133, /*title*/"西園寺琴歌", /*sub_title*/"", /*disp_order*/33);
INSERT INTO `story_category` VALUES (/*id*/34, /*type*/2, /*chara_type*/1, /*chara_id*/134, /*title*/"双葉杏", /*sub_title*/"", /*disp_order*/34);
INSERT INTO `story_category` VALUES (/*id*/35, /*type*/2, /*chara_type*/1, /*chara_id*/135, /*title*/"楊菲菲", /*sub_title*/"", /*disp_order*/35);
INSERT INTO `story_category` VALUES (/*id*/36, /*type*/2, /*chara_type*/1, /*chara_id*/136, /*title*/"桃井あずき", /*sub_title*/"", /*disp_order*/36);
INSERT INTO `story_category` VALUES (/*id*/37, /*type*/2, /*chara_type*/1, /*chara_id*/137, /*title*/"涼宮星花", /*sub_title*/"", /*disp_order*/37);
INSERT INTO `story_category` VALUES (/*id*/38, /*type*/2, /*chara_type*/1, /*chara_id*/138, /*title*/"月宮雅", /*sub_title*/"", /*disp_order*/38);
INSERT INTO `story_category` VALUES (/*id*/39, /*type*/2, /*chara_type*/1, /*chara_id*/139, /*title*/"兵藤レナ", /*sub_title*/"", /*disp_order*/39);
INSERT INTO `story_category` VALUES (/*id*/40, /*type*/2, /*chara_type*/1, /*chara_id*/140, /*title*/"丹羽仁美", /*sub_title*/"", /*disp_order*/40);
INSERT INTO `story_category` VALUES (/*id*/41, /*type*/2, /*chara_type*/1, /*chara_id*/141, /*title*/"道明寺歌鈴", /*sub_title*/"", /*disp_order*/41);
INSERT INTO `story_category` VALUES (/*id*/45, /*type*/2, /*chara_type*/1, /*chara_id*/145, /*title*/"柳清良", /*sub_title*/"", /*disp_order*/45);
INSERT INTO `story_category` VALUES (/*id*/47, /*type*/2, /*chara_type*/1, /*chara_id*/147, /*title*/"井村雪菜", /*sub_title*/"", /*disp_order*/47);
INSERT INTO `story_category` VALUES (/*id*/48, /*type*/2, /*chara_type*/1, /*chara_id*/148, /*title*/"日下部若葉", /*sub_title*/"", /*disp_order*/48);
INSERT INTO `story_category` VALUES (/*id*/49, /*type*/2, /*chara_type*/1, /*chara_id*/149, /*title*/"榊原里美", /*sub_title*/"", /*disp_order*/49);
INSERT INTO `story_category` VALUES (/*id*/50, /*type*/2, /*chara_type*/1, /*chara_id*/150, /*title*/"輿水幸子", /*sub_title*/"", /*disp_order*/50);
INSERT INTO `story_category` VALUES (/*id*/51, /*type*/2, /*chara_type*/1, /*chara_id*/151, /*title*/"安斎都", /*sub_title*/"", /*disp_order*/51);
INSERT INTO `story_category` VALUES (/*id*/52, /*type*/2, /*chara_type*/1, /*chara_id*/152, /*title*/"浅野風香", /*sub_title*/"", /*disp_order*/52);
INSERT INTO `story_category` VALUES (/*id*/53, /*type*/2, /*chara_type*/1, /*chara_id*/153, /*title*/"大西由里子", /*sub_title*/"", /*disp_order*/53);
INSERT INTO `story_category` VALUES (/*id*/54, /*type*/2, /*chara_type*/1, /*chara_id*/154, /*title*/"安部菜々", /*sub_title*/"", /*disp_order*/54);
INSERT INTO `story_category` VALUES (/*id*/55, /*type*/2, /*chara_type*/1, /*chara_id*/155, /*title*/"工藤忍", /*sub_title*/"", /*disp_order*/55);
INSERT INTO `story_category` VALUES (/*id*/56, /*type*/2, /*chara_type*/1, /*chara_id*/156, /*title*/"栗原ネネ", /*sub_title*/"", /*disp_order*/56);
INSERT INTO `story_category` VALUES (/*id*/57, /*type*/2, /*chara_type*/1, /*chara_id*/157, /*title*/"古賀小春", /*sub_title*/"", /*disp_order*/57);
INSERT INTO `story_category` VALUES (/*id*/58, /*type*/2, /*chara_type*/1, /*chara_id*/158, /*title*/"クラリス", /*sub_title*/"", /*disp_order*/58);
INSERT INTO `story_category` VALUES (/*id*/59, /*type*/2, /*chara_type*/1, /*chara_id*/159, /*title*/"佐久間まゆ", /*sub_title*/"", /*disp_order*/59);
INSERT INTO `story_category` VALUES (/*id*/60, /*type*/2, /*chara_type*/1, /*chara_id*/160, /*title*/"村松さくら", /*sub_title*/"", /*disp_order*/60);
INSERT INTO `story_category` VALUES (/*id*/61, /*type*/2, /*chara_type*/1, /*chara_id*/161, /*title*/"白菊ほたる", /*sub_title*/"", /*disp_order*/61);
INSERT INTO `story_category` VALUES (/*id*/62, /*type*/2, /*chara_type*/1, /*chara_id*/162, /*title*/"早坂美玲", /*sub_title*/"", /*disp_order*/62);
INSERT INTO `story_category` VALUES (/*id*/63, /*type*/2, /*chara_type*/1, /*chara_id*/163, /*title*/"有浦柑奈", /*sub_title*/"", /*disp_order*/63);
INSERT INTO `story_category` VALUES (/*id*/64, /*type*/2, /*chara_type*/1, /*chara_id*/164, /*title*/"乙倉悠貴", /*sub_title*/"", /*disp_order*/64);
INSERT INTO `story_category` VALUES (/*id*/65, /*type*/2, /*chara_type*/1, /*chara_id*/165, /*title*/"原田美世", /*sub_title*/"", /*disp_order*/65);
INSERT INTO `story_category` VALUES (/*id*/66, /*type*/2, /*chara_type*/1, /*chara_id*/166, /*title*/"池袋晶葉", /*sub_title*/"", /*disp_order*/66);
INSERT INTO `story_category` VALUES (/*id*/67, /*type*/2, /*chara_type*/2, /*chara_id*/167, /*title*/"渋谷凛", /*sub_title*/"", /*disp_order*/67);
INSERT INTO `story_category` VALUES (/*id*/68, /*type*/2, /*chara_type*/2, /*chara_id*/168, /*title*/"黒川千秋", /*sub_title*/"", /*disp_order*/68);
INSERT INTO `story_category` VALUES (/*id*/69, /*type*/2, /*chara_type*/2, /*chara_id*/169, /*title*/"松本沙理奈", /*sub_title*/"", /*disp_order*/69);
INSERT INTO `story_category` VALUES (/*id*/70, /*type*/2, /*chara_type*/2, /*chara_id*/170, /*title*/"桐野アヤ", /*sub_title*/"", /*disp_order*/70);
INSERT INTO `story_category` VALUES (/*id*/71, /*type*/2, /*chara_type*/2, /*chara_id*/171, /*title*/"高橋礼子", /*sub_title*/"", /*disp_order*/71);
INSERT INTO `story_category` VALUES (/*id*/72, /*type*/2, /*chara_type*/2, /*chara_id*/172, /*title*/"相川千夏", /*sub_title*/"", /*disp_order*/72);
INSERT INTO `story_category` VALUES (/*id*/73, /*type*/2, /*chara_type*/2, /*chara_id*/173, /*title*/"川島瑞樹", /*sub_title*/"", /*disp_order*/73);
INSERT INTO `story_category` VALUES (/*id*/74, /*type*/2, /*chara_type*/2, /*chara_id*/174, /*title*/"神谷奈緒", /*sub_title*/"", /*disp_order*/74);
INSERT INTO `story_category` VALUES (/*id*/75, /*type*/2, /*chara_type*/2, /*chara_id*/175, /*title*/"上条春菜", /*sub_title*/"", /*disp_order*/75);
INSERT INTO `story_category` VALUES (/*id*/76, /*type*/2, /*chara_type*/2, /*chara_id*/176, /*title*/"荒木比奈", /*sub_title*/"", /*disp_order*/76);
INSERT INTO `story_category` VALUES (/*id*/77, /*type*/2, /*chara_type*/2, /*chara_id*/177, /*title*/"東郷あい", /*sub_title*/"", /*disp_order*/77);
INSERT INTO `story_category` VALUES (/*id*/78, /*type*/2, /*chara_type*/2, /*chara_id*/178, /*title*/"多田李衣菜", /*sub_title*/"", /*disp_order*/78);
INSERT INTO `story_category` VALUES (/*id*/79, /*type*/2, /*chara_type*/2, /*chara_id*/179, /*title*/"水木聖來", /*sub_title*/"", /*disp_order*/79);
INSERT INTO `story_category` VALUES (/*id*/80, /*type*/2, /*chara_type*/2, /*chara_id*/180, /*title*/"佐々木千枝", /*sub_title*/"", /*disp_order*/80);
INSERT INTO `story_category` VALUES (/*id*/81, /*type*/2, /*chara_type*/2, /*chara_id*/181, /*title*/"三船美優", /*sub_title*/"", /*disp_order*/81);
INSERT INTO `story_category` VALUES (/*id*/82, /*type*/2, /*chara_type*/2, /*chara_id*/182, /*title*/"服部瞳子", /*sub_title*/"", /*disp_order*/82);
INSERT INTO `story_category` VALUES (/*id*/83, /*type*/2, /*chara_type*/2, /*chara_id*/183, /*title*/"木場真奈美", /*sub_title*/"", /*disp_order*/83);
INSERT INTO `story_category` VALUES (/*id*/84, /*type*/2, /*chara_type*/2, /*chara_id*/184, /*title*/"藤原肇", /*sub_title*/"", /*disp_order*/84);
INSERT INTO `story_category` VALUES (/*id*/85, /*type*/2, /*chara_type*/2, /*chara_id*/185, /*title*/"新田美波", /*sub_title*/"", /*disp_order*/85);
INSERT INTO `story_category` VALUES (/*id*/86, /*type*/2, /*chara_type*/2, /*chara_id*/186, /*title*/"水野翠", /*sub_title*/"", /*disp_order*/86);
INSERT INTO `story_category` VALUES (/*id*/87, /*type*/2, /*chara_type*/2, /*chara_id*/187, /*title*/"古澤頼子", /*sub_title*/"", /*disp_order*/87);
INSERT INTO `story_category` VALUES (/*id*/88, /*type*/2, /*chara_type*/2, /*chara_id*/188, /*title*/"橘ありす", /*sub_title*/"", /*disp_order*/88);
INSERT INTO `story_category` VALUES (/*id*/89, /*type*/2, /*chara_type*/2, /*chara_id*/189, /*title*/"鷺沢文香", /*sub_title*/"", /*disp_order*/89);
INSERT INTO `story_category` VALUES (/*id*/90, /*type*/2, /*chara_type*/2, /*chara_id*/190, /*title*/"八神マキノ", /*sub_title*/"", /*disp_order*/90);
INSERT INTO `story_category` VALUES (/*id*/91, /*type*/2, /*chara_type*/2, /*chara_id*/191, /*title*/"ライラ", /*sub_title*/"", /*disp_order*/91);
INSERT INTO `story_category` VALUES (/*id*/92, /*type*/2, /*chara_type*/2, /*chara_id*/192, /*title*/"浅利七海", /*sub_title*/"", /*disp_order*/92);
INSERT INTO `story_category` VALUES (/*id*/93, /*type*/2, /*chara_type*/2, /*chara_id*/193, /*title*/"ヘレン", /*sub_title*/"", /*disp_order*/93);
INSERT INTO `story_category` VALUES (/*id*/94, /*type*/2, /*chara_type*/2, /*chara_id*/194, /*title*/"松永涼", /*sub_title*/"", /*disp_order*/94);
INSERT INTO `story_category` VALUES (/*id*/95, /*type*/2, /*chara_type*/2, /*chara_id*/195, /*title*/"小室千奈美", /*sub_title*/"", /*disp_order*/95);
INSERT INTO `story_category` VALUES (/*id*/96, /*type*/2, /*chara_type*/2, /*chara_id*/196, /*title*/"高峯のあ", /*sub_title*/"", /*disp_order*/96);
INSERT INTO `story_category` VALUES (/*id*/97, /*type*/2, /*chara_type*/2, /*chara_id*/197, /*title*/"高垣楓", /*sub_title*/"", /*disp_order*/97);
INSERT INTO `story_category` VALUES (/*id*/98, /*type*/2, /*chara_type*/2, /*chara_id*/198, /*title*/"神崎蘭子", /*sub_title*/"", /*disp_order*/98);
INSERT INTO `story_category` VALUES (/*id*/99, /*type*/2, /*chara_type*/2, /*chara_id*/199, /*title*/"伊集院惠", /*sub_title*/"", /*disp_order*/99);
INSERT INTO `story_category` VALUES (/*id*/100, /*type*/2, /*chara_type*/2, /*chara_id*/200, /*title*/"柊志乃", /*sub_title*/"", /*disp_order*/100);
INSERT INTO `story_category` VALUES (/*id*/101, /*type*/2, /*chara_type*/2, /*chara_id*/201, /*title*/"北条加蓮", /*sub_title*/"", /*disp_order*/101);
INSERT INTO `story_category` VALUES (/*id*/102, /*type*/2, /*chara_type*/2, /*chara_id*/202, /*title*/"ケイト", /*sub_title*/"", /*disp_order*/102);
INSERT INTO `story_category` VALUES (/*id*/103, /*type*/2, /*chara_type*/2, /*chara_id*/203, /*title*/"瀬名詩織", /*sub_title*/"", /*disp_order*/103);
INSERT INTO `story_category` VALUES (/*id*/104, /*type*/2, /*chara_type*/2, /*chara_id*/204, /*title*/"綾瀬穂乃香", /*sub_title*/"", /*disp_order*/104);
INSERT INTO `story_category` VALUES (/*id*/105, /*type*/2, /*chara_type*/2, /*chara_id*/205, /*title*/"佐城雪美", /*sub_title*/"", /*disp_order*/105);
INSERT INTO `story_category` VALUES (/*id*/110, /*type*/2, /*chara_type*/2, /*chara_id*/210, /*title*/"篠原礼", /*sub_title*/"", /*disp_order*/110);
INSERT INTO `story_category` VALUES (/*id*/111, /*type*/2, /*chara_type*/2, /*chara_id*/211, /*title*/"和久井留美", /*sub_title*/"", /*disp_order*/111);
INSERT INTO `story_category` VALUES (/*id*/112, /*type*/2, /*chara_type*/2, /*chara_id*/212, /*title*/"吉岡沙紀", /*sub_title*/"", /*disp_order*/112);
INSERT INTO `story_category` VALUES (/*id*/113, /*type*/2, /*chara_type*/2, /*chara_id*/213, /*title*/"梅木音葉", /*sub_title*/"", /*disp_order*/113);
INSERT INTO `story_category` VALUES (/*id*/114, /*type*/2, /*chara_type*/2, /*chara_id*/214, /*title*/"白坂小梅", /*sub_title*/"", /*disp_order*/114);
INSERT INTO `story_category` VALUES (/*id*/115, /*type*/2, /*chara_type*/2, /*chara_id*/215, /*title*/"岸部彩華", /*sub_title*/"", /*disp_order*/115);
INSERT INTO `story_category` VALUES (/*id*/116, /*type*/2, /*chara_type*/2, /*chara_id*/216, /*title*/"氏家むつみ", /*sub_title*/"", /*disp_order*/116);
INSERT INTO `story_category` VALUES (/*id*/117, /*type*/2, /*chara_type*/2, /*chara_id*/217, /*title*/"西川保奈美", /*sub_title*/"", /*disp_order*/117);
INSERT INTO `story_category` VALUES (/*id*/118, /*type*/2, /*chara_type*/2, /*chara_id*/218, /*title*/"成宮由愛", /*sub_title*/"", /*disp_order*/118);
INSERT INTO `story_category` VALUES (/*id*/119, /*type*/2, /*chara_type*/2, /*chara_id*/219, /*title*/"藤居朋", /*sub_title*/"", /*disp_order*/119);
INSERT INTO `story_category` VALUES (/*id*/120, /*type*/2, /*chara_type*/2, /*chara_id*/220, /*title*/"塩見周子", /*sub_title*/"", /*disp_order*/120);
INSERT INTO `story_category` VALUES (/*id*/121, /*type*/2, /*chara_type*/2, /*chara_id*/221, /*title*/"脇山珠美", /*sub_title*/"", /*disp_order*/121);
INSERT INTO `story_category` VALUES (/*id*/122, /*type*/2, /*chara_type*/2, /*chara_id*/222, /*title*/"岡崎泰葉", /*sub_title*/"", /*disp_order*/122);
INSERT INTO `story_category` VALUES (/*id*/123, /*type*/2, /*chara_type*/2, /*chara_id*/223, /*title*/"速水奏", /*sub_title*/"", /*disp_order*/123);
INSERT INTO `story_category` VALUES (/*id*/124, /*type*/2, /*chara_type*/2, /*chara_id*/224, /*title*/"大石泉", /*sub_title*/"", /*disp_order*/124);
INSERT INTO `story_category` VALUES (/*id*/125, /*type*/2, /*chara_type*/2, /*chara_id*/225, /*title*/"松尾千鶴", /*sub_title*/"", /*disp_order*/125);
INSERT INTO `story_category` VALUES (/*id*/126, /*type*/2, /*chara_type*/2, /*chara_id*/226, /*title*/"森久保乃々", /*sub_title*/"", /*disp_order*/126);
INSERT INTO `story_category` VALUES (/*id*/127, /*type*/2, /*chara_type*/2, /*chara_id*/227, /*title*/"アナスタシア", /*sub_title*/"", /*disp_order*/127);
INSERT INTO `story_category` VALUES (/*id*/128, /*type*/2, /*chara_type*/2, /*chara_id*/228, /*title*/"大和亜季", /*sub_title*/"", /*disp_order*/128);
INSERT INTO `story_category` VALUES (/*id*/129, /*type*/2, /*chara_type*/2, /*chara_id*/229, /*title*/"結城晴", /*sub_title*/"", /*disp_order*/129);
INSERT INTO `story_category` VALUES (/*id*/130, /*type*/2, /*chara_type*/2, /*chara_id*/230, /*title*/"二宮飛鳥", /*sub_title*/"", /*disp_order*/130);
INSERT INTO `story_category` VALUES (/*id*/131, /*type*/2, /*chara_type*/2, /*chara_id*/231, /*title*/"桐生つかさ", /*sub_title*/"", /*disp_order*/131);
INSERT INTO `story_category` VALUES (/*id*/132, /*type*/2, /*chara_type*/2, /*chara_id*/232, /*title*/"望月聖", /*sub_title*/"", /*disp_order*/132);
INSERT INTO `story_category` VALUES (/*id*/133, /*type*/2, /*chara_type*/2, /*chara_id*/233, /*title*/"鷹富士茄子", /*sub_title*/"", /*disp_order*/133);
INSERT INTO `story_category` VALUES (/*id*/134, /*type*/2, /*chara_type*/3, /*chara_id*/234, /*title*/"本田未央", /*sub_title*/"", /*disp_order*/134);
INSERT INTO `story_category` VALUES (/*id*/135, /*type*/2, /*chara_type*/3, /*chara_id*/235, /*title*/"高森藍子", /*sub_title*/"", /*disp_order*/135);
INSERT INTO `story_category` VALUES (/*id*/136, /*type*/2, /*chara_type*/3, /*chara_id*/236, /*title*/"並木芽衣子", /*sub_title*/"", /*disp_order*/136);
INSERT INTO `story_category` VALUES (/*id*/137, /*type*/2, /*chara_type*/3, /*chara_id*/237, /*title*/"龍崎薫", /*sub_title*/"", /*disp_order*/137);
INSERT INTO `story_category` VALUES (/*id*/138, /*type*/2, /*chara_type*/3, /*chara_id*/238, /*title*/"木村夏樹", /*sub_title*/"", /*disp_order*/138);
INSERT INTO `story_category` VALUES (/*id*/139, /*type*/2, /*chara_type*/3, /*chara_id*/239, /*title*/"松山久美子", /*sub_title*/"", /*disp_order*/139);
INSERT INTO `story_category` VALUES (/*id*/140, /*type*/2, /*chara_type*/3, /*chara_id*/240, /*title*/"斉藤洋子", /*sub_title*/"", /*disp_order*/140);
INSERT INTO `story_category` VALUES (/*id*/141, /*type*/2, /*chara_type*/3, /*chara_id*/241, /*title*/"沢田麻理菜", /*sub_title*/"", /*disp_order*/141);
INSERT INTO `story_category` VALUES (/*id*/142, /*type*/2, /*chara_type*/3, /*chara_id*/242, /*title*/"矢口美羽", /*sub_title*/"", /*disp_order*/142);
INSERT INTO `story_category` VALUES (/*id*/143, /*type*/2, /*chara_type*/3, /*chara_id*/243, /*title*/"赤城みりあ", /*sub_title*/"", /*disp_order*/143);
INSERT INTO `story_category` VALUES (/*id*/144, /*type*/2, /*chara_type*/3, /*chara_id*/244, /*title*/"愛野渚", /*sub_title*/"", /*disp_order*/144);
INSERT INTO `story_category` VALUES (/*id*/145, /*type*/2, /*chara_type*/3, /*chara_id*/245, /*title*/"真鍋いつき", /*sub_title*/"", /*disp_order*/145);
INSERT INTO `story_category` VALUES (/*id*/146, /*type*/2, /*chara_type*/3, /*chara_id*/246, /*title*/"大槻唯", /*sub_title*/"", /*disp_order*/146);
INSERT INTO `story_category` VALUES (/*id*/147, /*type*/2, /*chara_type*/3, /*chara_id*/247, /*title*/"姫川友紀", /*sub_title*/"", /*disp_order*/147);
INSERT INTO `story_category` VALUES (/*id*/149, /*type*/2, /*chara_type*/3, /*chara_id*/249, /*title*/"喜多見柚", /*sub_title*/"", /*disp_order*/149);
INSERT INTO `story_category` VALUES (/*id*/150, /*type*/2, /*chara_type*/3, /*chara_id*/250, /*title*/"上田鈴帆", /*sub_title*/"", /*disp_order*/150);
INSERT INTO `story_category` VALUES (/*id*/151, /*type*/2, /*chara_type*/3, /*chara_id*/251, /*title*/"海老原菜帆", /*sub_title*/"", /*disp_order*/151);
INSERT INTO `story_category` VALUES (/*id*/153, /*type*/2, /*chara_type*/3, /*chara_id*/253, /*title*/"及川雫", /*sub_title*/"", /*disp_order*/153);
INSERT INTO `story_category` VALUES (/*id*/154, /*type*/2, /*chara_type*/3, /*chara_id*/254, /*title*/"小関麗奈", /*sub_title*/"", /*disp_order*/154);
INSERT INTO `story_category` VALUES (/*id*/155, /*type*/2, /*chara_type*/3, /*chara_id*/255, /*title*/"衛藤美紗希", /*sub_title*/"", /*disp_order*/155);
INSERT INTO `story_category` VALUES (/*id*/156, /*type*/2, /*chara_type*/3, /*chara_id*/256, /*title*/"星輝子", /*sub_title*/"", /*disp_order*/156);
INSERT INTO `story_category` VALUES (/*id*/157, /*type*/2, /*chara_type*/3, /*chara_id*/257, /*title*/"片桐早苗", /*sub_title*/"", /*disp_order*/157);
INSERT INTO `story_category` VALUES (/*id*/158, /*type*/2, /*chara_type*/3, /*chara_id*/258, /*title*/"堀裕子", /*sub_title*/"", /*disp_order*/158);
INSERT INTO `story_category` VALUES (/*id*/159, /*type*/2, /*chara_type*/3, /*chara_id*/259, /*title*/"西島櫂", /*sub_title*/"", /*disp_order*/159);
INSERT INTO `story_category` VALUES (/*id*/160, /*type*/2, /*chara_type*/3, /*chara_id*/260, /*title*/"的場梨沙", /*sub_title*/"", /*disp_order*/160);
INSERT INTO `story_category` VALUES (/*id*/161, /*type*/2, /*chara_type*/3, /*chara_id*/261, /*title*/"財前時子", /*sub_title*/"", /*disp_order*/161);
INSERT INTO `story_category` VALUES (/*id*/162, /*type*/2, /*chara_type*/3, /*chara_id*/262, /*title*/"依田芳乃", /*sub_title*/"", /*disp_order*/162);
INSERT INTO `story_category` VALUES (/*id*/163, /*type*/2, /*chara_type*/3, /*chara_id*/263, /*title*/"相葉夕美", /*sub_title*/"", /*disp_order*/163);
INSERT INTO `story_category` VALUES (/*id*/164, /*type*/2, /*chara_type*/3, /*chara_id*/264, /*title*/"野々村そら", /*sub_title*/"", /*disp_order*/164);
INSERT INTO `story_category` VALUES (/*id*/165, /*type*/2, /*chara_type*/3, /*chara_id*/265, /*title*/"浜川愛結奈", /*sub_title*/"", /*disp_order*/165);
INSERT INTO `story_category` VALUES (/*id*/166, /*type*/2, /*chara_type*/3, /*chara_id*/266, /*title*/"若林智香", /*sub_title*/"", /*disp_order*/166);
INSERT INTO `story_category` VALUES (/*id*/167, /*type*/2, /*chara_type*/3, /*chara_id*/267, /*title*/"城ヶ崎美嘉", /*sub_title*/"", /*disp_order*/167);
INSERT INTO `story_category` VALUES (/*id*/168, /*type*/2, /*chara_type*/3, /*chara_id*/268, /*title*/"城ヶ崎莉嘉", /*sub_title*/"", /*disp_order*/168);
INSERT INTO `story_category` VALUES (/*id*/169, /*type*/2, /*chara_type*/3, /*chara_id*/269, /*title*/"仙崎恵磨", /*sub_title*/"", /*disp_order*/169);
INSERT INTO `story_category` VALUES (/*id*/170, /*type*/2, /*chara_type*/3, /*chara_id*/270, /*title*/"日野茜", /*sub_title*/"", /*disp_order*/170);
INSERT INTO `story_category` VALUES (/*id*/171, /*type*/2, /*chara_type*/3, /*chara_id*/271, /*title*/"諸星きらり", /*sub_title*/"", /*disp_order*/171);
INSERT INTO `story_category` VALUES (/*id*/172, /*type*/2, /*chara_type*/3, /*chara_id*/272, /*title*/"十時愛梨", /*sub_title*/"", /*disp_order*/172);
INSERT INTO `story_category` VALUES (/*id*/173, /*type*/2, /*chara_type*/3, /*chara_id*/273, /*title*/"ナターリア", /*sub_title*/"", /*disp_order*/173);
INSERT INTO `story_category` VALUES (/*id*/174, /*type*/2, /*chara_type*/3, /*chara_id*/274, /*title*/"相馬夏美", /*sub_title*/"", /*disp_order*/174);
INSERT INTO `story_category` VALUES (/*id*/175, /*type*/2, /*chara_type*/3, /*chara_id*/275, /*title*/"槙原志保", /*sub_title*/"", /*disp_order*/175);
INSERT INTO `story_category` VALUES (/*id*/180, /*type*/2, /*chara_type*/3, /*chara_id*/280, /*title*/"向井拓海", /*sub_title*/"", /*disp_order*/180);
INSERT INTO `story_category` VALUES (/*id*/183, /*type*/2, /*chara_type*/3, /*chara_id*/283, /*title*/"市原仁奈", /*sub_title*/"", /*disp_order*/183);
INSERT INTO `story_category` VALUES (/*id*/184, /*type*/2, /*chara_type*/3, /*chara_id*/284, /*title*/"喜多日菜子", /*sub_title*/"", /*disp_order*/184);
INSERT INTO `story_category` VALUES (/*id*/185, /*type*/2, /*chara_type*/3, /*chara_id*/285, /*title*/"杉坂海", /*sub_title*/"", /*disp_order*/185);
INSERT INTO `story_category` VALUES (/*id*/186, /*type*/2, /*chara_type*/3, /*chara_id*/286, /*title*/"北川真尋", /*sub_title*/"", /*disp_order*/186);
INSERT INTO `story_category` VALUES (/*id*/187, /*type*/2, /*chara_type*/3, /*chara_id*/287, /*title*/"メアリー・コクラン", /*sub_title*/"", /*disp_order*/187);
INSERT INTO `story_category` VALUES (/*id*/188, /*type*/2, /*chara_type*/3, /*chara_id*/288, /*title*/"小松伊吹", /*sub_title*/"", /*disp_order*/188);
INSERT INTO `story_category` VALUES (/*id*/189, /*type*/2, /*chara_type*/3, /*chara_id*/289, /*title*/"三好紗南", /*sub_title*/"", /*disp_order*/189);
INSERT INTO `story_category` VALUES (/*id*/190, /*type*/2, /*chara_type*/3, /*chara_id*/290, /*title*/"キャシー・グラハム", /*sub_title*/"", /*disp_order*/190);
INSERT INTO `story_category` VALUES (/*id*/191, /*type*/2, /*chara_type*/3, /*chara_id*/291, /*title*/"難波笑美", /*sub_title*/"", /*disp_order*/191);
INSERT INTO `story_category` VALUES (/*id*/192, /*type*/2, /*chara_type*/3, /*chara_id*/292, /*title*/"浜口あやめ", /*sub_title*/"", /*disp_order*/192);
INSERT INTO `story_category` VALUES (/*id*/193, /*type*/2, /*chara_type*/3, /*chara_id*/293, /*title*/"村上巴", /*sub_title*/"", /*disp_order*/193);
INSERT INTO `story_category` VALUES (/*id*/194, /*type*/2, /*chara_type*/3, /*chara_id*/294, /*title*/"土屋亜子", /*sub_title*/"", /*disp_order*/194);
INSERT INTO `story_category` VALUES (/*id*/195, /*type*/2, /*chara_type*/3, /*chara_id*/295, /*title*/"首藤葵", /*sub_title*/"", /*disp_order*/195);
INSERT INTO `story_category` VALUES (/*id*/196, /*type*/2, /*chara_type*/3, /*chara_id*/296, /*title*/"冴島清美", /*sub_title*/"", /*disp_order*/196);
INSERT INTO `story_category` VALUES (/*id*/197, /*type*/2, /*chara_type*/3, /*chara_id*/297, /*title*/"佐藤心", /*sub_title*/"", /*disp_order*/197);
INSERT INTO `story_category` VALUES (/*id*/198, /*type*/2, /*chara_type*/3, /*chara_id*/298, /*title*/"南条光", /*sub_title*/"", /*disp_order*/198);
INSERT INTO `story_category` VALUES (/*id*/200, /*type*/2, /*chara_type*/3, /*chara_id*/300, /*title*/"イヴ・サンタクロース", /*sub_title*/"", /*disp_order*/200);
INSERT INTO `story_category` VALUES (/*id*/201, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第1話", /*sub_title*/"Stage, We climb the stairs.", /*disp_order*/202);
INSERT INTO `story_category` VALUES (/*id*/202, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第2話", /*sub_title*/"Wish upon a Star ! !", /*disp_order*/203);
INSERT INTO `story_category` VALUES (/*id*/203, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第3話", /*sub_title*/"SING, Smile, S(mile)ING !", /*disp_order*/204);
INSERT INTO `story_category` VALUES (/*id*/204, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第4話", /*sub_title*/"the flower of my heart.", /*disp_order*/205);
INSERT INTO `story_category` VALUES (/*id*/205, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第5話", /*sub_title*/"Lucky Star☆", /*disp_order*/206);
INSERT INTO `story_category` VALUES (/*id*/206, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第6話", /*sub_title*/"Cat's whiskers♪", /*disp_order*/207);
INSERT INTO `story_category` VALUES (/*id*/207, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第7話", /*sub_title*/"\"Rock\" is the coolest word.", /*disp_order*/208);
INSERT INTO `story_category` VALUES (/*id*/208, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第0話", /*sub_title*/"Cast a spell on me!", /*disp_order*/201);
INSERT INTO `story_category` VALUES (/*id*/209, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第8話", /*sub_title*/"Girls be Ambitious ! !", /*disp_order*/209);
INSERT INTO `story_category` VALUES (/*id*/210, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第9話", /*sub_title*/"Happiness is here.", /*disp_order*/210);
INSERT INTO `story_category` VALUES (/*id*/211, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第10話", /*sub_title*/"Large Star, Little girl.", /*disp_order*/211);
INSERT INTO `story_category` VALUES (/*id*/212, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第11話", /*sub_title*/"NO ID(O)L(E) NO LIFE !", /*disp_order*/212);
INSERT INTO `story_category` VALUES (/*id*/213, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第12話", /*sub_title*/"Drop in the Darkness !", /*disp_order*/213);
INSERT INTO `story_category` VALUES (/*id*/214, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第13話", /*sub_title*/"Sweets Party ! !", /*disp_order*/214);
INSERT INTO `story_category` VALUES (/*id*/215, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"アタシポンコツアンドロイド", /*sub_title*/"アタシポンコツアンドロイド", /*disp_order*/1);
INSERT INTO `story_category` VALUES (/*id*/216, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第14話", /*sub_title*/"Naked Venus", /*disp_order*/215);
INSERT INTO `story_category` VALUES (/*id*/217, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第15話", /*sub_title*/"Fun ! Fun ! ! Fun ! ! !", /*disp_order*/216);
INSERT INTO `story_category` VALUES (/*id*/218, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Nation Blue", /*sub_title*/"Nation Blue", /*disp_order*/2);
INSERT INTO `story_category` VALUES (/*id*/219, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第16話", /*sub_title*/"Alone, But Not Lonely", /*disp_order*/217);
INSERT INTO `story_category` VALUES (/*id*/220, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Orange Sapphire", /*sub_title*/"Orange Sapphire", /*disp_order*/3);
INSERT INTO `story_category` VALUES (/*id*/221, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第17話", /*sub_title*/"Everything About the Love", /*disp_order*/218);
INSERT INTO `story_category` VALUES (/*id*/222, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Snow Wings", /*sub_title*/"Snow Wings", /*disp_order*/4);
INSERT INTO `story_category` VALUES (/*id*/223, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"ゴキゲンParty Night", /*sub_title*/"ゴキゲンParty Night", /*disp_order*/5);
INSERT INTO `story_category` VALUES (/*id*/224, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第18話", /*sub_title*/"Dreaming Place", /*disp_order*/219);
INSERT INTO `story_category` VALUES (/*id*/225, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第19話", /*sub_title*/"Just Started", /*disp_order*/220);
INSERT INTO `story_category` VALUES (/*id*/226, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第20話", /*sub_title*/"Happiness Happening !", /*disp_order*/221);
INSERT INTO `story_category` VALUES (/*id*/227, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"パステルピンクな恋", /*sub_title*/"パステルピンクな恋", /*disp_order*/6);
INSERT INTO `story_category` VALUES (/*id*/228, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第21話", /*sub_title*/"With or Without You", /*disp_order*/222);
INSERT INTO `story_category` VALUES (/*id*/229, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Tulip", /*sub_title*/"Tulip", /*disp_order*/7);
INSERT INTO `story_category` VALUES (/*id*/230, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第22話", /*sub_title*/"Out of the Page", /*disp_order*/223);
INSERT INTO `story_category` VALUES (/*id*/231, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"オルゴールの小箱", /*sub_title*/"オルゴールの小箱", /*disp_order*/8);
INSERT INTO `story_category` VALUES (/*id*/232, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第23話", /*sub_title*/"Because You are You", /*disp_order*/224);
INSERT INTO `story_category` VALUES (/*id*/233, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第24話", /*sub_title*/"Sakura Bloom", /*disp_order*/225);
INSERT INTO `story_category` VALUES (/*id*/234, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第25話", /*sub_title*/"Nobody Knows", /*disp_order*/226);
INSERT INTO `story_category` VALUES (/*id*/235, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第26話", /*sub_title*/"P.P.Peace ! !", /*disp_order*/227);
INSERT INTO `story_category` VALUES (/*id*/236, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第27話", /*sub_title*/"Made by Maid", /*disp_order*/228);
INSERT INTO `story_category` VALUES (/*id*/237, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第28話", /*sub_title*/"Time of Pleasure", /*disp_order*/229);
INSERT INTO `story_category` VALUES (/*id*/238, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第29話", /*sub_title*/"Heat up Hearts", /*disp_order*/230);
INSERT INTO `story_category` VALUES (/*id*/239, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第30話", /*sub_title*/"Every Day is a Good Day", /*disp_order*/231);
INSERT INTO `story_category` VALUES (/*id*/240, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第31話", /*sub_title*/"Monochrome Memory", /*disp_order*/232);
INSERT INTO `story_category` VALUES (/*id*/241, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第32話", /*sub_title*/"Full Metal Soul", /*disp_order*/233);
INSERT INTO `story_category` VALUES (/*id*/242, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第33話", /*sub_title*/"Missing, If you want", /*disp_order*/234);
INSERT INTO `story_category` VALUES (/*id*/243, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第34話", /*sub_title*/"Whisper of another girl", /*disp_order*/235);
INSERT INTO `story_category` VALUES (/*id*/244, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第35話", /*sub_title*/"Easy Driver ! !", /*disp_order*/236);
INSERT INTO `story_category` VALUES (/*id*/245, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第36話", /*sub_title*/"Voi che sapete…", /*disp_order*/237);
INSERT INTO `story_category` VALUES (/*id*/246, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第37話", /*sub_title*/"Still up in the Air", /*disp_order*/238);
INSERT INTO `story_category` VALUES (/*id*/247, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第38話", /*sub_title*/"Cheer You ! Cheer Me !", /*disp_order*/239);
INSERT INTO `story_category` VALUES (/*id*/248, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第39話", /*sub_title*/"The Words for LOVE", /*disp_order*/240);
INSERT INTO `story_category` VALUES (/*id*/249, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第40話", /*sub_title*/"Be honest with yourself", /*disp_order*/241);
INSERT INTO `story_category` VALUES (/*id*/250, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第41話", /*sub_title*/"Go ! Go ! Super Girl !", /*disp_order*/242);
INSERT INTO `story_category` VALUES (/*id*/251, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第42話", /*sub_title*/"Home is where the heart is", /*disp_order*/243);
INSERT INTO `story_category` VALUES (/*id*/252, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第43話", /*sub_title*/"Cogito ergo sum", /*disp_order*/244);
INSERT INTO `story_category` VALUES (/*id*/253, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第44話", /*sub_title*/"Bonheur a la carte ! !", /*disp_order*/245);
INSERT INTO `story_category` VALUES (/*id*/254, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"絶対特権主張しますっ ! ", /*sub_title*/"絶対特権主張しますっ ! ", /*disp_order*/9);
INSERT INTO `story_category` VALUES (/*id*/255, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"ハイファイ☆デイズ", /*sub_title*/"ハイファイ☆デイズ", /*disp_order*/10);
INSERT INTO `story_category` VALUES (/*id*/256, /*type*/4, /*chara_type*/0, /*chara_id*/0, /*title*/"とある事務員の一日", /*sub_title*/"とある事務員の一日", /*disp_order*/5);
INSERT INTO `story_category` VALUES (/*id*/257, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"つぼみ", /*sub_title*/"つぼみ", /*disp_order*/11);
INSERT INTO `story_category` VALUES (/*id*/258, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"生存本能ヴァルキュリア", /*sub_title*/"生存本能ヴァルキュリア", /*disp_order*/12);
INSERT INTO `story_category` VALUES (/*id*/259, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"明日また会えるよね", /*sub_title*/"明日また会えるよね", /*disp_order*/13);
INSERT INTO `story_category` VALUES (/*id*/260, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"純情Midnight伝説", /*sub_title*/"純情Midnight伝説", /*disp_order*/14);
INSERT INTO `story_category` VALUES (/*id*/261, /*type*/4, /*chara_type*/0, /*chara_id*/0, /*title*/"ちひろのお知らせ", /*sub_title*/"ちひろのお知らせ", /*disp_order*/1);
INSERT INTO `story_category` VALUES (/*id*/262, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"咲いてJewel", /*sub_title*/"咲いてJewel", /*disp_order*/15);
INSERT INTO `story_category` VALUES (/*id*/263, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Love∞Destiny", /*sub_title*/"Love∞Destiny", /*disp_order*/16);
INSERT INTO `story_category` VALUES (/*id*/264, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"きみにいっぱい☆", /*sub_title*/"きみにいっぱい☆", /*disp_order*/17);
INSERT INTO `story_category` VALUES (/*id*/265, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"サマカニ ! !", /*sub_title*/"サマカニ ! !", /*disp_order*/18);
INSERT INTO `story_category` VALUES (/*id*/266, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Near to You", /*sub_title*/"Near to You", /*disp_order*/19);
INSERT INTO `story_category` VALUES (/*id*/267, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"BEYOND THE STARLIGHT", /*sub_title*/"BEYOND THE STARLIGHT", /*disp_order*/20);
INSERT INTO `story_category` VALUES (/*id*/268, /*type*/4, /*chara_type*/0, /*chara_id*/0, /*title*/"4thLIVE連動企画", /*sub_title*/"4thLIVE連動企画", /*disp_order*/2);
INSERT INTO `story_category` VALUES (/*id*/269, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"ラブレター", /*sub_title*/"ラブレター", /*disp_order*/21);
INSERT INTO `story_category` VALUES (/*id*/270, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"STORY", /*sub_title*/"STORY", /*disp_order*/22);
INSERT INTO `story_category` VALUES (/*id*/271, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Jet to the Future", /*sub_title*/"Jet to the Future", /*disp_order*/23);
INSERT INTO `story_category` VALUES (/*id*/272, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"あいくるしい", /*sub_title*/"あいくるしい", /*disp_order*/24);
INSERT INTO `story_category` VALUES (/*id*/273, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Flip Flop", /*sub_title*/"Flip Flop", /*disp_order*/25);
INSERT INTO `story_category` VALUES (/*id*/274, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"EVERMORE", /*sub_title*/"EVERMORE", /*disp_order*/26);
INSERT INTO `story_category` VALUES (/*id*/275, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"あんきら ! ？狂騒曲", /*sub_title*/"あんきら ! ？狂騒曲", /*disp_order*/27);
INSERT INTO `story_category` VALUES (/*id*/276, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"命燃やして恋せよ乙女", /*sub_title*/"命燃やして恋せよ乙女", /*disp_order*/28);
INSERT INTO `story_category` VALUES (/*id*/277, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Lunatic Show", /*sub_title*/"Lunatic Show", /*disp_order*/29);
INSERT INTO `story_category` VALUES (/*id*/278, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Sweet Witches' Night", /*sub_title*/"Sweet Witches' Night", /*disp_order*/30);
INSERT INTO `story_category` VALUES (/*id*/279, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"情熱ファンファンファーレ", /*sub_title*/"情熱ファンファンファーレ", /*disp_order*/31);
INSERT INTO `story_category` VALUES (/*id*/280, /*type*/4, /*chara_type*/0, /*chara_id*/0, /*title*/"The STARLIGHT Dream", /*sub_title*/"The STARLIGHT Dream", /*disp_order*/6);
INSERT INTO `story_category` VALUES (/*id*/281, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"桜の頃", /*sub_title*/"桜の頃", /*disp_order*/32);
INSERT INTO `story_category` VALUES (/*id*/282, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"∀NSWER", /*sub_title*/"∀NSWER", /*disp_order*/33);
INSERT INTO `story_category` VALUES (/*id*/283, /*type*/4, /*chara_type*/0, /*chara_id*/0, /*title*/"5thLIVE連動企画", /*sub_title*/"5thLIVE連動企画", /*disp_order*/3);
INSERT INTO `story_category` VALUES (/*id*/284, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"shabon song", /*sub_title*/"shabon song", /*disp_order*/34);
INSERT INTO `story_category` VALUES (/*id*/285, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Nocturne", /*sub_title*/"Nocturne", /*disp_order*/35);
INSERT INTO `story_category` VALUES (/*id*/286, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Nothing but You", /*sub_title*/"Nothing but You", /*disp_order*/36);
INSERT INTO `story_category` VALUES (/*id*/287, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第45話", /*sub_title*/"Kawaii or Lesson ？", /*disp_order*/246);
INSERT INTO `story_category` VALUES (/*id*/288, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第46話", /*sub_title*/"Stay by my side", /*disp_order*/247);
INSERT INTO `story_category` VALUES (/*id*/289, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第47話", /*sub_title*/"A very merry usual day", /*disp_order*/248);
INSERT INTO `story_category` VALUES (/*id*/290, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第48話", /*sub_title*/"The heart of growing flowers", /*disp_order*/249);
INSERT INTO `story_category` VALUES (/*id*/291, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第49話", /*sub_title*/"Running toward the longing", /*disp_order*/250);
INSERT INTO `story_category` VALUES (/*id*/292, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第50話", /*sub_title*/"coming soon", /*disp_order*/251);
INSERT INTO `story_category` VALUES (/*id*/302, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"モーレツ★世直しギルティ ! ", /*sub_title*/"モーレツ★世直しギルティ ! ", /*disp_order*/37);
INSERT INTO `story_category` VALUES (/*id*/303, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"With Love", /*sub_title*/"With Love", /*disp_order*/38);
INSERT INTO `story_category` VALUES (/*id*/304, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Yes ! Party Time ! ! ", /*sub_title*/"Yes ! Party Time ! ! ", /*disp_order*/39);
INSERT INTO `story_category` VALUES (/*id*/305, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"リトルリドル", /*sub_title*/"リトルリドル", /*disp_order*/40);
INSERT INTO `story_category` VALUES (/*id*/306, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Kawaii make MY day !", /*sub_title*/"Kawaii make MY day !", /*disp_order*/41);
INSERT INTO `story_category` VALUES (/*id*/307, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Take me☆Take you", /*sub_title*/"Take me☆Take you", /*disp_order*/42);
INSERT INTO `story_category` VALUES (/*id*/308, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"双翼の独奏歌", /*sub_title*/"双翼の独奏歌", /*disp_order*/43);
INSERT INTO `story_category` VALUES (/*id*/309, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"イリュージョニスタ !", /*sub_title*/"イリュージョニスタ !", /*disp_order*/44);
INSERT INTO `story_category` VALUES (/*id*/310, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Twin☆くるっ★テール", /*sub_title*/"Twin☆くるっ★テール", /*disp_order*/45);
INSERT INTO `story_category` VALUES (/*id*/311, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"キミのそばでずっと", /*sub_title*/"キミのそばでずっと", /*disp_order*/46);
INSERT INTO `story_category` VALUES (/*id*/312, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Halloween♥Code", /*sub_title*/"Halloween♥Code", /*disp_order*/47);
INSERT INTO `story_category` VALUES (/*id*/313, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"秋風に手を振って", /*sub_title*/"秋風に手を振って", /*disp_order*/48);
INSERT INTO `story_category` VALUES (/*id*/314, /*type*/4, /*chara_type*/0, /*chara_id*/0, /*title*/"オールスターカウントダウンLIVE", /*sub_title*/"オールスターカウントダウンLIVE", /*disp_order*/4);
INSERT INTO `story_category` VALUES (/*id*/315, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Trinity Field", /*sub_title*/"Trinity Field", /*disp_order*/49);
INSERT INTO `story_category` VALUES (/*id*/316, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"恋が咲く季節", /*sub_title*/"恋が咲く季節", /*disp_order*/50);
INSERT INTO `story_category` VALUES (/*id*/317, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"冬空プレシャス", /*sub_title*/"冬空プレシャス", /*disp_order*/51);
INSERT INTO `story_category` VALUES (/*id*/318, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Happy New Yeah ! ", /*sub_title*/"Happy New Yeah ! ", /*disp_order*/52);
INSERT INTO `story_category` VALUES (/*id*/319, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"遊佐こずえ / 首藤葵", /*sub_title*/"遊佐こずえ / 首藤葵", /*disp_order*/54);
INSERT INTO `story_category` VALUES (/*id*/320, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"美に入り彩を穿つ", /*sub_title*/"美に入り彩を穿つ", /*disp_order*/53);
INSERT INTO `story_category` VALUES (/*id*/321, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"always", /*sub_title*/"always", /*disp_order*/55);
INSERT INTO `story_category` VALUES (/*id*/322, /*type*/5, /*chara_type*/0, /*chara_id*/0, /*title*/"エイプリル2018", /*sub_title*/"エイプリル2018", /*disp_order*/1);
INSERT INTO `story_category` VALUES (/*id*/323, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Frost", /*sub_title*/"Frost", /*disp_order*/56);
INSERT INTO `story_category` VALUES (/*id*/324, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"ツインテールの風", /*sub_title*/"ツインテールの風", /*disp_order*/57);
INSERT INTO `story_category` VALUES (/*id*/325, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"小松伊吹 / 安斎都", /*sub_title*/"小松伊吹 / 安斎都", /*disp_order*/58);
INSERT INTO `story_category` VALUES (/*id*/326, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"キラッ ! 満開スマイル", /*sub_title*/"キラッ ! 満開スマイル", /*disp_order*/59);
