CREATE TABLE 'story_category' ('id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'chara_type' INTEGER NOT NULL, 'chara_id' INTEGER NOT NULL, 'title' TEXT NOT NULL, 'sub_title' TEXT NOT NULL, 'disp_order' INTEGER NOT NULL, PRIMARY KEY('id'), UNIQUE('type','disp_order'))
INSERT INTO `story_category` VALUES (/*id*/1, /*type*/2, /*chara_type*/1, /*chara_id*/101, /*title*/"島村卯月", /*sub_title*/"", /*disp_order*/1);
INSERT INTO `story_category` VALUES (/*id*/2, /*type*/2, /*chara_type*/1, /*chara_id*/102, /*title*/"中野有香", /*sub_title*/"", /*disp_order*/2);
INSERT INTO `story_category` VALUES (/*id*/3, /*type*/2, /*chara_type*/1, /*chara_id*/103, /*title*/"水本ゆかり", /*sub_title*/"", /*disp_order*/3);
INSERT INTO `story_category` VALUES (/*id*/4, /*type*/2, /*chara_type*/1, /*chara_id*/104, /*title*/"福山舞", /*sub_title*/"", /*disp_order*/4);
INSERT INTO `story_category` VALUES (/*id*/5, /*type*/2, /*chara_type*/1, /*chara_id*/105, /*title*/"椎名法子", /*sub_title*/"", /*disp_order*/5);
INSERT INTO `story_category` VALUES (/*id*/6, /*type*/2, /*chara_type*/1, /*chara_id*/106, /*title*/"今井加奈", /*sub_title*/"", /*disp_order*/6);
INSERT INTO `story_category` VALUES (/*id*/7, /*type*/2, /*chara_type*/1, /*chara_id*/107, /*title*/"持田亜里沙", /*sub_title*/"", /*disp_order*/7);
INSERT INTO `story_category` VALUES (/*id*/8, /*type*/2, /*chara_type*/1, /*chara_id*/108, /*title*/"三村かな子", /*sub_title*/"", /*disp_order*/8);
INSERT INTO `story_category` VALUES (/*id*/9, /*type*/2, /*chara_type*/1, /*chara_id*/109, /*title*/"奥山沙織", /*sub_title*/"", /*disp_order*/9);
INSERT INTO `story_category` VALUES (/*id*/11, /*type*/2, /*chara_type*/1, /*chara_id*/111, /*title*/"小日向美穂", /*sub_title*/"", /*disp_order*/11);
INSERT INTO `story_category` VALUES (/*id*/12, /*type*/2, /*chara_type*/1, /*chara_id*/112, /*title*/"緒方智絵里", /*sub_title*/"", /*disp_order*/12);
INSERT INTO `story_category` VALUES (/*id*/13, /*type*/2, /*chara_type*/1, /*chara_id*/113, /*title*/"五十嵐響子", /*sub_title*/"", /*disp_order*/13);
INSERT INTO `story_category` VALUES (/*id*/15, /*type*/2, /*chara_type*/1, /*chara_id*/115, /*title*/"櫻井桃華", /*sub_title*/"", /*disp_order*/15);
INSERT INTO `story_category` VALUES (/*id*/18, /*type*/2, /*chara_type*/1, /*chara_id*/118, /*title*/"横山千佳", /*sub_title*/"", /*disp_order*/18);
INSERT INTO `story_category` VALUES (/*id*/21, /*type*/2, /*chara_type*/1, /*chara_id*/121, /*title*/"棟方愛海", /*sub_title*/"", /*disp_order*/21);
INSERT INTO `story_category` VALUES (/*id*/22, /*type*/2, /*chara_type*/1, /*chara_id*/122, /*title*/"藤本里奈", /*sub_title*/"", /*disp_order*/22);
INSERT INTO `story_category` VALUES (/*id*/26, /*type*/2, /*chara_type*/1, /*chara_id*/126, /*title*/"一ノ瀬志希", /*sub_title*/"", /*disp_order*/26);
INSERT INTO `story_category` VALUES (/*id*/27, /*type*/2, /*chara_type*/1, /*chara_id*/127, /*title*/"前川みく", /*sub_title*/"", /*disp_order*/27);
INSERT INTO `story_category` VALUES (/*id*/31, /*type*/2, /*chara_type*/1, /*chara_id*/131, /*title*/"宮本フレデリカ", /*sub_title*/"", /*disp_order*/31);
INSERT INTO `story_category` VALUES (/*id*/32, /*type*/2, /*chara_type*/1, /*chara_id*/132, /*title*/"小早川紗枝", /*sub_title*/"", /*disp_order*/32);
INSERT INTO `story_category` VALUES (/*id*/33, /*type*/2, /*chara_type*/1, /*chara_id*/133, /*title*/"西園寺琴歌", /*sub_title*/"", /*disp_order*/33);
INSERT INTO `story_category` VALUES (/*id*/34, /*type*/2, /*chara_type*/1, /*chara_id*/134, /*title*/"双葉杏", /*sub_title*/"", /*disp_order*/34);
INSERT INTO `story_category` VALUES (/*id*/36, /*type*/2, /*chara_type*/1, /*chara_id*/136, /*title*/"桃井あずき", /*sub_title*/"", /*disp_order*/36);
INSERT INTO `story_category` VALUES (/*id*/38, /*type*/2, /*chara_type*/1, /*chara_id*/138, /*title*/"月宮雅", /*sub_title*/"", /*disp_order*/38);
INSERT INTO `story_category` VALUES (/*id*/39, /*type*/2, /*chara_type*/1, /*chara_id*/139, /*title*/"兵藤レナ", /*sub_title*/"", /*disp_order*/39);
INSERT INTO `story_category` VALUES (/*id*/41, /*type*/2, /*chara_type*/1, /*chara_id*/141, /*title*/"道明寺歌鈴", /*sub_title*/"", /*disp_order*/41);
INSERT INTO `story_category` VALUES (/*id*/47, /*type*/2, /*chara_type*/1, /*chara_id*/147, /*title*/"井村雪菜", /*sub_title*/"", /*disp_order*/47);
INSERT INTO `story_category` VALUES (/*id*/49, /*type*/2, /*chara_type*/1, /*chara_id*/149, /*title*/"榊原里美", /*sub_title*/"", /*disp_order*/49);
INSERT INTO `story_category` VALUES (/*id*/50, /*type*/2, /*chara_type*/1, /*chara_id*/150, /*title*/"輿水幸子", /*sub_title*/"", /*disp_order*/50);
INSERT INTO `story_category` VALUES (/*id*/54, /*type*/2, /*chara_type*/1, /*chara_id*/154, /*title*/"安部菜々", /*sub_title*/"", /*disp_order*/54);
INSERT INTO `story_category` VALUES (/*id*/55, /*type*/2, /*chara_type*/1, /*chara_id*/155, /*title*/"工藤忍", /*sub_title*/"", /*disp_order*/55);
INSERT INTO `story_category` VALUES (/*id*/58, /*type*/2, /*chara_type*/1, /*chara_id*/158, /*title*/"クラリス", /*sub_title*/"", /*disp_order*/58);
INSERT INTO `story_category` VALUES (/*id*/59, /*type*/2, /*chara_type*/1, /*chara_id*/159, /*title*/"佐久間まゆ", /*sub_title*/"", /*disp_order*/59);
INSERT INTO `story_category` VALUES (/*id*/60, /*type*/2, /*chara_type*/1, /*chara_id*/160, /*title*/"村松さくら", /*sub_title*/"", /*disp_order*/60);
INSERT INTO `story_category` VALUES (/*id*/61, /*type*/2, /*chara_type*/1, /*chara_id*/161, /*title*/"白菊ほたる", /*sub_title*/"", /*disp_order*/61);
INSERT INTO `story_category` VALUES (/*id*/62, /*type*/2, /*chara_type*/1, /*chara_id*/162, /*title*/"早坂美玲", /*sub_title*/"", /*disp_order*/62);
INSERT INTO `story_category` VALUES (/*id*/65, /*type*/2, /*chara_type*/1, /*chara_id*/165, /*title*/"原田美世", /*sub_title*/"", /*disp_order*/65);
INSERT INTO `story_category` VALUES (/*id*/67, /*type*/2, /*chara_type*/2, /*chara_id*/167, /*title*/"渋谷凛", /*sub_title*/"", /*disp_order*/67);
INSERT INTO `story_category` VALUES (/*id*/68, /*type*/2, /*chara_type*/2, /*chara_id*/168, /*title*/"黒川千秋", /*sub_title*/"", /*disp_order*/68);
INSERT INTO `story_category` VALUES (/*id*/69, /*type*/2, /*chara_type*/2, /*chara_id*/169, /*title*/"松本沙理奈", /*sub_title*/"", /*disp_order*/69);
INSERT INTO `story_category` VALUES (/*id*/72, /*type*/2, /*chara_type*/2, /*chara_id*/172, /*title*/"相川千夏", /*sub_title*/"", /*disp_order*/72);
INSERT INTO `story_category` VALUES (/*id*/73, /*type*/2, /*chara_type*/2, /*chara_id*/173, /*title*/"川島瑞樹", /*sub_title*/"", /*disp_order*/73);
INSERT INTO `story_category` VALUES (/*id*/74, /*type*/2, /*chara_type*/2, /*chara_id*/174, /*title*/"神谷奈緒", /*sub_title*/"", /*disp_order*/74);
INSERT INTO `story_category` VALUES (/*id*/75, /*type*/2, /*chara_type*/2, /*chara_id*/175, /*title*/"上条春菜", /*sub_title*/"", /*disp_order*/75);
INSERT INTO `story_category` VALUES (/*id*/76, /*type*/2, /*chara_type*/2, /*chara_id*/176, /*title*/"荒木比奈", /*sub_title*/"", /*disp_order*/76);
INSERT INTO `story_category` VALUES (/*id*/77, /*type*/2, /*chara_type*/2, /*chara_id*/177, /*title*/"東郷あい", /*sub_title*/"", /*disp_order*/77);
INSERT INTO `story_category` VALUES (/*id*/78, /*type*/2, /*chara_type*/2, /*chara_id*/178, /*title*/"多田李衣菜", /*sub_title*/"", /*disp_order*/78);
INSERT INTO `story_category` VALUES (/*id*/79, /*type*/2, /*chara_type*/2, /*chara_id*/179, /*title*/"水木聖來", /*sub_title*/"", /*disp_order*/79);
INSERT INTO `story_category` VALUES (/*id*/80, /*type*/2, /*chara_type*/2, /*chara_id*/180, /*title*/"佐々木千枝", /*sub_title*/"", /*disp_order*/80);
INSERT INTO `story_category` VALUES (/*id*/81, /*type*/2, /*chara_type*/2, /*chara_id*/181, /*title*/"三船美優", /*sub_title*/"", /*disp_order*/81);
INSERT INTO `story_category` VALUES (/*id*/84, /*type*/2, /*chara_type*/2, /*chara_id*/184, /*title*/"藤原肇", /*sub_title*/"", /*disp_order*/84);
INSERT INTO `story_category` VALUES (/*id*/85, /*type*/2, /*chara_type*/2, /*chara_id*/185, /*title*/"新田美波", /*sub_title*/"", /*disp_order*/85);
INSERT INTO `story_category` VALUES (/*id*/86, /*type*/2, /*chara_type*/2, /*chara_id*/186, /*title*/"水野翠", /*sub_title*/"", /*disp_order*/86);
INSERT INTO `story_category` VALUES (/*id*/88, /*type*/2, /*chara_type*/2, /*chara_id*/188, /*title*/"橘ありす", /*sub_title*/"", /*disp_order*/88);
INSERT INTO `story_category` VALUES (/*id*/89, /*type*/2, /*chara_type*/2, /*chara_id*/189, /*title*/"鷺沢文香", /*sub_title*/"", /*disp_order*/89);
INSERT INTO `story_category` VALUES (/*id*/90, /*type*/2, /*chara_type*/2, /*chara_id*/190, /*title*/"八神マキノ", /*sub_title*/"", /*disp_order*/90);
INSERT INTO `story_category` VALUES (/*id*/91, /*type*/2, /*chara_type*/2, /*chara_id*/191, /*title*/"ライラ", /*sub_title*/"", /*disp_order*/91);
INSERT INTO `story_category` VALUES (/*id*/94, /*type*/2, /*chara_type*/2, /*chara_id*/194, /*title*/"松永涼", /*sub_title*/"", /*disp_order*/94);
INSERT INTO `story_category` VALUES (/*id*/97, /*type*/2, /*chara_type*/2, /*chara_id*/197, /*title*/"高垣楓", /*sub_title*/"", /*disp_order*/97);
INSERT INTO `story_category` VALUES (/*id*/98, /*type*/2, /*chara_type*/2, /*chara_id*/198, /*title*/"神崎蘭子", /*sub_title*/"", /*disp_order*/98);
INSERT INTO `story_category` VALUES (/*id*/101, /*type*/2, /*chara_type*/2, /*chara_id*/201, /*title*/"北条加蓮", /*sub_title*/"", /*disp_order*/101);
INSERT INTO `story_category` VALUES (/*id*/104, /*type*/2, /*chara_type*/2, /*chara_id*/204, /*title*/"綾瀬穂乃香", /*sub_title*/"", /*disp_order*/104);
INSERT INTO `story_category` VALUES (/*id*/105, /*type*/2, /*chara_type*/2, /*chara_id*/205, /*title*/"佐城雪美", /*sub_title*/"", /*disp_order*/105);
INSERT INTO `story_category` VALUES (/*id*/114, /*type*/2, /*chara_type*/2, /*chara_id*/214, /*title*/"白坂小梅", /*sub_title*/"", /*disp_order*/114);
INSERT INTO `story_category` VALUES (/*id*/119, /*type*/2, /*chara_type*/2, /*chara_id*/219, /*title*/"藤居朋", /*sub_title*/"", /*disp_order*/119);
INSERT INTO `story_category` VALUES (/*id*/120, /*type*/2, /*chara_type*/2, /*chara_id*/220, /*title*/"塩見周子", /*sub_title*/"", /*disp_order*/120);
INSERT INTO `story_category` VALUES (/*id*/121, /*type*/2, /*chara_type*/2, /*chara_id*/221, /*title*/"脇山珠美", /*sub_title*/"", /*disp_order*/121);
INSERT INTO `story_category` VALUES (/*id*/122, /*type*/2, /*chara_type*/2, /*chara_id*/222, /*title*/"岡崎泰葉", /*sub_title*/"", /*disp_order*/122);
INSERT INTO `story_category` VALUES (/*id*/123, /*type*/2, /*chara_type*/2, /*chara_id*/223, /*title*/"速水奏", /*sub_title*/"", /*disp_order*/123);
INSERT INTO `story_category` VALUES (/*id*/124, /*type*/2, /*chara_type*/2, /*chara_id*/224, /*title*/"大石泉", /*sub_title*/"", /*disp_order*/124);
INSERT INTO `story_category` VALUES (/*id*/126, /*type*/2, /*chara_type*/2, /*chara_id*/226, /*title*/"森久保乃々", /*sub_title*/"", /*disp_order*/126);
INSERT INTO `story_category` VALUES (/*id*/127, /*type*/2, /*chara_type*/2, /*chara_id*/227, /*title*/"アナスタシア", /*sub_title*/"", /*disp_order*/127);
INSERT INTO `story_category` VALUES (/*id*/128, /*type*/2, /*chara_type*/2, /*chara_id*/228, /*title*/"大和亜季", /*sub_title*/"", /*disp_order*/128);
INSERT INTO `story_category` VALUES (/*id*/129, /*type*/2, /*chara_type*/2, /*chara_id*/229, /*title*/"結城晴", /*sub_title*/"", /*disp_order*/129);
INSERT INTO `story_category` VALUES (/*id*/130, /*type*/2, /*chara_type*/2, /*chara_id*/230, /*title*/"二宮飛鳥", /*sub_title*/"", /*disp_order*/130);
INSERT INTO `story_category` VALUES (/*id*/134, /*type*/2, /*chara_type*/3, /*chara_id*/234, /*title*/"本田未央", /*sub_title*/"", /*disp_order*/134);
INSERT INTO `story_category` VALUES (/*id*/135, /*type*/2, /*chara_type*/3, /*chara_id*/235, /*title*/"高森藍子", /*sub_title*/"", /*disp_order*/135);
INSERT INTO `story_category` VALUES (/*id*/137, /*type*/2, /*chara_type*/3, /*chara_id*/237, /*title*/"龍崎薫", /*sub_title*/"", /*disp_order*/137);
INSERT INTO `story_category` VALUES (/*id*/138, /*type*/2, /*chara_type*/3, /*chara_id*/238, /*title*/"木村夏樹", /*sub_title*/"", /*disp_order*/138);
INSERT INTO `story_category` VALUES (/*id*/139, /*type*/2, /*chara_type*/3, /*chara_id*/239, /*title*/"松山久美子", /*sub_title*/"", /*disp_order*/139);
INSERT INTO `story_category` VALUES (/*id*/142, /*type*/2, /*chara_type*/3, /*chara_id*/242, /*title*/"矢口美羽", /*sub_title*/"", /*disp_order*/142);
INSERT INTO `story_category` VALUES (/*id*/143, /*type*/2, /*chara_type*/3, /*chara_id*/243, /*title*/"赤城みりあ", /*sub_title*/"", /*disp_order*/143);
INSERT INTO `story_category` VALUES (/*id*/146, /*type*/2, /*chara_type*/3, /*chara_id*/246, /*title*/"大槻唯", /*sub_title*/"", /*disp_order*/146);
INSERT INTO `story_category` VALUES (/*id*/147, /*type*/2, /*chara_type*/3, /*chara_id*/247, /*title*/"姫川友紀", /*sub_title*/"", /*disp_order*/147);
INSERT INTO `story_category` VALUES (/*id*/149, /*type*/2, /*chara_type*/3, /*chara_id*/249, /*title*/"喜多見柚", /*sub_title*/"", /*disp_order*/149);
INSERT INTO `story_category` VALUES (/*id*/153, /*type*/2, /*chara_type*/3, /*chara_id*/253, /*title*/"及川雫", /*sub_title*/"", /*disp_order*/153);
INSERT INTO `story_category` VALUES (/*id*/154, /*type*/2, /*chara_type*/3, /*chara_id*/254, /*title*/"小関麗奈", /*sub_title*/"", /*disp_order*/154);
INSERT INTO `story_category` VALUES (/*id*/156, /*type*/2, /*chara_type*/3, /*chara_id*/256, /*title*/"星輝子", /*sub_title*/"", /*disp_order*/156);
INSERT INTO `story_category` VALUES (/*id*/157, /*type*/2, /*chara_type*/3, /*chara_id*/257, /*title*/"片桐早苗", /*sub_title*/"", /*disp_order*/157);
INSERT INTO `story_category` VALUES (/*id*/158, /*type*/2, /*chara_type*/3, /*chara_id*/258, /*title*/"堀裕子", /*sub_title*/"", /*disp_order*/158);
INSERT INTO `story_category` VALUES (/*id*/160, /*type*/2, /*chara_type*/3, /*chara_id*/260, /*title*/"的場梨沙", /*sub_title*/"", /*disp_order*/160);
INSERT INTO `story_category` VALUES (/*id*/162, /*type*/2, /*chara_type*/3, /*chara_id*/262, /*title*/"依田芳乃", /*sub_title*/"", /*disp_order*/162);
INSERT INTO `story_category` VALUES (/*id*/163, /*type*/2, /*chara_type*/3, /*chara_id*/263, /*title*/"相葉夕美", /*sub_title*/"", /*disp_order*/163);
INSERT INTO `story_category` VALUES (/*id*/166, /*type*/2, /*chara_type*/3, /*chara_id*/266, /*title*/"若林智香", /*sub_title*/"", /*disp_order*/166);
INSERT INTO `story_category` VALUES (/*id*/167, /*type*/2, /*chara_type*/3, /*chara_id*/267, /*title*/"城ヶ崎美嘉", /*sub_title*/"", /*disp_order*/167);
INSERT INTO `story_category` VALUES (/*id*/168, /*type*/2, /*chara_type*/3, /*chara_id*/268, /*title*/"城ヶ崎莉嘉", /*sub_title*/"", /*disp_order*/168);
INSERT INTO `story_category` VALUES (/*id*/169, /*type*/2, /*chara_type*/3, /*chara_id*/269, /*title*/"仙崎恵磨", /*sub_title*/"", /*disp_order*/169);
INSERT INTO `story_category` VALUES (/*id*/170, /*type*/2, /*chara_type*/3, /*chara_id*/270, /*title*/"日野茜", /*sub_title*/"", /*disp_order*/170);
INSERT INTO `story_category` VALUES (/*id*/171, /*type*/2, /*chara_type*/3, /*chara_id*/271, /*title*/"諸星きらり", /*sub_title*/"", /*disp_order*/171);
INSERT INTO `story_category` VALUES (/*id*/172, /*type*/2, /*chara_type*/3, /*chara_id*/272, /*title*/"十時愛梨", /*sub_title*/"", /*disp_order*/172);
INSERT INTO `story_category` VALUES (/*id*/173, /*type*/2, /*chara_type*/3, /*chara_id*/273, /*title*/"ナターリア", /*sub_title*/"", /*disp_order*/173);
INSERT INTO `story_category` VALUES (/*id*/180, /*type*/2, /*chara_type*/3, /*chara_id*/280, /*title*/"向井拓海", /*sub_title*/"", /*disp_order*/180);
INSERT INTO `story_category` VALUES (/*id*/183, /*type*/2, /*chara_type*/3, /*chara_id*/283, /*title*/"市原仁奈", /*sub_title*/"", /*disp_order*/183);
INSERT INTO `story_category` VALUES (/*id*/184, /*type*/2, /*chara_type*/3, /*chara_id*/284, /*title*/"喜多日菜子", /*sub_title*/"", /*disp_order*/184);
INSERT INTO `story_category` VALUES (/*id*/187, /*type*/2, /*chara_type*/3, /*chara_id*/287, /*title*/"メアリー・コクラン", /*sub_title*/"", /*disp_order*/187);
INSERT INTO `story_category` VALUES (/*id*/188, /*type*/2, /*chara_type*/3, /*chara_id*/288, /*title*/"小松伊吹", /*sub_title*/"", /*disp_order*/188);
INSERT INTO `story_category` VALUES (/*id*/189, /*type*/2, /*chara_type*/3, /*chara_id*/289, /*title*/"三好紗南", /*sub_title*/"", /*disp_order*/189);
INSERT INTO `story_category` VALUES (/*id*/191, /*type*/2, /*chara_type*/3, /*chara_id*/291, /*title*/"難波笑美", /*sub_title*/"", /*disp_order*/191);
INSERT INTO `story_category` VALUES (/*id*/192, /*type*/2, /*chara_type*/3, /*chara_id*/292, /*title*/"浜口あやめ", /*sub_title*/"", /*disp_order*/192);
INSERT INTO `story_category` VALUES (/*id*/193, /*type*/2, /*chara_type*/3, /*chara_id*/293, /*title*/"村上巴", /*sub_title*/"", /*disp_order*/193);
INSERT INTO `story_category` VALUES (/*id*/194, /*type*/2, /*chara_type*/3, /*chara_id*/294, /*title*/"土屋亜子", /*sub_title*/"", /*disp_order*/194);
INSERT INTO `story_category` VALUES (/*id*/195, /*type*/2, /*chara_type*/3, /*chara_id*/295, /*title*/"首藤葵", /*sub_title*/"", /*disp_order*/195);
INSERT INTO `story_category` VALUES (/*id*/201, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第1話", /*sub_title*/"Stage, We climb the stairs.", /*disp_order*/202);
INSERT INTO `story_category` VALUES (/*id*/202, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第2話", /*sub_title*/"Wish upon a Star ! !", /*disp_order*/203);
INSERT INTO `story_category` VALUES (/*id*/203, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第3話", /*sub_title*/"SING, Smile, S(mile)ING !", /*disp_order*/204);
INSERT INTO `story_category` VALUES (/*id*/204, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第4話", /*sub_title*/"the flower of my heart.", /*disp_order*/205);
INSERT INTO `story_category` VALUES (/*id*/205, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第5話", /*sub_title*/"Lucky Star☆", /*disp_order*/206);
INSERT INTO `story_category` VALUES (/*id*/206, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第6話", /*sub_title*/"Cat's whiskers♪", /*disp_order*/207);
INSERT INTO `story_category` VALUES (/*id*/207, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第7話", /*sub_title*/"\"Rock\" is the coolest word.", /*disp_order*/208);
INSERT INTO `story_category` VALUES (/*id*/208, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第0話", /*sub_title*/"Cast a spell on me!", /*disp_order*/201);
INSERT INTO `story_category` VALUES (/*id*/209, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第8話", /*sub_title*/"Girls be Ambitious ! !", /*disp_order*/209);
INSERT INTO `story_category` VALUES (/*id*/210, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第9話", /*sub_title*/"Happiness is here.", /*disp_order*/210);
INSERT INTO `story_category` VALUES (/*id*/211, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第10話", /*sub_title*/"Large Star, Little girl.", /*disp_order*/211);
INSERT INTO `story_category` VALUES (/*id*/212, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第11話", /*sub_title*/"NO ID(O)L(E) NO LIFE !", /*disp_order*/212);
INSERT INTO `story_category` VALUES (/*id*/213, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第12話", /*sub_title*/"Drop in the Darkness !", /*disp_order*/213);
INSERT INTO `story_category` VALUES (/*id*/214, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第13話", /*sub_title*/"Sweets Party ! !", /*disp_order*/214);
INSERT INTO `story_category` VALUES (/*id*/215, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"アタシポンコツアンドロイド", /*sub_title*/"アタシポンコツアンドロイド", /*disp_order*/1);
INSERT INTO `story_category` VALUES (/*id*/216, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第14話", /*sub_title*/"Naked Venus", /*disp_order*/215);
INSERT INTO `story_category` VALUES (/*id*/217, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第15話", /*sub_title*/"Fun ! Fun ! ! Fun ! ! !", /*disp_order*/216);
INSERT INTO `story_category` VALUES (/*id*/218, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Nation Blue", /*sub_title*/"Nation Blue", /*disp_order*/2);
INSERT INTO `story_category` VALUES (/*id*/219, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第16話", /*sub_title*/"Alone, But Not Lonely", /*disp_order*/217);
INSERT INTO `story_category` VALUES (/*id*/220, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Orange Sapphire", /*sub_title*/"Orange Sapphire", /*disp_order*/3);
INSERT INTO `story_category` VALUES (/*id*/221, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第17話", /*sub_title*/"Everything About the Love", /*disp_order*/218);
INSERT INTO `story_category` VALUES (/*id*/222, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Snow Wings", /*sub_title*/"Snow Wings", /*disp_order*/4);
INSERT INTO `story_category` VALUES (/*id*/223, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"ゴキゲンParty Night", /*sub_title*/"ゴキゲンParty Night", /*disp_order*/5);
INSERT INTO `story_category` VALUES (/*id*/224, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第18話", /*sub_title*/"Dreaming Place", /*disp_order*/219);
INSERT INTO `story_category` VALUES (/*id*/225, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第19話", /*sub_title*/"Just Started", /*disp_order*/220);
INSERT INTO `story_category` VALUES (/*id*/226, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第20話", /*sub_title*/"Happiness Happening !", /*disp_order*/221);
INSERT INTO `story_category` VALUES (/*id*/227, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"パステルピンクな恋", /*sub_title*/"パステルピンクな恋", /*disp_order*/6);
INSERT INTO `story_category` VALUES (/*id*/228, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第21話", /*sub_title*/"With or Without You", /*disp_order*/222);
INSERT INTO `story_category` VALUES (/*id*/229, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"Tulip", /*sub_title*/"Tulip", /*disp_order*/7);
INSERT INTO `story_category` VALUES (/*id*/230, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第22話", /*sub_title*/"Out of the Page", /*disp_order*/223);
INSERT INTO `story_category` VALUES (/*id*/231, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"オルゴールの小箱", /*sub_title*/"オルゴールの小箱", /*disp_order*/8);
INSERT INTO `story_category` VALUES (/*id*/232, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第23話", /*sub_title*/"Because You are You", /*disp_order*/224);
INSERT INTO `story_category` VALUES (/*id*/233, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第24話", /*sub_title*/"Sakura Bloom", /*disp_order*/225);
INSERT INTO `story_category` VALUES (/*id*/234, /*type*/1, /*chara_type*/0, /*chara_id*/0, /*title*/"第25話", /*sub_title*/"coming soon", /*disp_order*/226);
INSERT INTO `story_category` VALUES (/*id*/254, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"絶対特権主張しますっ ! ", /*sub_title*/"絶対特権主張しますっ ! ", /*disp_order*/9);
INSERT INTO `story_category` VALUES (/*id*/255, /*type*/3, /*chara_type*/0, /*chara_id*/0, /*title*/"ハイファイ☆デイズ", /*sub_title*/"ハイファイ☆デイズ", /*disp_order*/10);
INSERT INTO `story_category` VALUES (/*id*/256, /*type*/4, /*chara_type*/0, /*chara_id*/0, /*title*/"とある事務員の一日", /*sub_title*/"とある事務員の一日", /*disp_order*/1);
