CREATE TABLE 'tips' ('id' INTEGER NOT NULL, 'tips_type' INTEGER NOT NULL, 'value' INTEGER NOT NULL, 'index' INTEGER NOT NULL, 'title' TEXT NOT NULL, 'comment' TEXT NOT NULL, PRIMARY KEY('id'))
INSERT INTO `tips` VALUES (/*id*/1, /*tips_type*/1, /*value*/2, /*index*/1, /*title*/"千川ちひろのウワサ", /*comment*/"制服は夏服・冬服など\n５着あるらしい。");
INSERT INTO `tips` VALUES (/*id*/2, /*tips_type*/1, /*value*/101, /*index*/1, /*title*/"島村卯月のウワサ", /*comment*/"クラスメイトの誰もが\n「卯月ちゃんは友だち ! 」\nと言うらしい。");
INSERT INTO `tips` VALUES (/*id*/3, /*tips_type*/1, /*value*/102, /*index*/1, /*title*/"中野有香のウワサ", /*comment*/"髪の2本縛りをほどくと\nとても照れるらしい。");
INSERT INTO `tips` VALUES (/*id*/4, /*tips_type*/1, /*value*/103, /*index*/1, /*title*/"水本ゆかりのウワサ", /*comment*/"自分の吹くフルートの音色で\n眠ったことがあるらしい。");
INSERT INTO `tips` VALUES (/*id*/5, /*tips_type*/1, /*value*/104, /*index*/1, /*title*/"福山舞のウワサ", /*comment*/"いつもクラス代表や学年代表の\nあいさつを任されるらしい。");
INSERT INTO `tips` VALUES (/*id*/6, /*tips_type*/1, /*value*/105, /*index*/1, /*title*/"椎名法子のウワサ", /*comment*/"お気に入りのクッションは\n真ん中に穴が開いているらしい。");
INSERT INTO `tips` VALUES (/*id*/7, /*tips_type*/1, /*value*/136, /*index*/1, /*title*/"桃井あずきのウワサ", /*comment*/"反物の種類には\nかなりくわしいらしい。");
INSERT INTO `tips` VALUES (/*id*/8, /*tips_type*/1, /*value*/141, /*index*/1, /*title*/"道明寺歌鈴のウワサ", /*comment*/"神社の本殿の中では\n一度も転んだことがないらしい。");
INSERT INTO `tips` VALUES (/*id*/9, /*tips_type*/1, /*value*/108, /*index*/1, /*title*/"三村かな子のウワサ", /*comment*/"誰にでも自分から声をかけるよう\n意識しているらしい。");
INSERT INTO `tips` VALUES (/*id*/10, /*tips_type*/1, /*value*/109, /*index*/1, /*title*/"奥山沙織のウワサ", /*comment*/"お米の味には\nうるさいらしい。");
INSERT INTO `tips` VALUES (/*id*/11, /*tips_type*/1, /*value*/204, /*index*/1, /*title*/"綾瀬穂乃香のウワサ", /*comment*/"どんなところでも\nストレッチをしてしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/12, /*tips_type*/1, /*value*/111, /*index*/1, /*title*/"小日向美穂のウワサ", /*comment*/"馬刺しや辛子レンコンなど\nお酒のつまみが好きらしい。");
INSERT INTO `tips` VALUES (/*id*/13, /*tips_type*/1, /*value*/112, /*index*/1, /*title*/"緒方智絵里のウワサ", /*comment*/"動物番組を見ていると、\nつい泣いてしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/14, /*tips_type*/1, /*value*/205, /*index*/1, /*title*/"佐城雪美のウワサ", /*comment*/"会話の練習のため、\n鏡に映った自分と\n話しているらしい。");
INSERT INTO `tips` VALUES (/*id*/15, /*tips_type*/1, /*value*/266, /*index*/1, /*title*/"若林智香のウワサ", /*comment*/"実は、バック転ができるらしい。");
INSERT INTO `tips` VALUES (/*id*/16, /*tips_type*/1, /*value*/269, /*index*/1, /*title*/"仙崎恵磨のウワサ", /*comment*/"声が大きすぎて、\nマイクを壊したことが\nあるらしい。");
INSERT INTO `tips` VALUES (/*id*/17, /*tips_type*/1, /*value*/122, /*index*/1, /*title*/"藤本里奈のウワサ", /*comment*/"いつも行くコンビニの前に\nゴミが落ちていると\nつい拾ってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/18, /*tips_type*/1, /*value*/127, /*index*/1, /*title*/"前川みくのウワサ", /*comment*/"自室のネコ耳クローゼットには\n子どものころに撮った\n猫との写真がおいてあるらしい。");
INSERT INTO `tips` VALUES (/*id*/19, /*tips_type*/1, /*value*/131, /*index*/1, /*title*/"宮本フレデリカのウワサ", /*comment*/"短大では、デザインを\n学んでいるらしい。");
INSERT INTO `tips` VALUES (/*id*/20, /*tips_type*/1, /*value*/132, /*index*/1, /*title*/"小早川紗枝のウワサ", /*comment*/"バニラアイスに、黒蜜をかけて\n食べるのが好きらしい。");
INSERT INTO `tips` VALUES (/*id*/21, /*tips_type*/1, /*value*/134, /*index*/1, /*title*/"双葉杏のウワサ", /*comment*/"いつも連れている\nうさぎのぬいぐるみの名前は\n「うさぎ」らしい。");
INSERT INTO `tips` VALUES (/*id*/22, /*tips_type*/1, /*value*/150, /*index*/1, /*title*/"輿水幸子のウワサ", /*comment*/"体を張れる自分に\nプロ根性を感じているらしい。");
INSERT INTO `tips` VALUES (/*id*/23, /*tips_type*/1, /*value*/154, /*index*/1, /*title*/"安部菜々のウワサ", /*comment*/"自宅で、アニメを見ながら\nアフレコ練習をしているらしい。");
INSERT INTO `tips` VALUES (/*id*/24, /*tips_type*/1, /*value*/167, /*index*/1, /*title*/"渋谷凛のウワサ", /*comment*/"テストの答案は、わからなくても\n全部埋めているらしい。");
INSERT INTO `tips` VALUES (/*id*/25, /*tips_type*/1, /*value*/169, /*index*/1, /*title*/"松本沙理奈のウワサ", /*comment*/"夏以外の季節は、\n「早く夏にならないかな～」\nと言っているらしい。");
INSERT INTO `tips` VALUES (/*id*/26, /*tips_type*/1, /*value*/172, /*index*/1, /*title*/"相川千夏のウワサ", /*comment*/"髪の分け目は今の位置が\nお気に入りらしい。");
INSERT INTO `tips` VALUES (/*id*/27, /*tips_type*/1, /*value*/173, /*index*/1, /*title*/"川島瑞樹のウワサ", /*comment*/"時の流れを止められるらしい。");
INSERT INTO `tips` VALUES (/*id*/28, /*tips_type*/1, /*value*/174, /*index*/1, /*title*/"神谷奈緒のウワサ", /*comment*/"カッコイイ服もカワイイ服も\n持っているが、ふだん着るのは\nカッコイイ服らしい。");
INSERT INTO `tips` VALUES (/*id*/29, /*tips_type*/1, /*value*/175, /*index*/1, /*title*/"上条春菜のウワサ", /*comment*/"寝るときに掛けるための眼鏡を\n持っているらしい。");
INSERT INTO `tips` VALUES (/*id*/30, /*tips_type*/1, /*value*/176, /*index*/1, /*title*/"荒木比奈のウワサ", /*comment*/"夏と冬のスケジューリングは\n必死に調整するらしい。");
INSERT INTO `tips` VALUES (/*id*/31, /*tips_type*/1, /*value*/178, /*index*/1, /*title*/"多田李衣菜のウワサ", /*comment*/"実はすごく耳がいいので、\nヘッドホンからの音漏れは\n基本的にしないらしい。");
INSERT INTO `tips` VALUES (/*id*/32, /*tips_type*/1, /*value*/180, /*index*/1, /*title*/"佐々木千枝のウワサ", /*comment*/"学校で使う給食袋は\n自分で縫ったものらしい。");
INSERT INTO `tips` VALUES (/*id*/33, /*tips_type*/1, /*value*/185, /*index*/1, /*title*/"新田美波のウワサ", /*comment*/"手帳にはスケジュールが分刻みで\n書き込まれているらしい。");
INSERT INTO `tips` VALUES (/*id*/34, /*tips_type*/1, /*value*/188, /*index*/1, /*title*/"橘ありすのウワサ", /*comment*/"ためしに書いた歌詞は\n小論文のようだったらしい。");
INSERT INTO `tips` VALUES (/*id*/35, /*tips_type*/1, /*value*/197, /*index*/1, /*title*/"高垣楓のウワサ", /*comment*/"行きつけの美容院の担当は\nモデル時代のヘアメイクらしい。");
INSERT INTO `tips` VALUES (/*id*/36, /*tips_type*/1, /*value*/198, /*index*/1, /*title*/"神崎蘭子のウワサ", /*comment*/"実は結構な読書家らしい。");
INSERT INTO `tips` VALUES (/*id*/37, /*tips_type*/1, /*value*/201, /*index*/1, /*title*/"北条加蓮のウワサ", /*comment*/"水着の撮影や、日焼けに\n憧れているらしい。");
INSERT INTO `tips` VALUES (/*id*/38, /*tips_type*/1, /*value*/223, /*index*/1, /*title*/"速水奏のウワサ", /*comment*/"常になにかしらの\n隠し事を抱えているのが\n美貌の秘訣らしい。");
INSERT INTO `tips` VALUES (/*id*/39, /*tips_type*/1, /*value*/227, /*index*/1, /*title*/"アナスタシアのウワサ", /*comment*/"いつか小惑星を見つけて\n名前をつけたいらしい。");
INSERT INTO `tips` VALUES (/*id*/40, /*tips_type*/1, /*value*/234, /*index*/1, /*title*/"本田未央のウワサ", /*comment*/"学食のおばちゃんと仲良しで、\n大盛りにしてもらえるらしい。");
INSERT INTO `tips` VALUES (/*id*/41, /*tips_type*/1, /*value*/235, /*index*/1, /*title*/"高森藍子のウワサ", /*comment*/"散歩用の歩きやすくて可愛い靴を\n常に探しているらしい。");
INSERT INTO `tips` VALUES (/*id*/42, /*tips_type*/1, /*value*/237, /*index*/1, /*title*/"龍崎薫のウワサ", /*comment*/"お母さんの作ったごはんが、\nいちばん好きらしい。");
INSERT INTO `tips` VALUES (/*id*/43, /*tips_type*/1, /*value*/238, /*index*/1, /*title*/"木村夏樹のウワサ", /*comment*/"有名バンドのギターピックを\nお守り代わりにしているらしい。");
INSERT INTO `tips` VALUES (/*id*/44, /*tips_type*/1, /*value*/243, /*index*/1, /*title*/"赤城みりあのウワサ", /*comment*/"家族に花や現場のお菓子などの\nお土産を毎日持って帰るらしい。");
INSERT INTO `tips` VALUES (/*id*/45, /*tips_type*/1, /*value*/246, /*index*/1, /*title*/"大槻唯のウワサ", /*comment*/"初対面の人でも\nスキンシップから入るらしい。");
INSERT INTO `tips` VALUES (/*id*/46, /*tips_type*/1, /*value*/247, /*index*/1, /*title*/"姫川友紀のウワサ", /*comment*/"球場で飲むビールが\n世界で一番おいしいものらしい。");
INSERT INTO `tips` VALUES (/*id*/47, /*tips_type*/1, /*value*/253, /*index*/1, /*title*/"及川雫のウワサ", /*comment*/"利き牛乳ができるらしい。");
INSERT INTO `tips` VALUES (/*id*/48, /*tips_type*/1, /*value*/256, /*index*/1, /*title*/"星輝子のウワサ", /*comment*/"晴れている日は\n日陰を選んで歩くらしい。");
INSERT INTO `tips` VALUES (/*id*/49, /*tips_type*/1, /*value*/257, /*index*/1, /*title*/"片桐早苗のウワサ", /*comment*/"マイ警笛を持ち歩くのが、\n習慣になっているらしい。");
INSERT INTO `tips` VALUES (/*id*/50, /*tips_type*/1, /*value*/258, /*index*/1, /*title*/"堀裕子のウワサ", /*comment*/"常に7つのサイキックアイテムを\n持ち歩いているらしい。");
INSERT INTO `tips` VALUES (/*id*/51, /*tips_type*/1, /*value*/267, /*index*/1, /*title*/"城ヶ崎美嘉のウワサ", /*comment*/"ポーチはいつも最新のコスメで\nパンパンらしい。");
INSERT INTO `tips` VALUES (/*id*/52, /*tips_type*/1, /*value*/268, /*index*/1, /*title*/"城ヶ崎莉嘉のウワサ", /*comment*/"クラスの男子とも女子とも\n混ざって遊ぶのが好きらしい。");
INSERT INTO `tips` VALUES (/*id*/53, /*tips_type*/1, /*value*/270, /*index*/1, /*title*/"日野茜のウワサ", /*comment*/"一番得意な泳法は、\nバタフライらしい。");
INSERT INTO `tips` VALUES (/*id*/54, /*tips_type*/1, /*value*/271, /*index*/1, /*title*/"諸星きらりのウワサ", /*comment*/"小物をデコる腕前は、\nプロダクションでもなかなか\nらしい。");
INSERT INTO `tips` VALUES (/*id*/55, /*tips_type*/1, /*value*/272, /*index*/1, /*title*/"十時愛梨のウワサ", /*comment*/"大学のキャンパスでは\n常に、女友達が一緒らしい。");
INSERT INTO `tips` VALUES (/*id*/56, /*tips_type*/1, /*value*/273, /*index*/1, /*title*/"ナターリアのウワサ", /*comment*/"父親は、サッカーチームの\n指導者をしているらしい。");
INSERT INTO `tips` VALUES (/*id*/57, /*tips_type*/1, /*value*/214, /*index*/1, /*title*/"白坂小梅のウワサ", /*comment*/"ホラー映画用の棚の裏に…\nもうひとつ棚があるらしい…。");
INSERT INTO `tips` VALUES (/*id*/58, /*tips_type*/1, /*value*/126, /*index*/1, /*title*/"一ノ瀬志希のウワサ", /*comment*/"独り暮らしをしているが\nたまに家に帰らないらしい。");
INSERT INTO `tips` VALUES (/*id*/59, /*tips_type*/1, /*value*/220, /*index*/1, /*title*/"塩見周子のウワサ", /*comment*/"献血が好きなのは\n『スーッとするから』らしい。");
INSERT INTO `tips` VALUES (/*id*/60, /*tips_type*/1, /*value*/263, /*index*/1, /*title*/"相葉夕美のウワサ", /*comment*/"オーガニックのカフェにいって\nまったりするのが好きらしい。");
INSERT INTO `tips` VALUES (/*id*/61, /*tips_type*/1, /*value*/159, /*index*/1, /*title*/"佐久間まゆのウワサ", /*comment*/"真っ赤な日記帳に\nアイドルになってからの日々を\n綴っているらしい。");
INSERT INTO `tips` VALUES (/*id*/62, /*tips_type*/1, /*value*/292, /*index*/1, /*title*/"浜口あやめのウワサ", /*comment*/"手づくりの煙玉で、たまに\nゲホゲホむせているらしい。");
INSERT INTO `tips` VALUES (/*id*/63, /*tips_type*/1, /*value*/194, /*index*/1, /*title*/"松永涼のウワサ", /*comment*/"クラシックやジャズなどにも\n造詣が深いらしい。");
INSERT INTO `tips` VALUES (/*id*/64, /*tips_type*/1, /*value*/113, /*index*/1, /*title*/"五十嵐響子のウワサ", /*comment*/"着る服の趣味が、ガラッと\n変わることがあるらしい。");
INSERT INTO `tips` VALUES (/*id*/65, /*tips_type*/1, /*value*/189, /*index*/1, /*title*/"鷺沢文香のウワサ", /*comment*/"雨上がりだけは、いつも\n顔を上げて空をみるらしい。");
INSERT INTO `tips` VALUES (/*id*/66, /*tips_type*/1, /*value*/239, /*index*/1, /*title*/"松山久美子のウワサ", /*comment*/"いろいろな国のアロマオイルを\n集めているらしい。");
INSERT INTO `tips` VALUES (/*id*/67, /*tips_type*/1, /*value*/133, /*index*/1, /*title*/"西園寺琴歌のウワサ", /*comment*/"行きのロケバス内では\nやる気満々で眠れないが、\n帰りはぐっすりらしい。");
INSERT INTO `tips` VALUES (/*id*/68, /*tips_type*/1, /*value*/230, /*index*/1, /*title*/"二宮飛鳥のウワサ", /*comment*/"自分の目で見ないかぎり、\nウワサは信じないらしい。");
INSERT INTO `tips` VALUES (/*id*/69, /*tips_type*/1, /*value*/158, /*index*/1, /*title*/"クラリスのウワサ", /*comment*/"アイドルのギャラのほとんどは\n恵まれない人への募金などに\n費やすらしい。");
INSERT INTO `tips` VALUES (/*id*/70, /*tips_type*/1, /*value*/287, /*index*/1, /*title*/"メアリー・コクランのウワサ", /*comment*/"プロフィールの数字を\n少し多く申告したらしい。");
INSERT INTO `tips` VALUES (/*id*/71, /*tips_type*/1, /*value*/221, /*index*/1, /*title*/"脇山珠美のウワサ", /*comment*/"いつも持ち歩いている竹刀は\n『竹男』という名前らしい。");
INSERT INTO `tips` VALUES (/*id*/72, /*tips_type*/1, /*value*/118, /*index*/1, /*title*/"横山千佳のウワサ", /*comment*/"日曜日の朝は、早起きらしい。");
INSERT INTO `tips` VALUES (/*id*/73, /*tips_type*/1, /*value*/168, /*index*/1, /*title*/"黒川千秋のウワサ", /*comment*/"プライベートでは、ズボンを\nほとんどはかないらしい。");
INSERT INTO `tips` VALUES (/*id*/74, /*tips_type*/1, /*value*/242, /*index*/1, /*title*/"矢口美羽のウワサ", /*comment*/"沈黙が苦手で\nつい喋ってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/75, /*tips_type*/1, /*value*/283, /*index*/1, /*title*/"市原仁奈のウワサ", /*comment*/"着ぐるみを着ていると\nかわいがってもらえるのが\n嬉しいらしい。");
INSERT INTO `tips` VALUES (/*id*/76, /*tips_type*/1, /*value*/155, /*index*/1, /*title*/"工藤忍のウワサ", /*comment*/"いつか、父と母と自分で、\n新しい家族写真を撮りたいと\n思っているらしい。");
INSERT INTO `tips` VALUES (/*id*/77, /*tips_type*/1, /*value*/280, /*index*/1, /*title*/"向井拓海のウワサ", /*comment*/"コンサートライトを振られると\nつい、その方向に曲がりたく\nなってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/78, /*tips_type*/1, /*value*/161, /*index*/1, /*title*/"白菊ほたるのウワサ", /*comment*/"折りたたみ傘を持っていると\nいつも快晴らしい。");
INSERT INTO `tips` VALUES (/*id*/79, /*tips_type*/1, /*value*/226, /*index*/1, /*title*/"森久保乃々のウワサ", /*comment*/"絵本作家になる夢があり、\nそれを諦めていないらしい。");
INSERT INTO `tips` VALUES (/*id*/80, /*tips_type*/1, /*value*/284, /*index*/1, /*title*/"喜多日菜子のウワサ", /*comment*/"座右の銘は\n夢とは起きて見るもの\nらしい。");
INSERT INTO `tips` VALUES (/*id*/81, /*tips_type*/1, /*value*/115, /*index*/1, /*title*/"櫻井桃華のウワサ", /*comment*/"いい香りがするハンカチを\nいつも持っているらしい。");
INSERT INTO `tips` VALUES (/*id*/82, /*tips_type*/1, /*value*/181, /*index*/1, /*title*/"三船美優のウワサ", /*comment*/"満員電車で、\nよく流されているらしい。");
INSERT INTO `tips` VALUES (/*id*/83, /*tips_type*/1, /*value*/249, /*index*/1, /*title*/"喜多見柚のウワサ", /*comment*/"前髪とパーカーが\nオシャレのこだわりらしい。");
INSERT INTO `tips` VALUES (/*id*/84, /*tips_type*/1, /*value*/165, /*index*/1, /*title*/"原田美世のウワサ", /*comment*/"仕事先には、\n可能な限り車で向かうらしい。");
INSERT INTO `tips` VALUES (/*id*/85, /*tips_type*/1, /*value*/139, /*index*/1, /*title*/"兵藤レナのウワサ", /*comment*/"自分はイカサマしないが、\n誰かにイカサマされても\n1回は見逃すらしい。");
INSERT INTO `tips` VALUES (/*id*/86, /*tips_type*/1, /*value*/147, /*index*/1, /*title*/"井村雪菜のウワサ", /*comment*/"お仕事の内容や\n会う人の好みに合わせて、\nメイクを変えているらしい。");
INSERT INTO `tips` VALUES (/*id*/87, /*tips_type*/1, /*value*/228, /*index*/1, /*title*/"大和亜季のウワサ", /*comment*/"毎週金曜日は\nカレーを食べるらしい。");
INSERT INTO `tips` VALUES (/*id*/88, /*tips_type*/1, /*value*/190, /*index*/1, /*title*/"八神マキノのウワサ", /*comment*/"10歳からの自分の行動を\nデジタルデータで\n残しているらしい。");
INSERT INTO `tips` VALUES (/*id*/89, /*tips_type*/1, /*value*/293, /*index*/1, /*title*/"村上巴のウワサ", /*comment*/"将棋のネット対戦に\nハマっているらしい。");
INSERT INTO `tips` VALUES (/*id*/90, /*tips_type*/1, /*value*/162, /*index*/1, /*title*/"早坂美玲のウワサ", /*comment*/"フードを脱いでいるときは\n気合いのスイッチが入っていない\nときらしい。");
INSERT INTO `tips` VALUES (/*id*/91, /*tips_type*/1, /*value*/106, /*index*/1, /*title*/"今井加奈のウワサ", /*comment*/"寝る前にメモを見返すのが\n日課らしい。");
INSERT INTO `tips` VALUES (/*id*/92, /*tips_type*/1, /*value*/184, /*index*/1, /*title*/"藤原肇のウワサ", /*comment*/"生地をこねるのも得意らしい。");
INSERT INTO `tips` VALUES (/*id*/93, /*tips_type*/1, /*value*/262, /*index*/1, /*title*/"依田芳乃のウワサ", /*comment*/"話が長く、次第に説法のように\nなっていくのが癖らしい。");
INSERT INTO `tips` VALUES (/*id*/94, /*tips_type*/1, /*value*/291, /*index*/1, /*title*/"難波笑美のウワサ", /*comment*/"とっておきのかくし芸は\n真顔でしゃべる標準語らしい。");
INSERT INTO `tips` VALUES (/*id*/95, /*tips_type*/1, /*value*/229, /*index*/1, /*title*/"結城晴のウワサ", /*comment*/"足癖が悪いのを\nそのうち直す予定らしい。");
INSERT INTO `tips` VALUES (/*id*/96, /*tips_type*/1, /*value*/191, /*index*/1, /*title*/"ライラのウワサ", /*comment*/"使用人だったメイドといっしょに\n日本へやってきたらしい。");
INSERT INTO `tips` VALUES (/*id*/97, /*tips_type*/1, /*value*/222, /*index*/1, /*title*/"岡崎泰葉のウワサ", /*comment*/"手書きの字は\nとてもキレイらしい。");
INSERT INTO `tips` VALUES (/*id*/98, /*tips_type*/1, /*value*/254, /*index*/1, /*title*/"小関麗奈のウワサ", /*comment*/"高台を見つけるたびに、\n立って、高笑いするらしい。");
INSERT INTO `tips` VALUES (/*id*/99, /*tips_type*/1, /*value*/121, /*index*/1, /*title*/"棟方愛海のウワサ", /*comment*/"ものすごく寂しがり屋らしい。");
INSERT INTO `tips` VALUES (/*id*/100, /*tips_type*/1, /*value*/179, /*index*/1, /*title*/"水木聖來のウワサ", /*comment*/"聖來の『來』の字を\n間違えられるのに慣れすぎて、\nたまに自分でも間違えるらしい。");
INSERT INTO `tips` VALUES (/*id*/101, /*tips_type*/1, /*value*/260, /*index*/1, /*title*/"的場梨沙のウワサ", /*comment*/"本人いわく、梨沙のファンは、\nすべてロリコンらしい。");
INSERT INTO `tips` VALUES (/*id*/102, /*tips_type*/1, /*value*/219, /*index*/1, /*title*/"藤居朋のウワサ", /*comment*/"たまにパワースポットで\n変なポーズをしているらしい。");
INSERT INTO `tips` VALUES (/*id*/103, /*tips_type*/1, /*value*/224, /*index*/1, /*title*/"大石泉のウワサ", /*comment*/"泉にとって友情とは\n計算がいらないものらしい。");
INSERT INTO `tips` VALUES (/*id*/104, /*tips_type*/1, /*value*/289, /*index*/1, /*title*/"三好紗南のウワサ", /*comment*/"じっとしていても、\n指や足が、自然に動くらしい。");
INSERT INTO `tips` VALUES (/*id*/105, /*tips_type*/1, /*value*/294, /*index*/1, /*title*/"土屋亜子のウワサ", /*comment*/"亜子にとって友情とは、\nお金で買えないものらしい。");
INSERT INTO `tips` VALUES (/*id*/106, /*tips_type*/1, /*value*/160, /*index*/1, /*title*/"村松さくらのウワサ", /*comment*/"さくらにとって友情とは、\nいつでもそこにあるものらしい。");
INSERT INTO `tips` VALUES (/*id*/107, /*tips_type*/1, /*value*/107, /*index*/1, /*title*/"持田亜里沙のウワサ", /*comment*/"童謡以外の曲も\nそこそこ弾けるらしい。");
INSERT INTO `tips` VALUES (/*id*/108, /*tips_type*/1, /*value*/177, /*index*/1, /*title*/"東郷あいのウワサ", /*comment*/"小さなバーのステージで\nたまにサックス演奏するらしい。");
INSERT INTO `tips` VALUES (/*id*/109, /*tips_type*/1, /*value*/295, /*index*/1, /*title*/"首藤葵のウワサ", /*comment*/"いつか、事務所に\n社員食堂をつくりたいらしい。");
INSERT INTO `tips` VALUES (/*id*/110, /*tips_type*/1, /*value*/138, /*index*/1, /*title*/"月宮雅のウワサ", /*comment*/"自分の夢は、\nママの夢をかなえてから\n考えるらしい。");
INSERT INTO `tips` VALUES (/*id*/111, /*tips_type*/1, /*value*/186, /*index*/1, /*title*/"水野翠のウワサ", /*comment*/"行動する前に、つい\n溜めをつくるらしい。");
INSERT INTO `tips` VALUES (/*id*/112, /*tips_type*/1, /*value*/288, /*index*/1, /*title*/"小松伊吹のウワサ", /*comment*/"恋愛映画を見ている時は\nずっと顔が真っ赤らしい。");
INSERT INTO `tips` VALUES (/*id*/113, /*tips_type*/1, /*value*/149, /*index*/1, /*title*/"榊原里美のウワサ", /*comment*/"幼い頃は、兄と野原を\n駆け回っていたらしい。");
INSERT INTO `tips` VALUES (/*id*/114, /*tips_type*/1, /*value*/119, /*index*/1, /*title*/"関裕美のウワサ", /*comment*/"いつも、手鏡を\n持ち歩いているらしい。");
INSERT INTO `tips` VALUES (/*id*/115, /*tips_type*/1, /*value*/218, /*index*/1, /*title*/"成宮由愛のウワサ", /*comment*/"いろんな習い事をやったが、\n絵以外はどれも続かなかった\nらしい。");
INSERT INTO `tips` VALUES (/*id*/116, /*tips_type*/1, /*value*/250, /*index*/1, /*title*/"上田鈴帆のウワサ", /*comment*/"指先の傷は努力の証らしい。");
INSERT INTO `tips` VALUES (/*id*/117, /*tips_type*/1, /*value*/213, /*index*/1, /*title*/"梅木音葉のウワサ", /*comment*/"6種類の楽器が弾けるらしい。");
INSERT INTO `tips` VALUES (/*id*/118, /*tips_type*/1, /*value*/236, /*index*/1, /*title*/"並木芽衣子のウワサ", /*comment*/"旅先では、すべての名所に\nかならず立ち寄るらしい。");
INSERT INTO `tips` VALUES (/*id*/119, /*tips_type*/1, /*value*/135, /*index*/1, /*title*/"楊菲菲のウワサ", /*comment*/"おばあちゃんの顔を見に、\n二か月に一度は実家へ帰るらしい。");
INSERT INTO `tips` VALUES (/*id*/120, /*tips_type*/1, /*value*/211, /*index*/1, /*title*/"和久井留美のウワサ", /*comment*/"ストレスが限界に達すると、\nバッティングセンターで\n三振して帰ってくるらしい。");
INSERT INTO `tips` VALUES (/*id*/121, /*tips_type*/1, /*value*/164, /*index*/1, /*title*/"乙倉悠貴のウワサ", /*comment*/"ハイヒールの大人っぽさに\n憧れているらしい。");
INSERT INTO `tips` VALUES (/*id*/122, /*tips_type*/1, /*value*/216, /*index*/1, /*title*/"氏家むつみのウワサ", /*comment*/"手頃な長さの紐を見つけると、\nムチのように扱いたくなるらしい。");
INSERT INTO `tips` VALUES (/*id*/123, /*tips_type*/1, /*value*/285, /*index*/1, /*title*/"杉坂海のウワサ", /*comment*/"食べ物を人数分、均等に\n分けるのがうまいらしい。");
INSERT INTO `tips` VALUES (/*id*/124, /*tips_type*/1, /*value*/286, /*index*/1, /*title*/"北川真尋のウワサ", /*comment*/"前髪が伸びると、\n自分で切ってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/125, /*tips_type*/1, /*value*/129, /*index*/1, /*title*/"松原早耶のウワサ", /*comment*/"鏡の前に立つと、ポーズを\nとらなければいけない気に\nなるらしい。");
INSERT INTO `tips` VALUES (/*id*/126, /*tips_type*/1, /*value*/163, /*index*/1, /*title*/"有浦柑奈のウワサ", /*comment*/"ラブ＆ピースを広めるための歌を\n作詞・作曲する予定らしい。");
INSERT INTO `tips` VALUES (/*id*/127, /*tips_type*/1, /*value*/171, /*index*/1, /*title*/"高橋礼子のウワサ", /*comment*/"お酒を飲むと、\n真面目に将来のことを\n語りだすらしい。");
INSERT INTO `tips` VALUES (/*id*/128, /*tips_type*/1, /*value*/275, /*index*/1, /*title*/"槙原志保のウワサ", /*comment*/"深夜のパフェは月に３回までと\n決めているが、昼間のパフェは\nノーカウントらしい。");
INSERT INTO `tips` VALUES (/*id*/129, /*tips_type*/1, /*value*/123, /*index*/1, /*title*/"大原みちるのウワサ", /*comment*/"登校中は、パンをくわえながら\n走っているが、人をちゃんと\n避けてしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/130, /*tips_type*/1, /*value*/192, /*index*/1, /*title*/"浅利七海のウワサ", /*comment*/"昔、海で溺れたときに、\n大きな魚のような何かに\n助けられたらしい。");
INSERT INTO `tips` VALUES (/*id*/131, /*tips_type*/1, /*value*/240, /*index*/1, /*title*/"斉藤洋子のウワサ", /*comment*/"通販で健康器具を買っても、\n一回しか使わなかったものが\n数多くあるらしい。");
INSERT INTO `tips` VALUES (/*id*/132, /*tips_type*/1, /*value*/153, /*index*/1, /*title*/"大西由里子のウワサ", /*comment*/"部屋の本棚に収まりきらない\n本の、新たな隠し場所を\n探し回っているらしい。");
INSERT INTO `tips` VALUES (/*id*/133, /*tips_type*/1, /*value*/210, /*index*/1, /*title*/"篠原礼のウワサ", /*comment*/"ダンス中、\nボディタッチが少し多めらしい。");
INSERT INTO `tips` VALUES (/*id*/134, /*tips_type*/1, /*value*/183, /*index*/1, /*title*/"木場真奈美のウワサ", /*comment*/"なにかを失敗した日は\n一駅分走るらしい。");
INSERT INTO `tips` VALUES (/*id*/135, /*tips_type*/1, /*value*/259, /*index*/1, /*title*/"西島櫂のウワサ", /*comment*/"髪のセットをしたことが\nないらしい。");
INSERT INTO `tips` VALUES (/*id*/136, /*tips_type*/1, /*value*/156, /*index*/1, /*title*/"栗原ネネのウワサ", /*comment*/"たくさん食べる人が\n好きらしい。");
INSERT INTO `tips` VALUES (/*id*/137, /*tips_type*/1, /*value*/120, /*index*/1, /*title*/"太田優のウワサ", /*comment*/"アッキーとの出会いは\n涙なしでは語れないらしい。");
INSERT INTO `tips` VALUES (/*id*/138, /*tips_type*/1, /*value*/212, /*index*/1, /*title*/"吉岡沙紀のウワサ", /*comment*/"自由人に見られることが多いが、\n本人はしっかりしている\nつもりらしい。");
INSERT INTO `tips` VALUES (/*id*/139, /*tips_type*/1, /*value*/244, /*index*/1, /*title*/"愛野渚のウワサ", /*comment*/"髪をくくるための\nリボンを集めていることは\n誰にも言えないらしい。");
INSERT INTO `tips` VALUES (/*id*/140, /*tips_type*/1, /*value*/202, /*index*/1, /*title*/"ケイトのウワサ", /*comment*/"立ち飲み居酒屋へ行き、\nたこわさをつまみに\n一杯やるらしい。");
INSERT INTO `tips` VALUES (/*id*/141, /*tips_type*/1, /*value*/255, /*index*/1, /*title*/"衛藤美紗希のウワサ", /*comment*/"女子力を言葉で表すのは\n難しいので、身振り手振りで\n説明してしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/142, /*tips_type*/1, /*value*/298, /*index*/1, /*title*/"南条光のウワサ", /*comment*/"跳ねすぎて、\nベッドのスプリングを\nよく壊してしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/143, /*tips_type*/1, /*value*/125, /*index*/1, /*title*/"大沼くるみのウワサ", /*comment*/"頭をよくしたいので、\n大豆食品を食べるように\nしているらしい。");
INSERT INTO `tips` VALUES (/*id*/144, /*tips_type*/1, /*value*/187, /*index*/1, /*title*/"古澤頼子のウワサ", /*comment*/"美術館をハシゴしたことが\nあるらしい。");
INSERT INTO `tips` VALUES (/*id*/145, /*tips_type*/1, /*value*/151, /*index*/1, /*title*/"安斎都のウワサ", /*comment*/"直感は外れるらしい。");
INSERT INTO `tips` VALUES (/*id*/146, /*tips_type*/1, /*value*/170, /*index*/1, /*title*/"桐野アヤのウワサ", /*comment*/"一人焼肉にも\n行けるらしい。");
INSERT INTO `tips` VALUES (/*id*/147, /*tips_type*/1, /*value*/274, /*index*/1, /*title*/"相馬夏美のウワサ", /*comment*/"モテ期はこれから !\nらしい。");
INSERT INTO `tips` VALUES (/*id*/148, /*tips_type*/1, /*value*/297, /*index*/1, /*title*/"佐藤心のウワサ", /*comment*/"チャンスをモノにできるよう、\n完璧なビールの注ぎ方を\nマスターしたらしい。");
INSERT INTO `tips` VALUES (/*id*/149, /*tips_type*/1, /*value*/145, /*index*/1, /*title*/"柳清良のウワサ", /*comment*/"ピトッとするアレと\nチクッとするアレを\nバッグに忍ばせているらしい。");
INSERT INTO `tips` VALUES (/*id*/150, /*tips_type*/1, /*value*/231, /*index*/1, /*title*/"桐生つかさのウワサ", /*comment*/"ウワサで判断されるとか\n勘弁だし、アポとってくんない？\nらしい。");
INSERT INTO `tips` VALUES (/*id*/151, /*tips_type*/1, /*value*/124, /*index*/1, /*title*/"遊佐こずえのウワサ", /*comment*/"みんなのはなしを\nきいているだけで\nしあわせなきもちになるらしい。");
INSERT INTO `tips` VALUES (/*id*/152, /*tips_type*/1, /*value*/157, /*index*/1, /*title*/"古賀小春のウワサ", /*comment*/"虫は苦手じゃない\nらしい。");
INSERT INTO `tips` VALUES (/*id*/153, /*tips_type*/1, /*value*/225, /*index*/1, /*title*/"松尾千鶴のウワサ", /*comment*/"それなりにうまくやっている\nつもりらしい。");
INSERT INTO `tips` VALUES (/*id*/154, /*tips_type*/1, /*value*/241, /*index*/1, /*title*/"沢田麻理菜のウワサ", /*comment*/"一年中サマーソングを\n聴いているらしい。");
INSERT INTO `tips` VALUES (/*id*/155, /*tips_type*/1, /*value*/203, /*index*/1, /*title*/"瀬名詩織のウワサ", /*comment*/"悩んだときに、\n海を散歩していると、\n海風が背中を押してくれるらしい。");
INSERT INTO `tips` VALUES (/*id*/156, /*tips_type*/1, /*value*/182, /*index*/1, /*title*/"服部瞳子のウワサ", /*comment*/"一人の夜には\n熱帯魚から\n勇気をもらっているらしい。");
INSERT INTO `tips` VALUES (/*id*/157, /*tips_type*/1, /*value*/264, /*index*/1, /*title*/"野々村そらのウワサ", /*comment*/"「はっぴー来い来い\nすまいるげーと」らしい。");
INSERT INTO `tips` VALUES (/*id*/158, /*tips_type*/1, /*value*/137, /*index*/1, /*title*/"涼宮星花のウワサ", /*comment*/"ウィーンに留学中、\n毎晩電話をかけたせいで\n電話代が大変なことになったらしい。");
INSERT INTO `tips` VALUES (/*id*/20001, /*tips_type*/2, /*value*/1, /*index*/1, /*title*/"スタミナドリンク", /*comment*/"スタミナドリンクを使うと、スタミナを回復できます !");
INSERT INTO `tips` VALUES (/*id*/30001, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"アイドルを育てるには", /*comment*/"アイドルのレベルを上げるには、\nレッスンを行いましょう !");
INSERT INTO `tips` VALUES (/*id*/30002, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"アイドルとの親愛度を上げるには", /*comment*/"LIVEを行うと、\n参加したアイドルの親愛度が上がります !");
INSERT INTO `tips` VALUES (/*id*/30003, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"新しい楽曲を解放するには", /*comment*/"ストーリーコミュをクリアしたり、\nルームのサウンドブースで楽曲購入すると、新しい楽曲が解放できますよ !");
INSERT INTO `tips` VALUES (/*id*/30004, /*tips_type*/3, /*value*/1, /*index*/1, /*title*/"デレステへようこそ !", /*comment*/"これからアイドルのプロデュース\nがんばっていきましょう !");
INSERT INTO `tips` VALUES (/*id*/30005, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"センターアイドルにすると", /*comment*/"センターにしたアイドルは親愛度が\n上がりやすくなります !");
INSERT INTO `tips` VALUES (/*id*/30006, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ユニットを変更したい", /*comment*/"ユニットの編集は、\nアイドル編成からいつでも行えます。\nお気に入りのユニットを編成しよう !");
INSERT INTO `tips` VALUES (/*id*/30007, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ローカルオーディションガシャ", /*comment*/"ローカルオーディションガシャでは\nアイドルやアイテムが手に入ります !");
INSERT INTO `tips` VALUES (/*id*/30008, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ガシャを引くには", /*comment*/"ガシャはスタージュエルや友情ptを、\n利用して引くことができます !");
INSERT INTO `tips` VALUES (/*id*/30009, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"LIVEでリズムが合わない時は", /*comment*/"リズムアイコンのタイミングがずれる\n場合はタイミングを調整できます。");
INSERT INTO `tips` VALUES (/*id*/30010, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"LIVEが難しいと感じたら", /*comment*/"LIVEが難しい場合はLIVE設定から、\n練習LIVEを行うことができますよ !");
INSERT INTO `tips` VALUES (/*id*/30011, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"タイミング調整について", /*comment*/"タイミング調整は、LIVE設定から\nいつでも実行できます !");
INSERT INTO `tips` VALUES (/*id*/30012, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"アイドルを特訓するには", /*comment*/"アイドルとの親愛度がMAXになると、\nアイドルを特訓できます。\n特訓にはアイテムが必要になります。");
INSERT INTO `tips` VALUES (/*id*/30013, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"特訓に必要なアイテム", /*comment*/"特訓に必要なアイテムは、\nLIVEやルームで入手できます !");
INSERT INTO `tips` VALUES (/*id*/30014, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"エピソードコミュ", /*comment*/"アイドルを特訓すると、\nエピソードコミュが解放されます !");
INSERT INTO `tips` VALUES (/*id*/30015, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"特訓すると", /*comment*/"アイドルを特訓すると、\nビジュアルが変わったり\n能力がアップします !");
INSERT INTO `tips` VALUES (/*id*/30016, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ゲストメンバー", /*comment*/"LIVEでは、他のプロデューサーの\nセンターアイドルをゲストで\n呼ぶことができます !");
INSERT INTO `tips` VALUES (/*id*/30017, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"合計アピール", /*comment*/"ユニットの合計アピール値が\n上がるとLIVEで高いSCOREを\n獲得できるようになります !");
INSERT INTO `tips` VALUES (/*id*/30018, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"LIVEクリア", /*comment*/"LIVEに成功すると、アイテムや\nアイドルを獲得できます !");
INSERT INTO `tips` VALUES (/*id*/30019, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ルーム訪問", /*comment*/"他のプロデューサーのルームに\n訪問することができます。\nLikeすると友情ptも貰えますよ !");
INSERT INTO `tips` VALUES (/*id*/30020, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"名前を変更したい時は", /*comment*/"プロデューサー名は、プロフィールから\nいつでも変更できますよ !");
INSERT INTO `tips` VALUES (/*id*/30021, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"データ引き継ぎについて", /*comment*/"データ引き継ぎを行うと今まで遊んだ\nデータを他の端末に\n引き継ぐことができます !");
INSERT INTO `tips` VALUES (/*id*/30022, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ログインボーナスについて", /*comment*/"ゲームにログインするだけで、\n毎日アイテムやスタージュエルが\nGETできます !");
INSERT INTO `tips` VALUES (/*id*/30023, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"アイドルの特技", /*comment*/"特技を持っているアイドルは、\nLIVEが有利になる特技を\n発動することがあります !");
INSERT INTO `tips` VALUES (/*id*/30024, /*tips_type*/3, /*value*/1, /*index*/1, /*title*/"マッチング中", /*comment*/"現在マッチングを行っています。\nしばらくお待ちください。");
INSERT INTO `tips` VALUES (/*id*/40001, /*tips_type*/4, /*value*/101, /*index*/1, /*title*/"島村卯月①　がんばりすぎ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40002, /*tips_type*/4, /*value*/102, /*index*/1, /*title*/"中野有香①　リボンをギュっと !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40003, /*tips_type*/4, /*value*/103, /*index*/1, /*title*/"水本ゆかり①　私って天然ですか？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40004, /*tips_type*/4, /*value*/104, /*index*/1, /*title*/"福山舞①　一輪車が得意です♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40005, /*tips_type*/4, /*value*/105, /*index*/1, /*title*/"椎名法子①　ドーナツの不思議…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40006, /*tips_type*/4, /*value*/108, /*index*/1, /*title*/"三村かな子①　お菓子作りあるある？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40007, /*tips_type*/4, /*value*/109, /*index*/1, /*title*/"奥山沙織①　普段から…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40008, /*tips_type*/4, /*value*/111, /*index*/1, /*title*/"小日向美穂①　夢の中でも…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40009, /*tips_type*/4, /*value*/112, /*index*/1, /*title*/"緒方智絵里①　花かんむりを作ろう", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40010, /*tips_type*/4, /*value*/122, /*index*/1, /*title*/"藤本里奈①　ちょりっす変えてみた", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40011, /*tips_type*/4, /*value*/127, /*index*/1, /*title*/"前川みく①　一緒に『にゃあ♪』", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40012, /*tips_type*/4, /*value*/131, /*index*/1, /*title*/"宮本フレデリカ①　新曲 ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40013, /*tips_type*/4, /*value*/132, /*index*/1, /*title*/"小早川紗枝①　こんちきちん講座", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40014, /*tips_type*/4, /*value*/134, /*index*/1, /*title*/"双葉杏①　よかったことはー", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40015, /*tips_type*/4, /*value*/136, /*index*/1, /*title*/"桃井あずき①　得意な大作戦 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40016, /*tips_type*/4, /*value*/141, /*index*/1, /*title*/"道明寺歌鈴①　本人知らずの芸術", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40017, /*tips_type*/4, /*value*/150, /*index*/1, /*title*/"輿水幸子①　至福の時間ですね !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40018, /*tips_type*/4, /*value*/154, /*index*/1, /*title*/"安部菜々①　ここはウサミン星…？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40019, /*tips_type*/4, /*value*/167, /*index*/1, /*title*/"渋谷凛①　お店モード", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40020, /*tips_type*/4, /*value*/169, /*index*/1, /*title*/"松本沙理奈①　これが大人ポーズ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40021, /*tips_type*/4, /*value*/172, /*index*/1, /*title*/"相川千夏①　何語の本？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40022, /*tips_type*/4, /*value*/173, /*index*/1, /*title*/"川島瑞樹①　まだイケルわ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40023, /*tips_type*/4, /*value*/174, /*index*/1, /*title*/"神谷奈緒①　だーからっ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40024, /*tips_type*/4, /*value*/175, /*index*/1, /*title*/"上条春菜①　春菜チャレンジ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40025, /*tips_type*/4, /*value*/176, /*index*/1, /*title*/"荒木比奈①　これがベストッス", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40026, /*tips_type*/4, /*value*/178, /*index*/1, /*title*/"多田李衣菜①　カンペキ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40027, /*tips_type*/4, /*value*/180, /*index*/1, /*title*/"佐々木千枝①　うさぎさん大好き", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40028, /*tips_type*/4, /*value*/185, /*index*/1, /*title*/"新田美波①　美波はお勉強が好き", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40029, /*tips_type*/4, /*value*/188, /*index*/1, /*title*/"橘ありす①　名前で呼ばれるのは…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40030, /*tips_type*/4, /*value*/197, /*index*/1, /*title*/"高垣楓①　６×９=？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40031, /*tips_type*/4, /*value*/198, /*index*/1, /*title*/"神崎蘭子①　堕天使の裏側", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40032, /*tips_type*/4, /*value*/201, /*index*/1, /*title*/"北条加蓮①　ちがうから !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40033, /*tips_type*/4, /*value*/204, /*index*/1, /*title*/"綾瀬穂乃香①　お気に入りです", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40034, /*tips_type*/4, /*value*/205, /*index*/1, /*title*/"佐城雪美①　ペロとおはなし", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40035, /*tips_type*/4, /*value*/214, /*index*/1, /*title*/"白坂小梅①　ホラー映画なら…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40036, /*tips_type*/4, /*value*/223, /*index*/1, /*title*/"速水奏①　女子高生なんだけどな", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40037, /*tips_type*/4, /*value*/227, /*index*/1, /*title*/"アナスタシア①　危険な混ざり方", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40038, /*tips_type*/4, /*value*/234, /*index*/1, /*title*/"本田未央①　あの人のあだ名", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40039, /*tips_type*/4, /*value*/235, /*index*/1, /*title*/"高森藍子①　ゆるふわの弱点", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40040, /*tips_type*/4, /*value*/237, /*index*/1, /*title*/"龍崎薫①　いいまちがい", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40041, /*tips_type*/4, /*value*/238, /*index*/1, /*title*/"木村夏樹①　セットの時間", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40042, /*tips_type*/4, /*value*/243, /*index*/1, /*title*/"赤城みりあ①　なーう ! ! !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40043, /*tips_type*/4, /*value*/246, /*index*/1, /*title*/"大槻唯①　でも何で？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40044, /*tips_type*/4, /*value*/247, /*index*/1, /*title*/"姫川友紀①　こんな時もあるよ…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40045, /*tips_type*/4, /*value*/253, /*index*/1, /*title*/"及川雫①　牛乳で育ちました", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40046, /*tips_type*/4, /*value*/256, /*index*/1, /*title*/"星輝子①　Q・メタル好きなの？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40047, /*tips_type*/4, /*value*/257, /*index*/1, /*title*/"片桐早苗①　バブルとは", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40048, /*tips_type*/4, /*value*/258, /*index*/1, /*title*/"堀裕子①　サイキックー !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40049, /*tips_type*/4, /*value*/266, /*index*/1, /*title*/"若林智香①　応援 ! 応援 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40050, /*tips_type*/4, /*value*/267, /*index*/1, /*title*/"城ヶ崎美嘉①　得意でしょー ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40051, /*tips_type*/4, /*value*/268, /*index*/1, /*title*/"城ヶ崎莉嘉①　カリスマシール貼り", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40052, /*tips_type*/4, /*value*/269, /*index*/1, /*title*/"仙崎恵磨①　マイクVS声 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40053, /*tips_type*/4, /*value*/270, /*index*/1, /*title*/"日野茜①　茜のお散歩日和", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40054, /*tips_type*/4, /*value*/271, /*index*/1, /*title*/"諸星きらり①　してないにぃ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40055, /*tips_type*/4, /*value*/272, /*index*/1, /*title*/"十時愛梨①　テキパキ愛梨 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40056, /*tips_type*/4, /*value*/273, /*index*/1, /*title*/"ナターリア①　みくも安心な寿司？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40057, /*tips_type*/4, /*value*/999, /*index*/1, /*title*/"エトセトラ①　READY GO !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40058, /*tips_type*/4, /*value*/2, /*index*/1, /*title*/"千川ちひろ①　楽しんでくださいね", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40059, /*tips_type*/4, /*value*/2, /*index*/2, /*title*/"千川ちひろ②　ちひろさんの趣味", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40060, /*tips_type*/4, /*value*/126, /*index*/1, /*title*/"一ノ瀬志希①　いい匂いがする～", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40061, /*tips_type*/4, /*value*/263, /*index*/1, /*title*/"相葉夕美①　待ってる時間に", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40062, /*tips_type*/4, /*value*/220, /*index*/1, /*title*/"塩見周子①　趣味は献血", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40063, /*tips_type*/4, /*value*/159, /*index*/1, /*title*/"佐久間まゆ①　もう10冊目♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40064, /*tips_type*/4, /*value*/292, /*index*/1, /*title*/"浜口あやめ①　あやめも忍法… !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40065, /*tips_type*/4, /*value*/194, /*index*/1, /*title*/"松永涼①　ホラーはいいけど…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40066, /*tips_type*/4, /*value*/113, /*index*/1, /*title*/"五十嵐響子①　何の感想？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40067, /*tips_type*/4, /*value*/189, /*index*/1, /*title*/"鷺沢文香①　どこでも読書", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40068, /*tips_type*/4, /*value*/239, /*index*/1, /*title*/"松山久美子①　キレイを求めて", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40069, /*tips_type*/4, /*value*/133, /*index*/1, /*title*/"西園寺琴歌①　事務所でも愛好会", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40070, /*tips_type*/4, /*value*/230, /*index*/1, /*title*/"二宮飛鳥①　今この場所は…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40071, /*tips_type*/4, /*value*/158, /*index*/1, /*title*/"クラリス①　天使と堕天使", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40072, /*tips_type*/4, /*value*/287, /*index*/1, /*title*/"メアリー・コクラン①　大人っぽいところ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40073, /*tips_type*/4, /*value*/221, /*index*/1, /*title*/"脇山珠美①　時代劇鑑賞会", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40074, /*tips_type*/4, /*value*/118, /*index*/1, /*title*/"横山千佳①　A・魔法少女アニメ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40075, /*tips_type*/4, /*value*/168, /*index*/1, /*title*/"黒川千秋①　千秋、ここで一言", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40076, /*tips_type*/4, /*value*/242, /*index*/1, /*title*/"矢口美羽①　理想の…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40077, /*tips_type*/4, /*value*/283, /*index*/1, /*title*/"市原仁奈①　一緒に『ぴょん♪』", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40078, /*tips_type*/4, /*value*/155, /*index*/1, /*title*/"工藤忍①　バイリンガル？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40079, /*tips_type*/4, /*value*/280, /*index*/1, /*title*/"向井拓海①　薔薇・喧嘩", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40080, /*tips_type*/4, /*value*/161, /*index*/1, /*title*/"白菊ほたる①　私がいえ私が", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40081, /*tips_type*/4, /*value*/226, /*index*/1, /*title*/"森久保乃々①　乃々を探せ ! レベル1", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40082, /*tips_type*/4, /*value*/284, /*index*/1, /*title*/"喜多日菜子①　むふふなう", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40083, /*tips_type*/4, /*value*/115, /*index*/1, /*title*/"櫻井桃華①　たしなみですわよ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40084, /*tips_type*/4, /*value*/181, /*index*/1, /*title*/"三船美優①　お静かに…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40085, /*tips_type*/4, /*value*/249, /*index*/1, /*title*/"喜多見柚①　いいコト考えたっ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40086, /*tips_type*/4, /*value*/165, /*index*/1, /*title*/"原田美世①　車大好き !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40087, /*tips_type*/4, /*value*/139, /*index*/1, /*title*/"兵藤レナ①　not サイキック", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40088, /*tips_type*/4, /*value*/147, /*index*/1, /*title*/"井村雪菜①　変身するの♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40089, /*tips_type*/4, /*value*/228, /*index*/1, /*title*/"大和亜季①　サバゲのルール", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40090, /*tips_type*/4, /*value*/190, /*index*/1, /*title*/"八神マキノ①　それは周知です", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40091, /*tips_type*/4, /*value*/293, /*index*/1, /*title*/"村上巴①　お年寄りの影響？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40092, /*tips_type*/4, /*value*/162, /*index*/1, /*title*/"早坂美玲①　ファッションだぞッ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40093, /*tips_type*/4, /*value*/106, /*index*/1, /*title*/"今井加奈①　忘れないように !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40094, /*tips_type*/4, /*value*/184, /*index*/1, /*title*/"藤原肇①　肇の趣味は", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40095, /*tips_type*/4, /*value*/262, /*index*/1, /*title*/"依田芳乃①　探しものはおまかせ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40096, /*tips_type*/4, /*value*/291, /*index*/1, /*title*/"難波笑美①　本場の !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40097, /*tips_type*/4, /*value*/229, /*index*/1, /*title*/"結城晴①　とられる理由", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40098, /*tips_type*/4, /*value*/191, /*index*/1, /*title*/"ライラ①　冬でもアイス", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40099, /*tips_type*/4, /*value*/222, /*index*/1, /*title*/"岡崎泰葉①　業界用語？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40100, /*tips_type*/4, /*value*/254, /*index*/1, /*title*/"小関麗奈①　怯えなさいッ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40101, /*tips_type*/4, /*value*/121, /*index*/1, /*title*/"棟方愛海①　されるよりする側", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40102, /*tips_type*/4, /*value*/179, /*index*/1, /*title*/"水木聖來①　うちのわんこ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40103, /*tips_type*/4, /*value*/260, /*index*/1, /*title*/"的場梨沙①　大きな目標 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40104, /*tips_type*/4, /*value*/219, /*index*/1, /*title*/"藤居朋①　どうすれば ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40105, /*tips_type*/4, /*value*/224, /*index*/1, /*title*/"大石泉①　ノってきた !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40106, /*tips_type*/4, /*value*/289, /*index*/1, /*title*/"三好紗南①　一日一時間…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40107, /*tips_type*/4, /*value*/294, /*index*/1, /*title*/"土屋亜子①　初見の感想", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40108, /*tips_type*/4, /*value*/160, /*index*/1, /*title*/"村松さくら①　マスコット", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40109, /*tips_type*/4, /*value*/107, /*index*/1, /*title*/"持田亜里沙①　起こしてウサコ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40110, /*tips_type*/4, /*value*/177, /*index*/1, /*title*/"東郷あい①　趣味はサックス", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40111, /*tips_type*/4, /*value*/295, /*index*/1, /*title*/"首藤葵①　料理人のプライド", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40112, /*tips_type*/4, /*value*/138, /*index*/1, /*title*/"月宮雅①　会員番号1番", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40113, /*tips_type*/4, /*value*/186, /*index*/1, /*title*/"水野翠①　会", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40114, /*tips_type*/4, /*value*/288, /*index*/1, /*title*/"小松伊吹①　足がいい !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40115, /*tips_type*/4, /*value*/149, /*index*/1, /*title*/"榊原里美①　超・甘党", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40116, /*tips_type*/4, /*value*/119, /*index*/1, /*title*/"関裕美①　視力のせいじゃ…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40117, /*tips_type*/4, /*value*/218, /*index*/1, /*title*/"成宮由愛①　描きたい風景", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40118, /*tips_type*/4, /*value*/250, /*index*/1, /*title*/"上田鈴帆①　届くかこの想い", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40119, /*tips_type*/4, /*value*/213, /*index*/1, /*title*/"梅木音葉①　住人…？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40120, /*tips_type*/4, /*value*/236, /*index*/1, /*title*/"並木芽衣子①　新しい目標 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40121, /*tips_type*/4, /*value*/135, /*index*/1, /*title*/"楊菲菲①　強そうに見えル？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40122, /*tips_type*/4, /*value*/211, /*index*/1, /*title*/"和久井留美①　猫が好き", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40123, /*tips_type*/4, /*value*/164, /*index*/1, /*title*/"乙倉悠貴①　ミックスジュース作りが趣味", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40124, /*tips_type*/4, /*value*/216, /*index*/1, /*title*/"氏家むつみ①　今回の冒険 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40125, /*tips_type*/4, /*value*/285, /*index*/1, /*title*/"杉坂海①　お…ねえちゃん？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40126, /*tips_type*/4, /*value*/286, /*index*/1, /*title*/"北川真尋①　好きなことはー !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40127, /*tips_type*/4, /*value*/129, /*index*/1, /*title*/"松原早耶①　流行好き♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40128, /*tips_type*/4, /*value*/163, /*index*/1, /*title*/"有浦柑奈①　ここで一曲", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40129, /*tips_type*/4, /*value*/171, /*index*/1, /*title*/"高橋礼子①　夢と希望を", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40130, /*tips_type*/4, /*value*/275, /*index*/1, /*title*/"槙原志保①　何つながりか…わかる", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40131, /*tips_type*/4, /*value*/123, /*index*/1, /*title*/"大原みちる①　みちるチャレンジ ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40132, /*tips_type*/4, /*value*/192, /*index*/1, /*title*/"浅利七海①　心静かにれす", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40133, /*tips_type*/4, /*value*/240, /*index*/1, /*title*/"斉藤洋子①　何のポーズ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40134, /*tips_type*/4, /*value*/153, /*index*/1, /*title*/"大西由里子①　得意なハナシ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40135, /*tips_type*/4, /*value*/210, /*index*/1, /*title*/"篠原礼①　なぞなぞ考え中", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40136, /*tips_type*/4, /*value*/183, /*index*/1, /*title*/"木場真奈美①　真奈美の弱点？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40137, /*tips_type*/4, /*value*/259, /*index*/1, /*title*/"西島櫂①　水あるところに", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40138, /*tips_type*/4, /*value*/156, /*index*/1, /*title*/"栗原ネネ①　栄養第一です♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40139, /*tips_type*/4, /*value*/120, /*index*/1, /*title*/"太田優①　いつも抱いてる", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40140, /*tips_type*/4, /*value*/212, /*index*/1, /*title*/"吉岡沙紀①　これでどうっす？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40141, /*tips_type*/4, /*value*/244, /*index*/1, /*title*/"愛野渚①　ゴミ箱にシュート", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40142, /*tips_type*/4, /*value*/202, /*index*/1, /*title*/"ケイト①　雑誌が好きデス♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40143, /*tips_type*/4, /*value*/255, /*index*/1, /*title*/"衛藤美紗希①　オススメなのぉ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40144, /*tips_type*/4, /*value*/298, /*index*/1, /*title*/"南条光①　アタシが倒す !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40145, /*tips_type*/4, /*value*/125, /*index*/1, /*title*/"大沼くるみ①　ティッシュ収集趣味でしゅ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40146, /*tips_type*/4, /*value*/187, /*index*/1, /*title*/"古澤頼子①　皆で行きましょう", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40147, /*tips_type*/4, /*value*/151, /*index*/1, /*title*/"安斎都①　趣味は推理小説を…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40148, /*tips_type*/4, /*value*/170, /*index*/1, /*title*/"桐野アヤ①　インターバル中", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40149, /*tips_type*/4, /*value*/274, /*index*/1, /*title*/"相馬夏美①　CA風に", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40150, /*tips_type*/4, /*value*/297, /*index*/1, /*title*/"佐藤心①　和めよ☆", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40151, /*tips_type*/4, /*value*/145, /*index*/1, /*title*/"柳清良①　体調を心配して", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40152, /*tips_type*/4, /*value*/231, /*index*/1, /*title*/"桐生つかさ①　本気ってわかる？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40153, /*tips_type*/4, /*value*/124, /*index*/1, /*title*/"遊佐こずえ①　猫のように", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40154, /*tips_type*/4, /*value*/157, /*index*/1, /*title*/"古賀小春①　(…仲間かな？)", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40155, /*tips_type*/4, /*value*/225, /*index*/1, /*title*/"松尾千鶴①　渾身の書 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40156, /*tips_type*/4, /*value*/241, /*index*/1, /*title*/"沢田麻理菜①　よかったこと", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40157, /*tips_type*/4, /*value*/203, /*index*/1, /*title*/"瀬名詩織①　…分かります…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40158, /*tips_type*/4, /*value*/182, /*index*/1, /*title*/"服部瞳子①　昔デビューした時の…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40159, /*tips_type*/4, /*value*/264, /*index*/1, /*title*/"野々村そら①　れっつしんぐ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40160, /*tips_type*/4, /*value*/137, /*index*/1, /*title*/"涼宮星花①　A・ネイル無理繋がり", /*comment*/"");
