CREATE TABLE 'tips' ('id' INTEGER NOT NULL, 'tips_type' INTEGER NOT NULL, 'value' INTEGER NOT NULL, 'index' INTEGER NOT NULL, 'title' TEXT NOT NULL, 'comment' TEXT NOT NULL, PRIMARY KEY('id'))
INSERT INTO `tips` VALUES (/*id*/1, /*tips_type*/1, /*value*/2, /*index*/1, /*title*/"千川ちひろのウワサ①", /*comment*/"制服は夏服・冬服など\n５着あるらしい。");
INSERT INTO `tips` VALUES (/*id*/2, /*tips_type*/1, /*value*/101, /*index*/1, /*title*/"島村卯月のウワサ①", /*comment*/"クラスメイトの誰もが\n「卯月ちゃんは友だち ! 」\nと言うらしい。");
INSERT INTO `tips` VALUES (/*id*/3, /*tips_type*/1, /*value*/102, /*index*/1, /*title*/"中野有香のウワサ①", /*comment*/"髪の2本縛りをほどくと\nとても照れるらしい。");
INSERT INTO `tips` VALUES (/*id*/4, /*tips_type*/1, /*value*/103, /*index*/1, /*title*/"水本ゆかりのウワサ①", /*comment*/"自分の吹くフルートの音色で\n眠ったことがあるらしい。");
INSERT INTO `tips` VALUES (/*id*/5, /*tips_type*/1, /*value*/104, /*index*/1, /*title*/"福山舞のウワサ①", /*comment*/"いつもクラス代表や学年代表の\nあいさつを任されるらしい。");
INSERT INTO `tips` VALUES (/*id*/6, /*tips_type*/1, /*value*/105, /*index*/1, /*title*/"椎名法子のウワサ①", /*comment*/"お気に入りのクッションは\n真ん中に穴が開いているらしい。");
INSERT INTO `tips` VALUES (/*id*/7, /*tips_type*/1, /*value*/136, /*index*/1, /*title*/"桃井あずきのウワサ①", /*comment*/"反物の種類には\nかなりくわしいらしい。");
INSERT INTO `tips` VALUES (/*id*/8, /*tips_type*/1, /*value*/141, /*index*/1, /*title*/"道明寺歌鈴のウワサ①", /*comment*/"神社の本殿の中では\n一度も転んだことがないらしい。");
INSERT INTO `tips` VALUES (/*id*/9, /*tips_type*/1, /*value*/108, /*index*/1, /*title*/"三村かな子のウワサ①", /*comment*/"誰にでも自分から声をかけるよう\n意識しているらしい。");
INSERT INTO `tips` VALUES (/*id*/10, /*tips_type*/1, /*value*/109, /*index*/1, /*title*/"奥山沙織のウワサ①", /*comment*/"お米の味には\nうるさいらしい。");
INSERT INTO `tips` VALUES (/*id*/11, /*tips_type*/1, /*value*/204, /*index*/1, /*title*/"綾瀬穂乃香のウワサ①", /*comment*/"どんなところでも\nストレッチをしてしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/12, /*tips_type*/1, /*value*/111, /*index*/1, /*title*/"小日向美穂のウワサ①", /*comment*/"馬刺しや辛子レンコンなど\nお酒のつまみが好きらしい。");
INSERT INTO `tips` VALUES (/*id*/13, /*tips_type*/1, /*value*/112, /*index*/1, /*title*/"緒方智絵里のウワサ①", /*comment*/"動物番組を見ていると、\nつい泣いてしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/14, /*tips_type*/1, /*value*/205, /*index*/1, /*title*/"佐城雪美のウワサ①", /*comment*/"会話の練習のため、\n鏡に映った自分と\n話しているらしい。");
INSERT INTO `tips` VALUES (/*id*/15, /*tips_type*/1, /*value*/266, /*index*/1, /*title*/"若林智香のウワサ①", /*comment*/"実は、バック転ができるらしい。");
INSERT INTO `tips` VALUES (/*id*/16, /*tips_type*/1, /*value*/269, /*index*/1, /*title*/"仙崎恵磨のウワサ①", /*comment*/"声が大きすぎて、\nマイクを壊したことが\nあるらしい。");
INSERT INTO `tips` VALUES (/*id*/17, /*tips_type*/1, /*value*/122, /*index*/1, /*title*/"藤本里奈のウワサ①", /*comment*/"いつも行くコンビニの前に\nゴミが落ちていると\nつい拾ってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/18, /*tips_type*/1, /*value*/127, /*index*/1, /*title*/"前川みくのウワサ①", /*comment*/"自室のネコ耳クローゼットには\n子どものころに撮った\n猫との写真がおいてあるらしい。");
INSERT INTO `tips` VALUES (/*id*/19, /*tips_type*/1, /*value*/131, /*index*/1, /*title*/"宮本フレデリカのウワサ①", /*comment*/"短大では、デザインを\n学んでいるらしい。");
INSERT INTO `tips` VALUES (/*id*/20, /*tips_type*/1, /*value*/132, /*index*/1, /*title*/"小早川紗枝のウワサ①", /*comment*/"バニラアイスに、黒蜜をかけて\n食べるのが好きらしい。");
INSERT INTO `tips` VALUES (/*id*/21, /*tips_type*/1, /*value*/134, /*index*/1, /*title*/"双葉杏のウワサ①", /*comment*/"いつも連れている\nうさぎのぬいぐるみの名前は\n「うさぎ」らしい。");
INSERT INTO `tips` VALUES (/*id*/22, /*tips_type*/1, /*value*/150, /*index*/1, /*title*/"輿水幸子のウワサ①", /*comment*/"体を張れる自分に\nプロ根性を感じているらしい。");
INSERT INTO `tips` VALUES (/*id*/23, /*tips_type*/1, /*value*/154, /*index*/1, /*title*/"安部菜々のウワサ①", /*comment*/"自宅で、アニメを見ながら\nアフレコ練習をしているらしい。");
INSERT INTO `tips` VALUES (/*id*/24, /*tips_type*/1, /*value*/167, /*index*/1, /*title*/"渋谷凛のウワサ①", /*comment*/"テストの答案は、わからなくても\n全部埋めているらしい。");
INSERT INTO `tips` VALUES (/*id*/25, /*tips_type*/1, /*value*/169, /*index*/1, /*title*/"松本沙理奈のウワサ①", /*comment*/"夏以外の季節は、\n「早く夏にならないかな～」\nと言っているらしい。");
INSERT INTO `tips` VALUES (/*id*/26, /*tips_type*/1, /*value*/172, /*index*/1, /*title*/"相川千夏のウワサ①", /*comment*/"髪の分け目は今の位置が\nお気に入りらしい。");
INSERT INTO `tips` VALUES (/*id*/27, /*tips_type*/1, /*value*/173, /*index*/1, /*title*/"川島瑞樹のウワサ①", /*comment*/"時の流れを止められるらしい。");
INSERT INTO `tips` VALUES (/*id*/28, /*tips_type*/1, /*value*/174, /*index*/1, /*title*/"神谷奈緒のウワサ①", /*comment*/"カッコイイ服もカワイイ服も\n持っているが、ふだん着るのは\nカッコイイ服らしい。");
INSERT INTO `tips` VALUES (/*id*/29, /*tips_type*/1, /*value*/175, /*index*/1, /*title*/"上条春菜のウワサ①", /*comment*/"寝るときに掛けるための眼鏡を\n持っているらしい。");
INSERT INTO `tips` VALUES (/*id*/30, /*tips_type*/1, /*value*/176, /*index*/1, /*title*/"荒木比奈のウワサ①", /*comment*/"夏と冬のスケジューリングは\n必死に調整するらしい。");
INSERT INTO `tips` VALUES (/*id*/31, /*tips_type*/1, /*value*/178, /*index*/1, /*title*/"多田李衣菜のウワサ①", /*comment*/"実はすごく耳がいいので、\nヘッドホンからの音漏れは\n基本的にしないらしい。");
INSERT INTO `tips` VALUES (/*id*/32, /*tips_type*/1, /*value*/180, /*index*/1, /*title*/"佐々木千枝のウワサ①", /*comment*/"学校で使う給食袋は\n自分で縫ったものらしい。");
INSERT INTO `tips` VALUES (/*id*/33, /*tips_type*/1, /*value*/185, /*index*/1, /*title*/"新田美波のウワサ①", /*comment*/"手帳にはスケジュールが分刻みで\n書き込まれているらしい。");
INSERT INTO `tips` VALUES (/*id*/34, /*tips_type*/1, /*value*/188, /*index*/1, /*title*/"橘ありすのウワサ①", /*comment*/"ためしに書いた歌詞は\n小論文のようだったらしい。");
INSERT INTO `tips` VALUES (/*id*/35, /*tips_type*/1, /*value*/197, /*index*/1, /*title*/"高垣楓のウワサ①", /*comment*/"行きつけの美容院の担当は\nモデル時代のヘアメイクらしい。");
INSERT INTO `tips` VALUES (/*id*/36, /*tips_type*/1, /*value*/198, /*index*/1, /*title*/"神崎蘭子のウワサ①", /*comment*/"実は結構な読書家らしい。");
INSERT INTO `tips` VALUES (/*id*/37, /*tips_type*/1, /*value*/201, /*index*/1, /*title*/"北条加蓮のウワサ①", /*comment*/"水着の撮影や、日焼けに\n憧れているらしい。");
INSERT INTO `tips` VALUES (/*id*/38, /*tips_type*/1, /*value*/223, /*index*/1, /*title*/"速水奏のウワサ①", /*comment*/"常になにかしらの\n隠し事を抱えているのが\n美貌の秘訣らしい。");
INSERT INTO `tips` VALUES (/*id*/39, /*tips_type*/1, /*value*/227, /*index*/1, /*title*/"アナスタシアのウワサ①", /*comment*/"いつか小惑星を見つけて\n名前をつけたいらしい。");
INSERT INTO `tips` VALUES (/*id*/40, /*tips_type*/1, /*value*/234, /*index*/1, /*title*/"本田未央のウワサ①", /*comment*/"学食のおばちゃんと仲良しで、\n大盛りにしてもらえるらしい。");
INSERT INTO `tips` VALUES (/*id*/41, /*tips_type*/1, /*value*/235, /*index*/1, /*title*/"高森藍子のウワサ①", /*comment*/"散歩用の歩きやすくて可愛い靴を\n常に探しているらしい。");
INSERT INTO `tips` VALUES (/*id*/42, /*tips_type*/1, /*value*/237, /*index*/1, /*title*/"龍崎薫のウワサ①", /*comment*/"お母さんの作ったごはんが、\nいちばん好きらしい。");
INSERT INTO `tips` VALUES (/*id*/43, /*tips_type*/1, /*value*/238, /*index*/1, /*title*/"木村夏樹のウワサ①", /*comment*/"有名バンドのギターピックを\nお守り代わりにしているらしい。");
INSERT INTO `tips` VALUES (/*id*/44, /*tips_type*/1, /*value*/243, /*index*/1, /*title*/"赤城みりあのウワサ①", /*comment*/"家族に花や現場のお菓子などの\nお土産を毎日持って帰るらしい。");
INSERT INTO `tips` VALUES (/*id*/45, /*tips_type*/1, /*value*/246, /*index*/1, /*title*/"大槻唯のウワサ①", /*comment*/"初対面の人でも\nスキンシップから入るらしい。");
INSERT INTO `tips` VALUES (/*id*/46, /*tips_type*/1, /*value*/247, /*index*/1, /*title*/"姫川友紀のウワサ①", /*comment*/"球場で飲むビールが\n世界で一番おいしいものらしい。");
INSERT INTO `tips` VALUES (/*id*/47, /*tips_type*/1, /*value*/253, /*index*/1, /*title*/"及川雫のウワサ①", /*comment*/"利き牛乳ができるらしい。");
INSERT INTO `tips` VALUES (/*id*/48, /*tips_type*/1, /*value*/256, /*index*/1, /*title*/"星輝子のウワサ①", /*comment*/"晴れている日は\n日陰を選んで歩くらしい。");
INSERT INTO `tips` VALUES (/*id*/49, /*tips_type*/1, /*value*/257, /*index*/1, /*title*/"片桐早苗のウワサ①", /*comment*/"マイ警笛を持ち歩くのが、\n習慣になっているらしい。");
INSERT INTO `tips` VALUES (/*id*/50, /*tips_type*/1, /*value*/258, /*index*/1, /*title*/"堀裕子のウワサ①", /*comment*/"常に7つのサイキックアイテムを\n持ち歩いているらしい。");
INSERT INTO `tips` VALUES (/*id*/51, /*tips_type*/1, /*value*/267, /*index*/1, /*title*/"城ヶ崎美嘉のウワサ①", /*comment*/"ポーチはいつも最新のコスメで\nパンパンらしい。");
INSERT INTO `tips` VALUES (/*id*/52, /*tips_type*/1, /*value*/268, /*index*/1, /*title*/"城ヶ崎莉嘉のウワサ①", /*comment*/"クラスの男子とも女子とも\n混ざって遊ぶのが好きらしい。");
INSERT INTO `tips` VALUES (/*id*/53, /*tips_type*/1, /*value*/270, /*index*/1, /*title*/"日野茜のウワサ①", /*comment*/"一番得意な泳法は、\nバタフライらしい。");
INSERT INTO `tips` VALUES (/*id*/54, /*tips_type*/1, /*value*/271, /*index*/1, /*title*/"諸星きらりのウワサ①", /*comment*/"小物をデコる腕前は、\nプロダクションでもなかなか\nらしい。");
INSERT INTO `tips` VALUES (/*id*/55, /*tips_type*/1, /*value*/272, /*index*/1, /*title*/"十時愛梨のウワサ①", /*comment*/"大学のキャンパスでは\n常に、女友達が一緒らしい。");
INSERT INTO `tips` VALUES (/*id*/56, /*tips_type*/1, /*value*/273, /*index*/1, /*title*/"ナターリアのウワサ①", /*comment*/"父親は、サッカーチームの\n指導者をしているらしい。");
INSERT INTO `tips` VALUES (/*id*/57, /*tips_type*/1, /*value*/214, /*index*/1, /*title*/"白坂小梅のウワサ①", /*comment*/"ホラー映画用の棚の裏に…\nもうひとつ棚があるらしい…。");
INSERT INTO `tips` VALUES (/*id*/58, /*tips_type*/1, /*value*/126, /*index*/1, /*title*/"一ノ瀬志希のウワサ①", /*comment*/"独り暮らしをしているが\nたまに家に帰らないらしい。");
INSERT INTO `tips` VALUES (/*id*/59, /*tips_type*/1, /*value*/220, /*index*/1, /*title*/"塩見周子のウワサ①", /*comment*/"献血が好きなのは\n『スーッとするから』らしい。");
INSERT INTO `tips` VALUES (/*id*/60, /*tips_type*/1, /*value*/263, /*index*/1, /*title*/"相葉夕美のウワサ①", /*comment*/"オーガニックのカフェにいって\nまったりするのが好きらしい。");
INSERT INTO `tips` VALUES (/*id*/61, /*tips_type*/1, /*value*/159, /*index*/1, /*title*/"佐久間まゆのウワサ①", /*comment*/"真っ赤な日記帳に\nアイドルになってからの日々を\n綴っているらしい。");
INSERT INTO `tips` VALUES (/*id*/62, /*tips_type*/1, /*value*/292, /*index*/1, /*title*/"浜口あやめのウワサ①", /*comment*/"手づくりの煙玉で、たまに\nゲホゲホむせているらしい。");
INSERT INTO `tips` VALUES (/*id*/63, /*tips_type*/1, /*value*/194, /*index*/1, /*title*/"松永涼のウワサ①", /*comment*/"クラシックやジャズなどにも\n造詣が深いらしい。");
INSERT INTO `tips` VALUES (/*id*/64, /*tips_type*/1, /*value*/113, /*index*/1, /*title*/"五十嵐響子のウワサ①", /*comment*/"着る服の趣味が、ガラッと\n変わることがあるらしい。");
INSERT INTO `tips` VALUES (/*id*/65, /*tips_type*/1, /*value*/189, /*index*/1, /*title*/"鷺沢文香のウワサ①", /*comment*/"雨上がりだけは、いつも\n顔を上げて空をみるらしい。");
INSERT INTO `tips` VALUES (/*id*/66, /*tips_type*/1, /*value*/239, /*index*/1, /*title*/"松山久美子のウワサ①", /*comment*/"いろいろな国のアロマオイルを\n集めているらしい。");
INSERT INTO `tips` VALUES (/*id*/67, /*tips_type*/1, /*value*/133, /*index*/1, /*title*/"西園寺琴歌のウワサ①", /*comment*/"行きのロケバス内では\nやる気満々で眠れないが、\n帰りはぐっすりらしい。");
INSERT INTO `tips` VALUES (/*id*/68, /*tips_type*/1, /*value*/230, /*index*/1, /*title*/"二宮飛鳥のウワサ①", /*comment*/"自分の目で見ないかぎり、\nウワサは信じないらしい。");
INSERT INTO `tips` VALUES (/*id*/69, /*tips_type*/1, /*value*/158, /*index*/1, /*title*/"クラリスのウワサ①", /*comment*/"アイドルのギャラのほとんどは\n恵まれない人への募金などに\n費やすらしい。");
INSERT INTO `tips` VALUES (/*id*/70, /*tips_type*/1, /*value*/287, /*index*/1, /*title*/"メアリー・コクランのウワサ①", /*comment*/"プロフィールの数字を\n少し多く申告したらしい。");
INSERT INTO `tips` VALUES (/*id*/71, /*tips_type*/1, /*value*/221, /*index*/1, /*title*/"脇山珠美のウワサ①", /*comment*/"いつも持ち歩いている竹刀は\n『竹男』という名前らしい。");
INSERT INTO `tips` VALUES (/*id*/72, /*tips_type*/1, /*value*/118, /*index*/1, /*title*/"横山千佳のウワサ①", /*comment*/"日曜日の朝は、早起きらしい。");
INSERT INTO `tips` VALUES (/*id*/73, /*tips_type*/1, /*value*/168, /*index*/1, /*title*/"黒川千秋のウワサ①", /*comment*/"プライベートでは、ズボンを\nほとんどはかないらしい。");
INSERT INTO `tips` VALUES (/*id*/74, /*tips_type*/1, /*value*/242, /*index*/1, /*title*/"矢口美羽のウワサ①", /*comment*/"沈黙が苦手で\nつい喋ってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/75, /*tips_type*/1, /*value*/283, /*index*/1, /*title*/"市原仁奈のウワサ①", /*comment*/"着ぐるみを着ていると\nかわいがってもらえるのが\n嬉しいらしい。");
INSERT INTO `tips` VALUES (/*id*/76, /*tips_type*/1, /*value*/155, /*index*/1, /*title*/"工藤忍のウワサ①", /*comment*/"いつか、父と母と自分で、\n新しい家族写真を撮りたいと\n思っているらしい。");
INSERT INTO `tips` VALUES (/*id*/77, /*tips_type*/1, /*value*/280, /*index*/1, /*title*/"向井拓海のウワサ①", /*comment*/"コンサートライトを振られると\nつい、その方向に曲がりたく\nなってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/78, /*tips_type*/1, /*value*/161, /*index*/1, /*title*/"白菊ほたるのウワサ①", /*comment*/"折りたたみ傘を持っていると\nいつも快晴らしい。");
INSERT INTO `tips` VALUES (/*id*/79, /*tips_type*/1, /*value*/226, /*index*/1, /*title*/"森久保乃々のウワサ①", /*comment*/"絵本作家になる夢があり、\nそれを諦めていないらしい。");
INSERT INTO `tips` VALUES (/*id*/80, /*tips_type*/1, /*value*/284, /*index*/1, /*title*/"喜多日菜子のウワサ①", /*comment*/"座右の銘は\n夢とは起きて見るもの\nらしい。");
INSERT INTO `tips` VALUES (/*id*/81, /*tips_type*/1, /*value*/115, /*index*/1, /*title*/"櫻井桃華のウワサ①", /*comment*/"いい香りがするハンカチを\nいつも持っているらしい。");
INSERT INTO `tips` VALUES (/*id*/82, /*tips_type*/1, /*value*/181, /*index*/1, /*title*/"三船美優のウワサ①", /*comment*/"満員電車で、\nよく流されているらしい。");
INSERT INTO `tips` VALUES (/*id*/83, /*tips_type*/1, /*value*/249, /*index*/1, /*title*/"喜多見柚のウワサ①", /*comment*/"前髪とパーカーが\nオシャレのこだわりらしい。");
INSERT INTO `tips` VALUES (/*id*/84, /*tips_type*/1, /*value*/165, /*index*/1, /*title*/"原田美世のウワサ①", /*comment*/"仕事先には、\n可能な限り車で向かうらしい。");
INSERT INTO `tips` VALUES (/*id*/85, /*tips_type*/1, /*value*/139, /*index*/1, /*title*/"兵藤レナのウワサ①", /*comment*/"自分はイカサマしないが、\n誰かにイカサマされても\n1回は見逃すらしい。");
INSERT INTO `tips` VALUES (/*id*/86, /*tips_type*/1, /*value*/147, /*index*/1, /*title*/"井村雪菜のウワサ①", /*comment*/"お仕事の内容や\n会う人の好みに合わせて、\nメイクを変えているらしい。");
INSERT INTO `tips` VALUES (/*id*/87, /*tips_type*/1, /*value*/228, /*index*/1, /*title*/"大和亜季のウワサ①", /*comment*/"毎週金曜日は\nカレーを食べるらしい。");
INSERT INTO `tips` VALUES (/*id*/88, /*tips_type*/1, /*value*/190, /*index*/1, /*title*/"八神マキノのウワサ①", /*comment*/"10歳からの自分の行動を\nデジタルデータで\n残しているらしい。");
INSERT INTO `tips` VALUES (/*id*/89, /*tips_type*/1, /*value*/293, /*index*/1, /*title*/"村上巴のウワサ①", /*comment*/"将棋のネット対戦に\nハマっているらしい。");
INSERT INTO `tips` VALUES (/*id*/90, /*tips_type*/1, /*value*/162, /*index*/1, /*title*/"早坂美玲のウワサ①", /*comment*/"フードを脱いでいるときは\n気合いのスイッチが入っていない\nときらしい。");
INSERT INTO `tips` VALUES (/*id*/91, /*tips_type*/1, /*value*/106, /*index*/1, /*title*/"今井加奈のウワサ①", /*comment*/"寝る前にメモを見返すのが\n日課らしい。");
INSERT INTO `tips` VALUES (/*id*/92, /*tips_type*/1, /*value*/184, /*index*/1, /*title*/"藤原肇のウワサ①", /*comment*/"生地をこねるのも得意らしい。");
INSERT INTO `tips` VALUES (/*id*/93, /*tips_type*/1, /*value*/262, /*index*/1, /*title*/"依田芳乃のウワサ①", /*comment*/"話が長く、次第に説法のように\nなっていくのが癖らしい。");
INSERT INTO `tips` VALUES (/*id*/94, /*tips_type*/1, /*value*/291, /*index*/1, /*title*/"難波笑美のウワサ①", /*comment*/"とっておきのかくし芸は\n真顔でしゃべる標準語らしい。");
INSERT INTO `tips` VALUES (/*id*/95, /*tips_type*/1, /*value*/229, /*index*/1, /*title*/"結城晴のウワサ①", /*comment*/"足癖が悪いのを\nそのうち直す予定らしい。");
INSERT INTO `tips` VALUES (/*id*/96, /*tips_type*/1, /*value*/191, /*index*/1, /*title*/"ライラのウワサ①", /*comment*/"使用人だったメイドといっしょに\n日本へやってきたらしい。");
INSERT INTO `tips` VALUES (/*id*/97, /*tips_type*/1, /*value*/222, /*index*/1, /*title*/"岡崎泰葉のウワサ①", /*comment*/"手書きの字は\nとてもキレイらしい。");
INSERT INTO `tips` VALUES (/*id*/98, /*tips_type*/1, /*value*/254, /*index*/1, /*title*/"小関麗奈のウワサ①", /*comment*/"高台を見つけるたびに、\n立って、高笑いするらしい。");
INSERT INTO `tips` VALUES (/*id*/99, /*tips_type*/1, /*value*/121, /*index*/1, /*title*/"棟方愛海のウワサ①", /*comment*/"ものすごく寂しがり屋らしい。");
INSERT INTO `tips` VALUES (/*id*/100, /*tips_type*/1, /*value*/179, /*index*/1, /*title*/"水木聖來のウワサ①", /*comment*/"聖來の『來』の字を\n間違えられるのに慣れすぎて、\nたまに自分でも間違えるらしい。");
INSERT INTO `tips` VALUES (/*id*/101, /*tips_type*/1, /*value*/260, /*index*/1, /*title*/"的場梨沙のウワサ①", /*comment*/"本人いわく、梨沙のファンは、\nすべてロリコンらしい。");
INSERT INTO `tips` VALUES (/*id*/102, /*tips_type*/1, /*value*/219, /*index*/1, /*title*/"藤居朋のウワサ①", /*comment*/"たまにパワースポットで\n変なポーズをしているらしい。");
INSERT INTO `tips` VALUES (/*id*/103, /*tips_type*/1, /*value*/224, /*index*/1, /*title*/"大石泉のウワサ①", /*comment*/"泉にとって友情とは\n計算がいらないものらしい。");
INSERT INTO `tips` VALUES (/*id*/104, /*tips_type*/1, /*value*/289, /*index*/1, /*title*/"三好紗南のウワサ①", /*comment*/"じっとしていても、\n指や足が、自然に動くらしい。");
INSERT INTO `tips` VALUES (/*id*/105, /*tips_type*/1, /*value*/294, /*index*/1, /*title*/"土屋亜子のウワサ①", /*comment*/"亜子にとって友情とは、\nお金で買えないものらしい。");
INSERT INTO `tips` VALUES (/*id*/106, /*tips_type*/1, /*value*/160, /*index*/1, /*title*/"村松さくらのウワサ①", /*comment*/"さくらにとって友情とは、\nいつでもそこにあるものらしい。");
INSERT INTO `tips` VALUES (/*id*/107, /*tips_type*/1, /*value*/107, /*index*/1, /*title*/"持田亜里沙のウワサ①", /*comment*/"童謡以外の曲も\nそこそこ弾けるらしい。");
INSERT INTO `tips` VALUES (/*id*/108, /*tips_type*/1, /*value*/177, /*index*/1, /*title*/"東郷あいのウワサ①", /*comment*/"小さなバーのステージで\nたまにサックス演奏するらしい。");
INSERT INTO `tips` VALUES (/*id*/109, /*tips_type*/1, /*value*/295, /*index*/1, /*title*/"首藤葵のウワサ①", /*comment*/"いつか、事務所に\n社員食堂をつくりたいらしい。");
INSERT INTO `tips` VALUES (/*id*/110, /*tips_type*/1, /*value*/138, /*index*/1, /*title*/"月宮雅のウワサ①", /*comment*/"自分の夢は、\nママの夢をかなえてから\n考えるらしい。");
INSERT INTO `tips` VALUES (/*id*/111, /*tips_type*/1, /*value*/186, /*index*/1, /*title*/"水野翠のウワサ①", /*comment*/"行動する前に、つい\n溜めをつくるらしい。");
INSERT INTO `tips` VALUES (/*id*/112, /*tips_type*/1, /*value*/288, /*index*/1, /*title*/"小松伊吹のウワサ①", /*comment*/"恋愛映画を見ている時は\nずっと顔が真っ赤らしい。");
INSERT INTO `tips` VALUES (/*id*/113, /*tips_type*/1, /*value*/149, /*index*/1, /*title*/"榊原里美のウワサ①", /*comment*/"幼い頃は、兄と野原を\n駆け回っていたらしい。");
INSERT INTO `tips` VALUES (/*id*/114, /*tips_type*/1, /*value*/119, /*index*/1, /*title*/"関裕美のウワサ①", /*comment*/"いつも、手鏡を\n持ち歩いているらしい。");
INSERT INTO `tips` VALUES (/*id*/115, /*tips_type*/1, /*value*/218, /*index*/1, /*title*/"成宮由愛のウワサ①", /*comment*/"いろんな習い事をやったが、\n絵以外はどれも続かなかった\nらしい。");
INSERT INTO `tips` VALUES (/*id*/116, /*tips_type*/1, /*value*/250, /*index*/1, /*title*/"上田鈴帆のウワサ①", /*comment*/"指先の傷は努力の証らしい。");
INSERT INTO `tips` VALUES (/*id*/117, /*tips_type*/1, /*value*/213, /*index*/1, /*title*/"梅木音葉のウワサ①", /*comment*/"6種類の楽器が弾けるらしい。");
INSERT INTO `tips` VALUES (/*id*/118, /*tips_type*/1, /*value*/236, /*index*/1, /*title*/"並木芽衣子のウワサ①", /*comment*/"旅先では、すべての名所に\nかならず立ち寄るらしい。");
INSERT INTO `tips` VALUES (/*id*/119, /*tips_type*/1, /*value*/135, /*index*/1, /*title*/"楊菲菲のウワサ①", /*comment*/"おばあちゃんの顔を見に、\n二か月に一度は実家へ帰るらしい。");
INSERT INTO `tips` VALUES (/*id*/120, /*tips_type*/1, /*value*/211, /*index*/1, /*title*/"和久井留美のウワサ①", /*comment*/"ストレスが限界に達すると、\nバッティングセンターで\n三振して帰ってくるらしい。");
INSERT INTO `tips` VALUES (/*id*/121, /*tips_type*/1, /*value*/164, /*index*/1, /*title*/"乙倉悠貴のウワサ①", /*comment*/"ハイヒールの大人っぽさに\n憧れているらしい。");
INSERT INTO `tips` VALUES (/*id*/122, /*tips_type*/1, /*value*/216, /*index*/1, /*title*/"氏家むつみのウワサ①", /*comment*/"手頃な長さの紐を見つけると、\nムチのように扱いたくなるらしい。");
INSERT INTO `tips` VALUES (/*id*/123, /*tips_type*/1, /*value*/285, /*index*/1, /*title*/"杉坂海のウワサ①", /*comment*/"食べ物を人数分、均等に\n分けるのがうまいらしい。");
INSERT INTO `tips` VALUES (/*id*/124, /*tips_type*/1, /*value*/286, /*index*/1, /*title*/"北川真尋のウワサ①", /*comment*/"前髪が伸びると、\n自分で切ってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/125, /*tips_type*/1, /*value*/129, /*index*/1, /*title*/"松原早耶のウワサ①", /*comment*/"鏡の前に立つと、ポーズを\nとらなければいけない気に\nなるらしい。");
INSERT INTO `tips` VALUES (/*id*/126, /*tips_type*/1, /*value*/163, /*index*/1, /*title*/"有浦柑奈のウワサ①", /*comment*/"ラブ＆ピースを広めるための歌を\n作詞・作曲する予定らしい。");
INSERT INTO `tips` VALUES (/*id*/127, /*tips_type*/1, /*value*/171, /*index*/1, /*title*/"高橋礼子のウワサ①", /*comment*/"お酒を飲むと、\n真面目に将来のことを\n語りだすらしい。");
INSERT INTO `tips` VALUES (/*id*/128, /*tips_type*/1, /*value*/275, /*index*/1, /*title*/"槙原志保のウワサ①", /*comment*/"深夜のパフェは月に３回までと\n決めているが、昼間のパフェは\nノーカウントらしい。");
INSERT INTO `tips` VALUES (/*id*/129, /*tips_type*/1, /*value*/123, /*index*/1, /*title*/"大原みちるのウワサ①", /*comment*/"登校中は、パンをくわえながら\n走っているが、人をちゃんと\n避けてしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/130, /*tips_type*/1, /*value*/192, /*index*/1, /*title*/"浅利七海のウワサ①", /*comment*/"昔、海で溺れたときに、\n大きな魚のような何かに\n助けられたらしい。");
INSERT INTO `tips` VALUES (/*id*/131, /*tips_type*/1, /*value*/240, /*index*/1, /*title*/"斉藤洋子のウワサ①", /*comment*/"通販で健康器具を買っても、\n一回しか使わなかったものが\n数多くあるらしい。");
INSERT INTO `tips` VALUES (/*id*/132, /*tips_type*/1, /*value*/153, /*index*/1, /*title*/"大西由里子のウワサ①", /*comment*/"部屋の本棚に収まりきらない\n本の、新たな隠し場所を\n探し回っているらしい。");
INSERT INTO `tips` VALUES (/*id*/133, /*tips_type*/1, /*value*/210, /*index*/1, /*title*/"篠原礼のウワサ①", /*comment*/"ダンス中、\nボディタッチが少し多めらしい。");
INSERT INTO `tips` VALUES (/*id*/134, /*tips_type*/1, /*value*/183, /*index*/1, /*title*/"木場真奈美のウワサ①", /*comment*/"なにかを失敗した日は\n一駅分走るらしい。");
INSERT INTO `tips` VALUES (/*id*/135, /*tips_type*/1, /*value*/259, /*index*/1, /*title*/"西島櫂のウワサ①", /*comment*/"髪のセットをしたことが\nないらしい。");
INSERT INTO `tips` VALUES (/*id*/136, /*tips_type*/1, /*value*/156, /*index*/1, /*title*/"栗原ネネのウワサ①", /*comment*/"たくさん食べる人が\n好きらしい。");
INSERT INTO `tips` VALUES (/*id*/137, /*tips_type*/1, /*value*/120, /*index*/1, /*title*/"太田優のウワサ①", /*comment*/"アッキーとの出会いは\n涙なしでは語れないらしい。");
INSERT INTO `tips` VALUES (/*id*/138, /*tips_type*/1, /*value*/212, /*index*/1, /*title*/"吉岡沙紀のウワサ①", /*comment*/"自由人に見られることが多いが、\n本人はしっかりしている\nつもりらしい。");
INSERT INTO `tips` VALUES (/*id*/139, /*tips_type*/1, /*value*/244, /*index*/1, /*title*/"愛野渚のウワサ①", /*comment*/"髪をくくるための\nリボンを集めていることは\n誰にも言えないらしい。");
INSERT INTO `tips` VALUES (/*id*/140, /*tips_type*/1, /*value*/202, /*index*/1, /*title*/"ケイトのウワサ①", /*comment*/"立ち飲み居酒屋へ行き、\nたこわさをつまみに\n一杯やるらしい。");
INSERT INTO `tips` VALUES (/*id*/141, /*tips_type*/1, /*value*/255, /*index*/1, /*title*/"衛藤美紗希のウワサ①", /*comment*/"女子力を言葉で表すのは\n難しいので、身振り手振りで\n説明してしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/142, /*tips_type*/1, /*value*/298, /*index*/1, /*title*/"南条光のウワサ①", /*comment*/"跳ねすぎて、\nベッドのスプリングを\nよく壊してしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/143, /*tips_type*/1, /*value*/125, /*index*/1, /*title*/"大沼くるみのウワサ①", /*comment*/"頭をよくしたいので、\n大豆食品を食べるように\nしているらしい。");
INSERT INTO `tips` VALUES (/*id*/144, /*tips_type*/1, /*value*/187, /*index*/1, /*title*/"古澤頼子のウワサ①", /*comment*/"美術館をハシゴしたことが\nあるらしい。");
INSERT INTO `tips` VALUES (/*id*/145, /*tips_type*/1, /*value*/151, /*index*/1, /*title*/"安斎都のウワサ①", /*comment*/"直感は外れるらしい。");
INSERT INTO `tips` VALUES (/*id*/146, /*tips_type*/1, /*value*/170, /*index*/1, /*title*/"桐野アヤのウワサ①", /*comment*/"一人焼肉にも\n行けるらしい。");
INSERT INTO `tips` VALUES (/*id*/147, /*tips_type*/1, /*value*/274, /*index*/1, /*title*/"相馬夏美のウワサ①", /*comment*/"モテ期はこれから !\nらしい。");
INSERT INTO `tips` VALUES (/*id*/148, /*tips_type*/1, /*value*/297, /*index*/1, /*title*/"佐藤心のウワサ①", /*comment*/"チャンスをモノにできるよう、\n完璧なビールの注ぎ方を\nマスターしたらしい。");
INSERT INTO `tips` VALUES (/*id*/149, /*tips_type*/1, /*value*/145, /*index*/1, /*title*/"柳清良のウワサ①", /*comment*/"ピトッとするアレと\nチクッとするアレを\nバッグに忍ばせているらしい。");
INSERT INTO `tips` VALUES (/*id*/150, /*tips_type*/1, /*value*/231, /*index*/1, /*title*/"桐生つかさのウワサ①", /*comment*/"ウワサで判断されるとか\n勘弁だし、アポとってくんない？\nらしい。");
INSERT INTO `tips` VALUES (/*id*/151, /*tips_type*/1, /*value*/124, /*index*/1, /*title*/"遊佐こずえのウワサ①", /*comment*/"みんなのはなしを\nきいているだけで\nしあわせなきもちになるらしい。");
INSERT INTO `tips` VALUES (/*id*/152, /*tips_type*/1, /*value*/157, /*index*/1, /*title*/"古賀小春のウワサ①", /*comment*/"虫は苦手じゃない\nらしい。");
INSERT INTO `tips` VALUES (/*id*/153, /*tips_type*/1, /*value*/225, /*index*/1, /*title*/"松尾千鶴のウワサ①", /*comment*/"それなりにうまくやっている\nつもりらしい。");
INSERT INTO `tips` VALUES (/*id*/154, /*tips_type*/1, /*value*/241, /*index*/1, /*title*/"沢田麻理菜のウワサ①", /*comment*/"一年中サマーソングを\n聴いているらしい。");
INSERT INTO `tips` VALUES (/*id*/155, /*tips_type*/1, /*value*/203, /*index*/1, /*title*/"瀬名詩織のウワサ①", /*comment*/"悩んだときに、\n海を散歩していると、\n海風が背中を押してくれるらしい。");
INSERT INTO `tips` VALUES (/*id*/156, /*tips_type*/1, /*value*/182, /*index*/1, /*title*/"服部瞳子のウワサ①", /*comment*/"一人の夜には\n熱帯魚から\n勇気をもらっているらしい。");
INSERT INTO `tips` VALUES (/*id*/157, /*tips_type*/1, /*value*/264, /*index*/1, /*title*/"野々村そらのウワサ①", /*comment*/"「はっぴー来い来い\nすまいるげーと」らしい。");
INSERT INTO `tips` VALUES (/*id*/158, /*tips_type*/1, /*value*/137, /*index*/1, /*title*/"涼宮星花のウワサ①", /*comment*/"ウィーンに留学中、\n毎晩電話をかけたせいで電話代が\n大変なことになったらしい。");
INSERT INTO `tips` VALUES (/*id*/159, /*tips_type*/1, /*value*/261, /*index*/1, /*title*/"財前時子のウワサ①", /*comment*/"大学はお嬢様学校で、\n心理学を専攻しているらしい。");
INSERT INTO `tips` VALUES (/*id*/160, /*tips_type*/1, /*value*/117, /*index*/1, /*title*/"長富蓮実のウワサ①", /*comment*/"白いバルコニーのある家を\n買うのが夢らしい。");
INSERT INTO `tips` VALUES (/*id*/161, /*tips_type*/1, /*value*/215, /*index*/1, /*title*/"岸部彩華のウワサ①", /*comment*/"パパにもらったおこづかいは\nおこづかい帳につけて\nママに渡しているらしい。");
INSERT INTO `tips` VALUES (/*id*/162, /*tips_type*/1, /*value*/265, /*index*/1, /*title*/"浜川愛結奈のウワサ①", /*comment*/"鏡の前で支度をしていると、\nいつの間にかポージング練習に\nなってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/163, /*tips_type*/1, /*value*/196, /*index*/1, /*title*/"高峯のあのウワサ①", /*comment*/"日焼け止めが\n手離せないらしい。");
INSERT INTO `tips` VALUES (/*id*/164, /*tips_type*/1, /*value*/152, /*index*/1, /*title*/"浅野風香のウワサ①", /*comment*/"人の悩みで、\n自分も悩んでしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/165, /*tips_type*/1, /*value*/114, /*index*/1, /*title*/"柳瀬美由紀のウワサ①", /*comment*/"親の経営する水産工場の\nベテラン社員よりも\nカニ剥きの速度が速かったらしい。");
INSERT INTO `tips` VALUES (/*id*/166, /*tips_type*/1, /*value*/251, /*index*/1, /*title*/"海老原菜帆のウワサ①", /*comment*/"友だちによく\n抱きつかれるらしい。");
INSERT INTO `tips` VALUES (/*id*/167, /*tips_type*/1, /*value*/217, /*index*/1, /*title*/"西川保奈美のウワサ①", /*comment*/"気分がいいと、\n鼻歌がどんどん\n大きくなってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/168, /*tips_type*/1, /*value*/148, /*index*/1, /*title*/"日下部若葉のウワサ①", /*comment*/"髪を伸ばしているのは、\n大人っぽく見られたいかららしい。");
INSERT INTO `tips` VALUES (/*id*/169, /*tips_type*/1, /*value*/200, /*index*/1, /*title*/"柊志乃のウワサ①", /*comment*/"資源ごみ回収の日だけは\n早起きできることがあるらしい。");
INSERT INTO `tips` VALUES (/*id*/170, /*tips_type*/1, /*value*/300, /*index*/1, /*title*/"イヴ・サンタクロースのウワサ①", /*comment*/"サンタらしい。");
INSERT INTO `tips` VALUES (/*id*/171, /*tips_type*/1, /*value*/290, /*index*/1, /*title*/"キャシー・グラハムのウワサ①", /*comment*/"外国人に声をかけられたときは、\nジェスチャーで切り抜けるらしい。");
INSERT INTO `tips` VALUES (/*id*/172, /*tips_type*/1, /*value*/199, /*index*/1, /*title*/"伊集院惠のウワサ①", /*comment*/"二ヶ月に一度は\n旅に出るらしい。");
INSERT INTO `tips` VALUES (/*id*/173, /*tips_type*/1, /*value*/195, /*index*/1, /*title*/"小室千奈美のウワサ①", /*comment*/"強気は本気の証らしい。");
INSERT INTO `tips` VALUES (/*id*/174, /*tips_type*/1, /*value*/130, /*index*/1, /*title*/"相原雪乃のウワサ①", /*comment*/"高校生のとき、紅茶の道を\n極められると思い、茶道部に\n入部し、そのまま卒業したらしい。");
INSERT INTO `tips` VALUES (/*id*/175, /*tips_type*/1, /*value*/116, /*index*/1, /*title*/"江上椿のウワサ①", /*comment*/"写真を整理しようとしても、\n見入ってしまって、\nまったく捗らないらしい。");
INSERT INTO `tips` VALUES (/*id*/176, /*tips_type*/1, /*value*/233, /*index*/1, /*title*/"鷹富士茄子のウワサ①", /*comment*/"生きていることが\n何よりの幸運らしい。");
INSERT INTO `tips` VALUES (/*id*/177, /*tips_type*/1, /*value*/245, /*index*/1, /*title*/"真鍋いつきのウワサ①", /*comment*/"大学時代には\nスポーツ教育を\n専攻していたらしい。");
INSERT INTO `tips` VALUES (/*id*/178, /*tips_type*/1, /*value*/232, /*index*/1, /*title*/"望月聖のウワサ①", /*comment*/"歌は好きだが、\n楽譜は読めないらしい。");
INSERT INTO `tips` VALUES (/*id*/179, /*tips_type*/1, /*value*/166, /*index*/1, /*title*/"池袋晶葉のウワサ①", /*comment*/"初めての友達は\nもらったロボだったらしい。");
INSERT INTO `tips` VALUES (/*id*/180, /*tips_type*/1, /*value*/110, /*index*/1, /*title*/"間中美里のウワサ①", /*comment*/"経験上、\n迷ったら、現地の人に\n聞くのが一番らしい。");
INSERT INTO `tips` VALUES (/*id*/181, /*tips_type*/1, /*value*/128, /*index*/1, /*title*/"赤西瑛梨華のウワサ①", /*comment*/"靴を選ぶときに\n一番大切なポイントは、\n滑らないことらしい。");
INSERT INTO `tips` VALUES (/*id*/182, /*tips_type*/1, /*value*/140, /*index*/1, /*title*/"丹羽仁美のウワサ①", /*comment*/"日本史は\n得意科目ではないらしい。");
INSERT INTO `tips` VALUES (/*id*/183, /*tips_type*/1, /*value*/193, /*index*/1, /*title*/"ヘレンのウワサ①", /*comment*/"世界レベルらしい。");
INSERT INTO `tips` VALUES (/*id*/184, /*tips_type*/1, /*value*/296, /*index*/1, /*title*/"冴島清美のウワサ①", /*comment*/"何事もまずは形から\n入ってみるタイプらしい。");
INSERT INTO `tips` VALUES (/*id*/185, /*tips_type*/1, /*value*/104, /*index*/2, /*title*/"福山舞のウワサ②", /*comment*/"日直が回ってくると\nワクワクするらしい。");
INSERT INTO `tips` VALUES (/*id*/186, /*tips_type*/1, /*value*/239, /*index*/2, /*title*/"松山久美子のウワサ②", /*comment*/"月に一度、誰にも会わず、\nすっぴんで過ごすらしい。");
INSERT INTO `tips` VALUES (/*id*/187, /*tips_type*/1, /*value*/230, /*index*/2, /*title*/"二宮飛鳥のウワサ②", /*comment*/"授業中、退屈そうにしているが、\nノートはキッチリ\nとってあるらしい。");
INSERT INTO `tips` VALUES (/*id*/188, /*tips_type*/1, /*value*/116, /*index*/2, /*title*/"江上椿のウワサ②", /*comment*/"人が自撮りをしていると、\n自前の一眼レフで\n撮ってあげるらしい。");
INSERT INTO `tips` VALUES (/*id*/189, /*tips_type*/1, /*value*/131, /*index*/2, /*title*/"宮本フレデリカのウワサ②", /*comment*/"目が合うと、\nいつも笑顔が返ってくるらしい。");
INSERT INTO `tips` VALUES (/*id*/190, /*tips_type*/1, /*value*/130, /*index*/2, /*title*/"相原雪乃のウワサ②", /*comment*/"ばあやにお願いされて、\n髪を伸ばしているらしい。");
INSERT INTO `tips` VALUES (/*id*/191, /*tips_type*/1, /*value*/127, /*index*/2, /*title*/"前川みくのウワサ②", /*comment*/"猫の毛を取るためのブラシを\n持ち歩いているらしい。");
INSERT INTO `tips` VALUES (/*id*/192, /*tips_type*/1, /*value*/181, /*index*/2, /*title*/"三船美優のウワサ②", /*comment*/"OL時代の服や靴を、\nいまだに捨てられていないらしい。");
INSERT INTO `tips` VALUES (/*id*/193, /*tips_type*/1, /*value*/168, /*index*/2, /*title*/"黒川千秋のウワサ②", /*comment*/"歩いていて抜かされると、\n抜かし返すらしい。");
INSERT INTO `tips` VALUES (/*id*/194, /*tips_type*/1, /*value*/163, /*index*/2, /*title*/"有浦柑奈のウワサ②", /*comment*/"切ないバラードも弾き語りを\nしていると、いつの間にか\n陽気になってしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/195, /*tips_type*/1, /*value*/257, /*index*/2, /*title*/"片桐早苗のウワサ②", /*comment*/"栄養ドリンクに頼るのは、\n負けた感じがするらしい。");
INSERT INTO `tips` VALUES (/*id*/196, /*tips_type*/1, /*value*/155, /*index*/2, /*title*/"工藤忍のウワサ②", /*comment*/"目標を書いた紙を壁に貼って\nいったら、壁が埋まって\n困ったらしい。");
INSERT INTO `tips` VALUES (/*id*/197, /*tips_type*/1, /*value*/114, /*index*/2, /*title*/"柳瀬美由紀のウワサ②", /*comment*/"両親に電話をすると\n長電話になるので、\n手紙を送っているらしい。");
INSERT INTO `tips` VALUES (/*id*/198, /*tips_type*/1, /*value*/117, /*index*/2, /*title*/"長富蓮実のウワサ②", /*comment*/"CDを出すときには、同時に\nレコードも出したいらしい。");
INSERT INTO `tips` VALUES (/*id*/199, /*tips_type*/1, /*value*/153, /*index*/2, /*title*/"大西由里子のウワサ②", /*comment*/"沼は怖いらしい。");
INSERT INTO `tips` VALUES (/*id*/200, /*tips_type*/1, /*value*/225, /*index*/2, /*title*/"松尾千鶴のウワサ②", /*comment*/"色紙にサインを\n書くのが楽しくて、\n書きすぎてしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/201, /*tips_type*/1, /*value*/196, /*index*/2, /*title*/"高峯のあのウワサ②", /*comment*/"食べ物の好き嫌いはない…\nということに\nなっているらしい。");
INSERT INTO `tips` VALUES (/*id*/202, /*tips_type*/1, /*value*/160, /*index*/2, /*title*/"村松さくらのウワサ②", /*comment*/"友達いわく、\n頭がまんまるで、\nなで心地最高らしい。");
INSERT INTO `tips` VALUES (/*id*/203, /*tips_type*/1, /*value*/125, /*index*/2, /*title*/"大沼くるみのウワサ②", /*comment*/"最近、涙がこぼれるまでの\n時間が少し長くなったらしい。");
INSERT INTO `tips` VALUES (/*id*/204, /*tips_type*/1, /*value*/193, /*index*/2, /*title*/"ヘレンのウワサ②", /*comment*/"店員を呼び止めるのが得意らしい。");
INSERT INTO `tips` VALUES (/*id*/205, /*tips_type*/1, /*value*/211, /*index*/2, /*title*/"和久井留美のウワサ②", /*comment*/"よく聴く曲が懐メロ扱いされて\nショックだったらしい。");
INSERT INTO `tips` VALUES (/*id*/206, /*tips_type*/1, /*value*/115, /*index*/2, /*title*/"櫻井桃華のウワサ②", /*comment*/"ひとりで駄菓子屋に\n入れるようになりたいらしい。");
INSERT INTO `tips` VALUES (/*id*/207, /*tips_type*/1, /*value*/170, /*index*/2, /*title*/"桐野アヤのウワサ②", /*comment*/"撮影で使ったアクセサリーを、\nこっそり買い取っているらしい。");
INSERT INTO `tips` VALUES (/*id*/208, /*tips_type*/1, /*value*/176, /*index*/2, /*title*/"荒木比奈のウワサ②", /*comment*/"ペンネームと原稿は、\n墓まで持っていくらしい。");
INSERT INTO `tips` VALUES (/*id*/209, /*tips_type*/1, /*value*/175, /*index*/2, /*title*/"上条春菜のウワサ②", /*comment*/"熱い汁物が苦手らしい。");
INSERT INTO `tips` VALUES (/*id*/210, /*tips_type*/1, /*value*/123, /*index*/2, /*title*/"大原みちるのウワサ②", /*comment*/"実家では、パン以外のおやつを\n食べたことがないらしい。");
INSERT INTO `tips` VALUES (/*id*/211, /*tips_type*/1, /*value*/243, /*index*/2, /*title*/"赤城みりあのウワサ②", /*comment*/"跳び箱が8段まで跳べたらしい。");
INSERT INTO `tips` VALUES (/*id*/212, /*tips_type*/1, /*value*/263, /*index*/2, /*title*/"相葉夕美のウワサ②", /*comment*/"野菜を育てたこともあるが\n実より花を優先してしまい\nうまく育たなかったらしい。");
INSERT INTO `tips` VALUES (/*id*/213, /*tips_type*/1, /*value*/101, /*index*/2, /*title*/"島村卯月のウワサ②", /*comment*/"自分をほめられるのは\nシューズに穴が空いたとき\nらしい。");
INSERT INTO `tips` VALUES (/*id*/214, /*tips_type*/1, /*value*/275, /*index*/2, /*title*/"槙原志保のウワサ②", /*comment*/"飲食店のアンケート用紙は\n必ず書くようにしているらしい。");
INSERT INTO `tips` VALUES (/*id*/215, /*tips_type*/1, /*value*/294, /*index*/2, /*title*/"土屋亜子のウワサ②", /*comment*/"友達いわく、\n力強いハグが最高に\n元気づけられるらしい。");
INSERT INTO `tips` VALUES (/*id*/216, /*tips_type*/1, /*value*/148, /*index*/2, /*title*/"日下部若葉のウワサ②", /*comment*/"七夕の短冊には毎年\n『大きくなれますように』\nと書いているらしい。");
INSERT INTO `tips` VALUES (/*id*/217, /*tips_type*/1, /*value*/241, /*index*/2, /*title*/"沢田麻理菜のウワサ②", /*comment*/"どんなバイト先に行っても\n初日から先輩扱いされてしまうらしい。");
INSERT INTO `tips` VALUES (/*id*/218, /*tips_type*/1, /*value*/246, /*index*/2, /*title*/"大槻唯のウワサ②", /*comment*/"人からもらったプレゼントは\nすべてとってあるらしい。");
INSERT INTO `tips` VALUES (/*id*/219, /*tips_type*/1, /*value*/212, /*index*/2, /*title*/"吉岡沙紀のウワサ②", /*comment*/"言葉より、アートの方が\n思いは伝わるものらしい。");
INSERT INTO `tips` VALUES (/*id*/220, /*tips_type*/1, /*value*/145, /*index*/2, /*title*/"柳清良のウワサ②", /*comment*/"緊張している人を\nリラックスさせるのが得意らしい。");
INSERT INTO `tips` VALUES (/*id*/221, /*tips_type*/1, /*value*/154, /*index*/2, /*title*/"安部菜々のウワサ②", /*comment*/"徹夜は苦手だが、早起きは得意らしい。");
INSERT INTO `tips` VALUES (/*id*/222, /*tips_type*/1, /*value*/187, /*index*/2, /*title*/"古澤頼子のウワサ②", /*comment*/"名画を家に飾るのが夢だが\nいまはポストカードを飾って\n我慢しているらしい。");
INSERT INTO `tips` VALUES (/*id*/223, /*tips_type*/1, /*value*/191, /*index*/2, /*title*/"ライラのウワサ②", /*comment*/"ロケ弁が余ったときは\n持って帰るようにスタッフから\n押しつけられるらしい。");
INSERT INTO `tips` VALUES (/*id*/224, /*tips_type*/1, /*value*/253, /*index*/2, /*title*/"及川雫のウワサ②", /*comment*/"おいかわ牧場も\n順調に成長中らしい。");
INSERT INTO `tips` VALUES (/*id*/225, /*tips_type*/1, /*value*/140, /*index*/2, /*title*/"丹羽仁美のウワサ②", /*comment*/"タイムスリップするのが\n夢らしい。");
INSERT INTO `tips` VALUES (/*id*/226, /*tips_type*/1, /*value*/180, /*index*/2, /*title*/"佐々木千枝のウワサ②", /*comment*/"家族や友達の誕生日には\n手作りの贈り物をするらしい。");
INSERT INTO `tips` VALUES (/*id*/227, /*tips_type*/1, /*value*/195, /*index*/2, /*title*/"小室千奈美のウワサ②", /*comment*/"10代だといっても\n信じてもらえないらしい。");
INSERT INTO `tips` VALUES (/*id*/228, /*tips_type*/1, /*value*/166, /*index*/2, /*title*/"池袋晶葉のウワサ②", /*comment*/"時計やリモコンを\n分解する遊びが好きだが\n元に戻せないらしい。");
INSERT INTO `tips` VALUES (/*id*/229, /*tips_type*/1, /*value*/112, /*index*/2, /*title*/"緒方智絵里のウワサ②", /*comment*/"ファンレターをもらったときに\nぺこぺこする姿が\n小動物のようで可愛いらしい。");
INSERT INTO `tips` VALUES (/*id*/230, /*tips_type*/1, /*value*/197, /*index*/2, /*title*/"高垣楓のウワサ②", /*comment*/"どうしようもない人扱い\nされると嬉しくなるらしい。");
INSERT INTO `tips` VALUES (/*id*/231, /*tips_type*/1, /*value*/213, /*index*/2, /*title*/"梅木音葉のウワサ②", /*comment*/"行きつけの森で歌っていたら、\n子どもに妖精と間違われたらしい。");
INSERT INTO `tips` VALUES (/*id*/232, /*tips_type*/1, /*value*/269, /*index*/2, /*title*/"仙崎恵磨のウワサ②", /*comment*/"カラオケで人が歌っているときは\nたいてい踊っているらしい。");
INSERT INTO `tips` VALUES (/*id*/233, /*tips_type*/1, /*value*/219, /*index*/2, /*title*/"藤居朋のウワサ②", /*comment*/"占いのラッキーカラーの\nアイテムを揃えていったら、\n部屋の中が七色になったらしい。");
INSERT INTO `tips` VALUES (/*id*/234, /*tips_type*/1, /*value*/262, /*index*/2, /*title*/"依田芳乃のウワサ②", /*comment*/"お年寄りのファンに会うと\n拝まれるらしい。");
INSERT INTO `tips` VALUES (/*id*/235, /*tips_type*/1, /*value*/128, /*index*/2, /*title*/"赤西瑛梨華のウワサ②", /*comment*/"通っている女子高の文化祭で\n一発ギャグを披露したら\n一発で人気者になったらしい。");
INSERT INTO `tips` VALUES (/*id*/236, /*tips_type*/1, /*value*/216, /*index*/2, /*title*/"氏家むつみのウワサ②", /*comment*/"食べ物で冒険するのは\nおすすめできないらしい。");
INSERT INTO `tips` VALUES (/*id*/237, /*tips_type*/1, /*value*/222, /*index*/2, /*title*/"岡崎泰葉のウワサ②", /*comment*/"人前で読むのは古典文学だが、\n子供向けの絵本を集めている\nらしい。");
INSERT INTO `tips` VALUES (/*id*/238, /*tips_type*/1, /*value*/237, /*index*/2, /*title*/"龍崎薫のウワサ②", /*comment*/"共演者全員と友達になるのが\nいつもの目標らしい。");
INSERT INTO `tips` VALUES (/*id*/239, /*tips_type*/1, /*value*/285, /*index*/2, /*title*/"杉坂海のウワサ②", /*comment*/"アネキと呼ばれるのはOKだが\nアネゴと呼ばれるのはNGらしい。");
INSERT INTO `tips` VALUES (/*id*/240, /*tips_type*/1, /*value*/274, /*index*/2, /*title*/"相馬夏美のウワサ②", /*comment*/"20kgくらい軽く落とせるわ\nが持論らしい。");
INSERT INTO `tips` VALUES (/*id*/241, /*tips_type*/1, /*value*/235, /*index*/2, /*title*/"高森藍子のウワサ②", /*comment*/"変装せず散歩しているとき、\n声をかけないのがファンの間でのマナーらしい。");
INSERT INTO `tips` VALUES (/*id*/242, /*tips_type*/1, /*value*/185, /*index*/2, /*title*/"新田美波のウワサ②", /*comment*/"20歳になったら飲みましょう\nという約束が数え切れないほどあるらしい。");
INSERT INTO `tips` VALUES (/*id*/243, /*tips_type*/1, /*value*/188, /*index*/2, /*title*/"橘ありすのウワサ②", /*comment*/"インターネット上での議論は\n建設的ではないため\nやらない主義らしい。");
INSERT INTO `tips` VALUES (/*id*/244, /*tips_type*/1, /*value*/244, /*index*/2, /*title*/"愛野渚のウワサ②", /*comment*/"サイン会によく\nバスケットボールを\n持ってこられるらしい。");
INSERT INTO `tips` VALUES (/*id*/245, /*tips_type*/1, /*value*/270, /*index*/2, /*title*/"日野茜のウワサ②", /*comment*/"お風呂は42℃で\n長湯はしないらしい。");
INSERT INTO `tips` VALUES (/*id*/246, /*tips_type*/1, /*value*/280, /*index*/2, /*title*/"向井拓海のウワサ②", /*comment*/"教室が退屈で落ち着かなかったが\n最近は別の理由で\nやっぱり落ち着かないらしい。");
INSERT INTO `tips` VALUES (/*id*/247, /*tips_type*/1, /*value*/167, /*index*/2, /*title*/"渋谷凛のウワサ②", /*comment*/"カラオケでも全力で歌うが\n自分の曲は歌わないらしい。");
INSERT INTO `tips` VALUES (/*id*/248, /*tips_type*/1, /*value*/113, /*index*/2, /*title*/"五十嵐響子のウワサ②", /*comment*/"寮のキッチンで料理をしていると\nいつの間にかみんな\n集まってくるらしい。");
INSERT INTO `tips` VALUES (/*id*/249, /*tips_type*/1, /*value*/202, /*index*/2, /*title*/"ケイトのウワサ②", /*comment*/"時々、漢字で「毛糸」と\nサインするらしい。");
INSERT INTO `tips` VALUES (/*id*/250, /*tips_type*/1, /*value*/295, /*index*/2, /*title*/"首藤葵のウワサ②", /*comment*/"前髪が垂れると\nソワソワするらしい。");
INSERT INTO `tips` VALUES (/*id*/251, /*tips_type*/1, /*value*/226, /*index*/2, /*title*/"森久保乃々のウワサ②", /*comment*/"乃々はノーノー…らしい。");
INSERT INTO `tips` VALUES (/*id*/252, /*tips_type*/1, /*value*/238, /*index*/2, /*title*/"木村夏樹のウワサ②", /*comment*/"他のアイドルの曲を、たまに\nギターアレンジしているらしい。");
INSERT INTO `tips` VALUES (/*id*/253, /*tips_type*/1, /*value*/107, /*index*/2, /*title*/"持田亜里沙のウワサ②", /*comment*/"握手会では、ウサコちゃんとも\n握手できるらしい。");
INSERT INTO `tips` VALUES (/*id*/254, /*tips_type*/1, /*value*/158, /*index*/2, /*title*/"クラリスのウワサ②", /*comment*/"怒らせると神罰が下るらしい。");
INSERT INTO `tips` VALUES (/*id*/255, /*tips_type*/1, /*value*/147, /*index*/2, /*title*/"井村雪菜のウワサ②", /*comment*/"知人と会わない日は\nメイクの実験日らしい。");
INSERT INTO `tips` VALUES (/*id*/256, /*tips_type*/1, /*value*/149, /*index*/2, /*title*/"榊原里美のウワサ②", /*comment*/"利きハチミツができるらしい。");
INSERT INTO `tips` VALUES (/*id*/257, /*tips_type*/1, /*value*/266, /*index*/2, /*title*/"若林智香のウワサ②", /*comment*/"レッスンの休憩時間中、\n他のアイドルを\n応援しているらしい。");
INSERT INTO `tips` VALUES (/*id*/258, /*tips_type*/1, /*value*/169, /*index*/2, /*title*/"松本沙理奈のウワサ②", /*comment*/"毎朝の豆乳は欠かさないらしい。");
INSERT INTO `tips` VALUES (/*id*/259, /*tips_type*/1, /*value*/271, /*index*/2, /*title*/"諸星きらりのウワサ②", /*comment*/"少女漫画を読むときは\n1ページごとに大騒ぎらしい。");
INSERT INTO `tips` VALUES (/*id*/260, /*tips_type*/1, /*value*/134, /*index*/2, /*title*/"双葉杏のウワサ②", /*comment*/"「うさぎ」は誰かが\n定期的に洗っているが\n杏は気づいていないらしい。");
INSERT INTO `tips` VALUES (/*id*/261, /*tips_type*/1, /*value*/156, /*index*/2, /*title*/"栗原ネネのウワサ②", /*comment*/"毎日、必要な栄養を\n必ず摂っているらしい。");
INSERT INTO `tips` VALUES (/*id*/262, /*tips_type*/1, /*value*/247, /*index*/2, /*title*/"姫川友紀のウワサ②", /*comment*/"野球選手のモノマネが\n細かすぎると評判らしい。");
INSERT INTO `tips` VALUES (/*id*/263, /*tips_type*/1, /*value*/174, /*index*/2, /*title*/"神谷奈緒のウワサ②", /*comment*/"翌朝の天気が\n髪の毛でわかるらしい。");
INSERT INTO `tips` VALUES (/*id*/264, /*tips_type*/1, /*value*/221, /*index*/2, /*title*/"脇山珠美のウワサ②", /*comment*/"事務所にはMY脚立を\n持ち込んでいるらしい。");
INSERT INTO `tips` VALUES (/*id*/265, /*tips_type*/1, /*value*/199, /*index*/2, /*title*/"伊集院惠のウワサ②", /*comment*/"一度行った国はなるべく行かず、\nいつでも次の国を\n探しているらしい。");
INSERT INTO `tips` VALUES (/*id*/266, /*tips_type*/1, /*value*/296, /*index*/2, /*title*/"冴島清美のウワサ②", /*comment*/"整理整頓は趣味であって、\n習慣ではないらしい。");
INSERT INTO `tips` VALUES (/*id*/267, /*tips_type*/1, /*value*/205, /*index*/2, /*title*/"佐城雪美のウワサ②", /*comment*/"ゲームは得意ではないが、\n人がプレイしているのを\n見るのは好きらしい。");
INSERT INTO `tips` VALUES (/*id*/268, /*tips_type*/1, /*value*/139, /*index*/2, /*title*/"兵藤レナのウワサ②", /*comment*/"トランプを投げて、\n物を斬れるらしい。");
INSERT INTO `tips` VALUES (/*id*/269, /*tips_type*/1, /*value*/192, /*index*/2, /*title*/"浅利七海のウワサ②", /*comment*/"七海の夏休みの自由研究は、\n毎年、理科の先生の\nひそかな楽しみだったらしい。");
INSERT INTO `tips` VALUES (/*id*/270, /*tips_type*/1, /*value*/105, /*index*/2, /*title*/"椎名法子のウワサ②", /*comment*/"ドーナツのデコレーションが、\nファッションのお手本らしい。");
INSERT INTO `tips` VALUES (/*id*/271, /*tips_type*/1, /*value*/182, /*index*/2, /*title*/"服部瞳子のウワサ②", /*comment*/"将来の夢を書いた\n小学校の卒業アルバムを、\n捨てられずに持っているらしい。");
INSERT INTO `tips` VALUES (/*id*/272, /*tips_type*/1, /*value*/122, /*index*/2, /*title*/"藤本里奈のウワサ②", /*comment*/"アイドルになってから、\n200円台のカップ麺やスイーツを\n買うようになり、ヤバいらしい。");
INSERT INTO `tips` VALUES (/*id*/273, /*tips_type*/1, /*value*/132, /*index*/2, /*title*/"小早川紗枝のウワサ②", /*comment*/"持っている洋服には\nどれも思い出があるらしい。");
INSERT INTO `tips` VALUES (/*id*/274, /*tips_type*/1, /*value*/217, /*index*/2, /*title*/"西川保奈美のウワサ②", /*comment*/"舞台を観た日は、\n憧れのスターについて、\n学友と夜まで語り合うらしい。");
INSERT INTO `tips` VALUES (/*id*/275, /*tips_type*/1, /*value*/138, /*index*/2, /*title*/"月宮雅のウワサ②", /*comment*/"パパは、ママ好きの\n良きライバルらしい。");
INSERT INTO `tips` VALUES (/*id*/276, /*tips_type*/1, /*value*/218, /*index*/2, /*title*/"成宮由愛のウワサ②", /*comment*/"プロデューサーの似顔絵は\nこっそり練習しているらしい。");
INSERT INTO `tips` VALUES (/*id*/277, /*tips_type*/1, /*value*/110, /*index*/2, /*title*/"間中美里のウワサ②", /*comment*/"付箋だらけの旅行誌で\n本棚がいっぱいらしい。");
INSERT INTO `tips` VALUES (/*id*/278, /*tips_type*/1, /*value*/172, /*index*/2, /*title*/"相川千夏のウワサ②", /*comment*/"パーソナルスペースは\n広いつもりらしい。");
INSERT INTO `tips` VALUES (/*id*/279, /*tips_type*/1, /*value*/224, /*index*/2, /*title*/"大石泉のウワサ②", /*comment*/"友だちいわく、\n意外とスキンシップは\n嫌いじゃないらしい。");
INSERT INTO `tips` VALUES (/*id*/280, /*tips_type*/1, /*value*/215, /*index*/2, /*title*/"岸部彩華のウワサ②", /*comment*/"パパへのおねだりテクは\nママ仕込みらしい。");
INSERT INTO `tips` VALUES (/*id*/20001, /*tips_type*/2, /*value*/1, /*index*/1, /*title*/"スタミナドリンク", /*comment*/"スタミナドリンクを使うと、スタミナを回復できます !");
INSERT INTO `tips` VALUES (/*id*/20002, /*tips_type*/2, /*value*/1001, /*index*/1, /*title*/"思い出の鍵", /*comment*/"見逃してしまったイベントコミュ\nや、イベントの予告コミュを\n解放できます !");
INSERT INTO `tips` VALUES (/*id*/20003, /*tips_type*/2, /*value*/9001, /*index*/1, /*title*/"特訓アイテム", /*comment*/"アイドルの特訓や、\nポテンシャルの解放に必要なアイテムです !");
INSERT INTO `tips` VALUES (/*id*/20004, /*tips_type*/2, /*value*/9002, /*index*/1, /*title*/"ギフトアイテム", /*comment*/"ルームでアイドルに渡すと、\n親愛度を上げることができます !");
INSERT INTO `tips` VALUES (/*id*/20005, /*tips_type*/2, /*value*/9003, /*index*/1, /*title*/"トレーナーチケット", /*comment*/"レッスンで、アイドルのExpを\n大きく上昇させることができます !");
INSERT INTO `tips` VALUES (/*id*/20006, /*tips_type*/2, /*value*/40001, /*index*/1, /*title*/"リハーサルチケット", /*comment*/"スタミナを消費せずに、LIVEの\n練習ができます !");
INSERT INTO `tips` VALUES (/*id*/20007, /*tips_type*/2, /*value*/40011, /*index*/1, /*title*/"MASTER+チケット", /*comment*/"高難易度「MASTER+」のLIVEに挑戦できます !");
INSERT INTO `tips` VALUES (/*id*/30001, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"アイドルを育てるには", /*comment*/"アイドルのレベルを上げるには、\nレッスンを行いましょう !");
INSERT INTO `tips` VALUES (/*id*/30002, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"アイドルとの親愛度を上げるには", /*comment*/"LIVEに参加させたり、\nルームでギフトアイテムを渡すことで\nアイドルとの親愛度が上がります !");
INSERT INTO `tips` VALUES (/*id*/30003, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"新しい楽曲を解放するには", /*comment*/"ストーリーコミュをクリアしたり、\nルームのサウンドブースで楽曲購入すると、新しい楽曲が解放できますよ !");
INSERT INTO `tips` VALUES (/*id*/30004, /*tips_type*/3, /*value*/1, /*index*/1, /*title*/"デレステへようこそ !", /*comment*/"これからアイドルのプロデュース\nがんばっていきましょう !");
INSERT INTO `tips` VALUES (/*id*/30005, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"センターアイドルにすると", /*comment*/"センターにしたアイドルは\nLIVEで親愛度が\n上がりやすくなります !");
INSERT INTO `tips` VALUES (/*id*/30006, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ユニットを変更したい", /*comment*/"ユニットの編集は、\nアイドル編成からいつでも行えます。\nお気に入りのユニットを編成しよう !");
INSERT INTO `tips` VALUES (/*id*/30007, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ローカルオーディションガシャ", /*comment*/"ローカルオーディションガシャでは\nアイドルやアイテムが手に入ります !");
INSERT INTO `tips` VALUES (/*id*/30008, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ガシャを引くには", /*comment*/"ガシャはスタージュエルや友情ptを、\n利用して引くことができます !");
INSERT INTO `tips` VALUES (/*id*/30009, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"LIVEでリズムが合わない時は", /*comment*/"リズムアイコンのタイミングがずれる\n場合はタイミングを調整できます。");
INSERT INTO `tips` VALUES (/*id*/30010, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"LIVEのプレイ方法", /*comment*/"LIVEのプレイ方法を確認したい\nときは、LIVE設定から\n練習LIVEを行いましょう !");
INSERT INTO `tips` VALUES (/*id*/30011, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"タイミング調整について", /*comment*/"タイミング調整は、LIVE設定から\nいつでも実行できます !");
INSERT INTO `tips` VALUES (/*id*/30012, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"アイドルを特訓するには", /*comment*/"アイドルとの親愛度がMAXになると、\nアイドルを特訓できます。\n特訓にはアイテムが必要になります。");
INSERT INTO `tips` VALUES (/*id*/30013, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"特訓に必要なアイテム", /*comment*/"特訓に必要なアイテムは、\nLIVEやルームで入手できます !");
INSERT INTO `tips` VALUES (/*id*/30014, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"エピソードコミュ", /*comment*/"アイドルを特訓すると、\nエピソードコミュが解放されます !");
INSERT INTO `tips` VALUES (/*id*/30015, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"特訓すると", /*comment*/"アイドルを特訓すると、\n能力がアップし、\nLvや親愛度の上限が解放されます !");
INSERT INTO `tips` VALUES (/*id*/30016, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ゲストメンバー", /*comment*/"LIVEでは、他のプロデューサーが\n設定したゲスト参戦アイドルを\nゲストとして呼ぶことができます !");
INSERT INTO `tips` VALUES (/*id*/30017, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"合計アピール", /*comment*/"ユニットの合計アピール値が\n上がるとLIVEで高いSCOREを\n獲得できるようになります !");
INSERT INTO `tips` VALUES (/*id*/30018, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"LIVEクリア", /*comment*/"LIVEに成功すると、アイテムや\nアイドルを獲得できます !");
INSERT INTO `tips` VALUES (/*id*/30019, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ルーム訪問", /*comment*/"他のプロデューサーのルームに\n訪問することができます。\nLikeすると友情ptも貰えますよ !");
INSERT INTO `tips` VALUES (/*id*/30020, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"名前を変更したい時は", /*comment*/"プロデューサー名は、プロフィールから\nいつでも変更できますよ !");
INSERT INTO `tips` VALUES (/*id*/30021, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"データ引き継ぎについて", /*comment*/"データ引き継ぎを行うと今まで遊んだ\nデータを他の端末に\n引き継ぐことができます !");
INSERT INTO `tips` VALUES (/*id*/30022, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ログインボーナスについて", /*comment*/"ゲームにログインするだけで、\n毎日アイテムやスタージュエルが\nGETできます !");
INSERT INTO `tips` VALUES (/*id*/30023, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"アイドルの特技", /*comment*/"特技を持っているアイドルは、\nLIVEが有利になる特技を\n発動することがあります !");
INSERT INTO `tips` VALUES (/*id*/30024, /*tips_type*/3, /*value*/1, /*index*/1, /*title*/"マッチング中", /*comment*/"現在マッチングを行っています。\nしばらくお待ちください。");
INSERT INTO `tips` VALUES (/*id*/30025, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ポテンシャル解放とは", /*comment*/"特訓アイテムを利用して、\nLIVEで発揮されるアイドルの\n能力をアップできます !");
INSERT INTO `tips` VALUES (/*id*/30026, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"マニーショップとは", /*comment*/"マニーを利用して、\nスタミナドリンクなどのアイテムを\n売買することができます !");
INSERT INTO `tips` VALUES (/*id*/30027, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"特訓アイテム交換とは", /*comment*/"所持している特訓アイテムを\n他の特訓アイテムに交換できます !");
INSERT INTO `tips` VALUES (/*id*/30028, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"リハーサルのススメ", /*comment*/"難しいLIVEにチャレンジする前には\nライフが0になってもライブを継続できる\n「リハーサル」がおすすめです !");
INSERT INTO `tips` VALUES (/*id*/30029, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"ぴにゃリクエストとは", /*comment*/"DJぴにゃがLIVEの楽曲を選んで\nくれます。ちょっとした\nご褒美がもらえることも…？");
INSERT INTO `tips` VALUES (/*id*/30030, /*tips_type*/3, /*value*/0, /*index*/1, /*title*/"名刺を作ろう", /*comment*/"自分だけの名刺を作って、\n他のプロデューサーと交換しましょう !");
INSERT INTO `tips` VALUES (/*id*/40001, /*tips_type*/4, /*value*/101, /*index*/1, /*title*/"島村卯月①　がんばりすぎ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40002, /*tips_type*/4, /*value*/102, /*index*/1, /*title*/"中野有香①　リボンをギュっと !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40003, /*tips_type*/4, /*value*/103, /*index*/1, /*title*/"水本ゆかり①　私って天然ですか？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40004, /*tips_type*/4, /*value*/104, /*index*/1, /*title*/"福山舞①　一輪車が得意です♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40005, /*tips_type*/4, /*value*/105, /*index*/1, /*title*/"椎名法子①　ドーナツの不思議…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40006, /*tips_type*/4, /*value*/108, /*index*/1, /*title*/"三村かな子①　お菓子作りあるある？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40007, /*tips_type*/4, /*value*/109, /*index*/1, /*title*/"奥山沙織①　普段から…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40008, /*tips_type*/4, /*value*/111, /*index*/1, /*title*/"小日向美穂①　夢の中でも…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40009, /*tips_type*/4, /*value*/112, /*index*/1, /*title*/"緒方智絵里①　花かんむりを作ろう", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40010, /*tips_type*/4, /*value*/122, /*index*/1, /*title*/"藤本里奈①　ちょりっす変えてみた", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40011, /*tips_type*/4, /*value*/127, /*index*/1, /*title*/"前川みく①　一緒に『にゃあ♪』", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40012, /*tips_type*/4, /*value*/131, /*index*/1, /*title*/"宮本フレデリカ①　新曲 ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40013, /*tips_type*/4, /*value*/132, /*index*/1, /*title*/"小早川紗枝①　こんちきちん講座", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40014, /*tips_type*/4, /*value*/134, /*index*/1, /*title*/"双葉杏①　よかったことはー", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40015, /*tips_type*/4, /*value*/136, /*index*/1, /*title*/"桃井あずき①　得意な大作戦 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40016, /*tips_type*/4, /*value*/141, /*index*/1, /*title*/"道明寺歌鈴①　本人知らずの芸術", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40017, /*tips_type*/4, /*value*/150, /*index*/1, /*title*/"輿水幸子①　至福の時間ですね !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40018, /*tips_type*/4, /*value*/154, /*index*/1, /*title*/"安部菜々①　ここはウサミン星…？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40019, /*tips_type*/4, /*value*/167, /*index*/1, /*title*/"渋谷凛①　お店モード", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40020, /*tips_type*/4, /*value*/169, /*index*/1, /*title*/"松本沙理奈①　これが大人ポーズ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40021, /*tips_type*/4, /*value*/172, /*index*/1, /*title*/"相川千夏①　何語の本？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40022, /*tips_type*/4, /*value*/173, /*index*/1, /*title*/"川島瑞樹①　まだイケルわ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40023, /*tips_type*/4, /*value*/174, /*index*/1, /*title*/"神谷奈緒①　だーからっ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40024, /*tips_type*/4, /*value*/175, /*index*/1, /*title*/"上条春菜①　春菜チャレンジ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40025, /*tips_type*/4, /*value*/176, /*index*/1, /*title*/"荒木比奈①　これがベストッス", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40026, /*tips_type*/4, /*value*/178, /*index*/1, /*title*/"多田李衣菜①　カンペキ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40027, /*tips_type*/4, /*value*/180, /*index*/1, /*title*/"佐々木千枝①　うさぎさん大好き", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40028, /*tips_type*/4, /*value*/185, /*index*/1, /*title*/"新田美波①　美波はお勉強が好き", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40029, /*tips_type*/4, /*value*/188, /*index*/1, /*title*/"橘ありす①　名前で呼ばれるのは…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40030, /*tips_type*/4, /*value*/197, /*index*/1, /*title*/"高垣楓①　６×９=？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40031, /*tips_type*/4, /*value*/198, /*index*/1, /*title*/"神崎蘭子①　堕天使の裏側", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40032, /*tips_type*/4, /*value*/201, /*index*/1, /*title*/"北条加蓮①　ちがうから !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40033, /*tips_type*/4, /*value*/204, /*index*/1, /*title*/"綾瀬穂乃香①　お気に入りです", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40034, /*tips_type*/4, /*value*/205, /*index*/1, /*title*/"佐城雪美①　ペロとおはなし", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40035, /*tips_type*/4, /*value*/214, /*index*/1, /*title*/"白坂小梅①　ホラー映画なら…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40036, /*tips_type*/4, /*value*/223, /*index*/1, /*title*/"速水奏①　女子高生なんだけどな", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40037, /*tips_type*/4, /*value*/227, /*index*/1, /*title*/"アナスタシア①　危険な混ざり方", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40038, /*tips_type*/4, /*value*/234, /*index*/1, /*title*/"本田未央①　あの人のあだ名", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40039, /*tips_type*/4, /*value*/235, /*index*/1, /*title*/"高森藍子①　ゆるふわの弱点", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40040, /*tips_type*/4, /*value*/237, /*index*/1, /*title*/"龍崎薫①　いいまちがい", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40041, /*tips_type*/4, /*value*/238, /*index*/1, /*title*/"木村夏樹①　セットの時間", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40042, /*tips_type*/4, /*value*/243, /*index*/1, /*title*/"赤城みりあ①　なーう ! ! !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40043, /*tips_type*/4, /*value*/246, /*index*/1, /*title*/"大槻唯①　でも何で？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40044, /*tips_type*/4, /*value*/247, /*index*/1, /*title*/"姫川友紀①　こんな時もあるよ…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40045, /*tips_type*/4, /*value*/253, /*index*/1, /*title*/"及川雫①　牛乳で育ちました", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40046, /*tips_type*/4, /*value*/256, /*index*/1, /*title*/"星輝子①　Q・メタル好きなの？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40047, /*tips_type*/4, /*value*/257, /*index*/1, /*title*/"片桐早苗①　バブルとは", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40048, /*tips_type*/4, /*value*/258, /*index*/1, /*title*/"堀裕子①　サイキックー !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40049, /*tips_type*/4, /*value*/266, /*index*/1, /*title*/"若林智香①　応援 ! 応援 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40050, /*tips_type*/4, /*value*/267, /*index*/1, /*title*/"城ヶ崎美嘉①　得意でしょー ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40051, /*tips_type*/4, /*value*/268, /*index*/1, /*title*/"城ヶ崎莉嘉①　カリスマシール貼り", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40052, /*tips_type*/4, /*value*/269, /*index*/1, /*title*/"仙崎恵磨①　マイクVS声 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40053, /*tips_type*/4, /*value*/270, /*index*/1, /*title*/"日野茜①　茜のお散歩日和", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40054, /*tips_type*/4, /*value*/271, /*index*/1, /*title*/"諸星きらり①　してないにぃ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40055, /*tips_type*/4, /*value*/272, /*index*/1, /*title*/"十時愛梨①　テキパキ愛梨 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40056, /*tips_type*/4, /*value*/273, /*index*/1, /*title*/"ナターリア①　みくも安心な寿司？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40057, /*tips_type*/4, /*value*/999, /*index*/1, /*title*/"エトセトラ①　READY GO !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40058, /*tips_type*/4, /*value*/2, /*index*/1, /*title*/"千川ちひろ①　楽しんでくださいね", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40059, /*tips_type*/4, /*value*/2, /*index*/2, /*title*/"千川ちひろ②　ちひろさんの趣味", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40060, /*tips_type*/4, /*value*/126, /*index*/1, /*title*/"一ノ瀬志希①　いい匂いがする～", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40061, /*tips_type*/4, /*value*/263, /*index*/1, /*title*/"相葉夕美①　待ってる時間に", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40062, /*tips_type*/4, /*value*/220, /*index*/1, /*title*/"塩見周子①　趣味は献血", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40063, /*tips_type*/4, /*value*/159, /*index*/1, /*title*/"佐久間まゆ①　もう10冊目♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40064, /*tips_type*/4, /*value*/292, /*index*/1, /*title*/"浜口あやめ①　あやめも忍法… !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40065, /*tips_type*/4, /*value*/194, /*index*/1, /*title*/"松永涼①　ホラーはいいけど…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40066, /*tips_type*/4, /*value*/113, /*index*/1, /*title*/"五十嵐響子①　何の感想？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40067, /*tips_type*/4, /*value*/189, /*index*/1, /*title*/"鷺沢文香①　どこでも読書", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40068, /*tips_type*/4, /*value*/239, /*index*/1, /*title*/"松山久美子①　キレイを求めて", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40069, /*tips_type*/4, /*value*/133, /*index*/1, /*title*/"西園寺琴歌①　事務所でも愛好会", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40070, /*tips_type*/4, /*value*/230, /*index*/1, /*title*/"二宮飛鳥①　今この場所は…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40071, /*tips_type*/4, /*value*/158, /*index*/1, /*title*/"クラリス①　天使と堕天使", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40072, /*tips_type*/4, /*value*/287, /*index*/1, /*title*/"メアリー・コクラン①　大人っぽいところ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40073, /*tips_type*/4, /*value*/221, /*index*/1, /*title*/"脇山珠美①　時代劇鑑賞会", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40074, /*tips_type*/4, /*value*/118, /*index*/1, /*title*/"横山千佳①　A・魔法少女アニメ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40075, /*tips_type*/4, /*value*/168, /*index*/1, /*title*/"黒川千秋①　千秋、ここで一言", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40076, /*tips_type*/4, /*value*/242, /*index*/1, /*title*/"矢口美羽①　理想の…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40077, /*tips_type*/4, /*value*/283, /*index*/1, /*title*/"市原仁奈①　一緒に『ぴょん♪』", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40078, /*tips_type*/4, /*value*/155, /*index*/1, /*title*/"工藤忍①　バイリンガル？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40079, /*tips_type*/4, /*value*/280, /*index*/1, /*title*/"向井拓海①　薔薇・喧嘩", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40080, /*tips_type*/4, /*value*/161, /*index*/1, /*title*/"白菊ほたる①　私がいえ私が", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40081, /*tips_type*/4, /*value*/226, /*index*/1, /*title*/"森久保乃々①　乃々を探せ ! レベル1", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40082, /*tips_type*/4, /*value*/284, /*index*/1, /*title*/"喜多日菜子①　むふふなう", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40083, /*tips_type*/4, /*value*/115, /*index*/1, /*title*/"櫻井桃華①　たしなみですわよ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40084, /*tips_type*/4, /*value*/181, /*index*/1, /*title*/"三船美優①　お静かに…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40085, /*tips_type*/4, /*value*/249, /*index*/1, /*title*/"喜多見柚①　いいコト考えたっ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40086, /*tips_type*/4, /*value*/165, /*index*/1, /*title*/"原田美世①　車大好き !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40087, /*tips_type*/4, /*value*/139, /*index*/1, /*title*/"兵藤レナ①　not サイキック", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40088, /*tips_type*/4, /*value*/147, /*index*/1, /*title*/"井村雪菜①　変身するの♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40089, /*tips_type*/4, /*value*/228, /*index*/1, /*title*/"大和亜季①　サバゲのルール", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40090, /*tips_type*/4, /*value*/190, /*index*/1, /*title*/"八神マキノ①　それは周知です", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40091, /*tips_type*/4, /*value*/293, /*index*/1, /*title*/"村上巴①　お年寄りの影響？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40092, /*tips_type*/4, /*value*/162, /*index*/1, /*title*/"早坂美玲①　ファッションだぞッ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40093, /*tips_type*/4, /*value*/106, /*index*/1, /*title*/"今井加奈①　忘れないように !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40094, /*tips_type*/4, /*value*/184, /*index*/1, /*title*/"藤原肇①　肇の趣味は", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40095, /*tips_type*/4, /*value*/262, /*index*/1, /*title*/"依田芳乃①　探しものはおまかせ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40096, /*tips_type*/4, /*value*/291, /*index*/1, /*title*/"難波笑美①　本場の !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40097, /*tips_type*/4, /*value*/229, /*index*/1, /*title*/"結城晴①　とられる理由", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40098, /*tips_type*/4, /*value*/191, /*index*/1, /*title*/"ライラ①　冬でもアイス", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40099, /*tips_type*/4, /*value*/222, /*index*/1, /*title*/"岡崎泰葉①　業界用語？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40100, /*tips_type*/4, /*value*/254, /*index*/1, /*title*/"小関麗奈①　怯えなさいッ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40101, /*tips_type*/4, /*value*/121, /*index*/1, /*title*/"棟方愛海①　されるよりする側", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40102, /*tips_type*/4, /*value*/179, /*index*/1, /*title*/"水木聖來①　うちのわんこ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40103, /*tips_type*/4, /*value*/260, /*index*/1, /*title*/"的場梨沙①　大きな目標 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40104, /*tips_type*/4, /*value*/219, /*index*/1, /*title*/"藤居朋①　どうすれば ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40105, /*tips_type*/4, /*value*/224, /*index*/1, /*title*/"大石泉①　ノってきた !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40106, /*tips_type*/4, /*value*/289, /*index*/1, /*title*/"三好紗南①　一日一時間…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40107, /*tips_type*/4, /*value*/294, /*index*/1, /*title*/"土屋亜子①　初見の感想", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40108, /*tips_type*/4, /*value*/160, /*index*/1, /*title*/"村松さくら①　マスコット", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40109, /*tips_type*/4, /*value*/107, /*index*/1, /*title*/"持田亜里沙①　起こしてウサコ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40110, /*tips_type*/4, /*value*/177, /*index*/1, /*title*/"東郷あい①　趣味はサックス", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40111, /*tips_type*/4, /*value*/295, /*index*/1, /*title*/"首藤葵①　料理人のプライド", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40112, /*tips_type*/4, /*value*/138, /*index*/1, /*title*/"月宮雅①　会員番号1番", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40113, /*tips_type*/4, /*value*/186, /*index*/1, /*title*/"水野翠①　会", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40114, /*tips_type*/4, /*value*/288, /*index*/1, /*title*/"小松伊吹①　足がいい !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40115, /*tips_type*/4, /*value*/149, /*index*/1, /*title*/"榊原里美①　超・甘党", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40116, /*tips_type*/4, /*value*/119, /*index*/1, /*title*/"関裕美①　視力のせいじゃ…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40117, /*tips_type*/4, /*value*/218, /*index*/1, /*title*/"成宮由愛①　描きたい風景", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40118, /*tips_type*/4, /*value*/250, /*index*/1, /*title*/"上田鈴帆①　届くかこの想い", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40119, /*tips_type*/4, /*value*/213, /*index*/1, /*title*/"梅木音葉①　住人…？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40120, /*tips_type*/4, /*value*/236, /*index*/1, /*title*/"並木芽衣子①　新しい目標 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40121, /*tips_type*/4, /*value*/135, /*index*/1, /*title*/"楊菲菲①　強そうに見えル？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40122, /*tips_type*/4, /*value*/211, /*index*/1, /*title*/"和久井留美①　猫が好き", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40123, /*tips_type*/4, /*value*/164, /*index*/1, /*title*/"乙倉悠貴①　ミックスジュース作りが趣味", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40124, /*tips_type*/4, /*value*/216, /*index*/1, /*title*/"氏家むつみ①　今回の冒険 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40125, /*tips_type*/4, /*value*/285, /*index*/1, /*title*/"杉坂海①　お…ねえちゃん？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40126, /*tips_type*/4, /*value*/286, /*index*/1, /*title*/"北川真尋①　好きなことはー !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40127, /*tips_type*/4, /*value*/129, /*index*/1, /*title*/"松原早耶①　流行好き♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40128, /*tips_type*/4, /*value*/163, /*index*/1, /*title*/"有浦柑奈①　ここで一曲", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40129, /*tips_type*/4, /*value*/171, /*index*/1, /*title*/"高橋礼子①　夢と希望を", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40130, /*tips_type*/4, /*value*/275, /*index*/1, /*title*/"槙原志保①　何つながりか…わかる", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40131, /*tips_type*/4, /*value*/123, /*index*/1, /*title*/"大原みちる①　みちるチャレンジ ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40132, /*tips_type*/4, /*value*/192, /*index*/1, /*title*/"浅利七海①　心静かにれす", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40133, /*tips_type*/4, /*value*/240, /*index*/1, /*title*/"斉藤洋子①　何のポーズ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40134, /*tips_type*/4, /*value*/153, /*index*/1, /*title*/"大西由里子①　得意なハナシ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40135, /*tips_type*/4, /*value*/210, /*index*/1, /*title*/"篠原礼①　なぞなぞ考え中", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40136, /*tips_type*/4, /*value*/183, /*index*/1, /*title*/"木場真奈美①　真奈美の弱点？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40137, /*tips_type*/4, /*value*/259, /*index*/1, /*title*/"西島櫂①　水あるところに", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40138, /*tips_type*/4, /*value*/156, /*index*/1, /*title*/"栗原ネネ①　栄養第一です♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40139, /*tips_type*/4, /*value*/120, /*index*/1, /*title*/"太田優①　いつも抱いてる", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40140, /*tips_type*/4, /*value*/212, /*index*/1, /*title*/"吉岡沙紀①　これでどうっす？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40141, /*tips_type*/4, /*value*/244, /*index*/1, /*title*/"愛野渚①　ゴミ箱にシュート", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40142, /*tips_type*/4, /*value*/202, /*index*/1, /*title*/"ケイト①　雑誌が好きデス♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40143, /*tips_type*/4, /*value*/255, /*index*/1, /*title*/"衛藤美紗希①　オススメなのぉ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40144, /*tips_type*/4, /*value*/298, /*index*/1, /*title*/"南条光①　アタシが倒す !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40145, /*tips_type*/4, /*value*/125, /*index*/1, /*title*/"大沼くるみ①　ティッシュ収集趣味でしゅ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40146, /*tips_type*/4, /*value*/187, /*index*/1, /*title*/"古澤頼子①　皆で行きましょう", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40147, /*tips_type*/4, /*value*/151, /*index*/1, /*title*/"安斎都①　趣味は推理小説を…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40148, /*tips_type*/4, /*value*/170, /*index*/1, /*title*/"桐野アヤ①　インターバル中", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40149, /*tips_type*/4, /*value*/274, /*index*/1, /*title*/"相馬夏美①　CA風に", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40150, /*tips_type*/4, /*value*/297, /*index*/1, /*title*/"佐藤心①　和めよ☆", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40151, /*tips_type*/4, /*value*/145, /*index*/1, /*title*/"柳清良①　体調を心配して", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40152, /*tips_type*/4, /*value*/231, /*index*/1, /*title*/"桐生つかさ①　本気ってわかる？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40153, /*tips_type*/4, /*value*/124, /*index*/1, /*title*/"遊佐こずえ①　猫のように", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40154, /*tips_type*/4, /*value*/157, /*index*/1, /*title*/"古賀小春①　(…仲間かな？)", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40155, /*tips_type*/4, /*value*/225, /*index*/1, /*title*/"松尾千鶴①　渾身の書 !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40156, /*tips_type*/4, /*value*/241, /*index*/1, /*title*/"沢田麻理菜①　よかったこと", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40157, /*tips_type*/4, /*value*/203, /*index*/1, /*title*/"瀬名詩織①　…分かります…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40158, /*tips_type*/4, /*value*/182, /*index*/1, /*title*/"服部瞳子①　昔デビューした時の…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40159, /*tips_type*/4, /*value*/264, /*index*/1, /*title*/"野々村そら①　れっつしんぐ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40160, /*tips_type*/4, /*value*/137, /*index*/1, /*title*/"涼宮星花①　A・ネイル無理繋がり", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40161, /*tips_type*/4, /*value*/261, /*index*/1, /*title*/"財前時子①　時子様のお言葉", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40162, /*tips_type*/4, /*value*/117, /*index*/1, /*title*/"長富蓮実①　ママにも人気", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40163, /*tips_type*/4, /*value*/215, /*index*/1, /*title*/"岸部彩華①　永遠にガールズ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40164, /*tips_type*/4, /*value*/265, /*index*/1, /*title*/"浜川愛結奈①　馬なら任せてっ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40165, /*tips_type*/4, /*value*/196, /*index*/1, /*title*/"高峯のあ①　中二な憧れ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40166, /*tips_type*/4, /*value*/152, /*index*/1, /*title*/"浅野風香①　明日こそは", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40167, /*tips_type*/4, /*value*/114, /*index*/1, /*title*/"柳瀬美由紀①　けどなんで？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40168, /*tips_type*/4, /*value*/251, /*index*/1, /*title*/"海老原菜帆①　我慢しないで～♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40169, /*tips_type*/4, /*value*/217, /*index*/1, /*title*/"西川保奈美①　NOT オペラ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40170, /*tips_type*/4, /*value*/148, /*index*/1, /*title*/"日下部若葉①　必須なんです～", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40171, /*tips_type*/4, /*value*/200, /*index*/1, /*title*/"柊志乃①　またおいで…♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40172, /*tips_type*/4, /*value*/300, /*index*/1, /*title*/"イヴ・サンタクロース①　彼女はサンタ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40173, /*tips_type*/4, /*value*/290, /*index*/1, /*title*/"キャシー・グラハム①　英語でどうぞ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40174, /*tips_type*/4, /*value*/199, /*index*/1, /*title*/"伊集院惠①　楽しむコツ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40175, /*tips_type*/4, /*value*/195, /*index*/1, /*title*/"小室千奈美①　ダーツで言うと？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40176, /*tips_type*/4, /*value*/130, /*index*/1, /*title*/"相原雪乃①　A・お茶(紅茶、緑茶、珈琲)", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40177, /*tips_type*/4, /*value*/232, /*index*/1, /*title*/"望月聖①　天使の宴", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40178, /*tips_type*/4, /*value*/116, /*index*/1, /*title*/"江上椿①　趣味は写真です♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40179, /*tips_type*/4, /*value*/233, /*index*/1, /*title*/"鷹富士茄子①　1コマおみくじ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40180, /*tips_type*/4, /*value*/245, /*index*/1, /*title*/"真鍋いつき①　再スカウト？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40181, /*tips_type*/4, /*value*/166, /*index*/1, /*title*/"池袋晶葉①　力が欲しいのか？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40182, /*tips_type*/4, /*value*/110, /*index*/1, /*title*/"間中美里①　あっ旅行の話♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40183, /*tips_type*/4, /*value*/128, /*index*/1, /*title*/"赤西瑛梨華①　路線変更？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40184, /*tips_type*/4, /*value*/296, /*index*/1, /*title*/"冴島清美①　事務所の風紀を…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40185, /*tips_type*/4, /*value*/140, /*index*/1, /*title*/"丹羽仁美①　アタシの憧れは", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40186, /*tips_type*/4, /*value*/193, /*index*/1, /*title*/"ヘレン①　1コマおみくじ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40187, /*tips_type*/4, /*value*/133, /*index*/2, /*title*/"西園寺琴歌②　心強い表情", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40188, /*tips_type*/4, /*value*/287, /*index*/2, /*title*/"メアリー・コクラン②　レディーのトーク", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40189, /*tips_type*/4, /*value*/120, /*index*/2, /*title*/"太田優②　あたしにおまかせぇ♪", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40190, /*tips_type*/4, /*value*/177, /*index*/2, /*title*/"東郷あい②　ブラックだが…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40191, /*tips_type*/4, /*value*/283, /*index*/2, /*title*/"市原仁奈②　うさぎの誘惑", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40192, /*tips_type*/4, /*value*/152, /*index*/2, /*title*/"浅野風香②　鞄につけてます", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40193, /*tips_type*/4, /*value*/286, /*index*/2, /*title*/"北川真尋②　インターバルの使い道", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40194, /*tips_type*/4, /*value*/124, /*index*/2, /*title*/"遊佐こずえ②　寝る子は育つ…？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40195, /*tips_type*/4, /*value*/231, /*index*/2, /*title*/"桐生つかさ②　社長に学べ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40196, /*tips_type*/4, /*value*/106, /*index*/2, /*title*/"今井加奈②　おのぼりさんが通る道", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40197, /*tips_type*/4, /*value*/254, /*index*/2, /*title*/"小関麗奈②　説明書を読むであります !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40198, /*tips_type*/4, /*value*/258, /*index*/2, /*title*/"堀裕子②　最終回直前でよくある…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40199, /*tips_type*/4, /*value*/102, /*index*/2, /*title*/"中野有香②　髪留めの秘密", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40200, /*tips_type*/4, /*value*/214, /*index*/2, /*title*/"白坂小梅②　自撮りのコツは…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40201, /*tips_type*/4, /*value*/255, /*index*/2, /*title*/"衛藤美紗希②　女子力の使い道", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40202, /*tips_type*/4, /*value*/157, /*index*/2, /*title*/"古賀小春②　ぺろぺろペロ…？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40203, /*tips_type*/4, /*value*/284, /*index*/2, /*title*/"喜多日菜子②　妄想を祈りにこめて", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40204, /*tips_type*/4, /*value*/198, /*index*/2, /*title*/"神崎蘭子②　闇の眷属に手当ては不要っ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40205, /*tips_type*/4, /*value*/261, /*index*/2, /*title*/"財前時子②　豚の調理法", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40206, /*tips_type*/4, /*value*/161, /*index*/2, /*title*/"白菊ほたる②　ポジティブ？ネガティブ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40207, /*tips_type*/4, /*value*/179, /*index*/2, /*title*/"水木聖來②　ストリートも大好き", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40208, /*tips_type*/4, /*value*/291, /*index*/2, /*title*/"難波笑美②　ツッコミ待ち", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40209, /*tips_type*/4, /*value*/171, /*index*/2, /*title*/"高橋礼子②　女豹のきもち", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40210, /*tips_type*/4, /*value*/162, /*index*/2, /*title*/"早坂美玲②　趣味はぬいぐるみ集め", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40211, /*tips_type*/4, /*value*/265, /*index*/2, /*title*/"浜川愛結奈②　鞭の扱い", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40212, /*tips_type*/4, /*value*/204, /*index*/2, /*title*/"綾瀬穂乃香②　やわらかい", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40213, /*tips_type*/4, /*value*/126, /*index*/2, /*title*/"一ノ瀬志希②　いつのまにか", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40214, /*tips_type*/4, /*value*/256, /*index*/2, /*title*/"星輝子②　カモンサンダー !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40215, /*tips_type*/4, /*value*/109, /*index*/2, /*title*/"奥山沙織②　方言アイドル", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40216, /*tips_type*/4, /*value*/184, /*index*/2, /*title*/"藤原肇②　陶芸スペース導入後", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40217, /*tips_type*/4, /*value*/289, /*index*/2, /*title*/"三好紗南②　今の技は… !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40218, /*tips_type*/4, /*value*/273, /*index*/2, /*title*/"ナターリア②　一緒に勉強ダゾ !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40219, /*tips_type*/4, /*value*/178, /*index*/2, /*title*/"多田李衣菜②　はやくやりたい", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40220, /*tips_type*/4, /*value*/223, /*index*/2, /*title*/"速水奏②　映画のジャンル !", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40221, /*tips_type*/4, /*value*/136, /*index*/2, /*title*/"桃井あずき②　大作戦なし大作戦", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40222, /*tips_type*/4, /*value*/242, /*index*/2, /*title*/"矢口美羽②　勇気の一発", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40223, /*tips_type*/4, /*value*/229, /*index*/2, /*title*/"結城晴②　狙われてる…？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40224, /*tips_type*/4, /*value*/297, /*index*/2, /*title*/"佐藤心②　スウィーティーとは", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40225, /*tips_type*/4, /*value*/268, /*index*/2, /*title*/"城ヶ崎莉嘉②　つい喋っちゃう☆", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40226, /*tips_type*/4, /*value*/121, /*index*/2, /*title*/"棟方愛海②　グラビア用ではなく", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40227, /*tips_type*/4, /*value*/183, /*index*/2, /*title*/"木場真奈美②　真奈美隙なし", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40228, /*tips_type*/4, /*value*/251, /*index*/2, /*title*/"海老原菜帆②　女子高生なんですが", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40229, /*tips_type*/4, /*value*/119, /*index*/2, /*title*/"関裕美②　本人は知らない", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40230, /*tips_type*/4, /*value*/137, /*index*/2, /*title*/"涼宮星花②　夢の一つ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40231, /*tips_type*/4, /*value*/259, /*index*/2, /*title*/"西島櫂②　ウワサについて", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40232, /*tips_type*/4, /*value*/201, /*index*/2, /*title*/"北条加蓮②　髪型は変えるけど", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40233, /*tips_type*/4, /*value*/159, /*index*/2, /*title*/"佐久間まゆ②　いろいろ深い", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40234, /*tips_type*/4, /*value*/298, /*index*/2, /*title*/"南条光②　ファンの年齢層", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40235, /*tips_type*/4, /*value*/135, /*index*/2, /*title*/"楊菲菲②　実はお嬢様ヨー", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40236, /*tips_type*/4, /*value*/227, /*index*/2, /*title*/"アナスタシア②　訳：落ち着く", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40237, /*tips_type*/4, /*value*/290, /*index*/2, /*title*/"キャシー・グラハム②　江戸っ子は…", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40238, /*tips_type*/4, /*value*/164, /*index*/2, /*title*/"乙倉悠貴②　冒険なんですっ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40239, /*tips_type*/4, /*value*/194, /*index*/2, /*title*/"松永涼②　路上ライブを見て", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40240, /*tips_type*/4, /*value*/236, /*index*/2, /*title*/"並木芽衣子②　ビーチサンダル", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40241, /*tips_type*/4, /*value*/103, /*index*/2, /*title*/"水本ゆかり②　ゆかりフルーティー", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40242, /*tips_type*/4, /*value*/189, /*index*/2, /*title*/"鷺沢文香②　電子書籍勧めてみた", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40243, /*tips_type*/4, /*value*/250, /*index*/2, /*title*/"上田鈴帆②　バレない人", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40244, /*tips_type*/4, /*value*/165, /*index*/2, /*title*/"原田美世②　メカ最強 ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40245, /*tips_type*/4, /*value*/190, /*index*/2, /*title*/"八神マキノ②　興味ありませんか ! ？", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/40246, /*tips_type*/4, /*value*/267, /*index*/2, /*title*/"城ヶ崎美嘉②　ギャルオケの１コマ", /*comment*/"");
INSERT INTO `tips` VALUES (/*id*/50001, /*tips_type*/5, /*value*/1, /*index*/1, /*title*/"縦画面持ち替え説明画像", /*comment*/"");
