CREATE TABLE 'tower_floor_release' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'target_area_id' INTEGER NOT NULL, 'target_floor_number' INTEGER NOT NULL, 'need_area_id' INTEGER NOT NULL, 'need_floor_number' INTEGER NOT NULL, UNIQUE('id'));
INSERT INTO `tower_floor_release` VALUES (/*id*/1, /*event_id*/8001, /*target_area_id*/2, /*target_floor_number*/1, /*need_area_id*/1, /*need_floor_number*/11);
INSERT INTO `tower_floor_release` VALUES (/*id*/2, /*event_id*/8001, /*target_area_id*/3, /*target_floor_number*/1, /*need_area_id*/1, /*need_floor_number*/11);
INSERT INTO `tower_floor_release` VALUES (/*id*/3, /*event_id*/8001, /*target_area_id*/4, /*target_floor_number*/1, /*need_area_id*/1, /*need_floor_number*/11);
INSERT INTO `tower_floor_release` VALUES (/*id*/4, /*event_id*/8001, /*target_area_id*/5, /*target_floor_number*/1, /*need_area_id*/1, /*need_floor_number*/11);
INSERT INTO `tower_floor_release` VALUES (/*id*/5, /*event_id*/8001, /*target_area_id*/2, /*target_floor_number*/7, /*need_area_id*/1, /*need_floor_number*/21);
INSERT INTO `tower_floor_release` VALUES (/*id*/6, /*event_id*/8001, /*target_area_id*/3, /*target_floor_number*/7, /*need_area_id*/1, /*need_floor_number*/21);
INSERT INTO `tower_floor_release` VALUES (/*id*/7, /*event_id*/8001, /*target_area_id*/4, /*target_floor_number*/7, /*need_area_id*/1, /*need_floor_number*/21);
INSERT INTO `tower_floor_release` VALUES (/*id*/8, /*event_id*/8001, /*target_area_id*/5, /*target_floor_number*/7, /*need_area_id*/1, /*need_floor_number*/21);
INSERT INTO `tower_floor_release` VALUES (/*id*/9, /*event_id*/8001, /*target_area_id*/2, /*target_floor_number*/18, /*need_area_id*/1, /*need_floor_number*/41);
INSERT INTO `tower_floor_release` VALUES (/*id*/10, /*event_id*/8001, /*target_area_id*/3, /*target_floor_number*/18, /*need_area_id*/1, /*need_floor_number*/41);
INSERT INTO `tower_floor_release` VALUES (/*id*/11, /*event_id*/8001, /*target_area_id*/4, /*target_floor_number*/18, /*need_area_id*/1, /*need_floor_number*/41);
INSERT INTO `tower_floor_release` VALUES (/*id*/12, /*event_id*/8001, /*target_area_id*/5, /*target_floor_number*/18, /*need_area_id*/1, /*need_floor_number*/41);
INSERT INTO `tower_floor_release` VALUES (/*id*/13, /*event_id*/8001, /*target_area_id*/2, /*target_floor_number*/19, /*need_area_id*/1, /*need_floor_number*/51);
INSERT INTO `tower_floor_release` VALUES (/*id*/14, /*event_id*/8001, /*target_area_id*/3, /*target_floor_number*/19, /*need_area_id*/1, /*need_floor_number*/51);
INSERT INTO `tower_floor_release` VALUES (/*id*/15, /*event_id*/8001, /*target_area_id*/4, /*target_floor_number*/19, /*need_area_id*/1, /*need_floor_number*/51);
INSERT INTO `tower_floor_release` VALUES (/*id*/16, /*event_id*/8001, /*target_area_id*/5, /*target_floor_number*/19, /*need_area_id*/1, /*need_floor_number*/51);
CREATE INDEX 'tower_floor_release_0_target_area_id' on 'tower_floor_release'('target_area_id');
CREATE UNIQUE INDEX 'tower_floor_release_0_target_area_id_1_target_floor_number' on 'tower_floor_release'('target_area_id','target_floor_number');
